### ISSUE TITLE
Unable to login to Apps after IDM upgrade to 6.3.0

### ISSUE THREAD

**Issue by zwets** [flowable/flowable-engine#1013]
After upgrading Flowable IDM to 6.3.0, I can't login to Task, Modeler or Admin (still at 6.2.0). They keep redirecting to the IDM login page. I can login to IDM itself, and see the users.

The issue seems to be with Spring Security. The access log shows this `500`:

```
127.0.0.1 - - [22/Apr/2018:10:37:44 +0300] "GET /flowable-idm/api/idm/tokens/9hSNoUgSkv6IHNcNKXPIhQ%253D%253D HTTP/1.1" 500 274                                                                                     
``` 

and `catalina.out` logs:

```
2018-04-22 10:37:44.660 ERROR 8340 --- [nio-8080-exec-3] o.s.b.w.s.s.ErrorPageFilter              : Forwarding to error page from request [/api/idm/tokens/9hSNoUgSkv6IHNcNKXPIhQ%3D%3D] due to exception [The request was rejected because the URL contained a potentially malicious String "%25"] 
```

This issue may be the cause of the issue in [this forum post](https://forum.flowable.org/t/redirected-to-login-page-when-trying-to-access-flowable-modeler-flowable-task/1322), and is not the same as #550.

**Comment by tijsrademakers** [comment]
Hi Marco,

Did you try to delete the existing token from the ACT_ID_TOKEN table? Because of the upgrade to Spring Security 5.x and Spring Boot for the UI apps the token logic was changed in a way that we couldn't find a backwards compatible way. In the release notes we therefore mention to remove the existing entries from the ACT_ID_TOKEN table.

**Comment by zwets** [comment]
Hi Tijs, tried that just now (I remember making a mental note when reading the release notes, then forgot about it) but it doesn't work. 

Looking in the `ACT_ID_TOKEN` table I see that the new token values still end with `==`, which I suppose is part of the issue. They escape as `%3D` which then somehow is double escaped to `%253D` as the access log shows.

Who allocates the tokens? The Task App or IDM? Note that my Task app is still 6.2.0.

**Comment by zwets** [comment]
Looking at this some more: the double encoding, not the value of the token as such (unless it would contain `%` characters), looks to me to be the problem.

Spring security's [StrictHttpFirewall](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/firewall/StrictHttpFirewall.java) rejects encoded `%` characters in URLs, i.e. the character sequence `%25`.

The token values end in `==` (I assume due to base64 encoding). This should go on the line as `%3D` in the `GET`, which would be fine. Somehow, however, they're URL-encoded again, and there's the problem.

**Comment by zwets** [comment]
Owww, that's understandable but a pity. My idea was to have my 6.2.0 (Task-based) application co-exist with a new 6.3.0, while making them share a single IDM. Seems like I'll need to either upgrade the old, or have separate setups. 

Thanks guys for this within-the-hour solution of the issue!

**Comment by filiphr** [comment]
In theory you could achieve that by changing the way the the cookie is decoded in the Task app. Although, I can't guarantee for 100% compatibility across the different versions, there might be some other things which might interfere.

In any case updating the Task App to 6.3.0 would give you some boost in performance. See [Flowable 6.3.0 Performance Benchmark](https://blog.flowable.org/2018/03/05/flowable-6-3-0-performance-benchmark/) and [Asynchronous History Performance Benchmark](https://blog.flowable.org/2018/03/13/async-history-performance-benchmark/) blogs 😉
