### ISSUE TITLE
Colloection IN operations perform Contains not IN

### ISSUE THREAD

**Issue by AminaZoheir** [flowable/flowable-engine#1023]
Collection A IN Collection B
Should do Collection B containsAll Collection A, but it does the opposite.

This applies to all collection operators (IN, NOTIN, ANY, NOTANY) incase of input type = collection.

**Comment by tijsrademakers** [comment]
We refactored the collection operator names to make them more self explanatory. You can see the commit here https://github.com/flowable/flowable-engine/commit/281632cfb59d4a3f5f82d2d351d4bf65b57f4d71. We welcome any feedback,
