### ISSUE TITLE
Feature Request: Add contains, contains any, not contains and not contains any to decision table

### ISSUE THREAD

**Issue by AminaZoheir** [flowable/flowable-engine#1033]

**Comment by yvoswillens** [comment]
Hi Amina,

Are you referring to something else than the collection functions that were added to the Decision Table editor in the last release?

Regards,

Yvo

**Comment by AminaZoheir** [comment]
Hello Yvo,

Yes the operators added in the last release are the IN operations which is the opposite of the contains.
Except in case of type collection which is very confusing. As I described in #1023 

So basically I made the IN operator work the same for all variable types #1024  and I'm now adding the Contains operators which are the opposite.

Please let me know if there is something that I might have understood incorrectly.

Best,
Amina

**Comment by yvoswillens** [comment]
Hi Amina,

I agree that this should be better described in the docs.

You probably already know this, but to avoid confusion; 
How it currently works is that you can do collections related operation on;
1. a collection as input variable and define 'simple value(s)' in the rule entries to use for the 'occurrence checks'
2. define the collection in the rule entries and use a 'simple value' input variable to use for the 'occurrence checks'

This translates to the DMN XML to a JUEL expression like;

1. ${collection:containsAny(inputVariable1, '"test2", "test5"')}
2. ${collection:containsAny('"test1", "test2"', customerOne.name)}

In both case the collection to operate on is the first parameter. The values to check the second.

Is this behaviour not the way you would expect it to work?

Regards,

Yvo

**Comment by AminaZoheir** [comment]
Hello Yvo,

Yes I understand that this is what is happening, but the issue is if I'm using type= "collection":
So I'm saying inputCollection1 IN '"test1", "test2"'. This maps to inputCollection1 contains '"test1, "test2"' which is the opposite. So what I'm proposing is that we have both in the UI side to avoid confusion.

Best,
Amina

**Comment by yvoswillens** [comment]
Hi,

okay. I think I understand now. It's a matter of the 'direction of reading'. In this case top to bottom. Which can be the other way around depending of the type of the input. 
I'll have a look at the 2 PRs and discuss it with the rest of the team.

Thanks for the input.

Regards,

Yvo

**Comment by AminaZoheir** [comment]
Hi,

I created the pull request #1035 and closed the older one #1024 as it I implemented it again in #1035

**Comment by tijsrademakers** [comment]
We refactored the collection operator names to make them more self explanatory. You can see the commit here 281632c. We welcome any feedback.
