### ISSUE TITLE
CmmnRuntimeService.setVariable() issue due invalid PlanItemInstance.xml mapping

### ISSUE THREAD

**Issue by andrejafanasjev** [flowable/flowable-engine#1063]
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: unexpected token: SENTRY_PART_INST_COUNT_ : line: 22 in statement [update ACT_CMMN_RU_PLAN_ITEM_INST
     SET REV_ = ?,
            VAR_COUNT_ = ?
            SENTRY_PART_INST_COUNT_ = ? 
    where ID_ = ? and REV_ = ?]

**Comment by tijsrademakers** [comment]
Thanks for raising this issue, it's fixed now
