### ISSUE TITLE
Custom variable types are not copied to Flowable 5 config when using flowable5 compatibility

### ISSUE THREAD

**Issue by mlippens** [flowable/flowable-engine#1065]
In `org.flowable.compatibility.DefaultProcessEngineFactory`, a new configuration is made based upon a flowable 6 configuration. However, I noticed that custom variable types are not copied in this class.

I'll submit a PR for this :)

**Comment by mlippens** [comment]
See PR #1066

**Comment by tijsrademakers** [comment]
Thanks for the PR
