### ISSUE TITLE
Flowable Task UI experience breaks with Async History Enabled

### ISSUE THREAD

**Issue by aronim** [flowable/flowable-engine#1079]
It appears that most of the Task related features rely work off the FlowableTaskService which in turn relies heavily on the HistoryService. This unfortunately causes a few issues if the Async History feature is enabled.

Examples:
1. When I claim a task, the controller makes an immediate attempt to update the state of the task from the server, in order to retrieve the form key and form data. Since the history task has not been updated yet, I am presented with a disabled claim button. Its only when I navigate away from the task and return do I get the data from the update history.
2. The active Task list is populated from the runtime TaskService, but the form details are populated from the HistoricTaskInstances. If I attempt to select a task that has not been saved to the history task table yet, the I get an error.

Potential solutions:
1. Duplicating the task queries in FlowableTaskService, first checking the history tasks, if none exists, then checking the runtime tasks.
2. Creating an query facade abstraction layer for the FlowableTaskService to use, that will first query on the Historic Tasks and then the query runtime Tasks.

**Comment by tijsrademakers** [comment]
Yes, this can indeed be improved.
I think option 1 would be a good one to implement, but first it needs to be check if a runtime task exists and then second the history task. This is because the history contains all tasks, runtime and completed ones.

**Comment by aronim** [comment]
Considering this issue can manifest in a number of ways, should I create an issue for each case individually?

**Comment by tijsrademakers** [comment]
There are no plans to support this feature in the task application, therefore closing the issue.
