### ISSUE TITLE
AbstractAsyncExecutor modifications cause an NPE when Spring is used

### ISSUE THREAD

**Issue by rgreig** [flowable/flowable-engine#109]
Using the latest 6.0.0 snapshot, I get an NPE when using the SpringAsyncExecutor, e.g.

Exception in thread "flowable-acquire-async-jobs" java.lang.NullPointerException
	at org.flowable.engine.impl.asyncexecutor.DefaultAsyncJobExecutor.getRemainingCapacity(DefaultAsyncJobExecutor.java:254)
	at org.flowable.engine.impl.asyncexecutor.AcquireAsyncJobsDueRunnable.run(AcquireAsyncJobsDueRunnable.java:53)
	at java.lang.Thread.run(Thread.java:745)

I believe this is a result of the recent commit 3c223159a01e2c86e0367f37ad206079814fbe6c - pull request #44. It introduced two additional methods that are called from the start() method in AbstractAsyncExecutor:

- initializeRunnables();
- startAdditionalComponents();

The problem is that the SpringAsyncExecutor overrides initAsyncJobExecutionThreadPool() to do nothing, since it relies on the spring executor framework. However, startAdditionalComponents (which is not overridden) requires certain data structures to be initialised that would have been done in the initAsyncJobExecutionThreadPool method.

I have thrown together a "fix" which at least resolves the problem but it is a little bit messy - the SpringAsyncExecutor does need to ensure that the timer acquisition thread is created so it cannot simply override the startAdditionalComponents method to do nothing.

It does appear that the inheritance hierarchy is not really correct - should SpringAsyncExecutor really inherit from DefaultAsyncJobExecutor?

I am happy to submit a pull request with what I have done but not sure it is a great fix!

**Comment by tijsrademakers** [comment]
Thanks for reporting the issue. It should be fixed now, and there's a unit test added to test this specific case.
