### ISSUE TITLE
Provide Transaction depentent EventListeners

### ISSUE THREAD

**Issue by wblancqu** [flowable/flowable-engine#11]
Just as with the new TransactionDependent Task/Execution Listener (as nicely demonstrated by Yvo in his blogpost: http://blog.mark-it-zero.com/transaction-dependent-listeners/), it might make sense to have the same kind of functionality for EventListeners.

e.g. I want to notify on a Kafka topic each time a process instance has started / ended, but do not want to clutter the BPMN xml with that. The current implementation (if I'm not mistaking) will notify the EventListeners even when the transaction has not yet been committed. I want to be notified only when I'm sure that the process instance really started / ended.

In the project I'm currently working on, we implemented this functionality on top of Flowable (/Activiti). Do you guys think it makes sense to move this closer to the core?

**Comment by jbarrez** [comment]
Yes, it does make sense if the same transaction lifecycle semantics would be added for event listeners too. 

There are three ways of adding such event listeners (see http://www.flowable.org/docs/userguide/index.html#eventDispatcher):

1. Via process engine configuration
2. Via the API (RuntimeService)
3. in the bpmn 2.0 xml

Implementation-wise, I'm assuming a new more specialized event listener interface is need (extending the current event listener interface would not be backwards compatible). When the event is fired (here: https://github.com/flowable/flowable-engine/blob/master/modules/flowable-engine/src/main/java/org/activiti/engine/delegate/event/impl/ActivitiEventDispatcherImpl.java#L65), the event listener should be wrapper in a TransactionListener, like is done for the task/executionListener (see https://github.com/flowable/flowable-engine/blob/master/modules/flowable-engine/src/main/java/org/activiti/engine/impl/bpmn/listener/ListenerNotificationHelper.java#L185).

For 1 and 2, the current API's could be kept or a new methods are added where a transaction state is passed as extra argument. For 3, a new attribute is needed.

**Comment by wblancqu** [comment]
I'll try working on this the coming next days, but quite a busy schedule. I'll reach out asap :-)

Grtz

**Comment by mlippens** [comment]
@wblancqu any updates on this? Seems like an interesting feature to have.

**Comment by wblancqu** [comment]
Sorry, no longer working actively on this. Feel free to pick this up!

Grtz

**Comment by faizal-manan** [comment]
By adding this functionality for EventListener, does it'll affect FlowableEventListener?
or something totally new is required, like TransactionDependentEventListener & FlowableTransactionDependentEventListener

**Comment by tijsrademakers** [comment]
I think a new class like TransactionDependentEventListener is needed.

**Comment by faizal-manan** [comment]
I'll pick up this one. 
Need to some time to understand current process and Transaction Dependent process.

**Comment by faizal-manan** [comment]
I'm working on this features atm,
Manage to get execution to work as expected. Currently listeners registration is only via process engine configuration. Will take some few days (or weeks) to complete listeners registration 

Working branch
[https://github.com/faizal-manan/flowable-engine/tree/transaction-event-listener](https://github.com/faizal-manan/flowable-engine/tree/transaction-event-listener)

Unit Test Log
[https://gist.github.com/faizal-manan/f5d1433d8eb3f77d91c4f27e17c08bf9](https://gist.github.com/faizal-manan/f5d1433d8eb3f77d91c4f27e17c08bf9)

Highlight
1. New listener class [TransactionDependentFlowableEventListener](https://github.com/faizal-manan/flowable-engine/blob/transaction-event-listener/modules/flowable-engine-common-api/src/main/java/org/flowable/engine/common/api/delegate/event/TransactionDependentFlowableEventListener.java) 
2. Event dispatcher is via [FlowableEventDispatcherImpl](https://github.com/faizal-manan/flowable-engine/blob/transaction-event-listener/modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/event/FlowableEventDispatcherImpl.java#L79)
3. TransactionListener wrapper [TransactionDependentFlowableEventSupport](https://github.com/faizal-manan/flowable-engine/blob/transaction-event-listener/modules/flowable-engine/src/main/java/org/flowable/engine/delegate/event/TransactionDependentFlowableEventSupport.java#L107)
4. Unit Test source [ActivityEventsTest.testActivityEvents](https://github.com/faizal-manan/flowable-engine/blob/transaction-event-listener/modules/flowable-engine-common/src/main/java/org/flowable/engine/common/impl/event/FlowableEventDispatcherImpl.java#L105)

Thanks

**Comment by faizal-manan** [comment]
@jbarrez 
@tijsrademakers 

Should transaction dependent event listener handle listener throwing BPMN event  (SignalThrowingEventListener, MessageThrowingEventListener, ErrorThrowingEventListener )?

**Comment by PascalSchumacher** [comment]
I guess this can be closed now that https://github.com/flowable/flowable-engine/pull/589 has been merged (and enhanced in https://github.com/flowable/flowable-engine/commit/66df9ab5c2e4d44e3c859d5bc42af79e211c6acc)

**Comment by tijsrademakers** [comment]
Done

**Comment by sijitang** [comment]
> 3. in the bpmn 2.0 xml
> For 3, a new attribute is needed.
As your said, Is there any new attribute needed if we using bpmn 2.0 xml to define this Transaction dependent eventListener state? like onTransaction="committed" in transaction dependent TaskListener?  i can not find it in flowable doc
