### ISSUE TITLE
6.3.1 - TaskQuery CandidateUser not matching Task.CandidateGroup...

### ISSUE THREAD

**Issue by pdsway** [flowable/flowable-engine#1104]
TaskQuery problem...
When supplied Candidate User is in the Task Candidate Group(s), Task not found.

Possible bug in this code: "MybatisidentityLinkDataManager.java" line 57

package org.flowable.identitylink.service.impl.persistence.entity.data.impl;

    @Override
    public List<IdentityLinkEntity> findIdentityLinksByTaskId(String taskId) {
        DbSqlSession dbSqlSession = getDbSqlSession();
        
        if (isEntityInserted(dbSqlSession, "task", taskId)) {
            return getListFromCache(identityLinksByTaskIdMatcher, taskId);
        }
        
        return getList("selectIdentityLinksByTaskId", taskId, **identityLinkByProcessInstanceMatcher**, true);
    }

Should be "identityLinksByTaskIdMatcher" ?

**Comment by martin-grofcik** [comment]
Hi pdsway,

You can be right, but can you provide a jUnit test for this case, please?
What I see as a problem there is that candidate **user** is added into candidate **groups**.

**Comment by pdsway** [comment]
Yes I can work on a unit test, it would go like this, tell me if I'm doing it wrong...

Create user1
Create group1
Add user1 to group1
Create process1 with User Task "task1"
Set task1 assignment.CandidateGroup "group1"
Start process (task1 instance created)
TaskQuery where "CandidateUser" = user1
AssertEqual(result,task1)

**Comment by tijsrademakers** [comment]
Hi,

Searching on a candidate user will only return tasks with that have that user as a candidate. It doesn't check for the candidate groups. So if you want to include candidate groups in the search as well, then it needs to be done explicitly when doing the task query. Therefore I'm closing the issue.

**Comment by tijsrademakers** [comment]
We recently did a bug fix:

https://github.com/flowable/flowable-engine/commit/d690ec034544649b1c7b359736cb3ad708a67e7a

My statement that candidate user only looks for tasks with the provided candidate user is not correct. When you query on candidate user the Task service will automatically try to get the groups for the candidate user as well.

**Comment by pdsway** [comment]
thank you all!
