### ISSUE TITLE
The changeState method reports an error under the multi-instance node

### ISSUE THREAD

**Issue by opera4130** [flowable/flowable-engine#1122]
I call the changeState method from one multi-instance task node to another node, and the parent Execution cannot be deleted. Error when calling flushDeletes(), foreign key conflict exception.

runtimeService.createChangeActivityStateBuilder().processInstanceId(processInstanceId)
				.moveExecutionsToSingleActivityId(executionIdList, newActivityId).changeState();

Under version 6.3.1

**Comment by tijsrademakers** [comment]
Hi,

We added functionality to provide better support for multi instance nodes. Could you test on the latest master if you still have the issues? (See PR #1150 )

**Comment by opera4130** [comment]
thanks
