### ISSUE TITLE
Flowable and Activiti

### ISSUE THREAD

**Issue by ShuiLianZHu** [flowable/flowable-engine#1127]
I see the document say that : "Flowable is a fork of Activiti (registered trademark of Alfresco)." ,  I want to know why we fork a new one and what difference between them, how to choose which one should I use.

ps: My apologize, I can't find any other way to contact ,so I come here and ask my question;

**Comment by paulhh** [comment]
This is really a topic for the forums, not a code issue.

The team that built Activiti left Alfresco and could not continue working on it with the constraints made by Alfresco, so it was forked.  The original Activiti architects - Joram and Tijs - are now working on Flowable.  Advances have continued to be made in the core engines, including many new features and significant performance improvements.  You can look at the code that's been added to Activiti and Flowable and make the comparison yourself.
