### ISSUE TITLE
API Start Process Error : Could not write JSON: Cannot get process model: no current command context is active; 

### ISSUE THREAD

**Issue by dongwenting** [flowable/flowable-engine#1152]
flowable 6.3.1

runtimeService.startProcessInstanceByKey(processDefinitionKey, variables);

Error message is

org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: Cannot get process model: no current command context is active; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Cannot get process model: no current command context is active (through reference chain: org.flowable.engine.impl.persistence.entity.ExecutionEntityImpl["currentFlowElement"])
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:293)
	

I figure out the reason.

I return processInstance in the controller like fellow, and the error is thrown
@RestController
public class Controller {
@RequestMapping
public ProcessInstance  start(Map<String, Object> model){
   return runtimeService.startProcessInstanceByKey(processDefinitionKey, variables);
}
}

so please close the issue

**Comment by tijsrademakers** [comment]
Thanks for updating the issue with your findings.

**Comment by dongwenting** [comment]
You can not return ProcessInstance  in Controller,  because Spring MVC convert ProcessInstance to JSON which causes the error. So I change the return to boolean. Sorry for my pool English, I try my best to explain.  ^ ^!

```
       @PostMapping(value = "/start")
	public Boolean start(@RequestBody Map<String, Object> model) {
```

**Comment by filiphr** [comment]
Why don't you use the REST API from Flowable? You can start a process instance and do much more with it if you want to.

On top of that there are mappings that would return a clean Response back

**Comment by dongwenting** [comment]
@filiphr  In addition to start a process instance, I do need to do a lot of extra work, like add attachments, set businessKey, set variables, set Initiator etc. I don't know how to do those only by REST API, so I invoke the api
`
ProcessInstance processInstance = runtimeService.startProcessInstanceByKey(processDefinitionKey, businessKey, variables);`

**Comment by filiphr** [comment]
@dongwenting makes sense. Thanks for giving the example.

I would suggest you to create your own DTO that would be returned on your REST call. Something like [`ProcessInstanceResponse`](https://github.com/flowable/flowable-engine/blob/master/modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/process/ProcessInstanceResponse.java). This is the one returned by the Flowable REST API
