### ISSUE TITLE
How to start Flowable in a Apache Karaf container

### ISSUE THREAD

**Issue by ravikmr474** [flowable/flowable-engine#1157]
I’d like to install flowable in Apache Karaf.
How I can run flowable in apache karaf and 
Where I can find a good tutorial?. 
Please suggest 
Regards
Ravi

**Comment by tijsrademakers** [comment]
Hi Ravi,

I'm not aware of such a tutorial. But maybe there are other members of the Flowable community that have experience with this who can help you. The best place to ask is the forum (which you also did I think).

**Comment by ajayhada** [comment]
Hello Tijs Rademakers, 

I also want to run/install flowable  in Apache Karaf, and looking for document or article which explain the same but no luck.  also went through forum but did not get any help from there as well. 

somewhere i read that flowable  will support Karaf soon, is that true?
should I create feature.xml file manually?

thanks in advance.
