### ISSUE TITLE
TaskQuery taskDescriptionLike not work <flowable.version>6.3.1</flowable.version>	

### ISSUE THREAD

**Issue by dongwenting** [flowable/flowable-engine#1164]
TaskQuery taskQuery = taskService.createTaskQuery();
		taskQuery.taskDescriptionLike(taskDescription);
	        List<Task> taskList = taskQuery.orderByTaskCreateTime().asc();
               
               return empty list

**Comment by tijsrademakers** [comment]
What is the taskDescription value you are querying for? Does it have the %someText% structure or just a text value? You need to include the % like operators as well. If it still doesn't work, can you provide a unit test showing the issue?
