### ISSUE TITLE
Support for using java.time.Duration as dueDate for timers

### ISSUE THREAD

**Issue by filiphr** [flowable/flowable-engine#1174]
The [TimerUtil](https://github.com/flowable/flowable-engine/blob/master/modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/TimerUtil.java) is used to create the timer job entity. It would be nice if we support `java.time.Duration` as due time. 

If the expression returns `java.time.Duration` we can set the `dueDateString`

**Comment by lamtrhieu** [comment]
Hi @filiphr 
Can I worked on this one ?

**Comment by filiphr** [comment]
@lamtrhieu I was referring to when the `timeDuration` of the definition is an expression. For example `${customDuration}`. Have a look at the `InstantTimeTimerEventTest` which is a test for supporting `java.time.Instant`. We need to do something similar like that test but just use `java.time.Duration`.

**Comment by lamtrhieu** [comment]
Thanks @filiphr. Let me try with that.

**Comment by filiphr** [comment]
Done in PR #1228. Thanks @lamtrhieu for the contribution
