### ISSUE TITLE
Duplicated "duedatedefinitionpackage" in stencilset_bpmn.json

### ISSUE THREAD

**Issue by rye0catcher** [flowable/flowable-engine#1183]
In the file of stencilset_bpmn.json in module flowable-ui-modeler-logic, there are two "duedatedefinitionpackage" elements defined under "propertyPackages" attribute, located at lines of 217 and 237 respectively.

**Comment by tijsrademakers** [comment]
Thanks for raising the issue, the duplicate has been removed
