### ISSUE TITLE
Http Response variable name miss 

### ISSUE THREAD

**Issue by jianlinz** [flowable/flowable-engine#1197]
Hi:
     when  i  add  a http activity,edit response variable name is 'aaa'.save the process and download it,import it i see the response variable name missing.
     What did I use wrong?
I am honored to receive your reply:)

**Comment by tijsrademakers** [comment]
Hi,

Did you use the Flowable Modeler (web browser), to model the process and perform the steps you are describing?

Best regards,

**Comment by jianlinz** [comment]
Hi,
   yes,i use the Flowable Modeler.

**Comment by tijsrademakers** [comment]
Ok then there's probably a bug in the HTTP activity JSON conversion logic. This needs to be fixed.

**Comment by lamtrhieu** [comment]
Hi @tijsrademakers 
Can I work on this issue ?

**Comment by tijsrademakers** [comment]
@lamtrhieu that would be great!

**Comment by lamtrhieu** [comment]
Ok, let me try to reproduce and fix it.

**Comment by jianlinz** [comment]
Hi
  The first thing to be clear is that I used version 6.2.1.
  I'm sorry that I can't upload large gifs due to upload restrictions, so I split into several img uploads.

1. step1 edit httpTask add response variable name is 'aaa'
![image](https://user-images.githubusercontent.com/30485055/44639632-8cd75400-a9ef-11e8-88d3-9e5179bed0b5.png)

2. step 2 download the xml
![image](https://user-images.githubusercontent.com/30485055/44639687-d0ca5900-a9ef-11e8-8877-357c771c722b.png)

3. step 3 inport the xml
![image](https://user-images.githubusercontent.com/30485055/44639724-fa838000-a9ef-11e8-9351-c1b0e42aebd9.png)


4.step4  you can see the response variable name 'aaa' is missing
![image](https://user-images.githubusercontent.com/30485055/44639742-16872180-a9f0-11e8-8bdb-d7d30c7d510d.png)

I hope I've made that clear
Thank you for your help

**Comment by lamtrhieu** [comment]
Thanks so much @jianlinz. 
That's exactly what I have try to do. But I add an end step to the process, after the Http Activity step. 
And I am using version 6.3.1. Can you please try with 6.3.1 ? 
I will try your steps to see if I can reproduce it on 6.3.1.

**Comment by jianlinz** [comment]
Hi @tijsrademakers @lamtrhieu 

I've seen this bug fixed in version 6.3.1

Thank you for your help
