### ISSUE TITLE
Issues on publishing app from Modeler

### ISSUE THREAD

**Issue by RanjithNair** [flowable/flowable-engine#1198]
I have all the 3 apps running in a docker container :-

- flowable-idm
- flowable-task
- flowable-modeler

From the modeler when i try to publish the app definition, it errors out with the below message :-

> Invalid deploy result code: HTTP/1.1 404

I have set all the required environment variables required for flowable-modeller. As per the documentation, the environment variable which we have to set for deployment is `FLOWABLE_MODELER_APP_DEPLOYMENT-API-URL`. I have set this to `http://<host-ip>:9999/flowable-task/process-api`. Is this correct, because when i hit i am prompted for basic auth and on entering admin and test, it shows 404.

**Comment by yvoswillens** [comment]
Hi.
This has changed recently to http://<host-ip>:<port>/flowable-task/app-api.
I've updated the DockerHub readme.

Regards,

Yvo
