### ISSUE TITLE
HTTP task ignore certificate validation

### ISSUE THREAD

**Issue by gioppoluca** [flowable/flowable-engine#1205]
Is it possible to have the HTTP task to ignore certificate validation for https endpoints?

**Comment by tijsrademakers** [comment]
Good point, this should be added as an option to the HTTP task

**Comment by h7kanna** [comment]
https://flowable.org/docs/userguide/index.html#bpmnHttpTask
disableCertVerify = true did not work?

**Comment by tijsrademakers** [comment]
Thanks @h7kanna for pointing this out. The disableCertVerify option should solve this issue. Please reopen if there's still an issue.
