### ISSUE TITLE
HTTP task set proxy

### ISSUE THREAD

**Issue by gioppoluca** [flowable/flowable-engine#1206]
I have the floable aengine behind company proxy.
How can I set the proxy for each single task?
There could be endpoint internal and is no use to pass to the proxy or external and in this case proxy is needed.
Thanks
Luca

**Comment by tijsrademakers** [comment]
Hi Luca,

This is not within the scope of the Flowable project itself. There are tools available to provide the proxy capability like Nginx and Apache HTTP server etc.

Best regards

**Comment by gioppoluca** [comment]
I'm afraid that my request was not clear.
The HTTP client is located behind a proxy, so to call a service in the internet it needs to set the HTTP_PROXY variable otherwise it will not reach the internet.
Unless the HTTP TASK has an option for setting the http proxy for the httpclient it will not work.
This has nothing to do with proxy tools like nginx or other.
There could be the option to st the http_proxy environment variable for the java process, but it could be interesting to have these options inside the single task since in a process you could have the need to call http endpoints that are within the company networking (and in this case sysadm complains that you are doing a lot of unneeded traffic on the proxy for reaching internal machines) and outside the company network (needing to pass through the proxy).
Please reopen the issue.

**Comment by tijsrademakers** [comment]
Ah ok, sorry, I indeed misunderstood your request. You can use a HttpRequestHandler (like this example https://github.com/flowable/flowable-engine/blob/5208c07986fc80b258fb0d0e029bc4762b823505/modules/flowable-http/src/test/resources/org/flowable/http/bpmn/HttpServiceTaskTest.testGetWithRequestHandler.bpmn20.xml) and set the proxy variable on the http client.

**Comment by tarunp0707** [comment]
HI tijis ,
Httprequesthandler class can reside in any module as long as HttpRequestHandler interface is being implemented ?
I created handler in my project but whatever proxy i am setting in httpclient that is not getting reflected in HttpActivityExecutor class.
code is failing because of proxy .
