### ISSUE TITLE
dataObject definitions fails in xml with laneSet

### ISSUE THREAD

**Issue by Kirinfm** [flowable/flowable-engine#1217]
Hi,
when I define a data object as part of my process, the process can be deployed successful, but the data object definitions didn't work well.
And when I download the XML file, there are no data object label on XML file.
By the way, when the process use laneSet, the issue appears. 
What did I use wrong?

**Comment by Kirinfm** [comment]
@lamtrhieu can u help me fix this issue?

**Comment by lamtrhieu** [comment]
Hi @Kirinfm 
Let me try to reproduce and fix it. Will inform you later.

**Comment by lamtrhieu** [comment]
Hi @Kirinfm 
I try to understand and reproduce your issue but I think I need your help here. In the process modeler app, I seems cannot find the "data object definition" ? Also, what is the laneset ? do you mean lane in swimlanes ?
So I think it's better if you can provide me your process screenshot so I can try to test it locally on my laptop. 

Regards,
Hieu

**Comment by lamtrhieu** [comment]
Hi @Kirinfm 
Thank you so much for detail info. I can reproduce it also with 6.4.0. 
Will do some debug and inform you.

**Comment by Kirinfm** [comment]
@qiudaoke @qiudaoke Thank you so much for taking your time to help fix this issue.
