### ISSUE TITLE
CountingTask (similar to the CountingExecution)

### ISSUE THREAD

**Issue by motorina0** [flowable/flowable-engine#123]
**Purpose**:
 - provide performance improvements by reducing the number of calls to the DB

**Counting Execution approach:**
 - has been implemented in this issue: https://github.com/Activiti/Activiti/pull/971
 - keep a count on executions to avoid deletes
 - an **ExecutionEntityImpl** holds references to lists of:

```
List<EventSubscriptionEntity>
List<JobEntity>
List<TimerJobEntity>
List<TaskEntity>
List<IdentityLinkEntity>
List<VariableInstanceEntity>
```
 - for each of these lists a count flag is kept separately (the **List.size()** can not be used since the lists are not populated in every scenario):
```
int eventSubscriptionCount
int jobCount
int timerJobCount
int taskCount
int identityLinkCount
int variableCount
```
 - two extra counts (no corresponding lists) are kept for
```
int suspendedJobCount
int deadLetterJobCount
```
 - these 8 counts are persisted to the ACT_RU_EXECUTION table (which now has 30 columns!)
 - the counts are increased/decreased in the **insert()/delete()** methods of their corresponding **XXXXEntityManagerImpl**
 - the counts are ONLY checked in the **ExecutionEntityManagerImpl.deleteDataForExecution()** method. Basically the delete is called for an entity only when we are sure that there is something to delete:
```
if (...((CountingExecutionEntity) executionEntity).getXXXXCount() > 0)) {
   //call delete
```
 - the "counting" performance improvement can be enabled/disabled by setting the **enableExecutionRelationshipCounts** property:
```
 	<bean id="processEngineConfiguration" class="...">
		<property name="enableExecutionRelationshipCounts" value="true" />
		...
```

**Counting Tasks approach:**
 - will follow the Counting Execution style
 - an **TaskEntityImpl** hold references to lists of:
```
List<IdentityLinkEntity> getIdentityLinks() 
List<VariableInstanceEntity> getQueryVariables()
```
 - **TaskEntityImpl** also has a Set of candidates (not sure how to be handled):
`public Set<IdentityLink> getCandidates()`
 - A **TaskEntityImpl** can have sub-tasks.  Let ExecutionEntityManager handle the sub-tasks count (together with normal task count)?

**Implementation**
 - add **CountingTaskEntity** interface (implemented by **TaskEntityImpl**)
 - add the two count fields (identityLinkCount and variableCount) to **TaskEntityImpl**
 - update the DB scripts and the persistence logic
 - add the **enableTaskRelationshipCounts**
 - benchmark performance before/after
 - add unit tests

**Comment by tijsrademakers** [comment]
Hi,

Is this something you would like to contribute? Or did you report this issue as an idea to improve performance?

**Comment by motorina0** [comment]
Hi Tij,
  This issue is based on the "Flowable roadmap" wiki page.
  I would like to contribute, but I would like to get some feedback on the approach before I start implementing.

**Comment by tijsrademakers** [comment]
Cool, sub tasks should be handled by the TaskEntityManager I think, because sub tasks are attached to a parent task, not to an execution. The implementation points look good to me.

**Comment by motorina0** [comment]
Implementation completed.  Added unit tests. Updated affected unit tests.

Main changes:
```
ProcessEngine - updated version, added task relationship count
ProcessEngineConfigurationImpl - added flag enableTaskRelationshipCounts
AddIdentityLinkCmd, DeleteIdentityLinkCmd, RemoveTaskVariablesCmd - call task.forceUpdate() in order to update the identityLinkCount
GetIdentityLinksForTaskCmd - minor change
ValidateTaskRelatedEntityCountCfgCmd, CountingTaskEntity - initial commit
AbstractEntityManager - added logic for task reltionship counting flag state (enabled/disabled
IdentityLinkEntityManagerImpl, VariableInstanceEntityManagerImpl - increase/decrease IdentityLinkCount on instert/delete
TaskEntityImpl - implements CountingTaskEntity
TaskEntityManagerImpl - check identityLinkCount and variableCount before delete
TaskDataManager, MybatisTaskDataManager - added updateAllTaskRelatedEntityCountFlags() method
ProfilingDbSqlSession - call super.flushUpdates() after collecting data
TaskServiceTest, VerifyDatabaseOperationsTest, ChangeTaskCountConfigAndRebootEngineTest - added unit tests identityLinkCount and variableCount
DatabaseTablePrefixTest, DatabaseTablePrefixTest - updated unit test after the new flag was added 
Updated SQL Scripts
```
**Implementation Comments**

  - Sub-task Count flag not added (yet) for the following reasons:
    - in order to update the flag a new `update` must be made on the parent task for the `subTaskCount` flag
    - we would add two `update` statements (on sub-task create and delete) in order to remove one `select` statement (select all sub-tasks when the parent task is completed)
    - not sure of the possible **concurrency** side effects if the (parent) TaskEntity is being updated and at the same time a sub-task is being completed (this trying to update the count on the parent).

  - Some Commands now have a `task.forceUpdate()` in order to update the `variableCount` and `indentityLinkCount`: `AddIdentityLinkCmd, DeleteIdentityLinkCmd, RemoveTaskVariablesCmd`

**Comment by tijsrademakers** [comment]
Merged the PR, thanks!
