### ISSUE TITLE
Flowable-modeler. Cannot change process version 

### ISSUE THREAD

**Issue by rgorzkowski** [flowable/flowable-engine#1231]
I'm trying to change process version but it looks like there is a bug in the history selection (dropdown list).

Screen capture showing the issue:
https://streamable.com/nll22

Original post:
https://forum.flowable.org/t/flowable-modeler-cannot-change-process-version/2392

**Comment by vzickner** [comment]
This seems to be resolved by https://github.com/flowable/flowable-engine/pull/1112 (not released yet, since it was merged after the 6.3.1 release)

**Comment by filiphr** [comment]
Thanks for the heads up @vzickner. @rgorzkowski if you try it on master or with the next release and it is still not working please let us know.
