### ISSUE TITLE
Set release debug level to WARN not INFO

### ISSUE THREAD

**Issue by paulhh** [flowable/flowable-engine#1233]
Currently, a lot of logging messages by default - it would be good to reduce the level for distributed releases.

**Comment by karadia10** [comment]
That is a matter of preference, you can reduce the level of logging by adding log property level of rootlogger in application.properties to lower level of logging.
@tijsrademakers what are your remarks?

**Comment by prem911** [comment]
@tijsrademakers How can this be done from the docker images? Can we set something like LOG_LEVEL=DEBUG?

**Comment by yvoswillens** [comment]
@prem911 You can set environment variables to set the desired log level.
When using docker compose you can do something like this;

```
            - LOGGING_LEVEL_ROOT=ERROR
            - LOGGING_LEVEL_ORG_FLOWABLE=DEBUG
```

or when starting a single container;

`docker run -p8080:8080 -e LOGGING_LEVEL_ROOT=ERROR -e LOGGING_LEVEL_ORG_FLOWABLE=DEBUG flowable/flowable-rest`

Hope this helps.

**Comment by tijsrademakers** [comment]
closing issue
