### ISSUE TITLE
flowable-spring-boot-starter-jpa 6.3.1 doesn't exist in maven central repository

### ISSUE THREAD

**Issue by majie1993** [flowable/flowable-engine#1242]
https://mvnrepository.com/artifact/org.flowable/flowable-spring-boot-starter-jpa

The latest version is 6.2.1, forgot to deploy to maven？

**Comment by tijsrademakers** [comment]
No, we don't have a starter with JPA starting from version 6.3 anymore, because the starter wasn't really providing any additional functionality.
