### ISSUE TITLE
 Flowable IDM saves passwords in plain text 

### ISSUE THREAD

**Issue by nickmancol** [flowable/flowable-engine#1253]
I have installed the Flowable IDM v6.3.1 and noticed that in postgres (v10) it saves passwords in plain text.

``sql
select * from act_id_user ;
``
results in
    id_     | rev_ | first_  |     last_     |            email_             |      pwd_      | picture_id_ | tenant_id_ 

 admin      |    3 | Alephsa | Administrator | sample@example.com               | EarthwormJ1m     |             | 

 nickmancol |    2 | Nicolas | Bohorquez     | nicolas@example.com | aWeirdPass@ |             |

**Comment by tijsrademakers** [comment]
In early releases of Flowable 6 the password was stored plain text. To not break the backwards compatibility this is still the case if you run the IDM engine. But for example our Spring boot 2 integration uses the Spring PasswordEncoder:

https://github.com/flowable/flowable-engine/blob/master/modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/idm/IdmEngineAutoConfiguration.java

You can define your own PasswordEncoder on the IdmEngineConfiguration, like for example the ApacheDigester PasswordEncoder we provide with the IDM engine:

https://github.com/flowable/flowable-engine/blob/master/modules/flowable-idm-engine/src/main/java/org/flowable/idm/engine/impl/authentication/ApacheDigester.java

**Comment by dnavre** [comment]
@tijsrademakers It's not that hard to move to lets say blowfish and also keep backward compatibility. you can just add a column specifying if the password is in plain text or blowfish and use blowfish only if the extra table says that.

Storing passwords in plain text is really-really bad :) even on the development server. One of the developers can type in their 'real' password without knowing that their colleagues can see it.

Please do something about this. It's an unexpected bad surprise from such a nice product.

**Comment by filiphr** [comment]
@tijsrademakers perhaps we can use the `spring_delegating_noop` option for the IDM apps. This would mean that all old passwords will work as the noop encoder would be used to match them, but all new passwords will be done with the bcrypt. I think that this is still backwards compatible, as if someone has overridden the property that would still take precedence.

@dnavre would you like to try this out and provide a PR with the change? There is no need for new columns, spring security is quite powerful 😄.

**Comment by tijsrademakers** [comment]
@filiphr does this mean that the noop option is used as a fallback in case the normal password encoder doesn't match? So this would basically mean that in case of a wrong password the noop encoder will always be tried as well (just to understand, not that this is a bad thing).

**Comment by filiphr** [comment]
@tijsrademakers nope. The `DelegatingPasswordEncoder` encodes the password with the prefix `{id}` where the id is the type of the encoder that it was used to encode the password.  

When it performs the [match](https://github.com/spring-projects/spring-security/blob/a7a9271313f50205c89dd8a91f815ab9c15a1308/crypto/src/main/java/org/springframework/security/crypto/password/DelegatingPasswordEncoder.java#L190). It will try to extract the id for the encoder. If it can't find an id (and it won't find as the passwords won't have that, it will fallback to using the default encoder (in the `spring_delegating_noop` case the default encoder is the noop encoder). The only problem can be if the passwords are contain both `{` and then `}` in them.

The password will only be matched once.

**Comment by dnavre** [comment]
@filiphr This also won't work if some bright mind has set his password to a string resembling bcypt encoded hash :D for those users authorization will break.

I'm honestly, not sure if I can work on this, we're still evaluating flowable so we don't even know yet if we're going to use it :) Once we have that decision, we'll think! I'm just trying to be of help.
