### ISSUE TITLE
ExclusiveGateway sequenceFlowOrder

### ISSUE THREAD

**Issue by Clinan** [flowable/flowable-engine#1267]
in modeler, I can define ExclusiveGateway sequenceFlowOrder ,but I can not get sequenceFlowOrder in ExclusiveGateway instance. 
mostly, I can't file the sequenceFlowOrder info under ExclusiveGateway element in the export bpmn20.xml file.

**Comment by tijsrademakers** [comment]
The sequence flow order is used to determine the export order in the BPMN XML. This means you can get the order of the sequence flows while looping through the FlowElements in the BpmnModel / Process instance of the process definition.

**Comment by Clinan** [comment]
Thank you
