### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/ibatis/transaction/TransactionFactory

### ISSUE THREAD

**Issue by avinash969** [flowable/flowable-engine#1273]
I am new to flowable. I am following flowable documents for getting started. I used the code mentioned in their documents. I am getting this error

java.lang.NoClassDefFoundError: org/apache/ibatis/transaction/TransactionFactory

Following is my code:

pom.xml
<dependencies>
  <dependency>
    <groupId>org.flowable</groupId>
    <artifactId>flowable-engine</artifactId>
    <version>6.3.1</version>
  </dependency>
  <dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
    <version>1.3.176</version>
  </dependency>
  
  <dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-api</artifactId>
  <version>1.7.21</version>
</dependency>
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-log4j12</artifactId>
  <version>1.7.21</version>
</dependency>

</dependencies>

App.java
public static void main(String[] args) {
	    ProcessEngineConfiguration cfg = new StandaloneProcessEngineConfiguration()
	      .setJdbcUrl("jdbc:h2:mem:flowable;DB_CLOSE_DELAY=-1")
	      .setJdbcUsername("sa")
	      .setJdbcPassword("")
	      .setJdbcDriver("org.h2.Driver")
	      .setDatabaseSchemaUpdate(ProcessEngineConfiguration.DB_SCHEMA_UPDATE_TRUE);

	    ProcessEngine processEngine = cfg.buildProcessEngine();
	  }

This is the link for doccument which I am following: https://www.flowable.org/docs/userguide/index.html#_getting_started

Error I am getting:

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/ibatis/transaction/TransactionFactory
	at com.flowable.example.App.main(App.java:80)
Caused by: java.lang.ClassNotFoundException: org.apache.ibatis.transaction.TransactionFactory
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more

**Comment by tijsrademakers** [comment]
Closing the issue based on Filip's feedback. Please reopen if this is still an issue.
