### ISSUE TITLE
IntermediateCatchSignalEventActivityBehavior dispatches the create event using signal Id instead of signal name

### ISSUE THREAD

**Issue by DennisFederico** [flowable/flowable-engine#1277]
The execute part of the behavior is dispatching the SignalWaiting event using the SignalId instead of the Signal Name as expected per the Event ... see below link
[https://github.com/flowable/flowable-engine/blob/eeebfd23af3571741b60e3f663f17c0ecc50a812/modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/IntermediateCatchSignalEventActivityBehavior.java#L52](url)

**Comment by tijsrademakers** [comment]
Closing issue
