### ISSUE TITLE
JavaScript not supported by flowable-task running in Docker container

### ISSUE THREAD

**Issue by cdeneux** [flowable/flowable-engine#1286]
I'm using the Flowable's docker images to start Flowable apps.

If I use a script task implemented using JavaScript, I get the error : `Can't find scripting engine for 'JavaScript'`.

The error is due to the JVM embedded in the Docker container. It must be a JDK instead of the JSE.

**Comment by PascalSchumacher** [comment]
I wondering if this issue was fixed by https://github.com/flowable/flowable-engine/commit/d1a84e0a9ce21b7a2988d39e992bdbc6ba7360e6?

**Comment by cdeneux** [comment]
Yes @PascalSchumacher, very probably as a JDK seems to be embedded into the Flowable Docker base image.

When a new version of Flowable Docker images will be published, I could check that the error is fixed. I'm not a Docker expert, and I don't know how to re-build all Flowable Docker images from their source code. If you have some pointers on how to do this, I can try to build Flowable Docker images and test them before their publication.

Regards

**Comment by yvoswillens** [comment]
Yes. The base image we currently used did not have Nashorn included.
I'm currently creating a new base image that will be used for the Docker images that will be published as part of the new release.
This new base image does include Nashorn (and some other updates).

@cdeneux If you can wait until next Monday or Tuesday you don't have to build the base image yourself (and rebuilding the current images)

**Comment by yvoswillens** [comment]
They will be published as part of the release that will be available next Monday or Tuesday.
I already did some testing regarding the Javascript script tasks.
Are there some other things I can take into account?

**Comment by cdeneux** [comment]
Perfect @yvoswillens 

I don't think that is linked but Groovy script tasks worked well into Flowable UI Task running as Docker container. Is this still the case?

**Comment by yvoswillens** [comment]
Yes. That shouldn't be affected. But I'll extra check.

**Comment by tijsrademakers** [comment]
Issue should be resolved
