### ISSUE TITLE
IntermediateCatchEventActivityBehavior generates incorrect SQL

### ISSUE THREAD

**Issue by FranPregernik** [flowable/flowable-engine#1295]
Hi,

We had a simple process, start->serviceTask->eventGateway->intermediateCatchEvent(signal)->serviceTask->end.

The event gateway had only one outgoing flow.
When we issued the signal an SQL exception would happen saying the SQL was incorrect.

We tracked this issue down to https://github.com/flowable/flowable-engine/blob/flowable-6.3.1/modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/IntermediateCatchEventActivityBehavior.java#L107

Happens when the eventActivityIds is empty. The SQL is using that list in a IN clause and since it is empty the generated SQL is wrong.

Br,
Fran

P.S. We removed the event gateway and all is good so this is not a priority for us: 
start->serviceTask->intermediateCatchEvent(signal)->serviceTask->end

**Comment by jbarrez** [comment]
Thanks! Good find and spot-on analysis.
