### ISSUE TITLE
6.4.0Version stencilset_bpmn.json

### ISSUE THREAD

**Issue by chonianxi** [flowable/flowable-engine#1335]
in 6.4.0Version stencilset_bpmn.json resources path save where?

**Comment by qiudaoke** [comment]
He is in this directory flowable-engine/modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/resources
![image](https://user-images.githubusercontent.com/17612111/46591431-49433000-caed-11e8-9448-d85f9fe4a468.png)
@chonianxi

**Comment by tijsrademakers** [comment]
Please use the Flowable forum for questions.
