### ISSUE TITLE
Eclipse designer plugin not working

### ISSUE THREAD

**Issue by samuel-petit** [flowable/flowable-engine#1337]
Hi,

When trying to follow the documentation (see https://flowable.org/docs/userguide/index.html#eclipseDesignerInstallation ), plugin isn't available at this URL

**Comment by tijsrademakers** [comment]
Hi,

Did you test this url using the Software Install dialog in Eclipse or via a browser? Via the browser this url doesn't work, it only works with the Software install dialog in Eclipse.

**Comment by samuel-petit** [comment]
Hi,
Thanks for your return. Test is on eclipse, and here is the screenshot associated to this issue:

![error](https://user-images.githubusercontent.com/44020687/46725661-f4ceba80-cc7c-11e8-8a9f-ccd2c40fcb7e.PNG)

**Comment by tijsrademakers** [comment]
Ok thanks, if that doesn't work then you can also fetch an archived plugin directly from http://flowable.org/designer/archived/flowable-designer-5.22.0.zip and then install from your local drive
