### ISSUE TITLE
how to get next tasks in flowable

### ISSUE THREAD

**Issue by dongwenting** [flowable/flowable-engine#1338]
I find old activiti example. but the interface not found any more.
`
   ProcessDefinitionEntity pde = (ProcessDefinitionEntity)   repositoryService.getProcessDefinition(processDefinitionId); 
    List<ActivityImpl> activitiList = pde.getActivities();
`
here is the link https://blog.csdn.net/junlong750/article/details/50925705
how to get next tasks in flowable ? thank you !

**Comment by tijsrademakers** [comment]
The Flowable API uses the BpmnModel instance as a Java representation of the BPMN XML file. You can use RepositoryService.getBpmnModel(processDefinitionId) to get the BpmnModel for a specific process definition. From there you can use getFlowElement on the BpmnModel instance to get a specific FlowElement / Activity and get all outgoing sequence flows to get a list of upcoming flow elements / activities.
