### ISSUE TITLE
Comments are not preserved when you import a bpmn file into the modeler, make a change and then export.

### ISSUE THREAD

**Issue by urayoan** [flowable/flowable-engine#1340]
I just noticed that the comments that I put into my bpmn20.xml file were gone after I exported my process. Is this intentional?

Thanks,
Ura

**Comment by tijsrademakers** [comment]
Hi Ura,

You are referring to comments like  right?
No, those comments are not preserved.

**Comment by tijsrademakers** [comment]
Closing issue, because XML comments are not preserved when exporting a process. Instead a data object or the documentation field can be used
