### ISSUE TITLE
Flowable6.4.0  Spring boot 1.5.X

### ISSUE THREAD

**Issue by chonianxi** [flowable/flowable-engine#1341]
Flowable 6.4.0 How to configure spring boot 1.5.X;By Spring-core-4.3.9.RELEASE

**Comment by lamtrhieu** [comment]
When reading the pom https://github.com/flowable/flowable-engine/blob/master/pom.xml I think version 6.4.0 is using spring boot version 2.0.6.RELEASE. 

If you want to use spring boot 1.5.X then you should find older release of flowable. 

Or you can try to edit the pom, edit the spring boot version to 1.5.x and build the project locally.

**Comment by filiphr** [comment]
In order to use Spring Boot 1.5.x one needs to use the appropriate parent from Spring Boot for that version.

So to use it you need to have

```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-dependencies</artifactId>
    <version>1.5.17.RELEASE</version>
    <relativePath/> <!-- lookup parent from repository -->
</parent>
```
