### ISSUE TITLE
Flowable Modeler, Listeners not exported to BPMN when using Swimlanes (laneSet).

### ISSUE THREAD

**Issue by quetico** [flowable/flowable-engine#1372]
Hello,

There is an issue when using Flowable Modeler (v 6.4.0), where process Event and Execution Listeners are not exported to the BPMN file when using swimlanes.

1. Create a new process (with no Pool or Lanes) and define an Event or Execution listener. Save.

2. Export BPMN file and confirm listener is present.

3. Return to model and add a swimlane (Pool). Save.

4. Export BPMN file and confirm listener is no longer present. 

Thank you.

**Comment by PascalSchumacher** [comment]
I guess this can be closed as the pull request was merged and the fix was released with flowable `6.4.1`?

**Comment by kmgenoguin** [comment]
Hi all,

May I add that the targetNamespace as well as the candidateStarterGroups are also not exported whenever swimlanes are involved.

Thanks
