### ISSUE TITLE
How to update hi_varinst data？Can you give me a example. Thank you so much.

### ISSUE THREAD

**Issue by Clinan** [flowable/flowable-engine#1388]
How to update hi_varinst data？Can you give me a example. Thank you so much.

**Comment by Clinan** [comment]
This is not good, I just want to update the end process history variable.
If the process running, can use it:
`runtimeService.setVariable()`

**Comment by tijsrademakers** [comment]
Hi Clinan,

Please use the forum to ask questions about the Flowable Engine. The Flowable Engine service api only allows you to update variables while the process instance is running. If you want to modify a variable of an ended process instance, you can do this using the HistoricVariableInstanceEntityManager running the logic within a Command like youlingke was already sharing.

Best regards,

Tijs
