### ISSUE TITLE
Bug! Meaningless line of code

### ISSUE THREAD

**Issue by Clinan** [flowable/flowable-engine#1390]
org/flowable/variable/service/impl/persistence/entity/HistoricVariableInstanceEntityManagerImpl.java:63
The method `copyVariableValue(historicVariableInstance, variableInstance);` already set it.

**Comment by tijsrademakers** [comment]
Thanks for pointing at the duplicate line, but calling this a bug with an exclamation mark feels a bit too much for this. We'll make sure it gets cleaned up.
