### ISSUE TITLE
DynamicBpmnService changeSequenceFlowCondition not work

### ISSUE THREAD

**Issue by winterzhuang** [flowable/flowable-engine#1393]
ObjectNode objectInfo = DynamicBpmnService.changeSequenceFlowCondition(id, condition);
DynamicBpmnService.saveProcessDefinitionInfo(processDefinitionId, objectInfo);
butSequenceFlow condition is still null, what i miss?

**Comment by tijsrademakers** [comment]
Hi, did you set enableProcessDefinitionInfoCache to true for the process engine configuration? By default this is set to false, because it has some performance impact to lookup the dynamic process definition info.

**Comment by tijsrademakers** [comment]
Yes that is correct, how did you validate that the sequence flow condition was still null?

**Comment by winterzhuang** [comment]
> Yes that is correct, how did you validate that the sequence flow condition was still null?

thx, 
My code:

 BpmnModel bpmnModel = repositoryService.getBpmnModel(processDefinitionId); 
 org.flowable.bpmn.model.Process process = bpmnModel.getMainProcess();
 FlowNode userTaskNode = (FlowNode) process.getFlowElement(taskDefinitionKey);
 List<SequenceFlow> outgoingFlows = userTaskNode.getOutgoingFlows();
 for (SequenceFlow outgoingFlow : outgoingFlows) {
	String value = outgoingFlow.getConditionExpression();
	### value is null??
 }

thanks again ^v^

**Comment by tijsrademakers** [comment]
Thanks,

Please look at this ConditionUtil class in the BPMN engine code.

https://github.com/flowable/flowable-engine/blob/eeebfd23af3571741b60e3f663f17c0ecc50a812/modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/condition/ConditionUtil.java#L36

Here you can see that the sequence flow condition is retrieved from the process definition info table when enableProcessDefinitionInfoCache is set to true. And if a value can be retrieved this value is used for the sequence flow condition.

**Comment by winterzhuang** [comment]
Hi,
 I test the code, and found cache is enabled, but when I do 'DynamicBpmnService.saveProcessDefinitionInfo' one more time(for loop), 
last sequence condition will be found but others are still null, that's really weird.

**Comment by tijsrademakers** [comment]
When changing the process definition info for multiple sequence flows it's important to use the ObjectNode after the first insert. So like this:

ObjectNode objectInfo = dynamicBpmnService.changeSequenceFlowCondition(id, condition);
dynamicBpmnService.changeSequenceFlowCondition(id2, condition2, objectInfo);
dynamicBpmnService.changeSequenceFlowCondition(id3, condition3, objectInfo);
dynamicBpmnService.saveProcessDefinitionInfo(processDefinitionId, objectInfo);

**Comment by winterzhuang** [comment]
nice, it's work!  thanks
