### ISSUE TITLE
about Authentication

### ISSUE THREAD

**Issue by jianlinz** [flowable/flowable-engine#1417]
Hi,
     There is some confusion about org.flowable.common.engine.impl.identity.Authentication in flowable6.4.0.
     Authentication.getAuthenticatedUserId is static, the  authenticationContext = new UserIdAuthenticationContext(),any time I use it, it's a new instance.
    ExecutionEntityManagerImpl line 250(String authenticatedUserId = Authentication.getAuthenticatedUserId()),when i use  identityService.setAuthenticatedUserId("aa"),
i think Authentication.getAuthenticatedUserId() is null.

Is there something wrong with my understanding.Thanks.

**Comment by filiphr** [comment]
Just to clarify this a bit. 

The `authenticationContext` is also static and is created when the class is created. It can be changed to something else. And when using Spring Boot it uses the `SpringAuthenticationContext` which behind the scenes uses the `SecurityContextHolder` to get the authentication.
