### ISSUE TITLE
Call to equals() with different types

### ISSUE THREAD

**Issue by dbmalkovsky** [flowable/flowable-engine#142]
In the `flowable-ui-task` module there is a class, `org.flowable.app.service.runtime.PermissionService`.  The class has a method, `canDeleteProcessInstance()`:

<pre>
public boolean canDeleteProcessInstance(User currentUser, HistoricProcessInstance processInstance) {
    boolean canDelete = false;
    if (processInstance.getStartUserId() != null) {
      try {
        Long starterId = Long.parseLong(processInstance.getStartUserId());
        canDelete = starterId.equals(currentUser.getId());
      } catch (NumberFormatException nfe) {
        // Ignore illegal starter id value
      }
    }

    return canDelete;
  }
</pre>

It appears that a `String` value of the `currentUser`'s `id` is being compared to a `Long` value that originally was a `String` value for the user that started the process.

This just doesn't look right or am I missing something?

**Comment by tijsrademakers** [comment]
Thanks for raising the issue David. It should be a String comparison, now all ids are just Strings. I'll commit a fix.

**Comment by tijsrademakers** [comment]
Fixed
