### ISSUE TITLE
how to modify "activityFontName"  "labelFontName" "annotationFontName" in flowable-rest.war 6.4.0

### ISSUE THREAD

**Issue by awliern** [flowable/flowable-engine#1425]
GET /runtime/process-instances/{processInstanceId}/diagram ,this api has problems if has Chinese,so i want to modify these properties?

**Comment by awliern** [comment]
but in other war ,likes flowable-admin,doesnot has this problems，it can display the diagram correct ，even if has chinese in processdefinition

**Comment by qiudaoke** [comment]
@awliern  
You can look at the following PR https://github.com/flowable/flowable-engine/pull/1339/files

**Comment by filiphr** [comment]
The properties can be set via `flowable.activity-font-name`, `flowable.label-font-name` and `flowable.annotation-font-name`. 

Keep in mind that this has not yet been released. It would be part of the next 6.4.1 release.
