### ISSUE TITLE
Difference in USERS for process and idm of flowable-rest-api

### ISSUE THREAD

**Issue by lohiavivek** [flowable/flowable-engine#1427]
Is there any difference between creating users for process and idm of flowable-rest-api?Or are both the same thing?

**Comment by filiphr** [comment]
@lohiavivek please use our [forum](https://forum.flowable.org/) for asking questions.

Which endpoints are you talking about? If you are referring to the endpoints that are under `/identity` from the `process-api` and the ones from `idm-api` then there is no difference. They are modifying the same tables.
