### ISSUE TITLE
Unsupported variable query operation: EQUALS

### ISSUE THREAD

**Issue by awliern** [flowable/flowable-engine#1437]
flowable-rest.war 6.4.0 
POST /query/historic-process-instances
when the parameters like :
{
  "variables": [
    {
      "name": "applyUserId",
      "operation": "EQUALS",
      "value": {},
      "type": "string",
      "variableOperation": "EQUALS"
    }
  ]
}

the respose is :
{
  "message": "Bad request",
  "exception": "Unsupported variable query operation: EQUALS"
}

**Comment by tijsrademakers** [comment]
Hi,

Please have a look at the docs for a good example on how to query using variables:

https://docs.flowable.org/docs/userguide/index.html#_query_for_historic_process_instances

The operation property should be lowercase equals.

**Comment by awliern** [comment]
> Hi,
> 
> Please have a look at the docs for a good example on how to query using variables:
> 
> https://docs.flowable.org/docs/userguide/index.html#_query_for_historic_process_instances
> 
> The operation property should be lowercase equals.

thank you! 
![image](https://user-images.githubusercontent.com/20470677/49620839-a2501700-f9fd-11e8-976c-22d2302ea9ff.png)
in the swagger(/flowable-rest/docs),it is uppercase ,next time ,I will see the userguide,not for the swagger examples
