### ISSUE TITLE
UserTask gets skipped after exclusive gateway

### ISSUE THREAD

**Issue by ArcMarkus** [flowable/flowable-engine#1439]
Hello, i createad that simple test proces to show my Problem:

![testprocess](https://user-images.githubusercontent.com/45625424/49508774-d6073180-f883-11e8-9ece-40db268346f0.PNG)

In the start of the process a class will be executed to check if all relevant data to send a message automatically is available. After that the result will be checked in the flow conditions after Exclusive Gateway. 
**My Problem is here**, that if we go to the UserTask"Create Message manually" (Data was not valid, so the user has to create the message manually) it will be skipped automatically so the process is instant in the State "TestTask". 
The UserTask "Create Message manually" though is still available as UserTask. In the Process State History is the UserTask "Create Message manually" available and has a start and enddate which is equal.

If i put some other element before the UserTask"Create Message manually" like another gateway or a ServiceTask it will work perfectly fine, but this is not the best option to avoid this problem.

If i changed the gateway type to Inclusive Gateway it is also working as intend, but this is also not really the best solution.

Do you have an idea to this problem? Thanks in advanced

My BPMN Process (.xml) is attached:

[Test_Process.bpmn20.xml.zip](https://github.com/flowable/flowable-engine/files/2648491/Test_Process.bpmn20.xml.zip)

**Comment by martin-grofcik** [comment]
Hi Marcus,
Could you reproduce the issue in more simple jUnit test please? (Just a simple process model without external calls)
There are exclusiveGateway tests in the flowable source (e.g. org.flowable.engine.test.bpmn.gateway.ExclusiveGatewayTest#testDefaultSequenceFlow) which test this functionality.

Regards
Martin

**Comment by martin-grofcik** [comment]
Hi Markus.

ExecutionListener should be able to add variable too. (e.g `org.flowable.examples.bpmn.executionlistener.ExampleExecutionListenerOne`) in flowable source code.
Could you reproduce the issue?

Regards
Martin

**Comment by ArcMarkus** [comment]
Hi Martin,

yes i can reproduce this case in a java testclass. (.java and bpmnprocess is in the zip)

The Process is the process i posted before and as Execution Listener i took the class itself to add the "valid" variable for the flow condition.

What happen here is that there will be 2 open Tasks and it should only be the one: "Create Message manually" because i never completed the task. Also the List<HistoricActivityInstance> contains both usertask activities and the "Create Message manually" has already an end date.

Does this help you to reproduce the issue or do you need anything more?

Best regards!

The class:

public class FlowableUserTaskExclusiveGateWayTest implements JavaDelegate{
	
	private static ProcessEngine engine = null;

	@Test
	public void test() {
		Deployment deployment = engine.getRepositoryService()
				.createDeployment()
				.addClasspathResource("Test_Prozess.bpmn20.xml")
				.deploy();
		
		Map<String, Object> processVariables = new HashMap<String, Object>();
		processVariables.put("valid", false);
		
		ProcessInstance processInstance = engine.getRuntimeService().startProcessInstanceByKey("PITest", processVariables);
		
		List<Task> tasks = engine.getTaskService().createTaskQuery().list();
		
		List<HistoricActivityInstance> statusHistory= engine.getHistoryService().createHistoricActivityInstanceQuery()
				.processInstanceId(processInstance.getProcessInstanceId())
				.list();
		
		assertTrue(tasks.size() == 1);
	}
	
	@Before
	public void initTest() {
		ProcessEngineConfiguration flowableConfig = new StandaloneProcessEngineConfiguration()
				.setJdbcUrl("jdbc:postgresql://localhost:5432/postgres")
				.setJdbcUsername("postgres")
				.setJdbcPassword("admin")
				.setDatabaseSchemaUpdate("drop-create");
		
		engine = flowableConfig.buildProcessEngine();
	}

	@Override
	public void execute(DelegateExecution execution) {
		engine.getRuntimeService().setVariable(execution.getProcessInstanceId(), "valid", false);
	}
}

[Testcase.zip](https://github.com/flowable/flowable-engine/files/2649255/Testcase.zip)

**Comment by tijsrademakers** [comment]
Hi Markus,

I've tested your example process and unit test and the problem is that the test class should not implement the JavaDelegate interface but the org.flowable.engine.delegate.ExecutionListener interface. Then the valid variable is set to false and the behaviour is as expected.

Best regards,

Tijs
