### ISSUE TITLE
Fix (or disable) failing azure build

### ISSUE THREAD

**Issue by PascalSchumacher** [flowable/flowable-engine#1441]
It would be great if the azure build introduced in https://github.com/flowable/flowable-engine/commit/4a779bac29093c644e62b19c8bcb47cff2fefe72 was fixed (or disabled).

Imho it is annoying to see every commit and every pull request marked as failed by github because of  the azure build is always failing.

Thanks!

**Comment by jacarui** [comment]
Hi Pascal,

The problem is that is being built with JDK 11:

`2018-12-09T22:54:30.5828273Z ##[warning]JDK 9 and JDK 10 are out of support. Please switch to a later version in your project and pipeline. Attempting to build with JDK 11...`

Could be changed to JDK 8 or removed if it's not useful.

**Comment by filiphr** [comment]
@PascalSchumacher the azure build has been disabled for now. Once we move to JDK 11 support (we haven't forgotten your PR) we might introduce it again 😄.

**Comment by PascalSchumacher** [comment]
Thanks! :+1: :smile:
