### ISSUE TITLE
Mail Server Configuration for different tenant id

### ISSUE THREAD

**Issue by lohiavivek** [flowable/flowable-engine#1457]
How to set Mail Server Configuration for different tenant id?....Where is the mail server configuration stored in db?Can we access them using REST API?

**Comment by tijsrademakers** [comment]
Here you can find an example that sets a mail server for one tenant id (myEmailTenant):

https://github.com/flowable/flowable-engine/blob/master/modules/flowable-engine/src/test/resources/flowable.cfg.xml

**Comment by lohiavivek** [comment]
@tijsrademakers Help me understand this little more.
I have tenant1 who needs to send mail from sender@tenant1.com

When I get one more tenant say tenant2 and he needs to send using sender@tenant2.com, do I need to make changes to this cfg and spin the server over again? How can this be acheived at runtime?

Can this be achieved using the REST API?
