### ISSUE TITLE
how to get completedSequenceFlows in flowable?

### ISSUE THREAD

**Issue by sscfaith** [flowable/flowable-engine#1465]
how to get completedSequenceFlows in flowable?
thank you!

**Comment by tijsrademakers** [comment]
We have introduced runtime activity instances in the master branch and registering completed sequence flows will be part of this as well. For Flowable versions up until 6.4.0 you can use the Historic activity instance query in the HistoryService to get all completed activities. The completed sequence flows can then be calculated based on these completed activities.
