### ISSUE TITLE
POST /form/form-data

### ISSUE THREAD

**Issue by Robinyo** [flowable/flowable-engine#1473]
Using Flowable's REST API to submit task form data:

```
curl -H "Content-Type: application/json" 
     -X POST http://admin:test@localhost:8080/flowable-task/process-api/form/form-data 
     -d "@data-2.json"
```

data-2.json:

```
{
  "taskId" : "1fae489a-070f-11e9-a85e-0242ac110002",
  "properties" : [
    {
      "id": "givenName",
      "name": "Given Name",
      "type": "string",
      "value": "Rob"
    },
    {
      "id": "familyName",
      "name": "Family Name",
      "type": "string",
      "value": "Ferguson"
    },
    {
      "id": "employeeNumber",
      "name": "Employee Number",
      "type": "integer",
      "value": 123456
    },
    {
      "id": "fromDate",
      "name": "From Date",
      "type": "date",
      "value": "2018-12-21T00:00:00+00:00"
    },
    {
      "id": "toDate",
      "name": "To Date",
      "type": "date",
      "value": "2019-01-07T00:00:00+00:00"
    }
  ]
}
```

Returns:

```
Status: 204 No Content
```

However it appears to save the User task's form data (and completes the User task):

![form-data](https://user-images.githubusercontent.com/12203540/50456764-dd18ef80-09aa-11e9-9a09-cea8d352dbdf.png)

See: https://robferguson.org/blog/2018/12/24/flowable-rest-api-part-1/

**Comment by tijsrademakers** [comment]
The form REST API that's part of the Flowable REST module can be used to work with form properties. When using the form JSON definitions used in the Flowable Task application this REST service can not be used. Instead use the REST services explained in my comment here:

https://github.com/flowable/flowable-engine/issues/1471
