### ISSUE TITLE
JSON body parameters

### ISSUE THREAD

**Issue by Robinyo** [flowable/flowable-engine#1474]
The JSON representation of a form model:

```
    "fields": [
        {
            "fieldType": "FormField",
            "id": "givenName",
            "name": "Given Name",
            "type": "text",
            "value": null,
            "required": true,
            "readOnly": false,
            "overrideId": true,
            "placeholder": "",
            "layout": null
        },
    
        ...
    
    ]
```

Uses  "type": "text"

To update a Task:

```
{
  "action" : "complete",
  "variables" : [
    {
        "id": "givenName",
        "name": "Given Name",
        "type": "string",
        "value": "Rob"
    },

    ...

  ]
}
```

Uses  "type": "string"

The Users Guide re [JSON body parameters](https://www.flowable.org/docs/userguide/index.html#restJsonBody) refers to 'String'.

**Comment by tijsrademakers** [comment]
There is no direct naming relationship between the variable types used in the Engines and the form definition field types. text fields translate into string variable types, number fields translate into long variable types.
