### ISSUE TITLE
docker all-in-one build issues

### ISSUE THREAD

**Issue by prem911** [flowable/flowable-engine#1476]
After making some changes to the modeler ui, I wanted to get the all-in-one image created.
Ran docker/all-in-one/build.sh 

...

Copying artifact
cp: directory /Users/prem/work/flowable-engine/docker/all-in-one/assets does not exist
Building Docker image
Sending build context to Docker daemon  7.168kB
Step 1/17 : FROM flowable/java8_server:8.181
 ---> 9300a513c18b
Step 2/17 : ADD wait-for-something.sh .
 ---> Using cache
 ---> 6bb8920225d3
Step 3/17 : RUN addgroup tomcat && adduser -s /bin/false -G tomcat -h /opt/tomcat -D tomcat
 ---> Using cache
 ---> b2da0c7f4973
Step 4/17 : RUN wget http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.34/bin/apache-tomcat-8.5.34.tar.gz -O /tmp/tomcat.tar.gz
 ---> Using cache
 ---> 7958ec1ffd43
Step 5/17 : RUN cd /tmp && tar xvfz tomcat.tar.gz && cp -Rv /tmp/apache-tomcat-8.5.34/* /opt/tomcat/ && rm -Rf /tmp/apache-tomcat-8.5.34
 ---> Using cache
 ---> ce34315c8515
Step 6/17 : COPY assets/flowable-idm.war.original /opt/tomcat/webapps/flowable-idm.war
COPY failed: stat /var/lib/docker/tmp/docker-builder681604995/assets/flowable-idm.war.original: no such file or directory

Any idea how this can be fixed?

**Comment by Robinyo** [comment]
See: [How to build Flowable from source](https://forum.flowable.org/t/how-to-build-flowable-from-source/3174)

**Comment by tijsrademakers** [comment]
Thanks Rob
