### ISSUE TITLE
Tenant Id attribute not returned for REST API /identity/users

### ISSUE THREAD

**Issue by lohiavivek** [flowable/flowable-engine#1479]
Created User with tenantId using POST REST API call to localhost:9080/flowable-rest/service/identity/users
BODY : 
    {
      "id": "user2",
      "firstName": "user",
      "lastName": "2",
      "displayName": "user 2",
      "email": "user2@example.com",
      "tenantId": "tenant2",
      "password": "something"
    }

A GET call on localhost:9080/flowable-rest/service/identity/users/user2 doesnot return tenantId
Response :
    {
        "id": "user2",
        "firstName": "user",
        "lastName": "2",
        "displayName": "user 2",
        "url": "http://localhost:9080/flowable-rest/service/identity/users/user2",
        "email": "user2@example.com",
        "pictureUrl": null
    }
![image](https://user-images.githubusercontent.com/17848089/50560317-b699e200-0d25-11e9-9139-fed654ac6621.png)
As per the swagger documentation, we should get the following
{
  "data": [
    {
      "id": "testuser",
      "firstName": "Fred",
      "lastName": "Smith",
      "displayName": "Fred Smith",
      "url": "http://localhost:8182/identity/users/testuser",
      "email": "no-reply@flowable.org",
      **"tenantId": "companyTenantId",**
      "pictureUrl": "http://localhost:8182/identity/users/testuser/picture",
      "password": "string"
    }
  ],
  "total": 0,
  "start": 0,
  "sort": "string",
  "order": "string",
  "size": 0
}

**Comment by Robinyo** [comment]
I'm using the **flowable/all-in-one** Docker image.

See: [Getting started with Flowable}(https://robferguson.org/blog/2018/12/10/getting-started-with-flowable/)

GET [identity/users](https://www.flowable.org/docs/userguide/index.html#_get_a_list_of_users)

```
curl -i 'http://admin:test@localhost:8080/flowable-task/process-api/identity/users'
````

Returns:

```
{
    "data": [
        {
            "id": "admin",
            "firstName": "Test",
            "lastName": "Administrator",
            "displayName": null,
            "url": "http://localhost:8080/flowable-task/process-api/identity/users/admin",
            "email": "admin@flowable.org",
            "pictureUrl": null
        }
    ],
    "total": 1,
    "start": 0,
    "sort": "id",
    "order": "asc",
    "size": 1
}
```

GET [identity/users/admin](https://www.flowable.org/docs/userguide/index.html#_get_a_single_user)

```
curl -i 'http://admin:test@localhost:8080/flowable-task/process-api/identity/users/admin'
```

Returns:

```
{
    "id": "admin",
    "firstName": "Test",
    "lastName": "Administrator",
    "displayName": null,
    "url": "http://localhost:8080/flowable-task/process-api/identity/users/admin",
    "email": "admin@flowable.org",
    "pictureUrl": null
}
```

**Comment by prem911** [comment]
@tijsrademakers Can someone acknowledge the problem in the REST API for /flowable-rest/service/identity/users/{userId}

@Robinyo GET [identity/users](https://www.flowable.org/docs/userguide/index.html#_get_a_list_of_users) example shows that the response doesnot contain tenantId.

This is adding to the confusion.

all-in-one docker doesnot include the REST app. We have modified the yml to spin the REST app along with the all-in-one linked to the same postgres db.

Looking for help from the flowable team to resolve this confusion.

**Comment by Robinyo** [comment]
> all-in-one docker does not include the REST app.

The `flowable/all-in-one` image **includes** Flowable's REST API.

The `flowable/all-in-one` image **doesn't include** Flowable's OpenAPI (Swagger) docs.

The `flowable/flowable-rest` image **includes** the Flowable OpenAPI (Swagger) docs:

See: [Getting started with Flowable](https://robferguson.org/blog/2018/12/10/getting-started-with-flowable/)

I have noticed several inconsistencies between the REST API as described in the [user's guide](https://www.flowable.org/docs/userguide/index.html#restApiChapter) and the REST API as described in the OpenAPI (Swagger) docs.

I know that the Flowable team have been addressing several REST API-related issues and hopefully the bug fixes/change requests will be included in the 6.4.1 release.

**Comment by tijsrademakers** [comment]
@lohiavivek yes, the tenant id is indeed not yet returned, we'll make sure that this gets fixed. The all-in-one Docker doesn't include the separate REST app, because the full REST API is part of the Flowable Task app (which is included). And it's a bit redundant to include it twice.

**Comment by prem911** [comment]
@tijsrademakers When is this getting fixed?

**Comment by PascalSchumacher** [comment]
https://github.com/flowable/flowable-engine/commit/fa3b90ac134e66dada89c521aab53681dd7174cf should fix this, so I guess this can be closed.

**Comment by filiphr** [comment]
@PascalSchumacher is correct. This has been fixed. Closing the issue.
