### ISSUE TITLE
App deployment using REST API is not showing the process or app.

### ISSUE THREAD

**Issue by lohiavivek** [flowable/flowable-engine#1481]
App deployment using REST API is not showing the process or app.
 
There is a difference in modeler UI behavior for App Import and REST API for app deployment

Steps :
This is the app deployment file a1.zip ( which has been exported from flowable itself )
Remove any existing process definition and app deployments.
Import this zip and we can see the new process definition and app deployment.

Using REST API,
POST to localhost:9080/flowable-rest/app-api/app-repository/deployments with this file doesnot show either the process or the app in the modeler UI.

However, when we start a process using Task app, then we see the process in the list.

Can someone explain if there is anything wrong in the REST API call?
![image](https://user-images.githubusercontent.com/17848089/50560745-e3e88f00-0d29-11e9-84cd-cbd9c6441dc4.png)

**Comment by tijsrademakers** [comment]
The Flowable Modeler and the Flowable Engines / REST application are two separate components. When using the app-repository/deployments REST service you are deploying the app to the App and Process Engine. If you want to import an app in the Flowable Modeler application, then the Modeler application has a UI or separate REST service to do this.

**Comment by lohiavivek** [comment]
Swagger Doc is showing REST API documentation for the following :
Process, Form, CMMN,DMN, APP, IDM, Content
I dont see specific for Modeler.

However, When I import app using Modeler UI there is a network call to : 
POST http://localhost:8080/flowable-modeler/app/rest/app-definitions/import?renewIdmEntries=false
Is this the REST call you are referring above?

If I try this using a REST client using Basic Auth, it responds with the IDM login page. Not sure which auth credentials I should be trying.

Do we have documentation around this topic?
@tijsrademakers Kindly help

**Comment by filiphr** [comment]
@lohiavivek the Flowable Modeler application is documented [here](https://www.flowable.org/docs/userguide/index.html#flowableModelerApp). The API you are referring to is an API that is internal to the modeler application.

**Comment by prem911** [comment]
![image](https://user-images.githubusercontent.com/7778147/50757806-6f13d880-1286-11e9-88a2-a6e330a02861.png)
@filiphr Can you help with flowable.modeler.app.rest-enabled. Document says it is enabled by default. Which endpoint is getting enabled?
