### ISSUE TITLE
Incorrect HSQL create script

### ISSUE THREAD

**Issue by garybrc** [flowable/flowable-engine#1485]
Using HSQL for unit tests causes; "java.sql.SQLSyntaxErrorException: unexpected token: DEFAULT : line: 18"
Caused by;
2019-01-02 11:22:07,916 ERROR [org.flowable.common.engine.impl.db.AbstractSqlScriptBasedDbSchemaManager] - problem during schema create, statement create table ACT_RE_PROCDEF ( 
ID_ varchar(64) NOT NULL, 
REV_ integer, 
CATEGORY_ varchar(255), 
NAME_ varchar(255), 
KEY_ varchar(255) NOT NULL, 
VERSION_ integer NOT NULL, 
DEPLOYMENT_ID_ varchar(64), 
RESOURCE_NAME_ varchar(4000), 
DGRM_RESOURCE_NAME_ varchar(4000), 
DESCRIPTION_ varchar(4000), 
HAS_START_FORM_KEY_ bit, 
HAS_GRAPHICAL_NOTATION_ bit, 
SUSPENSION_STATE_ integer, 
TENANT_ID_ varchar(255) default '', 
DERIVED_FROM_ varchar(64), 
DERIVED_FROM_ROOT_ varchar(64), 
DERIVED_VERSION_ integer NOT NULL default 0, 
ENGINE_VERSION_ varchar(255), 
primary key (ID_) 
)

The issue relates to the 'default' clause being before the 'NOT NULL'. I have already submitted a pull request to fix this.

**Comment by tijsrademakers** [comment]
Thanks for the PR and raising the issue.
