### ISSUE TITLE
UserTask concurrent submission problem

### ISSUE THREAD

**Issue by mnhy520** [flowable/flowable-engine#1487]
When I concurrently execute multiple taskservice.complete (ID) ; the system throws a FlowableOptimisticLockingException, and the system does not retry。
1.The Usertask not support retry?
2.Is there a good solution?

**Comment by tijsrademakers** [comment]
When you concurrently execute a complete call for a specific task id value, the first call will succeed and continue the process instance. All other calls will fail with a FlowableOptimisticLockingException. Are you saying that no call is succeeding at all?

**Comment by mnhy520** [comment]
Yes, and the system did not try again

**Comment by tijsrademakers** [comment]
Please provide a unit test showing the issue, so we can reproduce it. By default it should work like I explained in the previous comment, so there must be some more logic involved.

**Comment by mnhy520** [comment]
The following is my test code, thank you for your reply.
Flowchart
![image](https://user-images.githubusercontent.com/1035467/50672771-f9550600-1014-11e9-8e96-ad7740d8b292.png)
Code
List<String> taskIds = new ArrayList<>();
       taskIds.add("2feeb7fe-0f43-11e9-9988-a44cc872a36b");
       taskIds.add("2ffa02a7-0f43-11e9-9988-a44cc872a36b");
        taskIds.add("23r0fee-0f43-11e9-9988-a44cc872a36b");
        taskIds.stream().parallel().forEach(id->{
                  taskService.complete(id);
        });

XML

```
<process id="userTaskParallel" name="用户服务并发测试" isExecutable="true">
    <documentation>用户服务并发测试描述</documentation>
    <startEvent id="startEvent1"></startEvent>
    <sequenceFlow id="sid-D6C7EEBB-C4A1-4F59-9BFE-5F7C45238A07" sourceRef="startEvent1" targetRef="sid-9A5B5B5B-434A-4ED9-9EAE-9F1F5038CBCE"></sequenceFlow>
    <parallelGateway id="sid-9A5B5B5B-434A-4ED9-9EAE-9F1F5038CBCE"></parallelGateway>
    <userTask id="sid-C9217449-8BF1-4D27-80F1-D28FFF507DF1" name="用户节点一" flowable:async="true" flowable:exclusive="false" >
      <extensionElements>
        <flowable:failedJobRetryTimeCycle>R5/PT1M</flowable:failedJobRetryTimeCycle>
      </extensionElements>

    </userTask>
    <sequenceFlow id="sid-D04698EC-D833-498A-A324-C7656F6CC818" sourceRef="sid-9A5B5B5B-434A-4ED9-9EAE-9F1F5038CBCE" targetRef="sid-C9217449-8BF1-4D27-80F1-D28FFF507DF1"></sequenceFlow>
    <userTask id="sid-A207ACE3-2880-4D08-9388-47EC7EB2129A" name="用户节点三" flowable:async="true" flowable:exclusive="false">
      <extensionElements>
        <flowable:failedJobRetryTimeCycle>R5/PT1M</flowable:failedJobRetryTimeCycle>
      </extensionElements>
    </userTask>
    <sequenceFlow id="sid-F57CD5F7-3922-42F2-B950-83F01E4F70EE" sourceRef="sid-9A5B5B5B-434A-4ED9-9EAE-9F1F5038CBCE" targetRef="sid-A207ACE3-2880-4D08-9388-47EC7EB2129A"></sequenceFlow>
    <userTask id="sid-F16E9E08-EB56-4EF7-9FD3-3E5564FF7378" name="用户节点二" flowable:async="true" flowable:exclusive="false">
      <extensionElements>
        <flowable:failedJobRetryTimeCycle>R5/PT1M</flowable:failedJobRetryTimeCycle>
      </extensionElements>
    </userTask>
    <sequenceFlow id="sid-08A27C0A-598F-4A74-B242-B2A391C8159C" sourceRef="sid-9A5B5B5B-434A-4ED9-9EAE-9F1F5038CBCE" targetRef="sid-F16E9E08-EB56-4EF7-9FD3-3E5564FF7378"></sequenceFlow>
    <sequenceFlow id="sid-7A51E245-D4EE-4429-A829-5BF02C179C8E" sourceRef="sid-F16E9E08-EB56-4EF7-9FD3-3E5564FF7378" targetRef="sid-A702D180-47D1-4B86-B25D-8B03318DF445"></sequenceFlow>
    <parallelGateway id="sid-A702D180-47D1-4B86-B25D-8B03318DF445"></parallelGateway>
    <sequenceFlow id="sid-22D7ECB0-2ED7-45A1-835C-F657FF08458D" sourceRef="sid-C9217449-8BF1-4D27-80F1-D28FFF507DF1" targetRef="sid-A702D180-47D1-4B86-B25D-8B03318DF445"></sequenceFlow>
    <sequenceFlow id="sid-17DC25C3-75D5-4440-9C83-2587D154504B" sourceRef="sid-A207ACE3-2880-4D08-9388-47EC7EB2129A" targetRef="sid-A702D180-47D1-4B86-B25D-8B03318DF445"></sequenceFlow>
    <endEvent id="sid-B1050100-E9BA-4B7E-9443-AF880749D4F2"></endEvent>
    <sequenceFlow id="sid-0C678503-C404-4C29-955C-4676DCFD968C" sourceRef="sid-A702D180-47D1-4B86-B25D-8B03318DF445" targetRef="sid-B1050100-E9BA-4B7E-9443-AF880749D4F2"></sequenceFlow>
  </process>
```

**Comment by tijsrademakers** [comment]
Ok, thanks for adding the process picture and BPMN XML, that helps a lot. The problem is that each of the three user tasks go to the parallel gateway join and the optimistic lock exception happens at this point. This can be solved by making the join parallel gateway async and exclusive.  Is there a reason to make the user tasks async? Because user tasks are wait states by default already and the async flag only does something if you have execution listeners defined on the user task.
