### ISSUE TITLE
Implement fix that was also suggeste to Activiti-project

### ISSUE THREAD

**Issue by elygre** [flowable/flowable-engine#149]
My comment at https://github.com/Activiti/Activiti/commit/40ae7efa6f93a2449fd12381d2cb76192d249327#commitcomment-20433801 probably also applies to Flowable.

Basically, in https://github.com/flowable/flowable-engine/blob/master/modules/flowable5-test/src/test/java/org/activiti/standalone/cfg/CustomMybatisMapperTest.java#L103, replace

```
Long variableValue = (Long) result.get("VARIABLEVALUE");
```

with

```
Long variableValue = ((Number)result.get("VARIABLEVALUE").longValue()
```

(The reason for the original problem is that Oracle returns a BigDecimal rather than a Long).

**Comment by tijsrademakers** [comment]
Thanks. I find it strange that we didn't run into the issue for Oracle on our Jenkins QA yet. Did you experience it failing on Oracle?

**Comment by elygre** [comment]
Honestly? I was really checking the state of Activiti vs Flowable (where to go), and saw the commit I mentioned, which specifically mentioned the Oracle-problem. I thought I'd chime in with a slightly better java-version, and then thought I'd let you guys know, too.

So, no. I never even ran the test :-(.

**Comment by tijsrademakers** [comment]
Ok thanks for the feedback. Always good to chime in :-)
I'll do some additional checks why we are not seeing the issue.

**Comment by tijsrademakers** [comment]
Done the change suggested, but couldn't reproduce the issue yet.
