### ISSUE TITLE
flowable-modeler ui

### ISSUE THREAD

**Issue by yanwencheng** [flowable/flowable-engine#1490]
I want to integrate flowable-modeler into spring boot as part of my project, rather than using it as a separate deployment. Is there any good way?
Or is it possible to provide restful ui-related services separately, like flowable-spring-boot-starter-rest.jar?

**Comment by tijsrademakers** [comment]
You can integrate the Flowable Modeler application in another Spring boot application by adding the flowable-modeler-logic, flowable-modeler-rest and flowable-modeler-conf modules and copying the UI artefacts from the flowable-modeler-app module. There are no plans to provide separate modules at the moment, of course we do accept PRs

**Comment by yanwencheng** [comment]
@tijsrademakers 
Thank you for your reply. I'm doing this right now, but I find many jar package reference problems, context-path problems, security problems. I've seen before that camunda has an open-box ready-to-use webapp that directly refers to camunda-bpm-spring-boot-starter-webapp in spring boot, so can we?
