### ISSUE TITLE
log4j property files not supported

### ISSUE THREAD

**Issue by karadia10** [flowable/flowable-engine#1495]
While working on source code I found that the log4j.properties files are of no use in terms of logging as all the modules are using **log4j2** and a property "logging.config" is missing from flowable-default.properties which specifies the path of log4j.properties file because none of the modules are able to find log4j.properties from resource folder.

**Comment by tijsrademakers** [comment]
Can you please elaborate on what you mean with this? The log4j.properties in the Flowable Engine module src/test/resource folder for example is definitely used when running the Flowable Engine module tests for example.

**Comment by karadia10** [comment]
What I did is:

1. Fork the code.
2. Made changes in log4j.properties to generate all the logs in a seperate file according to **log4j**
3. Run the system -> there was no change in logging as I was expecting.
4. Then I added a property "logging.config=classpath:log4j.properties", I was expecting this will work for sure but it did not.
5. Then I replaced all the **log4j** properties with **log4j2** properties and run the system -> this was working perfectly fine

**Comment by tijsrademakers** [comment]
ok, what do you mean with "run the system"?

**Comment by karadia10** [comment]
It is a spring boot project so I run it using eclipse from its main class for example "FlowableModelerApplication.java" in "flowable-ui-modeler-app"

**Comment by tijsrademakers** [comment]
Flowable consists of a lot of different modules, a number of UI applications and several Engines. The Flowable Modeler application is just one of them. When you want to change the logging for the Flowable Modeler / Spring boot application you can use the alternatives you have described, or you can use logging.level.root=ERROR in the application.properties. This choice can be made based on your preference.
