### ISSUE TITLE
GET method to models used in process which is alreaddeployed

### ISSUE THREAD

**Issue by madhu150894** [flowable/flowable-engine#1497]
The GET request API for [Models](http://localhost:9080/flowable-rest/service/repository/models)  isn't working for some reason.

1. This API response is always the same as below
`{
  "data": [],
  "total": 0,
  "start": 0,
  "sort": "id",
  "order": "asc",
  "size": 0
}`
2. I expect to see all the process definition BPMN models using this API and also filter the BPMN model which is used in particular deployed process using deployment ID.
3. Is this a right API to get the details which I have mentined above or does this API serve different purpose?

**Comment by yvoswillens** [comment]
Please use the forum (https://forum.flowable.org) for asking questions like this.

For querying deployed BPMN models use this API;

`GET repository/process-definitions`

and use deploymentId as query parameter.
See https://flowable.org/docs/userguide/index.html#_process_definitions for other query parameters.

Regards,

Yvo

**Comment by madhu150894** [comment]
Hi @yvoswillens 

Thanks for the information and  I consider your suggestion.

Regards,
Madhu
