### ISSUE TITLE
When will Flowable 6.4.1 be released?

### ISSUE THREAD

**Issue by mnhy520** [flowable/flowable-engine#1505]
The Flowable 6.4.0 had a lot of bugs.When will Flowable 6.4.1 be released?

**Comment by Robinyo** [comment]
Hi @mnhy520 

Have you tried posting your questions in the Flowable [forum](https://forum.flowable.org/)?

Cheers
Rob

**Comment by mnhy520** [comment]
I'm sorry, I didn't mean that. Thank you for bringing us such a great product.
