### ISSUE TITLE
Ignore databaseTablePrefix in 6 version

### ISSUE THREAD

**Issue by a-polyakov** [flowable/flowable-engine#151]
not start
ERROR: relation "act_id_property" does not exist
in the database to "Activiti" assigned to a separate scheme "activiti"
config
`<bean id="processEngineConfiguration" class="org.flowable.spring.SpringProcessEngineConfiguration">
        <property name="databaseTablePrefix" value="activiti." />
        <property name="tablePrefixIsSchema" value="true" />`
...
a request that is trying to query "select VALUE_ from ACT_ID_PROPERTY where NAME_ = 'schema.version'"
specified in the config file prefix does not substitute
but it work in 5.22.0 version

**Comment by tijsrademakers** [comment]
The issue should be fixed now, could you validate it with the latest master?

**Comment by a-polyakov** [comment]
rebuild 
last commit b10e218 Yvo Swillens on 17.01.2017 at 14:08 fixed invalid process bpmn xml
but error reproduce
