### ISSUE TITLE
External tasks feature

### ISSUE THREAD

**Issue by maratkalibek** [flowable/flowable-engine#1530]
Is there any plans to have functionality like external tasks in Camunda?

https://docs.camunda.org/manual/7.7/user-guide/process-engine/external-tasks/

**Comment by wberges** [comment]
Perhaps the `triggerable` attribute of a service task could be a solution?
https://www.flowable.org/docs/userguide/index.html#serviceTaskTriggerable
Regards

**Comment by maratkalibek** [comment]
It is a different thing. External tasks in camunda are processed by the external applications which are not in the same JVM as camunda engine. So external task handlers can be developed (started, updated) independently of processes applications.

**Comment by tijsrademakers** [comment]
@maratkalibek But this can be done using the HTTP task as well right? What are the exact features that you would like to see in the external task handler?

**Comment by maratkalibek** [comment]
I want to mention, that this feature really simplifies process development. External application subscribed to the topics which are produced by the process. In this way, all external task handlers are processed externally without being hardcoded in process application.

**Comment by zeldigas** [comment]
@maratkalibek I was also looking for something similar recently and so far it looks like that solution here would be to use manual task in combination with rest api provided by flowable. After all "external" semantics just say that there are some activity need to be done that is external to engine. Looks like manual fits this definition, although can look a bit misleading on diagram.
So separate and more straight forward api would be cool here like syntactic sugar in programming language, but it's possible to solve the task now as well..

**Comment by filiphr** [comment]
This was actually done as part of PR #2303 and was released in 6.6.0. Here is some more info for it:

* [BPMN Documentation](https://flowable.com/open-source/docs/bpmn/ch07b-BPMN-Constructs/#external-worker-task)
* [CMMN Documentation](https://flowable.com/open-source/docs/cmmn/ch06-cmmn/#external-worker-task)
