### ISSUE TITLE
How to change the tool bar icons.

### ISSUE THREAD

**Issue by vishaldenzil** [flowable/flowable-engine#1531]
I want to change the toolbar icons in the flowable ui modeler.

**Comment by Robinyo** [comment]
See: [Editor in my own application](https://forum.flowable.org/t/editor-in-my-own-application/3087/2?u=robinyo)

**Comment by karadia10** [comment]
[
        flowable-engine/modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/manifest.json
      ](url)
you can make changes here or replace all the images present in images folder to replace toolbar icon

**Comment by vishaldenzil** [comment]
Its pointing to content : 'a' (style.css file) How can we change icons in tool bar..

**Comment by karadia10** [comment]
Sorry, I am not able to understand your comment. Let me provide you the link to file
[https://github.com/flowable/flowable-engine/blob/master/modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/manifest.json](url)
Make changes to reflect changes
 `"src": "images\/android-chrome-192x192.png?v=Om5N75Y123",`

**Comment by vishaldenzil** [comment]
Am trying to change here Css name . 
{
            "type" : "button",
            "title" : "TOOLBAR.ACTION.SAVE",
            "cssClass" : "editor-icon editor-icon-save",
            "action" : "FLOWABLE.TOOLBAR.ACTIONS.saveModel"
        },

**Comment by tijsrademakers** [comment]
Please use the forum for questions like this. And thanks to @Robinyo and @karadia10 for providing the feedback.
