### ISSUE TITLE
Flowable IDM: No longer working with external LDAP after update from 6.4.0 to 6.4.1

### ISSUE THREAD

**Issue by PascalSchumacher** [flowable/flowable-engine#1532]
We use `flowable-ui-idm-app` configured to connect to an external LDAP provider.

After updating from `6.4.0` to `6.4.1` all logins fail with `"status":500, "error":"Internal Server Error", "message":"There is no PasswordEncoder mapped for the id "null"", "path":"/flowable-idm/app/authentication"`.

I guess this is a side effect of https://github.com/flowable/flowable-engine/commit/248de5aec346df61be4ccec603dfa58b5a97f6ae (Cleanup Flowable Spring Boot Security Auto configuration).

I tried setting `flowable.idm.password-encoder` to `spring_delegating_noop` (or other values), but this property is not used if `flowable.idm.ldap.enabled` is `true`. see: https://github.com/flowable/flowable-engine/blob/eeebfd23af3571741b60e3f663f17c0ecc50a812/modules/flowable-ui-idm/flowable-ui-idm-conf/src/main/java/org/flowable/ui/idm/conf/SecurityConfiguration.java#L79

**Edit:**
https://github.com/flowable/flowable-engine/commit/248de5aec346df61be4ccec603dfa58b5a97f6ae really seems to be the cause. I build `flowable-ui-idm-app` version `6.4.1` but replaced the `flowable-spring-boot-autoconfigure` dependency with version `6.4.0` and the error disappeared.

**Comment by filiphr** [comment]
Thanks for the analysis @PascalSchumacher. You are right the `flowable.idm.password-encoder` does not work with the external LDAP. This means that the default Spring Security 5 delegating password encoder kicks in.

I initially thought that with LDAP we won't need a `PasswordEncoder`. It seems I was wrong, we are going to fix this asap. Can you perhaps share the stacktrace that you are getting?

**Comment by filiphr** [comment]
@PascalSchumacher this has now been fixed on master. The issue was that there were 2 `AuthenticationProvider` beans, one from the `FlowableLdapAutoConfiguration` and another one from the UI IDM `SecurityConfiguration` this lead to Spring Security not being able to pick one and went to use the `DaoAuthenticationProvider` which uses the `PasswordEncoder`

**Comment by PascalSchumacher** [comment]
Thank you very much! :+1: :smiley:

**Comment by voronczoff** [comment]
Is there a way to fix current 6.4.1 installation? When can we expect new release with fixed issue?
