### ISSUE TITLE
ProcessDiagramGenerator generate image occur null point Exception

### ISSUE THREAD

**Issue by StephonDNG** [flowable/flowable-engine#1534]
`protected static DefaultProcessDiagramCanvas initProcessDiagramCanvas(BpmnModel bpmnModel, String imageType, String activityFontName, String labelFontName, String annotationFontName, ClassLoader customClassLoader) {
        double minX = 1.7976931348623157E308D;
        double maxX = 0.0D;
        double minY = 1.7976931348623157E308D;
        double maxY = 0.0D;

        GraphicInfo graphicInfo;
        for(Iterator var14 = bpmnModel.getPools().iterator(); var14.hasNext(); maxY = graphicInfo.getY() + graphicInfo.getHeight()) {
            Pool pool = (Pool)var14.next();
            graphicInfo = bpmnModel.getGraphicInfo(pool.getId());
            minX = graphicInfo.getX();
            maxX = graphicInfo.getX() + graphicInfo.getWidth();
            minY = graphicInfo.getY();
        }

        List<FlowNode> flowNodes = gatherAllFlowNodes(bpmnModel);
        Iterator var24 = flowNodes.iterator();

        label155:
        while(var24.hasNext()) {
            FlowNode flowNode = (FlowNode)var24.next();
            GraphicInfo flowNodeGraphicInfo = bpmnModel.getGraphicInfo(flowNode.getId());
            if (flowNodeGraphicInfo.getX() + flowNodeGraphicInfo.getWidth() > maxX) {
                maxX = flowNodeGraphicInfo.getX() + flowNodeGraphicInfo.getWidth();
            }

            if (flowNodeGraphicInfo.getX() < minX) {
                minX = flowNodeGraphicInfo.getX();
            }

            if (flowNodeGraphicInfo.getY() + flowNodeGraphicInfo.getHeight() > maxY) {
                maxY = flowNodeGraphicInfo.getY() + flowNodeGraphicInfo.getHeight();
            }

            if (flowNodeGraphicInfo.getY() < minY) {
                minY = flowNodeGraphicInfo.getY();
            }

            Iterator var18 = flowNode.getOutgoingFlows().iterator();

            while(true) {
                List graphicInfoList;
                do {
                    if (!var18.hasNext()) {
                        continue label155;
                    }

                    SequenceFlow sequenceFlow = (SequenceFlow)var18.next();
                    graphicInfoList = bpmnModel.getFlowLocationGraphicInfo(sequenceFlow.getId());
                } while(graphicInfoList == null);

                Iterator var21 = graphicInfoList.iterator();

                while(var21.hasNext()) {
                    GraphicInfo graphicInfo = (GraphicInfo)var21.next();
                    if (graphicInfo.getX() > maxX) {
                        maxX = graphicInfo.getX();
                    }

                    if (graphicInfo.getX() < minX) {
                        minX = graphicInfo.getX();
                    }

                    if (graphicInfo.getY() > maxY) {
                        maxY = graphicInfo.getY();
                    }

                    if (graphicInfo.getY() < minY) {
                        minY = graphicInfo.getY();
                    }
                }
            }
        }

        List<Artifact> artifacts = gatherAllArtifacts(bpmnModel);
        Iterator var27 = artifacts.iterator();

        GraphicInfo graphicInfo;
        while(var27.hasNext()) {
            Artifact artifact = (Artifact)var27.next();
            GraphicInfo artifactGraphicInfo = bpmnModel.getGraphicInfo(artifact.getId());
            if (artifactGraphicInfo != null) {
                if (artifactGraphicInfo.getX() + artifactGraphicInfo.getWidth() > maxX) {
                    maxX = artifactGraphicInfo.getX() + artifactGraphicInfo.getWidth();
                }

                if (artifactGraphicInfo.getX() < minX) {
                    minX = artifactGraphicInfo.getX();
                }

                if (artifactGraphicInfo.getY() + artifactGraphicInfo.getHeight() > maxY) {
                    maxY = artifactGraphicInfo.getY() + artifactGraphicInfo.getHeight();
                }

                if (artifactGraphicInfo.getY() < minY) {
                    minY = artifactGraphicInfo.getY();
                }
            }

            List<GraphicInfo> graphicInfoList = bpmnModel.getFlowLocationGraphicInfo(artifact.getId());
            if (graphicInfoList != null) {
                Iterator var35 = graphicInfoList.iterator();

                while(var35.hasNext()) {
                    graphicInfo = (GraphicInfo)var35.next();
                    if (graphicInfo.getX() > maxX) {
                        maxX = graphicInfo.getX();
                    }

                    if (graphicInfo.getX() < minX) {
                        minX = graphicInfo.getX();
                    }

                    if (graphicInfo.getY() > maxY) {
                        maxY = graphicInfo.getY();
                    }

                    if (graphicInfo.getY() < minY) {
                        minY = graphicInfo.getY();
                    }
                }
            }
        }

        int nrOfLanes = 0;
        Iterator var30 = bpmnModel.getProcesses().iterator();

        while(var30.hasNext()) {
            Process process = (Process)var30.next();
            Iterator var34 = process.getLanes().iterator();

            while(var34.hasNext()) {
                Lane l = (Lane)var34.next();
                ++nrOfLanes;
                graphicInfo = bpmnModel.getGraphicInfo(l.getId());
                if (graphicInfo.getX() + graphicInfo.getWidth() > maxX) {
                    maxX = graphicInfo.getX() + graphicInfo.getWidth();
                }

                if (graphicInfo.getX() < minX) {
                    minX = graphicInfo.getX();
                }

                if (graphicInfo.getY() + graphicInfo.getHeight() > maxY) {
                    maxY = graphicInfo.getY() + graphicInfo.getHeight();
                }

                if (graphicInfo.getY() < minY) {
                    minY = graphicInfo.getY();
                }
            }
        }

        if (flowNodes.isEmpty() && bpmnModel.getPools().isEmpty() && nrOfLanes == 0) {
            minX = 0.0D;
            minY = 0.0D;
        }

        return new DefaultProcessDiagramCanvas((int)maxX + 10, (int)maxY + 10, (int)minX, (int)minY, imageType, activityFontName, labelFontName, annotationFontName, customClassLoader);
    }`

this code  `GraphicInfo flowNodeGraphicInfo = bpmnModel.getGraphicInfo(flowNode.getId());`
The BpmnModel variable locationMap seems not put anything.

**Comment by jianchengwang** [comment]
> it seems this bpmnModel instance init with spring-boot project boot! Analysis the deploy file!

could you share how do you solve this problem?

**Comment by jianchengwang** [comment]
> > it seems this bpmnModel instance init with spring-boot project boot! Analysis the deploy file!
> 
> could you share how do you solve this problem?

i think i found my fault, my `bpmn xml` dont't have `bpmndi:BPMNDiagram` infomation

**Comment by jianchengwang** [comment]
> > > it seems this bpmnModel instance init with spring-boot project boot! Analysis the deploy file!
> > 
> > 
> > could you share how do you solve this problem?
> 
> i think i found my fault, my `bpmn xml` dont't have `bpmndi:BPMNDiagram` infomation

i am sorray, but problem is still exist,

**Comment by DongJigong** [comment]
> > > > it seems this bpmnModel instance init with spring-boot project boot! Analysis the deploy file!
> > > 
> > > 
> > > could you share how do you solve this problem?
> > 
> > 
> > i think i found my fault, my `bpmn xml` dont't have `bpmndi:BPMNDiagram` infomation
> 
> i am sorray, but problem is still exist,

Show me your code and error log detail.

**Comment by jianchengwang** [comment]
here is my code
```java
 BpmnModel bpmnModel = repositoryService.getBpmnModel(pi.getProcessDefinitionId());
        ProcessEngineConfiguration engconf = processEngine.getProcessEngineConfiguration();
        ProcessDiagramGenerator diagramGenerator = engconf.getProcessDiagramGenerator();
        InputStream in = diagramGenerator
                .generateDiagram(bpmnModel, "png", activityIds, flows, false);
```

here is exception stacktrace
```log
java.lang.NullPointerException: null
	at org.flowable.image.impl.DefaultProcessDiagramGenerator.initProcessDiagramCanvas(DefaultProcessDiagramGenerator.java:930) ~[flowable-image-generator-6.4.2.jar:6.4.2]
	at org.flowable.image.impl.DefaultProcessDiagramGenerator.generateProcessDiagram(DefaultProcessDiagramGenerator.java:574) ~[flowable-image-generator-6.4.2.jar:6.4.2]
	at org.flowable.image.impl.DefaultProcessDiagramGenerator.generateDiagram(DefaultProcessDiagramGenerator.java:489) ~[flowable-image-generator-6.4.2.jar:6.4.2]
	at org.flowable.image.impl.DefaultProcessDiagramGenerator.generateDiagram(DefaultProcessDiagramGenerator.java:495) ~[flowable-image-generator-6.4.2.jar:6.4.2]
	at cn.jianchengwang.todo.lib.flowable.example.springboot.web.ProcessController.genProcessDiagram(ProcessController.java:90) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893) ~[spring-webmvc-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:798) ~[spring-webmvc-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[tomcat-embed-core-9.0.26.jar:9.0.26]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.1.10.RELEASE.jar:5.1.10.RELEASE]
````
```java
  GraphicInfo flowNodeGraphicInfo = bpmnModel.getGraphicInfo(flowNode.getId());

            // width
            if (flowNodeGraphicInfo.getX() + flowNodeGraphicInfo.getWidth() > maxX) {
                maxX = flowNodeGraphicInfo.getX() + flowNodeGraphicInfo.getWidth();
            }
````
`NullPointException` occur because `flowNodeGraphicInfo is null`

and there is my bpmn.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
             xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC"
             xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI"
             xmlns:flowable="http://flowable.org/bpmn"
             typeLanguage="http://www.w3.org/2001/XMLSchema"
             expressionLanguage="http://www.w3.org/1999/XPath"
             targetNamespace="http://www.flowable.org/processdef">

    <process id="holidayRequest" name="Holiday Request" isExecutable="true">

        <startEvent id="startEvent"/>
        <sequenceFlow sourceRef="startEvent" targetRef="approveTask"/>

        <userTask id="approveTask" name="Approve or reject request" flowable:candidateGroups="managers"/>
        <sequenceFlow sourceRef="approveTask" targetRef="decision"/>

        <exclusiveGateway id="decision"/>
        <sequenceFlow sourceRef="decision" targetRef="externalSystemCall">
            <conditionExpression xsi:type="tFormalExpression">
                <![CDATA[
          ${approved}
        ]]>
            </conditionExpression>
        </sequenceFlow>
        <sequenceFlow  sourceRef="decision" targetRef="sendRejectionMail">
            <conditionExpression xsi:type="tFormalExpression">
                <![CDATA[
          ${!approved}
        ]]>
            </conditionExpression>
        </sequenceFlow>

        <serviceTask id="externalSystemCall" name="Enter holidays in external system"
                     flowable:class="cn.jianchengwang.todo.lib.flowable.example.service.CallExternalSystemDelegate"/>
        <sequenceFlow sourceRef="externalSystemCall" targetRef="holidayApprovedTask"/>

        <userTask id="holidayApprovedTask" name="Holiday approved" flowable:assignee="${employee}" />
        <sequenceFlow sourceRef="holidayApprovedTask" targetRef="approveEnd"/>

        <serviceTask id="sendRejectionMail" name="Send out rejection email"
                     flowable:class="cn.jianchengwang.todo.lib.flowable.example.service.SendRejectionMail"/>
        <sequenceFlow sourceRef="sendRejectionMail" targetRef="rejectEnd"/>

        <endEvent id="approveEnd"/>

        <endEvent id="rejectEnd"/>

    </process>

    <bpmndi:BPMNDiagram id="BPMNDiagram_Expense">
        <bpmndi:BPMNPlane id="BPMNPlane_holidayRequest" bpmnElement="holidayRequest">
            <bpmndi:BPMNShape id="BPMNShape_start" bpmnElement="startEvent">
                <omgdc:Bounds x="155" y="125" width="30" height="30" />
            </bpmndi:BPMNShape>
            <bpmndi:BPMNShape id="BPMNShape_approveTask" bpmnElement="approveTask">
                <omgdc:Bounds x="275" y="100" width="100" height="80" />
            </bpmndi:BPMNShape>
            <bpmndi:BPMNShape id="BPMNShape_decision" bpmnElement="decision" isMarkerVisible="true">
                <omgdc:Bounds x="455" y="120" width="40" height="40" />
            </bpmndi:BPMNShape>
            <bpmndi:BPMNShape id="BPMNShape_externalSystemCall" bpmnElement="externalSystemCall">
                <omgdc:Bounds x="605" y="100" width="100" height="80" />
            </bpmndi:BPMNShape>
            <bpmndi:BPMNShape id="BPMNShape_holidayApprovedTask" bpmnElement="holidayApprovedTask">
                <omgdc:Bounds x="800" y="100" width="100" height="80" />
            </bpmndi:BPMNShape>
            <bpmndi:BPMNShape id="BPMNShape_approveEnd" bpmnElement="approveEnd">
                <omgdc:Bounds x="956" y="126" width="28" height="28" />
            </bpmndi:BPMNShape>
            <bpmndi:BPMNEdge id="BPMNEdge_flow1">
                <omgdi:waypoint x="315" y="150" />
                <omgdi:waypoint x="405" y="150" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="BPMNEdge_flow2">
                <omgdi:waypoint x="505" y="150.16611295681062" />
                <omgdi:waypoint x="585.4333333333333" y="150.43333333333334" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="BPMNEdge_judgeLess">
                <omgdi:waypoint x="624.5530726256983" y="150.44692737430168" />
                <omgdi:waypoint x="735" y="150.1392757660167" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="BPMNEdge_directorNotPassFlow">
                <omgdi:waypoint x="785" y="110" />
                <omgdi:waypoint x="785" y="37" />
                <omgdi:waypoint x="455" y="37" />
                <omgdi:waypoint x="455" y="110" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="BPMNEdge_bossPassFlow">
                <omgdi:waypoint x="655" y="295" />
                <omgdi:waypoint x="771" y="295" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="BPMNEdge_judgeMore">
                <omgdi:waypoint x="605.4340277777778" y="169.56597222222223" />
                <omgdi:waypoint x="605.1384083044983" y="255" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="BPMNEdge_directorPassFlow">
                <omgdi:waypoint x="785" y="190" />
                <omgdi:waypoint x="785" y="281" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="BPMNEdge_bossNotPassFlow">
                <omgdi:waypoint x="555" y="295" />
                <omgdi:waypoint x="455" y="295" />
                <omgdi:waypoint x="455" y="190" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="SequenceFlow_1kgnczc_di" bpmnElement="SequenceFlow_1kgnczc">
                <omgdi:waypoint x="185" y="140" />
                <omgdi:waypoint x="275" y="140" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="SequenceFlow_1smyxb3_di" bpmnElement="SequenceFlow_1smyxb3">
                <omgdi:waypoint x="375" y="140" />
                <omgdi:waypoint x="455" y="140" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="SequenceFlow_0cp8q96_di" bpmnElement="SequenceFlow_0cp8q96">
                <omgdi:waypoint x="495" y="140" />
                <omgdi:waypoint x="605" y="140" />
                <bpmndi:BPMNLabel>
                    <omgdc:Bounds x="527" y="122" width="47" height="14" />
                </bpmndi:BPMNLabel>
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="SequenceFlow_1fdor3h_di" bpmnElement="SequenceFlow_1fdor3h">
                <omgdi:waypoint x="705" y="140" />
                <omgdi:waypoint x="800" y="140" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="SequenceFlow_0grg3k6_di" bpmnElement="SequenceFlow_0grg3k6">
                <omgdi:waypoint x="900" y="140" />
                <omgdi:waypoint x="956" y="140" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNShape id="Task_1yu6zp8_di" bpmnElement="sendRejectionMail">
                <omgdc:Bounds x="605" y="230" width="100" height="80" />
            </bpmndi:BPMNShape>
            <bpmndi:BPMNEdge id="SequenceFlow_127hv9g_di" bpmnElement="SequenceFlow_127hv9g">
                <omgdi:waypoint x="475" y="160" />
                <omgdi:waypoint x="475" y="280" />
                <omgdi:waypoint x="605" y="280" />
                <bpmndi:BPMNLabel>
                    <omgdc:Bounds x="470" y="217" width="40" height="14" />
                </bpmndi:BPMNLabel>
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="SequenceFlow_01dfoio_di" bpmnElement="SequenceFlow_01dfoio">
                <omgdi:waypoint x="705" y="270" />
                <omgdi:waypoint x="832" y="270" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNShape id="EndEvent_0sdbuyv_di" bpmnElement="rejectEnd">
                <omgdc:Bounds x="832" y="252" width="36" height="36" />
            </bpmndi:BPMNShape>
        </bpmndi:BPMNPlane>
    </bpmndi:BPMNDiagram>

</definitions>
```

thank you very much

**Comment by DongJigong** [comment]
@jianchengwang Are you have read this guide doc.[](https://www.flowable.org/docs/userguide/index.html#springSpringBoot)

**Comment by DongJigong** [comment]
@jianchengwang 
![image](https://user-images.githubusercontent.com/8855265/67081780-69aacd80-f1ca-11e9-88eb-739d74d7e3bb.png)

**Comment by jianchengwang** [comment]
> @jianchengwang
> ![image](https://user-images.githubusercontent.com/8855265/67081780-69aacd80-f1ca-11e9-88eb-739d74d7e3bb.png)
> Default support this kind files.Pls check your configuration.
> Btw I am using spring boot 2.1.0 + flowable-spring-boot 6.4.1

i will read this guide doc again, maybe i can find out problem by myself, thank a lot and good luck for me.

**Comment by DongJigong** [comment]
@jianchengwang 
![image](https://user-images.githubusercontent.com/8855265/67084819-4c78fd80-f1d0-11e9-875f-36194cc16533.png)
My console has log flag text '111111'. It means there is no error.Please checkout your code
![image](https://user-images.githubusercontent.com/8855265/67084928-7fbb8c80-f1d0-11e9-9066-0af0e83ea581.png)
This two params should not be null.

**Comment by jianchengwang** [comment]
> @jianchengwang
> ![image](https://user-images.githubusercontent.com/8855265/67084819-4c78fd80-f1d0-11e9-875f-36194cc16533.png)
> My console has log flag text '111111'. It means there is no error.Please checkout your code
> ![image](https://user-images.githubusercontent.com/8855265/67084928-7fbb8c80-f1d0-11e9-9066-0af0e83ea581.png)
> This two params should not be null.

it had been solved.

I read again guide doc, thanks again. 

````java
Any BPMN 2.0 process definitions in the processes folder will be automatically deployed. 

Create a folder processes and add a dummy process definition (named one-task-process.bpmn20.xml) to this folder. 

The content of this file is shown below.
````
then I found my folder name is `process` not `processes`, maybe it was a key. 

so I rename the folder to `processes`, but get the same problem.

so I guess maybe folder some infomation was stored to the database, so i empty database tables which auto created by `flowable` then it work.

thank a lot, brother.
