### ISSUE TITLE
Flowable distribution with OpenJDK 

### ISSUE THREAD

**Issue by bvedam** [flowable/flowable-engine#1537]
Is there a distribution of Flowable with OpenJDK 8 build, due to Oracle JDK 8 licensing changes? If not, is there a migration plan to move to OpenJDK? 

Appreciate your response.

**Comment by Robinyo** [comment]
See: [Flowable distribution with OpenJDK build](https://forum.flowable.org/t/flowable-distribution-with-openjdk-build/3263/2?u=robinyo)

**Comment by bvedam** [comment]
Thank you very much. I will take a look at it.
