### ISSUE TITLE
Asynchronous history

### ISSUE THREAD

**Issue by motorina0** [flowable/flowable-engine#154]
Currently, historical data is written in the same transaction as the runtime data. Benchmark profiling has shown that in many use cases, a significant amount of time is spent processing and persisting the historical data whilst the user has to wait for the transaction to finish. By making this asynchronous, a performance improvement is expected.

**Comment by motorina0** [comment]
Step 1: Investigate possible approaches. Suggest solutions with advantages vs disadvantages.

**Comment by tijsrademakers** [comment]
Hi, we are currently working on the async history feature. There's already quite a bit of code implemented, so no need to jump in on this feature I think.

**Comment by tijsrademakers** [comment]
Good thing, duplicate work would not be good :-)
