### ISSUE TITLE
Calling the /flowable-rest/service/identity/users?tenantId=org1 Rest api in Modeler App is throwing error

### ISSUE THREAD

**Issue by vishaldenzil** [flowable/flowable-engine#1545]
I am extending the Modeler Angular App to select users from a specific tenantId.

My Modeler app in running on localhost:8888.
Flowable REST is running on 9977.
While assigning the user in user task when we select the single user assignment, it displays all users irrespective its tenant id. 

I have created multiple users in different tenants.

My objective is to get a filtered list of users based on tenantId.

The modeler api was  
url : http://localhost:8888/flowable-modeler/app/rest/editor-users?filter=a

I have modified the modeler docker.yml to run both modeler and rest using the same postgres db.

 Docker.yml file modified for rest 
    flowable-rest-app:
        image: flowable/flowable-rest
        depends_on:
                    - flowable-db
        environment:
                   - SERVER_PORT=9977
                   - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
                   - SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-db:5432/flowable
                   - SPRING_DATASOURCE_USERNAME=flowable
                    - SPRING_DATASOURCE_PASSWORD=flowable
                    - FLOWABLE_REST_APP_ADMIN_USER-ID=rest-admin
                    - FLOWABLE_REST_APP_ADMIN_PASSWORD=test
                    - FLOWABLE_REST_APP_ADMIN_FIRST-NAME=Rest
                    - FLOWABLE_REST_APP_ADMIN_LAST-NAME=Admin
  
  
Using the Postman I  can get the desired data. 
url :http://admin:test@localhost:9977/flowable-rest/service/identity/users?tenantId=org1

When calling the same Api in Modeler app its giving the "OPTIONS" error.
http({
                method: 'GET',
                url: "http://admin:test@localhost:9977/flowable-rest/service/identity/users?tenantId=org1",
                params: {}
            });

So, the fundamental question is : Can I make the REST calls from the Angular App? If yes, what is the correct way of doing it.

**Comment by tijsrademakers** [comment]
When you are invoking the identity REST API it needs a basic auth call. The Modeler Angular application uses cookie based authentication for communicating with the Modeler REST API backend. If this is not working then this is an Angular specific question. The REST API just needs a regular basic auth call and then it works, like you experienced with Postman.
