### ISSUE TITLE
Spring boot create five modules of REST Servlet  Is there a corresponding documentation?

### ISSUE THREAD

**Issue by mmm8955405** [flowable/flowable-engine#1565]
When spring boot starts
Create five modules of REST Servlet:
Process-api
Cmmn-api
Dmn-api
Idm-api
Form-api
Content-api
Is there a corresponding documentation?
How do I know what functions are under each module?
Want to provide swagger for each module

**Comment by tijsrademakers** [comment]
There is Swagger documentation + a documented REST API on https://flowable.org/documentation.html

**Comment by mmm8955405** [comment]
I think this document is very deficient, and there is no specific information about these five modules. Https://flowable.org/documentation.html
