### ISSUE TITLE
Using the datastore rather than the file system for Content Storage

### ISSUE THREAD

**Issue by jmoraleda** [flowable/flowable-engine#1575]
I have looked through the source and have found the way to configure the Content Store Engine to use the datasource that is being used to store everything else rather than the filesystem when using the content-api. Have I missed this? If not, this is a feature request. I am willing to help implement it the project at large would find it useful.

**Comment by tijsrademakers** [comment]
The supported option is filesystem for the open source content engine. You could also look at flowable.com for the commercial options for Flowable, because there is support for database persistence in that version. Otherwise we welcome PRs for this feature of course.

**Comment by billerby** [comment]
@tijsrademakers "A PR is welcome". It seems @jmoraleda made a PR. However its in open state since quite a long time and without any comments whatsoever. Will you look in to the Pull Request sometime soon and perhaps merge it into flowable?

Thanks!

**Comment by tijsrademakers** [comment]
@billerby correct, but the PR is currently outdated and is also lacking some things that are mentioned in the PR comments. So right now some time needs to be invested to update the PR, before it can be considered for merging.

**Comment by billerby** [comment]
@tijsrademakers Ahh, missed the comments... sorry then I fully understand.

**Comment by billerby** [comment]
@tijsrademakers hmm, can't see those comments, or is the the travis_ci comments you are refering to?

**Comment by tijsrademakers** [comment]
@billerby what I mean mostly is that the PR is currently out of date and can't be merged, but there are also some things to discuss like the table structure, how the unit tests run for all the supported databases etc.
