### ISSUE TITLE
SaveContentItemCmd in the content engine does not delete old content data when resetting content data for an item

### ISSUE THREAD

**Issue by jmoraleda** [flowable/flowable-engine#1586]
The SaveContentItemCmd in the Content Engine
https://github.com/flowable/flowable-engine/blob/master/modules/flowable-content-engine/src/main/java/org/flowable/content/engine/impl/cmd/SaveContentItemCmd.java

does not delete old content data when invoked repeatedly for the same `contentItem` with `inputData` not null. This leads to the old data being leaked in the ContentStorage without any item owning it.

I will fix this by updating the data from the ContentStorage if it already existed rather than inserting new data and will submit a pull request.

**Comment by tijsrademakers** [comment]
Issue is resolved
