### ISSUE TITLE
GET /repository/process-definitions/{processDefinitionId}/image response MIME type wrong

### ISSUE THREAD

**Issue by bwangfdu** [flowable/flowable-engine#1599]
The swagger doc in flowable-app-rest on GET /repository/process-definitions/{processDefinitionId}/image the response content MIME type is wrong. The type should be image/png, but it doesn't defined in the document, and Swagger make it as default application/json. When try this interface in swagger ui, it blocks there, but actually the image is returned.

**Comment by dbmalkovsky** [comment]
Should be fixed by [PR 1735](https://github.com/flowable/flowable-engine/pull/1735)

**Comment by bwangfdu** [comment]
Thanks for taking care of it.
