### ISSUE TITLE
Undo functionality (Process step re-execution)

### ISSUE THREAD

**Issue by motorina0** [flowable/flowable-engine#160]
Undo functionality: allow to 'go back' in a process instance to a previous state via an API call.

**Comment by motorina0** [comment]
@tijsrademakers : I would like to give a try to this item this week. Is it taken?

**Comment by tijsrademakers** [comment]
Yes it's taken, a first version is already on master.
Do you have other ideas to work on, or would you like some suggestions?

**Comment by motorina0** [comment]
Hi Tijs,
Below are some ideas:

1. **BPM Test Generation**
    Writing unit tests is not a pleasant task for everyone. In many situation some executed processes exist in the DB and we just want to have a unit tests to verify that particular scenario.
    Suggestion: based on the data stored in DB generate unit tests. Depending on the log level a lot of data can be extracted. We know:
      - what variables have ben used to start the process
      - the steps that have been executed and their order
      - how each variable was changed
      - what assignments took place
      - what exceptions or boundary events took place

    Based on this collected data, tests that invoke the right API with the right data can be generated together with the right assertions.
    Extra API can be developed for assertions specific BPM assertions:
      - assertThatStepsExecutedInExactOrder(stepId1, stepId2, ...)
      - assertThatStepsExecutedInAnyOrder(stepId1, stepId2, ...)
      
    This feature is for testing the Business Process logic and not the process engine.
      
2.  **Stand Alone Task Engine**
   This topic requires of course a full architecture document, but below are the main points.

   - User Tasks are probably the most important type of tasks in BPM. This is true because the end users interact with these steps (usualy via a web app or a mobile app).
   - User Tasks can store just a few fields, but in many cases it happens that large data structures are being manipulated.
   - Even if just a small part of the data is shown to the user, often times most of the fields are required when searching for User Tasks. 
   - One problem of current (implicit or explicit) Task Engines is that business data is stored as binary data in the DB, this results in serialization/deserialization overhead and implicitly very high response times. 
   - A solution is using a document based NoSQL DB (like Mongo DB) for storing this data. A more detailed article I've wrote some time ago can be found here: https://goo.gl/fntyBt
   
   - The Task Engine should also be responsible for user access management, detailed audit (who changed what field value) and certain event handling (like a business value change).
   - The Task Engine can live in the cloud while the Process Engine is on premises.
   
 3. **Docker images**
  Besides having docker images for Flowable (wich is very useful), additional images should be created and ready for Flowable integration (LDAP, MySql, Tomcat) that allow a more "production like" setup.
   
  I have also documented my progress with Activiti/Flowable here:
 https://activitibpm.blogspot.ro/

**Comment by tijsrademakers** [comment]
Hi,

Thanks for the suggestions. The first two are bigger features which would some analysis and discussions (which we are always open for). I like the third option as a short term benefit. We do have Postgres support already in the Docker images and also Tomcat I think. So would be good to check which ones should be created in addition.

**Comment by tijsrademakers** [comment]
Closing this issue
