### ISSUE TITLE
Originating Stacktrace lost here when this Exception get thrown

### ISSUE THREAD

**Issue by billerby** [flowable/flowable-engine#1602]
https://github.com/flowable/flowable-engine/blob/c88d32693d7591a7e708c09e585bbdc44808da5c/modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/process/ProcessInstanceVariableResource.java#L109

**Comment by billerby** [comment]
When debugging an error with failure to update a process variable I found much more info of the cause in this catch-clause which is lost when the FlowableIllegalArgumentException is thrown here.
Please make sure the originating Exception is added as well.

**Comment by tijsrademakers** [comment]
Thanks for raising the issue, the stacktrace is added now.
