### ISSUE TITLE
flowable.postgres.upgradestep.6010.to.6100.history.sql incredibly slow

### ISSUE THREAD

**Issue by JacekMiszczak** [flowable/flowable-engine#1628]
When upgrading a system that was using an earlier version of the engine for a long time this particular upgrade step can take an unreasonably long time, even more than 6 hours. The system in question has around 15 million rows in the act_hi_varinst table.
The statement that causes the slowdown is
`update ACT_HI_VARINST set REV_ = 1 where REV_ is null OR REV_ = 0;`

We've managed to get it down to around 20 minutes by removing indexes before this step and restoring them afterwards, but this isn't maintainable.

**Comment by tijsrademakers** [comment]
Hi,

With a very large number of rows these kind of updates can be really slow. Removing indexes before the update or rewriting the update statement in Postgres optimal way could be a solution. We try to limit these kind of updates as much as possible, but in rare occasions like this one it's needed.
