### ISSUE TITLE
Process definition name is not copied into process instance upon start

### ISSUE THREAD

**Issue by michaelplavnik** [flowable/flowable-engine#163]
Attached code is slightly modified Flowable sample which throws exception to diagnose the issue.
[HollidayApp.zip](https://github.com/flowable/flowable-engine/files/718477/HollidayApp.zip)

Modifying ExecutionEntityManagerImpl.createProcessInstanceExecution line 218 resolves this issue.

    public ExecutionEntity createProcessInstanceExecution(ProcessDefinition processDefinition, String businessKey, String tenantId, String initiatorVariableName) {
    ExecutionEntity processInstanceExecution = executionDataManager.create();    

    if (isExecutionRelatedEntityCountEnabledGlobally()) {
      ((CountingExecutionEntity) processInstanceExecution).setCountEnabled(true);
    }    

    processInstanceExecution.setProcessDefinitionId(processDefinition.getId());
    processInstanceExecution.setProcessDefinitionKey(processDefinition.getKey());
    // FIX
    processInstanceExecution.setProcessDefinitionName(processDefinition.getName());

**Comment by tijsrademakers** [comment]
Thanks, implemented the fix:

https://github.com/flowable/flowable-engine/commit/fc20edb8d84a113ec8d5be946938c2c6ea032306
