### ISSUE TITLE
How do I generate the diagram for a completed process

### ISSUE THREAD

**Issue by ofaklintrafo** [flowable/flowable-engine#1630]
The rest-api has a method to return the diagram for a running process.

And according to https://github.com/flowable/flowable-engine/issues/447 it should also be possible to request the diagram for a completed process.

But I can not see that anywhere in the documentation how ?

**Comment by tijsrademakers** [comment]
No #447 mentions that the admin and task application can show a SVG in the browser for the completed process instance which is using a JavaScript component. Right now, via the REST API, only a diagram for a running process instance can be retrieved.

**Comment by ofaklintrafo** [comment]
Ok. Is there an example on how I can render/present the SVG process diagram in my web application? Or can you guide me to the pieces in the Flowable code which handle the SVG diagram generation ?
