### ISSUE TITLE
the Flowable docs 2.4.3 curl Start a process instance error

### ISSUE THREAD

**Issue by imxingquan** [flowable/flowable-engine#1632]
curl --user rest-admin:test -H "Content-Type: application/json" -X POST -d '{ "processDefinitionKey":"holidayRequest", "variables": [ { "name":"employee", "value": "John Doe" }, { "name":"nrOfHolidays", "value": 7 }]}' http://localhost:8080/flowable-rest/service/runtime/process-instances

```
curl: (3) Port number ended with 'h'
curl: (6) Could not resolve host: variables
curl: (3) [globbing] bad range specification in column 2
curl: (3) [globbing] unmatched brace in column 1
curl: (3) Port number ended with 'e'
curl: (6) Could not resolve host: value
curl: (6) Could not resolve host: John Doe
curl: (3) [globbing] unmatched close brace/bracket in column 1
curl: (3) [globbing] unmatched brace in column 1
curl: (3) Port number ended with 'n'
curl: (6) Could not resolve host: value
curl: (6) Could not resolve host: 7
curl: (3) [globbing] unmatched close brace/bracket in column 1
{"message":"Bad request","exception":"JSON parse error: Unexpected character (''' (code 39)): expected a valid value (number, String, array, object, 'true', 'false' or 'null'); nested exception is com.fasterxml.jackson.core.JsonParseException: Unexpected character (''' (code 39)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')\n at [Source: (PushbackInputStream); line: 1, column: 2]"}
```

Why?  I used   flowable-6.4.1  tomcat-8.5.31

**Comment by jbarrez** [comment]
(In the future, please use the forum, https://forum.flowable.org/, for these kind of questions)

When I locally  do 

`curl --user rest-admin:test -H "Content-Type: application/json" -X POST -d '{ "processDefinitionKey":"holidayRequest", "variables": [ { "name":"employee", "value": "John Doe" }, { "name":"nrOfHolidays", "value": 7 }]}' http://localhost:8080/flowable-rest/service/runtime/process-instances`

The result is as expected (as I didn't deploy any process definition):
`{"message":"Bad request","exception":"No process definition found for key 'holidayRequest'"}`

However, when swapping the " and ' characters in the payload:

`curl --user rest-admin:test -H "Content-Type: application/json" -X POST -d "{ 'processDefinitionKey':'holidayRequest', 'variables': [ { 'name':'employee', 'value': 'John Doe' }, { 'name':'nrOfHolidays', 'value': 7 }]}" http://localhost:8080/flowable-rest/service/runtime/process-instances`

The result is:
`{"message":"Bad request","exception":"JSON parse error: Unexpected character (''' (code 39)): was expecting double-quote to start field name; nested exception is com.fasterxml.jackson.core.JsonParseException: Unexpected character (''' (code 39)): was expecting double-quote to start field name\n at [Source: (PushbackInputStream); line: 1, column: 4]"}`

Which is similar to your exception.

So it looks like you might need to swap the quoting characters of your payload json?
