### ISSUE TITLE
Adapt AsynHistoryManager to use the new runtime ActivityInstance

### ISSUE THREAD

**Issue by filiphr** [flowable/flowable-engine#1637]
When the runtime `ActivityInstance` were added there were new methods added to the `HistoryManager`. The current implementation of `recordActivityEnd(ActivityInstance activityInstance)` uses the old `getActivityStart` to get the activity start based on the execution and activityId. We should add a new method that would get the activity start based on the runtime activity instance id

**Comment by thiyagu-7** [comment]
I would like to work on this

**Comment by filiphr** [comment]
Hey @thiyagu-7,

Sure no problem. Do you know where to start and how this needs to be done?

Let us know if you need more information.

**Comment by thiyagu-7** [comment]
@filiphr Can you help me with the PR?
