### ISSUE TITLE
Back to a branch of parallel gateway

### ISSUE THREAD

**Issue by asdxuchao** [flowable/flowable-engine#1641]
i use ChangeActivityStateBuilder.moveSingleExecutionToActivityIds to implement this demand，task has been successfully returned，if continue complete success.However, task stop in parallel gateways and cannot continue to run 。Missing to-do tasks

**Comment by tijsrademakers** [comment]
Please be very detailed about the process definition that you are using. The best way is to share the BPMN XML and explain which values you are using when invoking the 
moveSingleExecutionToActivityIds method

**Comment by asdxuchao** [comment]
Hey, brother.
How to retrieve process tasks，and Determine whether the task is allowed to be retrieved
Thank you very much for your reply.

**Comment by tijsrademakers** [comment]
Can you please ask your questions on the forum? https://forum.flowable.org.
