### ISSUE TITLE
Enhance Groovy capabilities by including groovy-all library

### ISSUE THREAD

**Issue by VeridianDynamics** [flowable/flowable-engine#1655]
The current Groovy scripting support is quite bare bones, I notices that if I add a dependency to groovy-all, I get all sorts of useful tools I can use in the scripts. For example JsonSlurper is very nice if you're dealing with JSON inputs.

I suggest to add the groovy-all artifact to a relevant POM (flowable-app-rest/pom.xml ?) by default. Would this be an acceptable pull request?

**Comment by VeridianDynamics** [comment]
By the way, I have now seen this PR: https://github.com/flowable/flowable-engine/pull/1247/
It seems that the pull request was made under wrong assumptions, groovy-all still exists, so I assume the groovy-all library was just not released together with the rest of Groovy that one time.

Groovy-all is still under active development, as evidenced by this recent issue: https://issues.apache.org/jira/browse/GROOVY-9030

**Comment by VeridianDynamics** [comment]
Hi, would someone in charge please comment on this?

**Comment by filiphr** [comment]
@VeridianDynamics are you sure that groovy-all is the same in 2.5.x. Looking on Maven Central [groovy-all:2.5.6](https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-all/2.5.6) is a pom and [groovy-all:2.4.16](https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-all/2.4.16) is a jar dependency. It seems like that `groovy-all` is just a bom now. Seems like they have also addressed this in their [2.5 Release Notes](http://groovy-lang.org/releasenotes/groovy-2.5.html).

Looking at the [Getting started](https://github.com/apache/groovy/blob/master/src/spec/doc/core-getting-started.adoc) on Github it mentions that as well. For some reason on their [website](http://groovy-lang.org/install.html) they don't have the part with the `<type>pom</type>`.

I would suggest that you add the modules that you would like to use manually in your own application. I think that if you put the `groovy` dependencies in the tomcat lib folder it should work as expected.

If you have other suggestions please feel free to share them.

**Comment by VeridianDynamics** [comment]
@filiphr You're actually right, I didn't notice it was just a POM now. But if I understand correctly, this still means that the same Groovy components will be pulled in, just not in a single JAR file, right?

**Comment by filiphr** [comment]
@VeridianDynamics it is not the same. If you pull the pom as a dependency it will pull all transitive dependencies. However, before the other dependencies were extra.
