### ISSUE TITLE
Oracle as database has SQL error in flowable.oracle.upgradestep.6410.to.6411.entitylink.sql

### ISSUE THREAD

**Issue by kyllyang** [flowable/flowable-engine#1676]
When the flowable-task service is started by default, the schema is upgraded, but the following exception message is generated:
`FlowableException: couldn't upgrade db schema:  alter table ACT_RU_ENTITYLINK add column HIERARCHY_TYPE_ NVARCHAR2(255) ORA-00904 Invalid Ddentifier`
Because the SQL in flowable-entitylink-service-6.4.1.jar(org\flowable\entitylink\service\db\upgrade\flowable.oracle.upgradestep.6410.to.6411.entitylink.sql) is: alter table ACT_HI_ENTITYLINK add column HIERARCHY_TYPE_ NVARCHAR2(255);
In Oracle it should be: alter table ACT_HI_ENTITYLINK add HIERARCHY_TYPE_ NVARCHAR2(255);

**Comment by kyllyang** [comment]
The same problem occurs in the flowable.oracle.upgradestep.6410.to.6411.entitylink.history.sql file.
My Oracle version is 11.2.0.4.0.

**Comment by tijsrademakers** [comment]
Thanks for reporting, fixed the upgrade script files accordingly
