### ISSUE TITLE
[flowable modeler] Response always return 409 confilct with updating bpmnModel.

### ISSUE THREAD

**Issue by wangmin-xidian** [flowable/flowable-engine#1684]
Need help, thanks.
env 
> Flowable :  6.4.0,  
> DB : postgres 9.6.0 
> Browser : Chrome

problem 
 > Using flowable moderler, return 409 confilct if update bpmn with UI. 

**Analysis** 
 I found the reason in API `POST` ` /editor/models/{modelId}/editor/json`, `(model.getLastUpdated().getTime() != lastUpdated) ` . 
Based on browser request, `lastUpdated` is `2019-04-01 11:10:00`, newverison is false , but in postgres  model table field ` last_updated`(timestamp(6)) is `2019-04-01 11:10:00.182,` . so the code run the confilct branch. 

My question is : Is browser get lastUpdated wrong or configuration need to modify ? or others reason ?

**Comment by tijsrademakers** [comment]
Hi,

Are you using the Flowable Modeler and running into this issue with every BPMN model you open and save?

**Comment by wangmin-xidian** [comment]
There are two scenario:
- It occurs few times when I running Flowable Modeler wars(idm, modeler) with Tomcat. 
- Running it with source code ( UI & backend) , it happens to every BPMN model saving .

**Comment by tijsrademakers** [comment]
Ok, but if it happens on a few times when running in Tomcat, do you know the difference between when it works and doesn't work?

When running with the source code, it feels like something is wrong with the setup, because that should work exactly the same as running the WAR in Tomcat.

**Comment by wangmin-xidian** [comment]
I agree with your point:  running war and source code should be get the same result. 
Verify it again, found in the following : 
1. war version is 6.4.1, source code version is 6.4.0 ;
2. based on 6.4.1 version,  when saving modeler, API request field `lastUpdated` value is : `2019-04-01T03:57:07.029+0000` and  `2019-04-01 11:10:00` in 6.4.0 version;
3. problem which running war in Tomcat maybe a mistake that I mixe using two verison (not sure?)

So Is there have configuration to set the data format in UI code ? Momentjs? ( I'm backend dev, not familiar to Angurar or js)

**Comment by wangmin-xidian** [comment]
@tijsrademakers ,  flowable modeler is ok, it's my fault, fixed it now . 
The reason is `lastUpdated`  is got from backend, but I set `spring.jackson.data-format` = `yyyy-MM-dd HH:mm:ss` in `application.yml`.
