### ISSUE TITLE
Task properties panel in flowable-modeler is too small and not resizable

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#169]
Task properties panel in flowable-modeler UI is too small and not resizable.
It is also on the bottom of the screen which is quite inconvenient.

Thanks

**Comment by tijsrademakers** [comment]
Proposals for improvement are always welcome. Currently you can scroll through the properties. Closing this issue because there's no item on the roadmap to change this in the coming months without a proposal and help from the community.
