### ISSUE TITLE
Tomcat HTTP Status 404 – Not Found

### ISSUE THREAD

**Issue by MaryCooperGD** [flowable/flowable-engine#1694]
Hi, I'm trying to run a flowable instance with docker using `docker run -p8080:8080 flowable/flowable-rest` but it's giving me problems. In particular, after running the command I have [these errors](https://codeshare.io/axj1kX) in the terminal. I have docker up and running and all I did was starting that command.   
After all those errors, I have 

`  08-Apr-2019 07:54:53.340 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/opt/tomcat/webapps/flowable-task.war] has finished in [74,627] ms
08-Apr-2019 07:54:53.342 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/ROOT]
08-Apr-2019 07:54:53.388 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/ROOT] has finished in [47] ms
08-Apr-2019 07:54:53.389 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/docs]
08-Apr-2019 07:54:53.399 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/docs] has finished in [9] ms
08-Apr-2019 07:54:53.399 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/examples]
08-Apr-2019 07:54:53.535 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/examples] has finished in [136] ms
08-Apr-2019 07:54:53.535 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/host-manager]
08-Apr-2019 07:54:53.556 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/host-manager] has finished in [21] ms
08-Apr-2019 07:54:53.556 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/manager]
08-Apr-2019 07:54:53.581 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/manager] has finished in [24] ms
08-Apr-2019 07:54:53.593 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
08-Apr-2019 07:54:53.607 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
08-Apr-2019 07:54:53.610 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 296018 ms`

so it seems that server is running, but if I go to `http://localhost:8080/flowable/all-in-one` I have this:

![image](https://user-images.githubusercontent.com/12009396/55708762-03591d00-59e7-11e9-967a-be7ca21502dc.png)

Are there any steps I missed? I've tried deleting all docker images and killed all processes before doing this, but still I can't get flowable run. I need a hint please

**Comment by yvoswillens** [comment]
Hi.
The provided logging is not from the mentioned command. 
To run the all-in-one container use the following command;

`docker run -p8080:8080 flowable/all-in-one
`

As mentioned here; https://hub.docker.com/r/flowable/all-in-one

The Flowable REST image is described here; https://hub.docker.com/r/flowable/flowable-rest

Regards,

Yvo

**Comment by MaryCooperGD** [comment]
Hi, sorry I've copied it wrong but I used the one you wrote.

**Comment by yvoswillens** [comment]
See in the documentation what links to use to access the different Flowable apps.

**Comment by MaryCooperGD** [comment]
They doesn't work, any of them, I've already tried it out.

**Comment by yvoswillens** [comment]
If there are no errors in the logging and Tomcat reports it initialized correctly .. then it's probably a docker issue. Or related on how you access the docker containers.
F.e. running it on a remote instance.
