### ISSUE TITLE
Dead Letter - Filter Dead Jobs (Ids) by Activity Type (e.g. task type)

### ISSUE THREAD

**Issue by wberges** [flowable/flowable-engine#1699]
Hello,

Is it possible to provide a way to retrieve all jobs in the DeadLetter **associated to a specific task type** (activityId)?
Here's the use-case and the forum thread: https://forum.flowable.org/t/dead-letter-retrieve-dead-jobs-associated-to-a-specific-task/3669

Using the java API, it could use the same syntax as for other filtering queries (e.g. executionId).
Something like that:

> DeadLetterJobQuery jobQuery = managementService.createDeadLetterJobQuery();
> List< Job > myJobsFilteredByActivityId = jobQuery.activityId('MY_ACTIVITY_ID').list();
> 

In the same way, the main goal of such methods being to retry jobs (move from dead letter to execution) using their job ids, it would perhaps also be interesting to have a method returning **only the job ids** present in the dead letter (without all other data, or a small subset) to minimize the size of the returned data.
It would execute the equivalent of the following native query:

> SELECT D.ID_ FROM ACT_RU_DEADLETTER_JOB D,ACT_RU_EXECUTION E WHERE D.EXECUTION_ID_ = E.ID_ and E.ACT_ID_ = 'MY_ACTIVITY_ID' and E.DEADLETTER_JOB_COUNT_ > 0

Thanks for your support :)
Best Regards
William

**Comment by tijsrademakers** [comment]
Hi William,

Support has been added to filter jobs on an element id (activity id) or element name (activity name).

**Comment by wberges** [comment]
Thanks Tijs 😁
