### ISSUE TITLE
Create a ROOT web application with a landing page with links to all other 5 web apps

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#170]
Create a ROOT web application with a landing page with links to all other 5 web apps

Thanks

**Comment by tijsrademakers** [comment]
Hi,

It's good to provide feedback to us. But what I would like to prevent is that we have a lot of open issues that are not resolved soon. Could you post enhancement discussions on the forum first, so there can be more discussion in the community about it? I'm closing this PR for now, because I don't expect much work on this on the short term.

**Comment by mgrouch** [comment]
It is simple to add. Just a web application with index.xml 

`<!DOCTYPE html>
<html>

<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Flowable</title>

    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/style_002.css">
</head>

<body class="ng-scope">

    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation" id="main-header">
        <div class="fixed-container">
            <div class="navbar-header">
                <a class="landing-logo ng-scope" title="Flowable Editor">
                    <img srcset="/img/flowable-logo.png 1x,/img/flowable-logo@2x.png 2x"
                         src="/img/flowable-logo.png">
                </a>
                <ul style="" class="nav navbar-nav" id="main-nav" ng-show="authenticated">
                    <li class="ng-scope" onclick="window.location = '/flowable-task'">
                        <a class="ng-binding">Tasks</a>
                    </li>
                    <li class="ng-scope" onclick="window.location = '/flowable-modeler'">
                        <a class="ng-binding">Modeler</a>
                    </li>
                    <li class="ng-scope" onclick="window.location = '/flowable-idm'">
                        <a class="ng-binding">Identities</a>
                    </li>
                    <li class="ng-scope" onclick="window.location = '/flowable-admin'">
                        <a class="ng-binding">Admin</a>
                    </li>
                </ul>
            </div>
         </div>
    </div>

</body>
</html>
`

Thanks

**Comment by yvoswillens** [comment]
I see this issue is closed. Please start a discussion on this enhancement in the Flowable forum (forum.flowable.org) 
As for you snippet. Did you test this? Mind that these are separate webapps and by default run on different containers / ports. 

Regards,

Yvo
