### ISSUE TITLE
execution processInstanceId doesn't exist

### ISSUE THREAD

**Issue by MaryCooperGD** [flowable/flowable-engine#1709]
I'm trying to get the map of variables but it throws an error:

`execution <processInstanceId> doesn't exist`

I've followed the code here and wrote:

```
Map <String, Object> pvar = new HashMap<String,Object>();
				pvar.put("status",200);
				pi = runtimeService.startProcessInstanceById(processDefinitionId, pvar);
```

then I try to get the map again and 

`Map<String,Object> variables = runtimeService.getVariables(pi.getId());`

and the error is thrown. I've searched for the `pi.getId()` in the list of instances and it's there.  I used this same method for other process instances and all went well. What could the problem be?

**Comment by filiphr** [comment]
Does your process have a wait state? This is the only reason that I can think about now for this to happen. If your process does not have a wait state then it would already be finished after the start. This means that you can't get the variables from the runtime service.

If the process does have a wait state, then perhaps you can share us a reproducal test case that fails on getting the map. This way we would be able to do a better analysis.

For the future please use the [Flowable Forum](https://forum.flowable.org/) for asking questions.
