### ISSUE TITLE
Create standardized user roles for admin,modeler,deployer etc

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#171]
Create standardized user roles for admin,modeler,deployer etc

Thanks

**Comment by tijsrademakers** [comment]
Did you look in the ACT_ID_PRIV and ACT_ID_PRIV_MAPPING tables? For admin and modeler there's already an access privilege.

**Comment by tijsrademakers** [comment]
Closing the issue due to no response. Please reopen when necessary.
