### ISSUE TITLE
CallActivity subprocess not properly deleted when contained in subprocess and parent deleted

### ISSUE THREAD

**Issue by paulstapleton** [flowable/flowable-engine#1711]
I have a process which looks like this:

![bild](https://user-images.githubusercontent.com/592501/56127788-3b7bd500-5f7e-11e9-8165-7352f682ecd8.png)

That is a callActivity contained in a subprocess.
If I then delete the parent processinstance using the runtime API `runtimeService.deleteProcessInstance(processInstance.getId(), null);` both the parent and the subprocess is deleted.

However the subprocess does not have the endTime set. This makes it hard to later determine that the process has actually been finished.

I have created a testcase which displays this behaviour - https://github.com/paulstapleton/testcases/blob/master/src/test/java/testcases/CallActivityInSubProcessTest.java

I believe the problem is here https://github.com/flowable/flowable-engine/blob/8da07272409e0320ce89bc92d4110d4b8676e00f/modules/flowable-engine/src/main/java/org/flowable/engine/impl/persistence/entity/ExecutionEntityManagerImpl.java#L469 where the additional subprocess around the callactivity is not taken into account. Though I am unsure how to fix it.

I have also experienced the same problem when using a multi-instance subprocess around a call activity.

This was tested using Flowable 6.5.0-SNAPSHOT.

**Comment by tijsrademakers** [comment]
Thanks for reporting the issue and the unit test. It's fixed now
