### ISSUE TITLE
problem during schema drop, statement drop index ACT_IDX_IDENT_LNK_SCOPE_DEF on ACT_RU_IDENTITYLINK

### ISSUE THREAD

**Issue by tangyibo** [flowable/flowable-engine#1713]
problem during schema drop, statement drop index ACT_IDX_IDENT_LNK_SCOPE_DEF on ACT_RU_IDENTITYLINK

mysql> show tables;
+-------------------------------+
| Tables_in_Flowable            |
+-------------------------------+
| ACT_APP_APPDEF                |
| ACT_APP_DATABASECHANGELOG     |
| ACT_APP_DATABASECHANGELOGLOCK |
| ACT_APP_DEPLOYMENT            |
| ACT_APP_DEPLOYMENT_RESOURCE   |
| ACT_GE_BYTEARRAY              |
| ACT_GE_PROPERTY               |
| ACT_HI_IDENTITYLINK           |
| ACT_HI_VARINST                |
| ACT_RU_IDENTITYLINK           |
| ACT_RU_VARIABLE               |
+-------------------------------+
11 rows in set

**Comment by tijsrademakers** [comment]
Please explain in more details what you mean with schema drop.

**Comment by tijsrademakers** [comment]
Closing issue, please reopen with more details when needed.
