### ISSUE TITLE
Start process instance with timer event runs just one time 

### ISSUE THREAD

**Issue by MaryCooperGD** [flowable/flowable-engine#1714]
In the docs it is said:

`a start timer event is scheduled as soon as process is deployed. There is no need to call startProcessInstanceByXXX, although calling start process methods is not restricted and will cause one more starting of the process at the time of startProcessInstanceByXXX invocation`

but I have a doubt. Does this mean that with `startProcessInstanceByXXX` starts one and only one additional execution? Or should it also work with the start timer event, and so repeat every X time (as specified in cron expression)? 

If it's the first case, then when I run my process instance it runs just one time

**Comment by tijsrademakers** [comment]
Hi,

A start timer event creates a timer job in the Flowable timer job table. Without having to call the startProcessInstanceByXXX method, it will automatically create instances with the timer job. When invoking the startProcessInstanceByXXX method anyway it will just create one additional instance. In the meantime the timer job will still create instances as well. For this to work, the async executor needs to be enabled and activated.

**Comment by MaryCooperGD** [comment]
Hi, thank you for your answer.
Is there an example I can look at to realize an asynchronous and repetitive for my process instance?

**Comment by tijsrademakers** [comment]
Did you check if a timer job is created in the ACT_RU_TIMER_JOB table when this process definition is deployed? Is the async executor enabled and active? What are you using to run this process definition? The Flowable Task application or the REST app?

**Comment by MaryCooperGD** [comment]
Yes, a timer job is created when it is deployed. I need to trigger the execution with a start timer event when I run a process instance. Let's say my process has a timer that says it has to run each minute. I need to start my process instance and then, from that moment and that instance, every minute a new istance is run. I know this can be done when I deploy an xml (and it works), but I was wondering if there's a way to do the same when I start a process instance, and if I can disable this behaviour from deployment's start.

**Comment by tijsrademakers** [comment]
No that's the way it is working according to the BPMN specification. When a process definition XML is deployed the timer job is created and it will automatically start new instances according to the timer start event definition. Manually starting a process instance with a timer start event is not very common.

**Comment by MaryCooperGD** [comment]
It is not very common, but is it possible? And if so, how?
Also, is it possible to disable the start of the process instances when deploying or it's the logic of the engine and cannot be modified?

**Comment by tijsrademakers** [comment]
No this can't be modified, because that's why you would use a timer start event in a process definition. 
Yes manually starting a process instance with a timer start event is possible, it will just create an additional process instance.

**Comment by MaryCooperGD** [comment]
> Yes manually starting a process instance with a timer start event is possible, it will just create an additional process instance

I know this, I was asking if it's possible to start a chain of process instances each X time (specified in cron) after a first instance is run, or this can never in any way be done

**Comment by tijsrademakers** [comment]
everything can be done, but it's not supported within Flowable. You could write your own start logic to implement this.

**Comment by MaryCooperGD** [comment]
Of course. I meant inside flowable engine to keep things "easy".
Thank you for the clarification.
