### ISSUE TITLE
<redacted> flowable-ui-modeler

### ISSUE THREAD

**Issue by Simon-Lau** [flowable/flowable-engine#1718]
Honestly, the source code of flowable-modeler UI is shit. It is not a good way to declare XXX.xml in different modules. And should not all base on JSON converter for app, bpmn and form ext..

**Comment by Simon-Lau** [comment]
What's more, all source code do not have one line of comment

**Comment by yvoswillens** [comment]
Please do not use profanity on a public GitHub repository. 
Message closed.
If you want to discuss improvements, please use the [forum](https://forum.flowable.org).

**Comment by Simon-Lau** [comment]
Sorry for that, My apologize
