### ISSUE TITLE
MariaDB not supported

### ISSUE THREAD

**Issue by ilgrosso** [flowable/flowable-engine#1729]
When configuring Apache Syncope with Flowable and MariaDB, an exception is raised during startup:

```
org.flowable.common.engine.api.FlowableException: couldn't deduct database type from database product name 'MariaDB'
```

At the moment we have simply extended `SpringProcessEngineConfiguration` with:

```java
         databaseTypeMappings.setProperty("MariaDB", DATABASE_TYPE_MYSQL);
```

e.g. treating MariaDB as MySQL - so far, so good.

See [SYNCOPE-1470](https://issues.apache.org/jira/browse/SYNCOPE-1470) for more details.

**Comment by dbmalkovsky** [comment]
MariaDB is actually supported as the code treats it as MySQL.  In recent revisions of MariaDB the metadata has changed causing this issue.  See https://forum.flowable.org/t/flowable-ui-app-properties-file-not-working/1836/20 to see another way to use MariaDB.

**Comment by ilgrosso** [comment]
@dbmalkovsky thanks for explanation.
I understand that the workaround provided in the links above works; I have anyway proposed PR #1737.

**Comment by DarkStar1** [comment]
@ilgrosso I had the same issue and commented and provided a workaround in [this reply](https://forum.flowable.org/t/flowable-ui-app-properties-file-not-working/1836/20?u=darkstar1) in the forum. Hope you find it useful.
