### ISSUE TITLE
Support login via SSO SAML IDPs in flowable-idm

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#173]
Support login via SSO SAML IDPs in flowable-idm (And document its setup)

Thanks

**Comment by tijsrademakers** [comment]
Is this something you would like to contribute?

**Comment by tijsrademakers** [comment]
Closing the issue because it's not on the roadmap. Please reopen when there are more people interested and/or people willing to contribute.

**Comment by mgrouch** [comment]
Well you are already using flowable-idm as identity provider (IDP). You just need to change the protocol you are using to standard SAML with open SAML and you will achieve the goal.
Thanks
