### ISSUE TITLE
Flowable logo in the admin page

### ISSUE THREAD

**Issue by daaast** [flowable/flowable-engine#1733]
![immagine](https://user-images.githubusercontent.com/17124731/57438542-7357fe80-7244-11e9-862d-c15f294b7fd5.png)

The flowable logo in the admin page is not visualized correctly in Firefox 66.0.5 windows 10.

**Comment by srinathganesh** [comment]
> ![immagine](https://user-images.githubusercontent.com/17124731/57438542-7357fe80-7244-11e9-862d-c15f294b7fd5.png)
> 
> The flowable logo in the admin page is not visualized correctly in Firefox 66.0.5 windows 10.

Looks exactly same in Chrome, Ubuntu 18
