### ISSUE TITLE
Multi-instance fails to pass correct element value to form

### ISSUE THREAD

**Issue by paulrda** [flowable/flowable-engine#1743]
i have a User Task in my process and i want to execute user tasks **parallel**. i use multi-instance feature and added a List collection array to Collection property. i added a name for element variable and passed element variable to form property to show assigned element value to the form but i can see only last index value of List collection in every form of User Tasks.
Multi-instance feature only works if i change the User Task multi-instance execution to **Sequential**.
I use default form engine and i access the process and view User Task from Flowable-task UI. 
In my Collection Array i have two entries. first index value is "item 1" and second index value is "item 2". after enabling multi-instance this is how forms looks like.

_Process diagram View From Eclipse designer_
<img width="922" alt="eclipse screen shot" src="https://user-images.githubusercontent.com/15071681/57704999-a05f4380-7680-11e9-8af6-b1afe03e9740.png">

_First Form_

<img width="1423" alt="Multi Instance Form 1" src="https://user-images.githubusercontent.com/15071681/57685354-52811600-7655-11e9-9ae2-e54c45119745.png">

_Second Form_

<img width="1423" alt="Multi Instance Form 2" src="https://user-images.githubusercontent.com/15071681/57685396-67f64000-7655-11e9-8adb-964bba93c5e3.png">

There is no errors in logs to post here.
i have created a uni test project for this issue.
[https://github.com/paulrda/Home-Test-Projects/tree/master/flowable-multi-instance](url)

**Comment by tijsrademakers** [comment]
Hi, the current form variable resolvement doesn't work for multi instance yet. You could still fetch the correct variables via the Java API and then invoke the getFormModelWithVariablesByKeyAndParentDeploymentId method in the org.flowable.form.api.FormService to get the correct form.
