### ISSUE TITLE
How to implement all swagger documentation together

### ISSUE THREAD

**Issue by rcanpahali** [flowable/flowable-engine#1749]
Hello,

I want to generate all documents for my C# projec. I'm generating documents for a single document type. For example below code only generate APIs for "content",

`java -jar swagger-codegen-cli.jar generate -i http://192.168.100.29:8080/flowable-rest/docs/specfile/content/flowable.json -l csharp`

But I want to generate all API's in one Class in my **.\src\IO.Swagger\Client\ApiClient.cs**, any way to achieve this?

Thank you.

**Comment by tijsrademakers** [comment]
Hi, please use the Flowable forum to ask questions. I think the easiest way to generate all APIs is to combine all swagger documents in one file.
