### ISSUE TITLE
initiator is null

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#175]
When I'm trying to start the process via REST call initiator is null inside the process

curl "http://localhost:8080/flowable-task/process-api/runtime/process-instances" \
      -H "Accept: application/json" \
      -H "Content-Type: application/json;charset=utf-8" \
      --user admin:test \
      -X POST -d '{"processDefinitionKey":"PilotFlow", "variables": [{"name":"startParameter","value":"startParameter value"}]}'

When I start same process via flowable-task web UI, initiator  is correct.

Also the processes started via previous REST call are not appearing in flowable-task web UI.

My process is just 3 service tasks (no user tasks).

Thanks,
--MG

**Comment by mgrouch** [comment]
and 
http://localhost:8080/flowable-task/process-api/history/historic-process-instances
shows the process instance but
flowable-task web UI doesn't show it anywhere.

**Comment by tijsrademakers** [comment]
Thanks, the issue should be fixed with this commit:

https://github.com/flowable/flowable-engine/commit/1ede6706d4ee0063ffb8cec2eef3426c221d878e
