### ISSUE TITLE
workflow process start time all is the same '2019-04-30 16:07:22.667'

### ISSUE THREAD

**Issue by tangyibo** [flowable/flowable-engine#1750]
I found the field value of START_TIME_ for table ACT_HI_ACTINST and  ACT_RU_ACTINST and ACT_RU_EXECUTION data all is the same '2019-04-30 16:07:22.667' , what can i do ? version:flowable 6.4.1.3

**Comment by filiphr** [comment]
Can you please use the [Flowable Forum](www.forum.flowable.org) for asking questions.

Your question is also similar to [this](https://forum.flowable.org/t/starttime-and-endtime-not-set-properly/3805) from the forum. It looks like the clock is set to some fixed value.

**Comment by tangyibo** [comment]
Thank you very much for your help, and after i read the question on the forum, i do follow it like this:
 # step 1: create a class which impliments org.flowable.common.engine.impl.runtime.Clock
```
import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;

import org.flowable.common.engine.impl.runtime.Clock;

public class MyDefaultClock implements Clock {

	@SuppressWarnings("unused")
	private Date currentTime;
	
	@SuppressWarnings("unused")
	private Calendar currentCalendar;

	public MyDefaultClock() {
		this.reset();
	}

	@Override
	public Date getCurrentTime() {
		return new Date();
	}

	@Override
	public Calendar getCurrentCalendar() {
		return Calendar.getInstance();
	}

	@Override
	public Calendar getCurrentCalendar(TimeZone timeZone) {
		return Calendar.getInstance();
	}

	@Override
	public TimeZone getCurrentTimeZone() {
		return TimeZone.getDefault();
	}

	@Override
	public void setCurrentTime(Date currentTime) {
		this.currentTime = currentTime;
	}

	@Override
	public void setCurrentCalendar(Calendar currentTime) {
		this.currentCalendar = currentTime;
	}

	@Override
	public void reset() {
		this.currentTime = new Date();
		this.currentCalendar = Calendar.getInstance();
	}

}
```

# step 2 : before build or create ProcessEngine  , set clock object for it , here is the object of class type "MyDefaultClock", the code like this:
```
       @Bean
	public ProcessEngine processEngine(SpringProcessEngineConfiguration configuration) throws IOException {
               configuration.setClock(new MyDefaultClock());
               return configuration.buildProcessEngine();
	}
```

## Question is : Is it right which i only do these ?

**Comment by filiphr** [comment]
@tangyibo it is enough to only post on the forum. You don't have to cross post. We have answered your question on the forum post.
