### ISSUE TITLE
Boundy timer event does not support configuring execution listeners in the flowable-modeler app.

### ISSUE THREAD

**Issue by G-ing** [flowable/flowable-engine#1754]
hi,
As described in the title, i want to add a execution listener into boundy timer event. By the way, some customized codes could be executed when the timer fired.
![timer_conf](https://user-images.githubusercontent.com/11309145/58000519-923f7600-7b0b-11e9-83e8-2c802c364a68.jpg)

**Comment by PascalSchumacher** [comment]
I guess this can be closed as the fix in https://github.com/flowable/flowable-engine/pull/1756 was merged.

**Comment by tijsrademakers** [comment]
Thanks
