### ISSUE TITLE
Rest API Authorization

### ISSUE THREAD

**Issue by BhushanChaudhary** [flowable/flowable-engine#1755]
Hi, 
I am working on rest api of flowable, but there is an issue while I am going to complete the task using api its allow any user to complete the process, for example, I have assigned the processes to the different assignee, but its allow any assignee to complete any process. Please help how to handle this authorization. Can we handle this in from flowable spring security?

**Comment by tijsrademakers** [comment]
Hi,

Please use the forum for questions. You can use the https://github.com/flowable/flowable-engine/blob/master/modules/flowable-rest/src/main/java/org/flowable/rest/service/api/BpmnRestApiInterceptor.java to add additional authorization logic when fetching a task. If an implementation of this interface is exposed as a Spring Bean it will get invoked when fetching a task with the REST API.

**Comment by BhushanChaudhary** [comment]
I want the only assign assignee can able to complete the process through Rest api, but its not happening now any assignee can able to complete any process that its not assign to them. 
From flowable UI its work correctly but issue using rest api.

**Comment by tijsrademakers** [comment]
Exactly, this rule can be implemented in the BpmnRestApiInterceptor with the accessTaskInfoById method. Because Flowable is used in a lot of different use case this is not checked by default but it can be easily implemented using the BpmnRestApiInterceptor interface.
