### ISSUE TITLE
flowable-spring-boot-starter breaks spring boot security

### ISSUE THREAD

**Issue by JJWTimmer** [flowable/flowable-engine#1762]
When I generate a start.spring.io 2.1.5 app with web, actuator, security, devtools, and I start it, I can access localhost:8080/actuator after logging in with user and the password from the console.

As soon as I add this to the pom, the generated password disappears from the log and the user.name and .password properties in application.properties are ignored:
```
<dependency>
    <groupId>org.flowable</groupId>
    <artifactId>flowable-spring-boot-starter</artifactId>
    <version>6.4.1</version>
</dependency>
```

**Comment by filiphr** [comment]
It is not really breaking it. When you adding the flowable starter as a dependency then we are going to provide with a Spring Security `UserDetailsService` backed by the Flowable `IdmIdentityService`.

Have a look at the [`FlowableSecurityAutoConfiguration`](https://github.com/flowable/flowable-engine/blob/master/modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/FlowableSecurityAutoConfiguration.java). 

If you provide your own `UserDetailsService` then the one from Flowable will back off. You can also exclude the `FlowableSecurityAutoConfiguration` if you don't need it. Keep in mind that if you do that you would need to take care for making sure that the `AuthenticationContext` has the current user id. This is needed for setting the start user id in process / cases.

**Comment by JJWTimmer** [comment]
I see. Just me being confused, trying to follow all tutorials/components together... Thanks!
