### ISSUE TITLE
Missing Table "ACT_RU_VARIABLE" Create Statement in db/create scripts

### ISSUE THREAD

**Issue by easense** [flowable/flowable-engine#1763]
![image](https://user-images.githubusercontent.com/3226402/58369627-9fa39880-7f2f-11e9-8ead-a3252aeb5d43.png)

When using sql scripts under flowable-engine-6.4.1.jar!/org/flowable/db/create/flowable.oracle.create.engine.sql, encountered above complaints.

**Comment by cyssxt** [comment]
how to resolve it

**Comment by yamil-rivera** [comment]
@easense I encountered the same issue on 6.5.0 for mysql. How did you fix it?
