### ISSUE TITLE
"script format" field in UI of flowable-modeler should be a dropdown

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#177]
"script format" field in UI of flowable-modeler should be a dropdown

Thanks,
--MG

**Comment by tijsrademakers** [comment]
The scripting options are pluggable and flexible. So having a dropdown would limit this.

**Comment by mgrouch** [comment]
Dropdown can be dynamic. There should be a REST service in engine to return list of supported scripting languages for that dropdown.
Thanks
