### ISSUE TITLE
why inputDataItem of multiInstanceLoopCharacteristics in API means dataInputRef of it in XML??? 

### ISSUE THREAD

**Issue by jjjjjjjava** [flowable/flowable-engine#1785]
Damn,guys,It's really confused me.
In the docs,InputDataItem is used with InputDataRef,and ElementVariable used With Collection,which means InputDataItem to InputDataRef is as ElementVariable to Collection.
But in API,there is a setter of InputDataItem without InputDataRefs.Meanwhile,there are setters of Collection and ElementVariable,but guess what?Nothing happen after setting collectionString.
Actually ,setting InputDataItem will do the work,which you expect setting inputDataRef or collectionString to do.

**Comment by tijsrademakers** [comment]
Please use the Flowable forum to ask questions. Using the collectionString should have impact because it's used in the multi instance Java logic. Maybe you can share the source code example of what you are trying to do.
