### ISSUE TITLE
Add support for accessing JsonNode elements by id in the JsonNodelELResolver

### ISSUE THREAD

**Issue by filiphr** [flowable/flowable-engine#1797]
Currently the `JsonNodelELResolver` supports only accessing nodes by string. It can be enhanced to also support doing a get by an integer. For example `arrayNode.get(0)` would return the first element of an array node.

**Comment by VishwajeetNehra** [comment]
Hi i'm interested in working on this issue

**Comment by filiphr** [comment]
Hey @VishwajeetNehra, feel free to start working on it. Do you need some help or you already know what to do?

**Comment by VishwajeetNehra** [comment]
The only tests for JsonNodeELResolver I could find were in the flowable-common-engine's test folder. Are these the only ones there? I tried to break the tests using the class's getValue() method but nothing happened. I am not sure how to check if my solution works, could you suggest how to check if it works?

**Comment by filiphr** [comment]
I would suggest looking into the [`JsonTest`](https://github.com/flowable/flowable-engine/blob/master/modules/flowable-engine/src/test/java/org/flowable/engine/test/json/JsonTest.java). More precisely the `testDirectJsonPropertyAccess`. The bpmn files are located in `https://github.com/flowable/flowable-engine/tree/master/modules/flowable-engine/src/test/resources/org/flowable/engine/test/json`.

Which tests did you actually find? Can you share a link, perhaps?
