### ISSUE TITLE
Default workflow behavior on error needs to allow to see an error in flowable-task UI

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#180]
If workflow fails currently there is nothing visible in task UI.
It is better by default make it to come into certain 'error' state and display it in UI, 
where authorized flowable-task UI user would click on it and see the cause of issue.
This should be default behavior for all workflows.
Thanks

**Comment by tijsrademakers** [comment]
What do you mean with "If a workflow fails"? What kind of error are you talking about? I think the task UI responds with an error message, when for example a service task fails after a user task is completed.

**Comment by mgrouch** [comment]
If the service task fails it only prints stacktrace in a log and nothing in UI.

**Comment by tijsrademakers** [comment]
ok, will verify this and make sure it shows an error message in the UI.

**Comment by tijsrademakers** [comment]
An error message is shown in the Task app UI when an exception occurs when for example completing a user task
