### ISSUE TITLE
Font in expression dialogues should be monospaced.

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#182]
Font in expression dialogues should be even spaced.
When you edit a script it is nice to have Courier type of font.

Thanks

**Comment by tijsrademakers** [comment]
If you think a Courier type of font is better, I'm ok to give that a try. But it would really need a PR from you or someone else in the community. Closing the issue for now.

**Comment by mgrouch** [comment]
Any kind of monospaced font

**Comment by tijsrademakers** [comment]
Again, fine with me, but please create a PR and we'll merge it.

**Comment by mgrouch** [comment]
In displaymodel.css you need to add (at the end)

```
div[class*='ui-tooltip-kisbpm-'] {
    font-family: Monaco,Andale Mono,Courier New,monospace;
    font-size: 11px;
    white-space: pre;
}

div[class*='ui-tooltip-kisbpm-'] .qtip-content {
    font-family: Monaco,Andale Mono,Courier New,monospace;
    font-size: 11px;
    white-space: pre;
}

.ui-tooltip-kisbpm-bpmn .qtip-titlebar {
    white-space: pre;
}

.ui-tooltip-kisbpm-bpmn .qtip-tip {
    white-space: pre;
}


.qtip {
    max-width: 680px;
    min-width: 100px;
}

```

and you should really have a single place for css instead of copying and pasting them around between several apps.
Might be create an overlay for maven war plugin and use it in all apps.

Thanks

**Comment by mgrouch** [comment]
Oh an the beginning of style.css
should have this 
```

textarea.form-control {
    height: auto;
    font-family: Consolas,Monaco,Lucida Console,Liberation Mono,DejaVu Sans Mono,Bitstream Vera Sans Mono,Courier New, monospace;
}


```
