### ISSUE TITLE
Suggestions to realize org.flowable.common.engine.impl.cfg.IdGenerator interface, unified model UUID generated

### ISSUE THREAD

**Issue by think-gem** [flowable/flowable-engine#1820]
https://github.com/flowable/flowable-engine/blob/999cac0920eb3c28658a94c66028a3d14d1fde8c/modules/flowable-ui-common/src/main/java/org/flowable/ui/common/repository/UuidIdGenerator.java#L29

**Comment by filiphr** [comment]
The flowable-ui-common module does not have and does not need a dependency to flowable artifacts. Flowable Admin and Flowable Modeler are standalone applications that do not need the dependency. 

What is wrong with the UuidIdGenerator?

**Comment by think-gem** [comment]
Oh, thanks. I'd like to rewrite it. Hope can using an interface

**Comment by filiphr** [comment]
If you want you can extract an interface and prepare a PR. We can look into it and merge it.
