### ISSUE TITLE
V6.4.1 DatabaseTablePrefix does not automatically create tables that set prefixes

### ISSUE THREAD

**Issue by think-gem** [flowable/flowable-engine#1829]
I set up:
```
SpringProcessEngineConfiguration conf = new SpringProcessEngineConfiguration();
conf.setDatabaseTablePrefix("flowable_");
conf.setTablePrefixIsSchema(true);
```
```
SpringIdmEngineConfiguration conf = new SpringIdmEngineConfiguration();
conf.setDatabaseTablePrefix("flowable_");
conf.setTablePrefixIsSchema(true);
```

- startup the project and still create tables starting with `act_` in the database without adding the prefix `flowable_act_`
- so the Table does not exist error: `Table 'flowable.flowable_act_ge_property' doesn't exist`

**Comment by unamanic** [comment]
With `conf.setTablePrefixIsSchema(true)` it's expecting the prefix to be the schema name, so it doesn't get prepended to the the table name.  It should be looking for `flowable_.act_ge_property` Are you getting the table does not exist error in app?

**Comment by MiniApp** [comment]
> With `conf.setTablePrefixIsSchema(true)` it's expecting the prefix to be the schema name, so it doesn't get prepended to the the table name. It should be looking for `flowable_.act_ge_property` Are you getting the table does not exist error in app?

mysql-connector-java use version 5.X.X

**Comment by tijsrademakers** [comment]
Closing the issue due to no feedback.
