### ISSUE TITLE
in taskflow-modeler GUI editor task details come up blank after I collapse details panel

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#184]
in taskflow-modeler GUI editor task details come up blank after I collapse details panel

Try collapsing and expanding it back.

Thanks

**Comment by tijsrademakers** [comment]
Could reproduce this on Safari, it's working on Chrome

**Comment by mgrouch** [comment]
I have this issue in FireFox. too.
Thanks

**Comment by boran-yeleser** [comment]
I have this issue too in fireFox.  If u use arrow icon(not name) it works fine...

**Comment by tijsrademakers** [comment]
Should be fixed now on Safari and Firefox
