### ISSUE TITLE
The BpmnModel to XML extension property is invalid

### ISSUE THREAD

**Issue by mnhy520** [flowable/flowable-engine#1841]
BpmnModel Object
Service task
![image](https://user-images.githubusercontent.com/1035467/61018574-de9b8980-a3c9-11e9-9f14-d1ffa124caae.png)
User task
![image](https://user-images.githubusercontent.com/1035467/61018686-4a7df200-a3ca-11e9-8551-2ce208894120.png)
code
```
 public static String bpmnModelToXml(BpmnModel bpmnModel) {
        try {
            BpmnXMLConverter bpmnXMLConverter = new BpmnXMLConverter();
            byte[] bytes = bpmnXMLConverter.convertToXML(bpmnModel);
            String newBpmnText = new String(bytes);
            return newBpmnText;
        } catch (Exception e) {
            throw new BpWorkFlowException("bpmnModelToXml has error.");
        }
    }
```

Produced XML
```
    <serviceTask id="eid-33b9ae4f-6190-4661-9144-9baf6b1cb32d" flowable:async="true" flowable:class="com.ebizprise.cloud.bp.workflow.delegate.CommonJavaDelegate" flowable:triggerable="true"></serviceTask>
    <userTask id="eid-ef29fb32-7c2a-4dbd-95b4-d7fc4583d970" xmlns:ebiz="ebiz" ebiz:status="ES_NOT_ARRIVED" ebiz:subtype="TEAMWORK"></userTask>
```

User task is valid Service task is invalid.

Ask the Great God for help and see why. Thank you.

**Comment by tijsrademakers** [comment]
Please create a unit test that reproduces this issue, then we'll have a look and fix the issue if it's reproducible. Thanks.

**Comment by mnhy520** [comment]
Create BpmnModel object.

BpmnModel bpmnModel = new BpmnModel();
Process process = new Process();      
......
ServiceTask serviceTask = new ServiceTask();
        serviceTask.setImplementationType(BpmnXMLConstants.ATTRIBUTE_TASK_SERVICE_CLASS);
        serviceTask.setImplementation(beanName);
        serviceTask.setId(pbfElement.getId());
        serviceTask.setTriggerable(true);
        serviceTask.setAsynchronous(true);
        **ExtensionAttribute attribute = new ExtensionAttribute("subtype");
        attribute.setValue("RUNNING");
        serviceTask.addAttribute(attribute);**
.......
process.addFlowElement(serviceTask);
bpmnModel.addProcess(process);

String xmlBpmn=bpmnModelToXml(bpmnModel);

**Comment by tijsrademakers** [comment]
For service tasks and other task types we recommend to use extension elements instead of attributes. That's why you are seeing this behaviour.
