### ISSUE TITLE
SQL ERROR at org.flowable.variable.service.impl.persistence.entity.HistoricVariableInstanceEntityImpl

### ISSUE THREAD

**Issue by zhangchunl** [flowable/flowable-engine#1842]
if upate NAME_

<update id="updateHistoricVariableInstance" parameterType="org.flowable.variable.service.impl.persistence.entity.HistoricVariableInstanceEntityImpl">
        update ${prefix}ACT_HI_VARINST
        <set>
            REV_ = #{revisionNext, jdbcType=INTEGER},
            <if test="originalPersistentState.name != name">
                NAME_ = #{name, jdbcType=VARCHAR}
            </if>
            <if test="(byteArrayRef != null and originalPersistentState.byteArrayRef == null) or (byteArrayRef == null and originalPersistentState.byteArrayRef != null) or (originalPersistentState.byteArrayRef != byteArrayRef.id)">
                BYTEARRAY_ID_ = #{byteArrayRef, typeHandler=VariableByteArrayRefTypeHandler},
            </if>
            <if test="originalPersistentState.doubleValue != doubleValue">
                DOUBLE_ = #{doubleValue, jdbcType=DOUBLE},
            </if>
            <if test="originalPersistentState.longValue != longValue">
                LONG_ = #{longValue, jdbcType=BIGINT},
            </if>
            <if test="originalPersistentState.textValue != textValue">
                TEXT_ = #{textValue, jdbcType=VARCHAR},
            </if>
            <if test="originalPersistentState.textValue2 != textValue2">
                TEXT2_ = #{textValue2, jdbcType=VARCHAR},
            </if>
            <if test="(originalPersistentState.typeName == null and variableType != null) or (originalPersistentState.typeName != null and variableType == null) or (originalPersistentState.typeName != variableType.typeName)">
                VAR_TYPE_ = #{variableType, jdbcType=VARCHAR},
            </if>
            <if test="originalPersistentState.lastUpdatedTime != lastUpdatedTime">
                LAST_UPDATED_TIME_ = #{lastUpdatedTime, jdbcType=TIMESTAMP}
            </if>
        </set>
        where ID_ = #{id, jdbcType=VARCHAR}
        and REV_ = #{revision, jdbcType=INTEGER}
    </update>

**Comment by tijsrademakers** [comment]
Can you share the SQL error and for which database you are using?

**Comment by zhangchunl** [comment]
### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'BYTEARRAY_ID_ = '2753327',                                    
  6244                                                                                                                                                                                                                                                                                                       
  6245                                                                                                                                                                                                                                                                                                       
  6246                                                                                                                                                                                                                                                                                                       
  6247                                                                                                                                                                                                                                                                                                       
  6248   ' at line 7                                                                                                                                                                                                                                                                                         
  6249  ### The error may involve org.flowable.variable.service.impl.persistence.entity.HistoricVariableInstanceEntityImpl.updateHistoricVariableInstance-Inline                                                                                                                                             
  6250  ### The error occurred while setting parameters                                                                                                                                                                                                                                                      
  6251  ### SQL: update ACT_HI_VARINST          SET REV_ = ?,                              NAME_ = ?                                           BYTEARRAY_ID_ = ?,                                                                                               VAR_TYPE_ = ?,                               
            LAST_UPDATED_TIME_ = ?          where ID_ = ?         and REV_ = ?                                                                                                                                                                                                                               
  6252  ### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'BYTEARRAY_ID_ = '2753327',                                                              
  6253                                                                                                                                                                                                                                                                                                       
  6254                                                                                                                                                                                                                                                                                                       
  6255                                                                                                                                                                                                                                                                                                       
  6256                                                                                                                                                                                                                                                                                                       
  6257   ' at line 7                                                                                                                                                                                                                                                                                         
  6258          at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)                                                                                                                                                                                                     
  6259          at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)                                                                                                                                                                                                   
  6260          at org.flowable.common.engine.impl.db.DbSqlSession.flushUpdates(DbSqlSession.java:503)                                                                                                                                                                                                       
  6261          at org.flowable.common.engine.impl.db.DbSqlSession.flush(DbSqlSession.java:292)                                                                                                                                                                                                              
  6262          at org.flowable.common.engine.impl.interceptor.CommandContext.flushSessions(CommandContext.java:191)                                                                                                                                                                                         
  6263          at org.flowable.common.engine.impl.interceptor.CommandContext.close(CommandContext.java:61)                                                                                                                                                                                                  
  6264          at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:80)                                                                                                                                                                          
  6265          at org.flowable.common.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:49)                                                                                                                                                                           
  6266          at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)                                                                                                                                                                                         
  6267          at org.flowable.common.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:46)                                                                                                                                                                                     
  6268          at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)                                                                                                                                                                                                
  6269          at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)                                                                                                                                                                                              
  6270          at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)

**Comment by zhangchunl** [comment]
need comma after **NAME_ = ?**

**Comment by tijsrademakers** [comment]
Thanks, fixed the issue
