### ISSUE TITLE
Javascript engine not found in docker image 6.4.2

### ISSUE THREAD

**Issue by robrez** [flowable/flowable-engine#1856]
Found similar issues were reported in the past.  #1286 stated to have fixed the problem via d1a84e0; however, it looks like a regression has landed in v6.4.2 since the base image was changed on  3425b90

```
org.flowable.common.engine.api.FlowableException: Can't find scripting engine for 'javascript'
	at org.flowable.common.engine.impl.scripting.ScriptingEngines.getEngineByName(ScriptingEngines.java:127) 
```

**Comment by erbg** [comment]
Also the single Docker Images are based on alpine-slim (https://github.com/flowable/flowable-engine/blob/master/modules/flowable-app-rest/src/main/docker/Dockerfile) for instance.

**Comment by yvoswillens** [comment]
We're investigating a fix for the issue. This will apply for all images.

**Comment by erbg** [comment]
Is there any work around we could use in the meantime?

**Comment by unamanic** [comment]
Despite the name, the PR updates all of the Dockerfiles to use the full Alpine openJDK 11 base and adds fonts (which caused another issue).  Since it’s using the full base instead of the slim, it will be bigger, but They do work.

**Comment by yvoswillens** [comment]
New docker images (6.4.2.1) have been published on Docker Hub.
Code changes present on master.
