### ISSUE TITLE
Getting Start UserGuide

### ISSUE THREAD

**Issue by btafarelo** [flowable/flowable-engine#1858]
Hi!

The getting start user guide at holiday-request.bpmn20.xml content doesn't have the **candidateGroups** property declared causing an error when the code retrieve the task list.

wrong:
`<userTask id="approveTask" name="Approve or reject request" />`

correct:
`<userTask id="approveTask" name="Approve or reject request" flowable:candidateGroups="managers"/>`

[https://www.flowable.org/docs/userguide/index.html#_getting_started]()

Regards

**Comment by mshutov** [comment]
@btafarelo hi, actually in section [2.3.5. Querying and completing tasks](https://flowable.org/docs/userguide/index.html#_querying_and_completing_tasks) it is specified with explanation for each option

**Comment by tijsrademakers** [comment]
Hi, like mentioned by @mshutov , this is described in section 2.3.5
