### ISSUE TITLE
Add 'retry' options to service task

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#186]
Service task should have options to allow retries. Those options should include number of retries and timeout between attempts. Flowable-modeler should allow setting the in UI as well.

Thanks

**Comment by tijsrademakers** [comment]
You can define service tasks as asynchronous and then it will use the default of 3 retries. If you want to define the retries yourself you can use failedJobRetryTimeCycle extension element:

http://www.flowable.org/docs/userguide/index.html#failRetry
