### ISSUE TITLE
docker flowable-idm support config domain

### ISSUE THREAD

**Issue by liguobao** [flowable/flowable-engine#1865]
[flowable-idm docker ](https://hub.docker.com/r/flowable/flowable-idm) support  environment properties config, but not contains domain.

```sh
SERVER_PORT=8080
SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-idm-db:5432/flowable
SPRING_DATASOURCE_USERNAME=flowable
SPRING_DATASOURCE_PASSWORD=flowable
FLOWABLE_REST_APP_ADMIN_USER-ID=rest-admin
FLOWABLE_REST_APP_ADMIN_PASSWORD=test
FLOWABLE_REST_APP_ADMIN_FIRST-NAME=Rest
FLOWABLE_REST_APP_ADMIN_LAST-NAME=Admin
```

the doamin config support on [commit/cbe966a95f4ea550c44f0b44ec68d2a217c9afdc](https://github.com/flowable/flowable-engine/commit/cbe966a95f4ea550c44f0b44ec68d2a217c9afdc)

[Allow remember me cookie's domain to be set from application properties](https://github.com/flowable/flowable-engine/pull/762)

so, we should support config IDM cookie domain by docker env

**Comment by yvoswillens** [comment]
Hi. 
You are referring to an old commit. The property that can be set is

```flowable.idm.app.security.cookie.domain```

which can be set as docker env property

```FLOWABLE_IDM_APP_SECURITY_COOKIE_DOMAIN```

Have a look here for an overview of configuration properties;

https://www.flowable.org/docs/userguide/index.html#flowableApps

I'll close the issue. Let us now if it does not work as expected.

Regards,

Yvo

**Comment by liguobao** [comment]
the “ FLOWABLE_IDM_APP_SECURITY_COOKIE_DOMAIN” not work, 
because flowable.idm.app.security.cookie.domain not in flowable-default.properties

**Comment by mystdeim** [comment]
I think the same issue with MANAGEMENT.ENDPOINT.HEALTH.SHOW-DETAILS in admin
