### ISSUE TITLE
Create generic task for JMS activity

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#187]
It would be nice if we can send JMS message from a service task via EL expression in similar fasion
to https://github.com/flowable/flowable-engine/issues/165

I. e. have a JMS end-point and use it to send messages from EL in a service task.

Thanks

**Comment by paulhh** [comment]
Closing as not a bug and no discussion on the forums for the feature (see https://github.com/flowable/flowable-engine/wiki).
