### ISSUE TITLE
Can not obtain data using api repository/models 

### ISSUE THREAD

**Issue by meathross** [flowable/flowable-engine#1875]
version: 6.4.2

create 4 models in flowable-modeler:
![image](https://user-images.githubusercontent.com/14865604/62355842-6cd6db80-b542-11e9-94b3-617a38fe1ba0.png)

call rest api : http://localhost:8080/flowable-rest/service/repository/models
![image](https://user-images.githubusercontent.com/14865604/62355998-b0314a00-b542-11e9-9695-4964ef307351.png)

flowable-modeler is using table act_de_model and  api repository/models gets data from act_re_model.

How should I configure flowable-modeler so that  I  can obtain the same data when I call rest api?

**Comment by PascalSchumacher** [comment]
Checkout the discussion at https://forum.flowable.org/t/flowable-rest-application-retrieve-models/3436 (and expecially https://forum.flowable.org/t/flowable-rest-application-retrieve-models/3436/4) for some information on this.

**Comment by meathross** [comment]
@PascalSchumacher  Thanks a lot.  But I still cannot find a way to retrieve flowable-modeler data from  api "repository/models"。 If there is no other way, I can only rollback to activiti6.0 or activiti5.22。

**Comment by PascalSchumacher** [comment]
To quote from https://forum.flowable.org/t/flowable-rest-application-retrieve-models/3436/4:
>The flowable-modeler application is an entirely standalone application that has its own database persistence. This means that the only way for you to see the models in flowable-rest is to publish them from the modeler.

Another hacky way is to use the internal and undocumented REST API of flowable-modeler.

**Comment by tijsrademakers** [comment]
Hi,

The repository models api was used for storing models as part of the Flowable Engine tables, but the Flowable Modeler uses it's own tabels to have a clean separation between the model data and the runtime engine data. You can use the Flowable Modeler public rest api to get model data, see --> https://github.com/flowable/flowable-engine/tree/master/modules/flowable-ui-modeler/flowable-ui-modeler-rest/src/main/java/org/flowable/ui/modeler/rest/api
