### ISSUE TITLE
Cannot delete a privilege for a group using REST API

### ISSUE THREAD

**Issue by raymark07** [flowable/flowable-engine#1878]
I tried to delete a privilege for a group using below API and I got a response status of 200 OK, but when I list all groups for a given privilege, the group that is not supposed to be fetched is included on the list. Moreover, I even tried to set a wrong/non-existent groupId and I am expecting it to throw an exception but still I got a response status of 200 OK.

`/privileges/{privilegeId}/group/{groupId}`

Upon checking the PrivilegeCollectionResource.java, I noticed that it is invoking deleteUserPrivilegeMapping of identityService.  Shouldn't it be invoking deleteGroupPrivilegeMapping instead?
```
    @ApiOperation(value = "Deletes a privilege for a group", nickname = "deleteGroupPrivilege", tags = { "Privileges" })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Indicates the group privilege has been deleted")
    })
    @DeleteMapping(value = "/privileges/{privilegeId}/group/{groupId}")
    public void deleteGroupPrivilege(@PathVariable String privilegeId, @PathVariable String groupId) {
        Privilege privilege = getPrivilegeById(privilegeId);
        
        if (restApiInterceptor != null) {
            restApiInterceptor.deleteGroupPrivilege(privilege, groupId);
        }
        
        identityService.deleteUserPrivilegeMapping(privilegeId, groupId);
    }
```

**Comment by tijsrademakers** [comment]
Thanks for reporting, it's fixed now.
