### ISSUE TITLE
can you offer an Process Design plugin for intellij idea?

### ISSUE THREAD

**Issue by bluesmi** [flowable/flowable-engine#1879]

**Comment by DarkStar1** [comment]
Have you tried the plugin that's refered to in this [Stackoverflow post](https://stackoverflow.com/questions/43469842/intellij-idea-plugin-for-bpmn-designer) ?

**Comment by tijsrademakers** [comment]
We have a web based Modeler that can be used in your web browser. There's no roadmap for an idea plugin.

**Comment by valb3r** [comment]
@bluesmi You can try this one (it is 3rd party, I'm the developer of it):
https://plugins.jetbrains.com/plugin/14318-flowable-bpmn-visualizer
(https://github.com/valb3r/flowable-bpmn-intellij-plugin)
If you haven't yet
