### ISSUE TITLE
Possible bug? BpmnModel Is there an explanation for the change in behavior.

### ISSUE THREAD

**Issue by osueboy** [flowable/flowable-engine#1885]
Is there an explanation why adding an escalation by passing all their params adds with escalationRef (Id) as key and passing the object adds with Escalation.EscalationCode? 
     
        public void AddEscalation(string escalationRef, string name, string escalationCode)
        {
            if (!string.IsNullOrEmpty(escalationRef))
            {
                EscalationMap.Add(escalationRef, new Escalation(escalationRef, name, escalationCode));
            }
        }

        public void AddEscalation(Escalation escalation)
        {
            if (!string.IsNullOrEmpty(escalation.EscalationCode))
            {
                EscalationMap.Add(escalation.EscalationCode, escalation);
            }
        }

**Comment by tijsrademakers** [comment]
Because an Escalation doesn't have an escalation ref value and the id value is not required the escalation code is used for the escalation ref value as well. But if there is a different escalation ref value the you can use the addEscalation method with the 3 parameters.
