### ISSUE TITLE
Is it possible to override arbitrary spring property?

### ISSUE THREAD

**Issue by mystdeim** [flowable/flowable-engine#1886]
For example I need to change tomcat log directory and enable actuator/info endpoint for anonymous when I start docker container with flowable-admin

**Comment by PascalSchumacher** [comment]
Yes it is possible.

By the way: You should use https://forum.flowable.org/ to ask questions. Thanks!

**Comment by filiphr** [comment]
@mystdeim have a look at [Flowable Application Properties](https://www.flowable.org/docs/userguide/index.html#springBootFlowableProperties) for more information. The Flowable UI Applications are normal Spring Boot apps.
