### ISSUE TITLE
Couldn't expose actuator to anonymous user

### ISSUE THREAD

**Issue by mystdeim** [flowable/flowable-engine#1887]
I run admin-app in docker, I try set:
MANAGEMENT.ENDPOINT.HEALTH.SHOW-DETAILS=always

and I expect that I can use /actuator/health without authorization, but it doesn't work

**Comment by PascalSchumacher** [comment]
Hi mystdeim,

(as far as I know) it is no longer possible to disable security for management endpoints via properties for Spring Boot 2.x.

I believe you have to add code as in the example after the `Additionally, if Spring Security is present, you would need to add custom security configuration that allows unauthenticated access to the endpoints as shown in the following example` sentence in:

https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-endpoints-security

**Comment by mystdeim** [comment]
Thanks for the link, but in this case it means it's impossible to configure /actuator/* endpoint for anonymous usage, doesn't it?

**Comment by PascalSchumacher** [comment]
Yes.

**Comment by filiphr** [comment]
Thanks @PascalSchumacher for the pointers.

@mystdeim please use the [Flowable Forum](https://forum.flowable.org/) for asking questions
