### ISSUE TITLE
Its seems there is no way in flowable-modeler to create <signal> or <message> elements in BPM xml

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#189]
Its seems there is no way in flowable-modeler UI to create <signal> or <message> elements in BPM xml.

For example:

When I add Signal as intermediate catching even I can't link it to Signal reference.
Signal reference dropdown is empty.

Thanks

**Comment by tijsrademakers** [comment]
You can add signals in the root canvas properties view. Click on an empty area in the canvas and look in the properties window.

**Comment by mgrouch** [comment]
Thanks. Just found it. It is under properties of a process.
