### ISSUE TITLE
Hope not use foreign key constraint(especially cascade) in db

### ISSUE THREAD

**Issue by imic07** [flowable/flowable-engine#1893]
for high availability(HA) , our mysql cluster is multi master mode, in this mode, Cascading foreign key constraints are not fully supported, hope use sql instead of cascade.

![image](https://user-images.githubusercontent.com/16321067/62913214-d31ef200-bdbd-11e9-92fb-8842cf53dd5a.png)

**Comment by imic07** [comment]
![image](https://user-images.githubusercontent.com/16321067/62913263-03669080-bdbe-11e9-92c1-e6dff09134d9.png)

**Comment by tijsrademakers** [comment]
You can remove the foreign key constraints without it changing the Flowable Engine functionality. It's just a safety check.
