### ISSUE TITLE
Transaction lifecycle EventListener doesn't have context

### ISSUE THREAD

**Issue by bwangfdu** [flowable/flowable-engine#1894]
I am trying to handle the event of creating a task entity and complete a task entity, so I implement my own EventListener and registered on TASK_CREATED and TASK_COMPLETED. Since I would like to trigger it when the whole transaction is committed to avoid inconstancy when transaction rolled back. When I defined my own EventListener and return "COMMITTED" in getOnTransaction, I find the Context.getCommandContext() is null. Then it causes when I try to get variables from the event's entity failed. The exception message is "lazy loading outside command context".
    Is this the recommended way to use the on-transaction event listener? Or I must use other way to handle the event? Thanks a lot.
   Btw, I find in ExecuteEventListenerTransactionListener.execute(CommandContext) send CommandContext into the function, but the function implement just throw it away.

**Comment by tijsrademakers** [comment]
Hi, 

Please ask questions via the Flowable forum. When the transaction is committed, it means there's no active CommandContext anymore. When you need to get additional data from the database you can use the ManagementService executeCommand method to start a new transaction and you can implement the service calls there.

**Comment by bwangfdu** [comment]
Hi @tijsrademakers ,
Thank you for quick replying. I agree with you that ideally when the transaction is committed, the transaction should be unavailable. But I even tried COMMITTING, the context is still not available. At the same time, when my COMMITTED event listener throw out exception and isFailOnException() returns true, the execution is rolled back, and the task is back to pending status. I think the transactional of this part is perfect. Is there any possibility to make the CommandContext available in EventListener? I find it was sent into the ExecuteEventListenerTransactionListener.execute(CommandContext) and it contains a lot of informations.

**Comment by tijsrademakers** [comment]
Hi @bwangfdu,

Can you share the code you implemented for this? Mainly how you registered the on event transaction listener, and the implementation of the listener.

**Comment by bwangfdu** [comment]
register:
```
@Bean
    public OmEventListener omEventListener(ProcessEngine processEngine) {
        OmEventListener listener = new OmEventListener(omEndpoint, client);
        processEngine.getRuntimeService().addEventListener(listener, FlowableEngineEventType.TASK_CREATED,
                FlowableEngineEventType.TASK_COMPLETED);
        return listener;
    }
```
Implement:
```
 @Override
    public void onEvent(FlowableEvent flowableEvent) {
        if (flowableEvent instanceof FlowableEntityEvent) {
            FlowableEntityEvent event = (FlowableEntityEvent) flowableEvent;
            Object obj = event.getEntity();
            if (obj instanceof TaskEntity) {
                try {
                    TaskEntity task = (TaskEntity) obj;
                    // Only deal with our defined work flows
                    if (task.getProcessDefinitionId().startsWith("Process-")) {
                        task.setEventName(flowableEvent.getType().name());
                        Map<String,Object> variables=task.getVariables();
                        ...
                    }
                } catch (Exception ex) {
                    throw new RuntimeException(ex);
                }
            }
        }

    }

    @Override
    public boolean isFailOnException() {
        return true;
    }

    @Override
    public boolean isFireOnTransactionLifecycleEvent() {
        return getOnTransaction() != null;
    }

    @Override
    public String getOnTransaction() {
        return null;
    }
```

At last, I injected the TaskService and use its getVariables(String) function to get the variables on the task successfully. 
Thank you for your hint.

**Comment by bwangfdu** [comment]
Thank you for your answer.  I will.
