### ISSUE TITLE
Whether the flowable community version continues to be maintained?

### ISSUE THREAD

**Issue by yfusong** [flowable/flowable-engine#1904]
After the flowable out of the commercial version, does the community version continue to be maintained? Will there be new features added in the future?

**Comment by tijsrademakers** [comment]
Yes of course, the open source project is focused on the Flowable engines (BPMN, CMMN and DMN) and every change that is done in the BPMN, CMMN or DMN engine will be done in the open source project. We have a roadmap for adding new features to the open source Engines as well.
