### ISSUE TITLE
Transactions and associations not drawn on process diagram on flowable admin

### ISSUE THREAD

**Issue by alagane** [flowable/flowable-engine#1905]
**Describe the bug**
When I load a process diagram on flowable admin (Process Engine -> Instances -> select one -> Show process diagram), associations and transactions are not drawn.

**Expected behavior**
They should be drawn like they are in the modeler.

**Additional context**
Release 6.4.2

Pull request incoming.

**Comment by tijsrademakers** [comment]
The issue is resolved
