### ISSUE TITLE
Test Automation support

### ISSUE THREAD

**Issue by ankush-sood** [flowable/flowable-engine#1908]
Hi,

I am facing an issue with test automation using webdriverIO.

The xpath for html based locators are dynamic in nature and change with every html update to a page.

with class attribute is the same problem as they are also dynamic in nature.

What i am looking for is a way to add id locators to the forms and their controls so as ot uniquely identify them .

Can you please suggest any solution to this. Thanks.

**Comment by PascalSchumacher** [comment]
Hi ankush-sood,

questions should be asked at https://forum.flowable.org/

**Comment by tijsrademakers** [comment]
Let's discuss this more on the forum
