### ISSUE TITLE
Rest API - Error executing an action of a task if it includes a date variable

### ISSUE THREAD

**Issue by dersteppenwolf** [flowable/flowable-engine#1915]
There is an error trying to complete a task using the rest api.

**Curl Request:**

> curl -s -H  "Content-Type: application/json" -d "@data-1.json"   -X POST   \
> 'http://admin:test@localhost:8080/flowable-rest/service/runtime/tasks/4e056411-cda3-11e9-9dac-0242ac110007'

**data-1.json:**

> {
>     "action": "complete",
>     "formDefinitionId": "c0acd5f6-cd9e-11e9-913a-0242ac110006",
>     "variables": [
>         {
>             "name": "ciudad",
>             "type": "string",
>             "value": "Cali"
>         },
>         {
>             "name": "fecha",
>             "type": "date",
>             "value": "2018-12-21"
>         },
>         {
>             "name": "cantidad",
>             "type": "string",
>             "value": "1"
>         },
>         {
>             "name": "aprobado",
>             "type": "string",
>             "value": "SI"
>         }
>     ]
> }

**Error**
> Caused by: java.lang.ClassCastException: class java.util.Date cannot be cast to class java.lang.String (java.util.Date and java.lang.String are in module java.base of loader 'bootstrap')
	at org.flowable.form.engine.impl.cmd.GetVariablesFromFormSubmissionCmd.transformFormFieldValueToVariableValue(GetVariablesFromFormSubmissionCmd.java:101) ~[flowable-form-engine-6.4.2.1.jar!/:6.4.2.1]

**Expected behavior**
The task is completed

**Additional context**
Docker flowable-rest:6.4.2.1
Database: Postgresql

**Comment by unamanic** [comment]
Tested in 6.5.0 with same results.  It appears that the task endpoint is converting the date into a `Date` object before passing it over to the Forms API.  Submitted a PR that checks the type of variables and converts Dates appropriately.

**Comment by tijsrademakers** [comment]
Should work fine now with the PR, thanks.
