### ISSUE TITLE
MySQL create act_de table error  

### ISSUE THREAD

**Issue by Jack-Ye** [flowable/flowable-engine#1941]
My MySQL engine default charset is utf8mb4. Which cause index of  column  ``id` varchar(255) NOT NULL,`  will be greater than 767 bytes(when mysql innodb_large_prefix is OFF.). And in `utf8` charset the size will be ok.

How about setting the charset to `utf8`  while create  table?
For example :
```
CREATE TABLE `act_de_model` (
  `id` varchar(255) NOT NULL,
  `name` varchar(400) NOT NULL,
  `model_key` varchar(400) NOT NULL,
  `description` varchar(4000) DEFAULT NULL,
  `model_comment` varchar(4000) DEFAULT NULL,
  `created` datetime(6) DEFAULT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `last_updated` datetime(6) DEFAULT NULL,
  `last_updated_by` varchar(255) DEFAULT NULL,
  `version` int(11) DEFAULT NULL,
  `model_editor_json` longtext,
  `thumbnail` longblob,
  `model_type` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) CHARSET=utf8;
```

**Comment by tijsrademakers** [comment]
Hi,

We use Liquibase to create this table (https://github.com/flowable/flowable-engine/blob/master/modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/resources/META-INF/liquibase/flowable-modeler-app-db-changelog.xml). Maybe you can create a PR with the changes to the changelog file?
