### ISSUE TITLE
Dead code as a result of file copying

### ISSUE THREAD

**Issue by dbmalkovsky** [flowable/flowable-engine#1942]
In `org.flowable.cmmn.engine.impl.cmd.AddIdentityLinkCmd` starting at [line 112](https://github.com/flowable/flowable-engine/blob/master/modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/cmd/AddIdentityLinkCmd.java#L112) this code is found:

<pre>
      boolean forceNullUserId = false;
        if (assignedToNoOne) {
            // ACT-1317: Special handling when assignee is set to NULL, a
            // CommentEntity notifying of assignee-delete should be created
            forceNullUserId = true;
            if (IdentityLinkType.ASSIGNEE.equals(identityType)) { 
                identityId = oldAssigneeId;
            } else {
                identityId = oldOwnerId;
            }
        }
</pre>

Note that `forceNullUserId` is set and never used in the file.  It appears that the CMMN code is a copy-n-paste from `org.flowable.engine.impl.cmd.AddIdentityLinkCmd` as similar code is found starting at [line  120](https://github.com/flowable/flowable-engine/blob/master/modules/flowable-engine/src/main/java/org/flowable/engine/impl/cmd/AddIdentityLinkCmd.java#L120):

<pre>
        boolean forceNullUserId = false;
        if (assignedToNoOne) {
            // ACT-1317: Special handling when assignee is set to NULL, a
            // CommentEntity notifying of assignee-delete should be created
            forceNullUserId = true;
            if (IdentityLinkType.ASSIGNEE.equals(identityType)) { 
                identityId = oldAssigneeId;
            } else {
                identityId = oldOwnerId;
            }
        }

        if (IDENTITY_USER == identityIdType) {
            CommandContextUtil.getHistoryManager(commandContext).createUserIdentityLinkComment(task, identityId, identityType, true, forceNullUserId);
        } else {
            CommandContextUtil.getHistoryManager(commandContext).createGroupIdentityLinkComment(task, identityId, identityType, true);
        }
</pre>

In this code the variable `forceNullUserId` is used (read).

I think the variable and comment in the CMMN code can be safely removed.

**Comment by tijsrademakers** [comment]
done
