### ISSUE TITLE
Consider H2 JDBC driver compatibility mode 

### ISSUE THREAD

**Issue by tdzhinski** [flowable/flowable-engine#1968]
When I use `flowable-spring-boot-starter` with `spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL` 

I get:
```
org.h2.jdbc.JdbcSQLNonTransientException: Unknown data type: ; SQL statement:
create table ACT_HI_TSK_LOG [...]

```
Check if H2 JDBC driver uses compatibility mode and apply correct SQL.

**Comment by tijsrademakers** [comment]
The tests are executed against all major databases including Postgres (see Github actions). I think the issue here could be that Flowable needs to be configured to use databaseType = postgres.

**Comment by tdzhinski** [comment]
Is it possible to define 'databaseType = postgres' in Spring Boot application.properties?

**Comment by filiphr** [comment]
Currently it is not possible to set the database type via a property

**Comment by filiphr** [comment]
However, you can do it via an `EngineConfigurationConfigurer`. For example:

```
@Configuration
public class CustomConfiguration {

    @Bean
    public EngineConfigurationConfigurer<SpringProcessEngineConfiguration> customProcessEngineConfigurer() {
        return engineConfiguration -> {
            engineConfiguration
                .setDatabaseType(SpringProcessEngineConfiguration.DATABASE_TYPE_POSTGRES);
        }
    }
}
```

**Comment by tdzhinski** [comment]
@filiphr : Thanks! Tested it but unfortunately still getting `JdbcSQLNonTransientException: Unknown data type: ` when use `MODE=PostgreSQL` in datasource.
