### ISSUE TITLE
As i am new for flowable. I download source code from github but i am unable to run it. Can you please suggest me steps how to run it.

### ISSUE THREAD

**Issue by ganeshdhokale** [flowable/flowable-engine#1971]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ganeshdhokale** [comment]
Build is done successfully, what will be next step to run.
Thanks in advance

**Comment by tijsrademakers** [comment]
Like mentioned on the other issue you raised, please use the forum (forum.flowable.org) for questions. I would suggest starting here https://flowable.org/documentation.html, and look for the documentation that is most interesting for you.
