### ISSUE TITLE
Is it possible to use flowable as an embeddable library in plain Java app?

### ISSUE THREAD

**Issue by parrotcar00** [flowable/flowable-engine#1990]
I have this use case where I want to be able to use flowable as a library in my Java app. I imagine something like constructing a custom bpmn on the fly, programmatically in the app and then submitting that to flowable.

My questions are:

1. Is it possible to use flowable engine like this?

2. If yes to (1), would I need to stand up a database server also or can flowable use some in-memory data structure itself, because ideally I would want to make my Java app a binary with no dependencies on any external server/service.

**Comment by unamanic** [comment]
The best place to ask questions like this is at https://forum.flowable.org

**Comment by parrotcar00** [comment]
Thanks, will do.
