### ISSUE TITLE
Bug: No job handler registered for type cmmn-history-cleanup in job config for engine: bpmn

### ISSUE THREAD

**Issue by tiffmaelite** [flowable/flowable-engine#2012]
**Describe the bug**
While manually testing the CMMN history cleanup feature, I stumbled upon the following exception, and noticed that no cleanup had happened for the cases (no problem at all with a similar manual test of the BPMN history cleanup feature): `org.flowable.common.engine.api.FlowableException: No job handler registered for type cmmn-history-cleanup in job config for engine: bpmn`

**Expected behavior**
Completed CMMN cases are deleted, no exception is raised.

**Code and steps taken to find the bug**
In my configuration class, I added:
```
@Bean
@ConditionalOnClass(SpringCmmnEngineConfiguration.class
public EngineConfigurationConfigurer<SpringCmmnEngineConfiguration> customCmmnEngineHistoryCleaningConfigurer() {
    return engineConfiguration -> {
        engineConfiguration.setEnableHistoryCleaning(true);
        engineConfiguration.setHistoryCleaningTimeCycleConfig("0 0 14 * * ?");
        engineConfiguration.setCleanInstancesEndedAfterNumberOfDays(1);
    }
}
```
Then I started my application on a database containing completed cases from a few days ago, and waited 2pm to see what would happen.

**Additional context**
Using the version of the library included in the latest release of Flowable Platform product, with async history enabled (internal release of 6.5.0-SNAPSHOT).

No problem experienced when testing the BPMN cleanup feature, with similar code.

**Comment by tiffmaelite** [comment]
After investigation, I found out that the cleanup timer job was missing the CMMN scope type. Problem appears to be solved when this scope type is properly set.

Fix proposal: https://github.com/flowable/flowable-engine/pull/2011

**Comment by PascalSchumacher** [comment]
I guess this can be closed now that https://github.com/flowable/flowable-engine/pull/2011 was merged?
