### ISSUE TITLE
Cannot install Flowable through Eclipse

### ISSUE THREAD

**Issue by lguinard123** [flowable/flowable-engine#2015]
**Describe the bug**
Attempting to install Flowable 5.23 or 6.42 using Eclipse IDE version 2019 -09 R (4.13.0) install new software tool and getting error that "no software site found".  Is it looking for the content.jar which I don't see in this version?

**Expected behavior**
Software download.
**Code**
N/A
**Additional context**
Listed above.

**Comment by tijsrademakers** [comment]
Please report bugs for the Eclipse plugin at the github repo for that. We currently don't have support for Eclipse IDE version 2019 - 09R.

**Comment by lguinard123** [comment]
Thanks Tijs.  I found the site a little hard to figure out but thanks for your quick reply!
