### ISSUE TITLE
 Flowable Modeler: Mail Task missing is htmlVar and textVar fields

### ISSUE THREAD

**Issue by PascalSchumacher** [flowable/flowable-engine#2018]
The flowable engine support `textVar` and `htmlVar` fields for the mail task  (see: https://www.flowable.org/docs/userguide/index.html#bpmnEmailTaskUsage), but these fields are missing in the flowable modeler GUI. 

It would be great if these fields were added.

**Comment by PascalSchumacher** [comment]
`htmlVar` was added with https://github.com/flowable/flowable-engine/commit/7a27027ac779073ad2785d92c5ff4236b8f251bc

**Comment by filiphr** [comment]
Closing this issue as @PascalSchumacher said it was added in https://github.com/flowable/flowable-engine/commit/7a27027ac779073ad2785d92c5ff4236b8f251bc

**Comment by PascalSchumacher** [comment]
Please reopen, as `textVar` is still missing. Thanks!

**Comment by filiphr** [comment]
Oops sorry @PascalSchumacher, forgot the `textVar`
