### ISSUE TITLE
Whether to support rollback

### ISSUE THREAD

**Issue by idawnorg** [flowable/flowable-engine#203]
Whether to support rollback？What is Related API ?

**Comment by tijsrademakers** [comment]
Ehm, can you please elaborate a bit more?

**Comment by idawnorg** [comment]
Scrolls the current task to the executed task node

**Comment by tijsrademakers** [comment]
Really no idea what the issue is. Closing the issue for now. Please reopen with detailed information about the issue when applicable.

**Comment by idawnorg** [comment]
thanks
