### ISSUE TITLE
Case Query API does not support identityLinks

### ISSUE THREAD

**Issue by rvillars** [flowable/flowable-engine#2035]
**Is your feature request related to a problem? Please describe.**
I would like to search for cases with a specific assignee with the Java API. `createHistoricCaseInstanceQuery().involvedUser(userId)`searches for any identityLink and does not allow filtering for a specific identityLink type like e.g. the assignee.

**Describe the solution you'd like**
Extend the API to allow to query for specific identityLink types like e.g. `createHistoricCaseInstanceQuery().involvedUser(userId, IdentityLinkType.ASSIGNEE)`

**Additional context**
Same might apply to `involvedGroups()? Not sure about that...

**Comment by tijsrademakers** [comment]
Added support in process instance, historic process instance, case instance, and historic case instance queries.
