### ISSUE TITLE
Allow to cancel executions triggered by boundary event

### ISSUE THREAD

**Issue by martin-grofcik** [flowable/flowable-engine#2038]
**Use Case:**
![image](https://user-images.githubusercontent.com/5585296/69870281-b1377580-12af-11ea-9648-787e8a6454c6.png)

Let's consider the situation that first line support timer was fired.
```
<boundaryEvent id="escalationTimer" cancelActivity="false" attachedToRef="firstLineSupport">
```
`First line support` user task is not cancelled. After some time user completes `First line support` task. What I would like to is to cancel `Handle escalated issue` task (and whole execution) 
I did not find a way how to find out that executions from the `First line support` and `escalationTimer` are somehow connected together. In fact they are independent.

**Proposed solution:**
Create a new flag in the process model to cancel fired execution. After that the code in `BoundaryEventActivityBehavior` could be changed to ()
``` java 
        ExecutionEntity scopeExecution = null;
        if (cancelTriggeredExecutions) {
             scopeExecution = parentExecutionEntity;
        } else {
            ExecutionEntity currentlyExaminedExecution = executionEntityManager.findById(parentExecutionEntity.getParentId());
            while (currentlyExaminedExecution != null && scopeExecution == null) {
                if (currentlyExaminedExecution.isScope()) {
                    scopeExecution = currentlyExaminedExecution;
                } else {
                    currentlyExaminedExecution = executionEntityManager.findById(currentlyExaminedExecution.getParentId());
                }
            }
        }
```

**Describe alternatives you've considered:**
- Listener which finds related executions and deletes them (relation to firing execution needs to be stored in e.g. variable)
- compensate event - too complicated, process design is messed up.

**Comment by unamanic** [comment]
Is there a reason an End Terminate Event would not solve this scenario?

![image](https://user-images.githubusercontent.com/144254/70852078-e244a800-1e62-11ea-9020-2879a9249373.png)

**Comment by unamanic** [comment]
It seems like what want is something like the exit sentry in CMMN:

![image](https://user-images.githubusercontent.com/144254/70866038-264eb000-1f2a-11ea-8685-cebafed90bb3.png)

A similar effect is possible in BPMN by wrapping the first line and handle escalation tasks in a subprocess:

![image](https://user-images.githubusercontent.com/144254/70865428-44fd7880-1f23-11ea-805c-f6d17b924caa.png)

**Comment by martin-grofcik** [comment]
Thank you for the comment. Yes it should work in this way. The process diagram is less readable.

**Comment by tijsrademakers** [comment]
This can be done like @unamanic explained. As an alternative you could also use a signal event. After completing the First line task you can send a signal event and you can have a boundary signal event on the Escalation task.
