### ISSUE TITLE
Port MariaDB support to Modeler

### ISSUE THREAD

**Issue by RAlfoeldi** [flowable/flowable-engine#2054]
**Describe the bug**
commit 674b577212c794f47b3976d7dfb8354ee54c0ff5 added support for MariaDB in org.flowable.common.engine.impl.AbstractEngineConfiguration.java.

`databaseTypeMappings.setProperty("HSQL Database Engine", DATABASE_TYPE_HSQL);
        databaseTypeMappings.setProperty("MySQL", DATABASE_TYPE_MYSQL);
        databaseTypeMappings.setProperty("MariaDB", DATABASE_TYPE_MYSQL);
        databaseTypeMappings.setProperty("Oracle", DATABASE_TYPE_ORACLE);`

This was not replicated in the code in Modeler. 
org.flowable.ui.modeler.conf.DatabaseConfiguration

`       databaseTypeMappings.setProperty("HSQL Database Engine", DATABASE_TYPE_HSQL);
        databaseTypeMappings.setProperty("MySQL", DATABASE_TYPE_MYSQL);
        databaseTypeMappings.setProperty("Oracle", DATABASE_TYPE_ORACLE);
` 

**Expected behavior**
It would be much appreciated if supported DBs were consistent across all flowable apps :-)

**Comment by tijsrademakers** [comment]
Support added thanks to @dbmalkovsky
