### ISSUE TITLE
there is not excuted initializeAdminUser in org.flowable.ui.idm.conf.Bootstrapper

### ISSUE THREAD

**Issue by MiniApp** [flowable/flowable-engine#2056]
I'm using Flowable 6.4.1 within Spring Cloud.
The event.getApplicationContext().getParent() is not null in org.flowable.ui.idm.conf.Bootstrapper at line 56. So the method initializeAdminUser is not excuted. 
```
@Override
    public void onApplicationEvent(ContextRefreshedEvent event) {
        if (event.getApplicationContext().getParent() == null) { // Using Spring MVC, there are multiple child contexts. We only care about the root

            if (ldapProperties == null || !ldapProperties.isEnabled()) {
                if (idmAppProperties.isBootstrap()) {
                    // First create the default IDM entities
                    createDefaultAdminUserAndPrivileges();
                }
            
            } else {
                if (identityService.createPrivilegeQuery().privilegeName(DefaultPrivileges.ACCESS_IDM).count() == 0) {
                    String adminUserId = idmAppProperties.getAdmin().getUserId();
                    if (StringUtils.isNotEmpty(adminUserId)) {
                        initializeDefaultPrivileges(adminUserId);
                    } else {
                        LOGGER.warn(
                            "No user found with IDM access. Set flowable.idp.app.admin.user-id to give at least one user access to the IDM application to configure privileges.");
                    }
                }
            }
        }
    }
```

**Comment by filiphr** [comment]
Thanks for reporting this @MiniApp.

So when using Spring Cloud there is no top level `ApplicationContext`?

Anyways, we could make all our `Bootstrapper` implement a `CommandLineRunner` or `ApplicationListener<ApplicationStartedEvent>` instead of `ApplicationListener<ContextRefreshedEvent>` .

Would you like to provide a PR for this @MiniApp?

**Comment by MiniApp** [comment]
> Thanks for reporting this @MiniApp.
> 
> So when using Spring Cloud there is no top level `ApplicationContext`?
> 
> Anyways, we could make all our `Bootstrapper` implement a `CommandLineRunner` or `ApplicationListener<ApplicationStartedEvent>` instead of `ApplicationListener<ContextRefreshedEvent>` .
> 
> Would you like to provide a PR for this @MiniApp?

there is anthoer question, schema is not auto create when use the mysql-connector-java of version 8.0.x

**Comment by filiphr** [comment]
@MiniApp please do not use the same issue to ask completely unrelated questions.

Use the forum for asking questions. Have a look at [this](https://forum.flowable.org/t/unable-to-create-more-than-one-database-in-same-server-mysql/2911/5?u=filiphr) forum post for your problem

**Comment by tijsrademakers** [comment]
Closing issue because of no feedback
