### ISSUE TITLE
Process instance delete does not fire listener events.

### ISSUE THREAD

**Issue by martin-grofcik** [flowable/flowable-engine#2058]
**Describe the bug**
When process instance is deleted there is no possibility to specify listener on the delete event.

```
    @Test
    @Deployment(resources= "org/flowable/engine/test/bpmn/event/end/TerminateEndEventTest.testTerminateExecutionListener.bpmn")
    public void terminateExecutionListenerOnDeleteEvent() throws Exception {
        ProcessInstance pi = runtimeService.startProcessInstanceByKey("terminateEndEventExample");
        assertTrue(taskService.createTaskQuery().processInstanceId(pi.getId()).taskDefinitionKey("preTerminateTask").count() > 0);

        runtimeService.deleteProcessInstance(pi.getId(), "test");

        assertProcessEnded(pi.getId());
        assertEquals(1, TerminateExecutionListener.startCalled);
        assertEquals(1, TerminateExecutionListener.deleteCalled);
    }
```

**Expected behavior**
When a process instance is deleted - delete listener is invoked.

v6.5-SNAPSHOT.

**Comment by tijsrademakers** [comment]
The execution listeners are not meant for listening to a process instance delete event. When the execution listener should be triggered then the process instance should be ended by triggering a signal event or something similar that is connected to a terminate end event.
