### ISSUE TITLE
Unexpected Nullpointer returned

### ISSUE THREAD

**Issue by j-kirsch** [flowable/flowable-engine#2059]
**Describe the bug**

In the file `modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/environment/FlowableLiquibaseEnvironmentPostProcessor.java` on line the methode `SpringBootVersion.getVersion()` is called and expected to return a string. 
However, this class is able to determine the Spring Boot version in all environments - as described in the [Docs](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/SpringBootVersion.html)

This goes unchecked and can cause a nullPointerException

**Expected behavior**

Handle the return of a null value like in the file `modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/environment/FlowableDefaultPropertiesEnvironmentPostProcessor.java`, for example using this code:

```
protected String getLiquibaseProperty() {
        String liquibaseProperty = "liquibase.enabled";
        String springBootVersion = SpringBootVersion.getVersion();
        if (springBootVersion != null && springBootVersion.startsWith("2")) {
            liquibaseProperty = "spring." + liquibaseProperty;
        }
        return liquibaseProperty;
    }
```

Or wrap this in a try-catch block

**Additional resources**
[SpringBootVersion Documentation](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/SpringBootVersion.html)

**Comment by dbmalkovsky** [comment]
Given that Spring Boot 1.x.x releases were "end of life" as of August 2019 and 2.0.x was EOL in April 2019 and the only supported "supported releases" are 2.1.x and 2.2.x (per this [doc](https://github.com/spring-projects/spring-boot/wiki/Supported-Versions)) can't this code written in March of 2018 be simplified to assume only version 2 code?

**Comment by filiphr** [comment]
Thanks for reporting this @j-kirsch. We've fixed this on master.

@dbmalkovsky I agree with you that Spring Boot 1.x is EOL as of August 2019. However, we still are testing with Spring Boot 1.5 and are not using new APIs for the time being. 

Perhaps after the next release we can completely drop the Spring Boot 1.x Support
