### ISSUE TITLE
Call Activity- how to show expanded diagram in Flowable Designer and REST API

### ISSUE THREAD

**Issue by wangmin-xidian** [flowable/flowable-engine#2062]
Hi, 
   This is my problem, look forward to your reply , thanks. 

Version : Flowable 6.4.2 
**Problem**
- When I use Eclipse Designer(Flowable BPMN Designer) to draw bpmn file, I could not set expanded for call activity;
- I want to show call activity expanded diagram by `service/repository/process-definitions/{processDefinitionId}/image` and `/service/runtime/process-instances/{processInstanceId}/diagram`;
- On the same time, I'm not found some configuration for this in REST APIs and Flowable docs.

**Solution**
- First, I can use flowable bpmn tag to set expanded call activity in bpmn file;
- Or I can use some rest API or service API to set and get expanded call activitiy processdefintion/processInstance diagram;

**Comment by tijsrademakers** [comment]
Hi,

An expanded call activity is not supported. In the Task and admin application we do however support that you click on the call activity element in the diagram and it will then load the sub process diagram and you can navigate back.

Yes you can also get the sub process diagram using the default REST API image endpoints as well. Just use the processDefinitionId or processInstanceId value of the sub process.
