### ISSUE TITLE
parent_task_id_  is null

### ISSUE THREAD

**Issue by oliuhuano** [flowable/flowable-engine#2077]
**Describe the bug**
I complete a task, but the parent_task_id_  is null.

**Expected behavior**
I want to know which task send to currenttask, how can I get the lasttaskid?

**Additional context**
flowable 6.4.0

**Comment by unamanic** [comment]
This is not a bug, the best place to ask questions is https://forum.flowable.org

The parent_task_id is used to indicate that a task is a subtask of another task, not to indicate of tasks that proceeded the current task.  I'm don't know a simple way to find what task in a process immediately proceeded any given active task.

**Comment by tijsrademakers** [comment]
Hi, you can use the historic task instance query to look for previous tasks completed in the process instance. You can also use the BpmnModel (via RepositoryService getBpmnModel(processDefinitionId) ), to lookup the previous task in the BPMN model.
