### ISSUE TITLE
JPA support

### ISSUE THREAD

**Issue by jisqaqov** [flowable/flowable-engine#209]
Good day. Could you consider moving from MyBatis to JPA. In fact, JPA support many kinds of RDBMS, MyBatis neither. I read in one article in internet that activiti/flowable has drawback in MyBatis.

**Comment by tijsrademakers** [comment]
Always open to discuss these kind of technical choices, but one article saying there's a drawback and without mentioning any details won't start the discussion. As you might know, we support all major databases (MySQL, Postgres, Oracle, DB2 and MSSQL) already with MyBatis
