### ISSUE TITLE
Nonoptimal upgrade step lowable.postgres.upgradestep.6010.to.6100.history.sql 

### ISSUE THREAD

**Issue by dkowzan** [flowable/flowable-engine#2100]
**Describe the bug**
On my system upgrade step take days on flowable.postgres.upgradestep.6010.to.6100.history.sql
After some investigation, I found out that sql script have unnecessary steps: 
For example: 
"alter table ACT_HI_PROCINST add column REV_ integer default 1;
update ACT_HI_PROCINST set REV_ = 1;"
update step is not needed because alter table with default value already sets REV_ to 1.  

After more digging, I found this commit: https://github.com/flowable/flowable-engine/commit/e3ce6a8c5d3b3e2c63895b64ede6340e01aed950#diff-b2468d30850f423b5d6c7bc13a845cbf
Where these excessive "updates" were added.
It looks like mssql have different behavior than postgres and in fact update with a default value clause doesn't add a default value to new rows(it's added only when column don't allow null values). During the fix of that problem, all of the upgrade scripts were changed even if that update was not needed.

**Comment by tijsrademakers** [comment]
Thanks for looking into this. But did you validate that removing the update calls like set REV_ = 1; decrease the upgrade time to an acceptable time?

**Comment by dkowzan** [comment]
I'm in the process of it. Currently, my server is stuck on "update ACT_HI_ACTINST set REV_ = 1" since 2019-12-31. So for sure without it, upgrade will be somehow faster :) Whether it will be acceptable? I'll see.

**Comment by tijsrademakers** [comment]
Closing the issue for now, of course we remain interested in feedback on how to improve it.
