### ISSUE TITLE
How to write history data to single MySQL server 

### ISSUE THREAD

**Issue by mf1632015** [flowable/flowable-engine#2103]
Dear engineers,
I am a developer in China. Our company hopes to use flowable to resolve millions of contents everyday. But as content increased, the database’s pressure is too high to load so much query. So we consider to move history data to another mysql server . I read the source codes ,and I found if I want to move history data to another MySQL server , I need to rewrite HistoricDataManager and DbSqlSession and so on. Is this way right? If it is right, the work is so huge, and I do not have enough time to do. I sincerely need your help , thank you!
Another way I thought is to make two engines. One is runtime and repository engine, and another one is historic engine. Two engines ’ s main differences is data source .I rewrite both of the historyjobhandler . By using kafka or other mq , the runtime engine’s historjobhandler send the messages in the override method. And the historic engine’s receive the messages in the override method and used all the original jsontransformer to save the data. Is this way feasible.
That’s all . Thank you very much.

**Comment by tijsrademakers** [comment]
Hi,
For this purpose we have the async history manager that you can enable with the asyncHistoryEnabled property on the process engine configuration. By default this still writes the historic information to the same history tables (in the same database), but you can override the historyManager in the process engine configuration with your own implementation and use the https://github.com/flowable/flowable-engine/blob/master/modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/async/AsyncHistoryManager.java as the starting point for this. 

Best regards
