### ISSUE TITLE
Eclipse Designer (Step 14.1. Installation from Documentation does not work)

### ISSUE THREAD

**Issue by AJatCollibra** [flowable/flowable-engine#2110]
Eclipse Designer (Step 14.1. Installation from Documentation does not work)

Documentation being followed:
https://flowable.org/docs/userguide/index.html#eclipseDesignerInstallation

Step 14.1 Installation
Location: http://www.flowable.org/designer/update/

Location is empty.

**Comment by tijsrademakers** [comment]
On which version of Eclipse are you trying this? Only old versions of Mars and Neon are currently supported.

**Comment by AJatCollibra** [comment]
Flowable DOCS (v 6.4.2)

**Comment by AJatCollibra** [comment]
![Screenshot (10)](https://user-images.githubusercontent.com/59622606/71923984-1eb2ad80-315c-11ea-80af-740d51695258.png)
![Screenshot (9)](https://user-images.githubusercontent.com/59622606/71923985-1eb2ad80-315c-11ea-956e-4351c243d94e.png)

**Comment by tijsrademakers** [comment]
This version of Eclipse is not supported at the moment. Only the Eclipse Mars and Neon releases are supported.

**Comment by AJatCollibra** [comment]
Ok thank you, The Eclipse Mars download link does not work either from their website... I guess I am stuck in Catch 22!

**Comment by tijsrademakers** [comment]
Eclipse Neon download should work fine from here:

https://www.eclipse.org/downloads/packages/release/neon/3

**Comment by AJatCollibra** [comment]
Not for Modeling Tools - 64Bit windows :(

**Comment by tijsrademakers** [comment]
Are you looking to do development on the Designer code? Because to just install and use the Eclipse Designer you can use Eclipse IDE for Java developers.

**Comment by AJatCollibra** [comment]
Yes just designer, let me try that on Mars, Thank you so much for your quick responses.

**Comment by AJatCollibra** [comment]
for some reason none of the download links for Mars work :( but will try Neon
