### ISSUE TITLE
Allow sorting tasks by category

### ISSUE THREAD

**Issue by andrewspencer** [flowable/flowable-engine#2113]
**Is your feature request related to a problem? Please describe.**
I would like to be able to sort by category, the same way I can sort by other fields using TaskInfoQuery methods orderByTaskName(), orderByTaskPriority() etc.

**Describe the solution you'd like**
Add a constant CATEGORY to TaskQueryProperty and HistoricTaskInstanceQueryProperty with name "RES.CATEGORY_" and method orderByTaskCategory() to TaskInfoQuery and implementations which uses this property.

**Describe alternatives you've considered**
It can be worked around by: query.orderBy(new ActivityInstanceQueryProperty("RES.CATEGORY_")) but this is not satisfactory / robust to future changes.

**Comment by filiphr** [comment]
Thanks for creating the issue @andrewspencer. 

Seems like you already know what needs to be done. Would you be interested in creating a PR with these changes 😄?

**Comment by albihasani94** [comment]
Hi @andrewspencer, @filiphr, I recently had some time on my hands and provided an implementation for this. If you have any suggestions or had something else in mind, please let me know.

**Comment by tijsrademakers** [comment]
Thanks for the PR, this adds the sort by category feature.
