### ISSUE TITLE
Clustering configuration

### ISSUE THREAD

**Issue by jisqaqov** [flowable/flowable-engine#212]
Good day. As far as i know activiti bpm community edition lack of clustering configuration.
Could you consider clustering configuration in flowable bpm UI web application. I think it can make this bpm better in comparison with others bpm engines.

**Comment by tijsrademakers** [comment]
What kind of functionality would you expect from the cluster config exactly? I assume you mean Flowable right? Flowable is easily clusterable already, so don't know what a cluster configuration in the admin application would bring.

**Comment by tijsrademakers** [comment]
Closing because of no feedback, please reopen when there's more info or discuss it on the Flowable forum

**Comment by emaginniss** [comment]
If it's something you're up for discussing, I have my thoughts on Flowable clustering.  My concerns are around the ability to have multiple instances of the Flowable engine sharing a database and being accessed with their REST api through a load balancer.  I worry that:

1) There might be state information being saved within the engine that would prevent two engine instances from correctly serving requests about the same tasks/processes
2) Timer activity might be replicated by each of the instances
3) No mechanism for determining a cluster master/timer authority in the case that one of the engines becomes unresponsive.

What sort of capabilities and support do you offer to handle those issues?

Thank you!

**Comment by emaginniss** [comment]
I can see from further review that the engines are stateless, thus handling one of my concerns.  For the others, is it possible to ensure that one, and only one, engine instance in a cluster will execute any timed tasks?

Thanks
