### ISSUE TITLE
Async history Cyclic execution, DataBase resource exhausted！

### ISSUE THREAD

**Issue by mf1632015** [flowable/flowable-engine#2127]
**Describe the bug**
History level is audit.
Flowable version is 6.4.0.
Async history is open and use Kafka as the message queue.
When history job message received form kafka is  later than the flow instance ended,  and "activity-end" history job execute to the AsyncHistoryJobHandler and call the json transformers method "isApplicable", it returns false. Then a AsyncHistoryJobNotApplicableException is throwed. Then the history job is always executed.
This is because the history job "activity-end" will query the act_ru_execution table. but the execution info was deleted when the process instance is ended.  

![image](https://user-images.githubusercontent.com/29472151/72403573-7e790c00-378d-11ea-9b41-92f540b2ece5.png)

**Expected behavior**
Usually ,this is not common. 

**Code**
![image](https://user-images.githubusercontent.com/29472151/72405828-2a722580-3795-11ea-838c-b295b1130b20.png)

**Comment by tijsrademakers** [comment]
For this reason the number of retries of a history job is limited:

https://github.com/flowable/flowable-engine/blob/93b6db71d1dbb1003c1964c67da98787cf9c5e6a/modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java#L747

This is an example of probably a rare case where this history job will be processed 10 times (at least by default), and then the history job will be removed.
