### ISSUE TITLE
On a form editor add ability to add 'amount', 'rate', 'quantity', 'phone', 'email' fields

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#213]
On a form editor add ability to add 'amount', 'rate/price', 'quantity', 'phone', 'email' type of fields
and you cover most business cases.
Just having a number field is not enough.

Thanks

**Comment by tijsrademakers** [comment]
We are open for PRs, please don't create this many issues. Discuss them on the Flowable forum first to get feedback from the community.

**Comment by mgrouch** [comment]
Unfortunately form doesn't pass our firewall checks and flowable forum is not accessible.
Thanks
