### ISSUE TITLE
Flowable Modeler: serviceTask extensionElements are removed at Process Definition Import/Edit/Export

### ISSUE THREAD

**Issue by remibantos** [flowable/flowable-engine#2134]
**Describe the bug**
When a process definition file having an _extensionElements_ element within a _serviceTask_ element is imported then edited and exported, _extensionElements_ are removed from the XML.
For example, when you import/edit/export a Process Definition with a serviceTask having a _failedJobRetryTimeCycle_ setting like bellow:
```xml
<serviceTask id="test" name="Test" flowable:async="true" flowable:expression="${someBean}"> <extensionElements><flowable:failedJobRetryTimeCycle>R60/PT1M</flowable:failedJobRetryTimeCycle></extensionElements> </serviceTask>
```
The corresponding export will just contain the following:
```xml
<serviceTask id="test" name="Test" flowable:async="true" flowable:expression="${someBean}"></serviceTask>
```

**Expected behavior**
_extensionElements_ should not be dropped from process definition as this is an official Flowable feature. See documentation here: https://flowable.org/docs/userguide/index.html#failRetry

**Code**
NA

**Additional context**
Flowable 6.4.2

**Comment by unamanic** [comment]
It appears PR #2009 resolved the specific issues with `flowable:failedJobRetryTimeCycle`.  Can you please retry with the newly released 6.5.0 modeler?

**Comment by remibantos** [comment]
Thanks @unamanic 
Indeed, since this PR, problem solved.
I close this issue.

**Comment by GOPALAKRISHNAYM** [comment]
hi,
failedJobRetryTimeCycle has wrong format:R5/PT5S
facing this issue even after changing to 6.5.0

Thank you.

**Comment by tijsrademakers** [comment]
Hi, can you please elaborate a bit more where you think the problem still exists?

**Comment by GOPALAKRISHNAYM** [comment]
im facing this issue.
		```
<serviceTask id="downloadDocuments"
			name="Download the documents"
			flowable:async="true"
			flowable:delegateExpression="${flowableFileDownloadServiceImpl}">
			<extensionElements>
				<flowable:failedJobRetryTimeCycle>R5/PT5S
				</flowable:failedJobRetryTimeCycle>
			</extensionElements>
		</serviceTask>
```
	i have only one service task
