### ISSUE TITLE
batchSearchKey2();

### ISSUE THREAD

**Issue by martin-grofcik** [flowable/flowable-engine#2135]
**Describe the issue**
[searchKey2](https://github.com/flowable/flowable-engine/blob/626b255e66ace086b96da7722e71eef3d157bb6a/modules/flowable-batch-service-api/src/main/java/org/flowable/batch/api/Batch.java#L31) - name is not self descriptive.

**Comment by tijsrademakers** [comment]
Hi Martin,
It's not meant to be descriptive :-)
It needs to be abstract so it can be used for a lot of different use cases.

**Comment by martin-grofcik** [comment]
Hi Tijs.

My expectation would be that migration process definition Ids would be encoded in the key. Something like
```
processDefinitionV1->processDefinitionV2
```
What will happen if we will need third search key or we won't need any?
