### ISSUE TITLE
Add support of JSON variable to the service task

### ISSUE THREAD

**Issue by cdeneux** [flowable/flowable-engine#2137]
**Is your feature request related to a problem? Please describe.**
JSON variables are supported in some places in the BPMN engine, for example for script task multi-instanciation. But they are not supported by the web service task, for example:
  * to put a JSON variable as a complex element of the SOAP Request
  * or put a complex element of a SOAP Response into a JSON variable

**Describe the solution you'd like**
Improve `flowable-cxf` to support JSON variables

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by filiphr** [comment]
Can you give some examples perhaps @cdeneux? I don't really understand the issue 😀. Or perhaps you are already working on a PR 😉?

**Comment by DarkStar1** [comment]
@cdeneux I think you can use the [Jackson library](https://github.com/FasterXML/jackson) to access the execution variables almost like you would in a Javascript context.

**Comment by cdeneux** [comment]
Hi @filiphr,

Currently, it is not possible to call a web service with a list of objects. We could do it with a Json variable, but the Json object associated to the variable is not converted when calling the web service. And perhaps, a similar question can occur on the webservice response: how to use a list returned by a webservice for task multi-instantiation ? Is it working ? I will check that.

Example: the following Json variable `values` defined as `{ "value": [ 12, 23, 34 ]}` will be converted into:
```
<values>
   <value>12</value>
   <value>23</value>
   <value>34</value>
</values>
```
with the following assignment:
```
         <dataInputAssociation>
            <targetRef>dataInputOfAddMultiRequest</targetRef>
            <assignment>
               <from>${values}</from>
               <to>${dataInputOfAddMultiRequest.values}</to>
            </assignment>
         </dataInputAssociation>
```

I work on a PR based on Flowable 6.4.2.

**Comment by cdeneux** [comment]
Sure @DarkStar1, I use the Jackson library to convert Json objects into Java objects expected by the CXF dynamic client.

**Comment by cdeneux** [comment]
Hi @filiphr, @tijsrademakers, @jbarrez 

I need help to know the best way to process a complex element of a SOAP Response as JSON variable.

I think that:
* a 1st way is to put the complex element of a SOAP Response as JSON into a data object, but how to define the data object as JSON ?
* 2nd way is to improve data objects to support types defined in service WSDL. With this solution, how to process the variable serialization ?

What is your opinion ?

**Comment by tijsrademakers** [comment]
The PR was merged, thanks
