### ISSUE TITLE
Make labels on forms right aligned (much easier to read and see)

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#214]
Make labels on the forms right aligned (much easier to read and see)
Thanks

**Comment by tijsrademakers** [comment]
We are open for PRs, please don't create this many issues. Discuss them on the Flowable forum first to get feedback from the community.

**Comment by mgrouch** [comment]
Unfortunately form doesn't pass our firewall checks and flowable forum is not accessible.
 Thanks

**Comment by mgrouch** [comment]
```
.property-row span.title {
    text-align: right;
```
