### ISSUE TITLE
Duplicate key at /flowable-engine/modules/flowable-ui-admin/flowable-ui-admin-app/src/main/resources/static/i18n/en.json

### ISSUE THREAD

**Issue by gdressino** [flowable/flowable-engine#2145]
I've found a duplicate key in file /flowable-engine/modules/flowable-ui-admin/flowable-ui-admin-app/src/main/resources/static/i18n/en.json

Branch: Master

The key is "APP-DEPLOYMENTS" (lines 776 and 1129).

**Comment by tijsrademakers** [comment]
Thanks for reporting the issue.

**Comment by dbmalkovsky** [comment]
@qiudaoke There is a similar problem in the translated files and I found two others:

modules/flowable-ui-admin/flowable-ui-admin-app/src/main/resources/static/i18n/zh-CN.json the key APP-DEPLOYMENTS is defined twice
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/i18n/zh-CN.json the key SERVICETASKRESULTVARIABLEPACKAGE is defined twice
modules/flowable-ui-modeler/flowable-ui-modeler-app/src/main/resources/static/i18n/zh-TW.json the key SERVICETASKRESULTVARIABLEPACKAGE is defined twice
