### ISSUE TITLE
On a form editor add ability to add a 'lookup' field

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#215]
On a form editor add ability to add a 'lookup' field.
It needs to be documented and have well defined behavior. Lookup should happened on a server side,

Typical use cases are
lookup of a product
lookup of a client.

Thanks

**Comment by tijsrademakers** [comment]
We are open for PRs, please don't create this many issues. Discuss them on the Flowable forum first to get feedback from the community.

**Comment by mgrouch** [comment]
Unfortunately form doesn't pass our firewall checks and flowable forum is not accessible.
 Thanks
