### ISSUE TITLE
Unexpected behaviour while accessing ArrayNode elements with juel expression

### ISSUE THREAD

**Issue by fubace** [flowable/flowable-engine#2150]
**Describe the bug**
Problem while retrieving a json element from ArrayNode with juel expression

**Expected behavior**
One should easily access ArrayNode elements with get(int index) method

**Code**
https://github.com/flowable/flowable-engine/blob/f0ce495d2d6b4bd39a5260b35771d889e2ad689b/modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/javax/el/BeanELResolver.java#L537

In this line you should also check the parameter type.
forex: com.fasterxml.jackson.databind.node.ArrayNode has 2 _get_ methods. One of them accepts int as parameter and the other one accepts String but here in this line it catches the first _get_ method which accepts String type parameter and just returns null.

**Additional context**
flowable-engine-common

**Comment by tijsrademakers** [comment]
Hi,

JUEL 2 is not great with method overloading and choosing the best matching method, so that's why the .get is not working. Instead you could do [index] on the array node like myArrayNode[index], that should work fine.

**Comment by fubace** [comment]
The problem is not related to JUEL itself, engine code is buggy.

By the way I also tried your solution but again it doesn't work. Because it also calls the same _get_ method I described above and beside that I am not the only one faced with this issue. You can also check the same problem here.

https://stackoverflow.com/questions/54774233/access-to-json-values-of-array-flowable

**Comment by tijsrademakers** [comment]
You are referring to the wrong code with the BeanELResolver.
We have a unit test showing that the [0] approach is working:

https://github.com/flowable/flowable-engine/blob/master/modules/flowable-engine/src/test/java/org/flowable/engine/test/json/JsonTest.java#L411

Are you using 6.5.0 or an earlier version?

**Comment by fubace** [comment]
Ok I see... I was working at 6.5.0-SNAPSHOT version

and i see that you have changed this line
`JsonNode resultNode = ((JsonNode) base).get(property.toString());`
with 
`JsonNode resultNode = getResultNode((JsonNode) base, property, context);
`
in org.flowable.common.engine.impl.el.JsonNodeELResolver

in newer version and it works now.

Thanks.
