### ISSUE TITLE
Scroll bar in flowable-task

### ISSUE THREAD

**Issue by NagarjunGV** [flowable/flowable-engine#2157]
Hello Team,

With apps having more than ~50 models, its almost impossible to view all the models inside the app in flowable-task. Thereby not providing the flexibility to choose the correct start model to start the app.

It would be highly helpful if we get a feature of scroll bar within the app in flowable-task. This would help us navigate to the right model to start the flow.

Regards,

**Comment by PascalSchumacher** [comment]
this issue duplicates https://github.com/flowable/flowable-engine/issues/1406

**Comment by tijsrademakers** [comment]
Closing issue because it's a duplicate.
