### ISSUE TITLE
Double list where a user selects from one list of choices and drags into another is also needed for form editor

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#216]
Double list where a user selects from one list of choices and drags into another is also needed for form editor

Thanks

**Comment by tijsrademakers** [comment]
We are open for PRs, please don't create this many issues. Discuss them on the Flowable forum first to get feedback from the community.

**Comment by mgrouch** [comment]
Unfortunately form doesn't pass our firewall checks and flowable forum is not accessible.
 Thanks
