### ISSUE TITLE
Apache Ignite support

### ISSUE THREAD

**Issue by szaluzhskiy** [flowable/flowable-engine#2164]
**Is your feature request related to a problem? Please describe.**
Please consider support of Apache Ignite\GridGain(https://ignite.apache.org) community in-memory data grid support as a persistence backend

**Describe the solution you'd like**
Use Apache Ignite as database 

**Describe alternatives you've considered**
Apache Ignite has a support of SQL interface - https://apacheignite-sql.readme.io/docs/how-ignite-sql-works
Which can be used but with certain limitations. See description of SQL API - https://apacheignite-sql.readme.io/docs/java-sql-api

**Comment by tijsrademakers** [comment]
@szaluzhskiy can you share a bit more background on why you created this feature request? Are there specific use cases you want to cover with this or are there other reasons? Thanks.

**Comment by szaluzhskiy** [comment]
@tijsrademakers The idea is that every project is using persistence layer. And it can be build on SQL\noSQL database. So it would be convenient if flowable can support as much databases as possible. For example via JPA or JDBC interface. In my case we finally decided to use Apache Ignite as persistence layer. Can you support it in flowable?

**Comment by tijsrademakers** [comment]
Flowable uses JDBC to communicate with all the major databases. In addition we have a MongoDB / NoSQL implementation (https://github.com/flowable/flowable-mongodb), which covers part of the functionality. We don't have plans at the moment to extend the support to also include Apache Ignite. If this is done with a community contribution then we can look at it again of course.

**Comment by szaluzhskiy** [comment]
@tijsrademakers That's is clear! We are triyng to go with JDBC interface.
