### ISSUE TITLE
Sql scripts committed do not match liquibase

### ISSUE THREAD

**Issue by DavidPLamas** [flowable/flowable-engine#2169]
Hi,
We use Flowable in very restricted environments where we can't use liquibase to automatically update the database schemas. 
For that reason, we use the sql scripts commited in [flowable repo](https://github.com/flowable/flowable-engine/tree/master/distro/sql) to manage our environment updates.
After executing the upgrade script from 6.4.2 to 6.5.0 and deploying our application we got the folowing error:
```
java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngine': FactoryBean threw exception on object creation; nested exception is org.flowable.common.engine.api.FlowableException: Error initialising eventregistry data model
Caused by: java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngine': FactoryBean threw exception on object creation; nested exception is org.flowable.common.engine.api.FlowableException: Error initialising eventregistry data model
    Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngine': FactoryBean threw exception on object creation; nested exception is org.flowable.common.engine.api.FlowableException: Error initialising eventregistry data model
    Caused by: org.flowable.common.engine.api.FlowableException: Error initialising eventregistry data model
    Caused by: org.flowable.common.engine.api.FlowableException: Error validating eventregistry engine schema
    Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
     1 change sets check sum
          org/flowable/eventregistry/db/liquibase/flowable-eventregistry-db-changelog.xml::1::flowable was: 7:0aaa7b01343f4cdaf1019cd2de3f98f3 but is now: 8:1b0c48c9cf7945be799d868a2626d687
```

To try to fix this issue, we've launched the same application with **databaseSchemaUpdate** set to **true** in a local environment and we found that the table *FLW_EV_DATABASECHANGELOG* had different data than the one provided by the SQL script that we executed.

There might be problems with other tables since we don't make use of all engines and for that reason we don't have all of Flowable's tables. Can you please check and make the necessary changes ? 

Thank you,
David.

**Comment by tijsrademakers** [comment]
Hi David,

We use Liquibase for our newer engines and services like the event registry engine and the CMMN engine. With databaseSchemaUpdate set to false Liquibase will expect the checksum value to match the checksum it generates on the fly. This is in most environments not the case. Therefore the databaseSchemaUpdate value should be set to true and then Liquibase will update the checksum values in the database schema log tables. When you run the manual sql scripts, setting databaseSchemaUpdate to true will not make any changes to the database schema, so it's safe to set it to this value.

Best regards,

Tijs

**Comment by DavidPLamas** [comment]
Hi @tijsrademakers ,
I'm afraid this a solution that we cannot take. In our client environments, the user used with datasource associated with Flowable's engine often doesn't have DDL permissions. It's something that we cannot control: it's a requirement that our clients impose us.
That means that everytime we want to update the database schema we have to login to the database with a different user a execute the DDL scripts. 
Before 6.5.0 this was never a problem because the SQL scripts commited in the repository were always up to date with the liquibase. Are you sure this cannot be fixed ?

**Comment by tijsrademakers** [comment]
Hi David,

Why would it not work for a user without DDL permissions? If you use the manual SQL scripts, Flowable won't do any schema changes. So I think it will work fine.

When you say it wasn't an issue for you before 6.5.0, were you using any of the Liquibase engines? This means either the CMMN, Form, Content or DMN engine? Because the BPMN and IDM engine are not using Liquibase, so they don't have the issue.

Thanks,

Tijs

**Comment by DavidPLamas** [comment]
Hi Tijs,

> Why would it not work for a user without DDL permissions? If you use the manual SQL scripts, Flowable won't do any schema changes. So I think it will work fine.

Can you please explain how you can make sure that liquibase wont touch the tables when the changelog doesn't match the one expected by liquibase? 


> When you say it wasn't an issue for you before 6.5.0, were you using any of the Liquibase engines? This means either the CMMN, Form, Content or DMN engine? Because the BPMN and IDM engine are not using Liquibase, so they don't have the issue.

Yes, we do use the Form Engine since 6.4.1. But the tables for this engine (and bpmn engine) were copied from a local environment due to the fact that our first release was based on Flowable 6.4.1. 
Now that we have clients in production we can't copy databases, we need to have migration scripts and we were relying on the scripts commited from the repository to do so.

**Comment by tijsrademakers** [comment]
Hi David,

Ok thanks for the additional info. We create the manual sql files based on the Liquibase changelog file and we do this against actual databases (Oracle, MS SQL Server, DB2 etc). So these manual sql script are created with a lot of care. Therefore we can ensure that this will work.
Also the user won't have rights to make changes to the database schema anyway, so there's nothing that can go wrong I would say.

Note that we are thinking about supporting databaseSchemaUpdate=false as well based on your feedback.
