### ISSUE TITLE
Simple grid control on a form editor with binding using EL is needed

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#217]
Simple grid control on a form editor with binding using EL is needed.

Flowable as a product would greatly benefit more elaborate form editor in general.
It should cover most common use cases with ability to design forms with EL binding 
(I. e. without any java or JavaScript coding). There are number of javascript libraries which could help with it.

Thanks

**Comment by tijsrademakers** [comment]
We are open for PRs, please don't create this many issues. Discuss them on the Flowable forum first to get feedback from the community.

**Comment by mgrouch** [comment]
Unfortunately form doesn't pass our firewall checks and flowable forum is not accessible.
 Thanks
