### ISSUE TITLE
flowable-6.5.0\database\create\bpmn\flowable.mssql.create.engine.sql failed to create tabeles

### ISSUE THREAD

**Issue by carbon-60** [flowable/flowable-engine#2174]
**Describe the bug**
Running flowable-6.5.0\database\create\bpmn\flowable.mssql.create.engine.sql in a new MSSQL DB, it encounters the following error:

Msg 1088, Level 16, State 12, Line 142
Cannot find the object "ACT_RU_VARIABLE" because it does not exist or you do not have permissions.

I have to run the script under all folder to get it working even though I only need bpmn:

flowable-6.5.0\database\create\all\flowable.mssql.all.create.sql

**Expected behavior**
It is expected this script creates tables without error.

**Code**
If applicable, add the code that you are using when having the issue.

**Additional context**
Add the version of Flowable that you are using, the database vendor and if you are using Flowable within Spring Boot, the Flowable Task application etc.

**Comment by tijsrademakers** [comment]
When you only want to have the BPMN engine tables then you need to run two sql scripts. Before running the flowable.mssql.create.engine.sql script you first need to run the common script:

https://github.com/flowable/flowable-engine/blob/master/distro/sql/create/common/flowable.mssql.create.common.sql

There it creates the variable table, amongst other common tables.
