### ISSUE TITLE
How Can I use MultiSchemaMultiTenantProcessEngineConfiguration.java in SpringBoot

### ISSUE THREAD

**Issue by phoema** [flowable/flowable-engine#2176]
<groupId>org.flowable</groupId>
			<artifactId>flowable-spring-boot-starter-process</artifactId>
		    <version>6.5.0</version>

I want use Flowable with  MultiSchemaMultiTenant Mode in Springboot

I tried to create TenantInfoHolderImpl
When I create many DataSources in Springboot With AbstractRoutingDataSource
But Flowable does not work very well.
first error like this:
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### The error may exist in org/flowable/eventregistry/db/mapping/entity/ChannelDefinition.xml

So How Can I use MultiSchemaMultiTenantProcessEngineConfiguration.java in SpringBoot?

**Comment by filiphr** [comment]
Can you please share an example project with how you are configuring all of this?

We currently don't support the `MultiSchemaMultiTenantProcessEngineConfiguration` via Spring Boot. So it can very much be that it isn't working properly.

**Comment by tijsrademakers** [comment]
Closing the issue due to no response. Please reopen with an example project when required,
