### ISSUE TITLE
Permissioning system should be made more granular

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#218]
Permissioning system should be made more granular

There should be roles to be a read-only user in modeler,
Separate role to upload applications , to publish, etc

Thanks

**Comment by tijsrademakers** [comment]
We are open for PRs, please don't create this many issues. Discuss them on the Flowable forum first to get feedback from the community.

**Comment by mgrouch** [comment]
Unfortunately form doesn't pass our firewall checks and flowable forum is not accessible.
 Thanks
