### ISSUE TITLE
Use of modified version of JUEL

### ISSUE THREAD

**Issue by dbmalkovsky** [flowable/flowable-engine#22]
In the user guide, ch04-API.adoc, in the first paragraph under [Expressions](http://www.flowable.org/docs/userguide/index.html#apiExpressions) is the statement:  

To support all features of latest UEL spec on ALL environments, we use a modified version of  JUEL.

I believe that @tijsrademakers  removed the JUEL classes from the Version 6 engine in July, 2016.

This statement should thus be removed or qualified that it is only true for the Version 5 compatibility engine.

Given the appropriate direction I will submit a pull request.

**Comment by jbarrez** [comment]
Your analysis is correct: Juel is now a dependency and not a modified version anymore (I believe the original issue why it was needed was fixed since).

**Comment by dbmalkovsky** [comment]
See this [pull request](https://github.com/flowable/flowable-engine/pull/24) for a suggested rewording.

**Comment by tijsrademakers** [comment]
Merged PR
