### ISSUE TITLE
Swagger UI displays error at the bottom of a page

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#220]
I'm not using localhost. Might be related to this

https://github.com/z0mt3c/hapi-swaggered/issues/33

{"schemaValidationMessages":[{"level":"error","message":"Can't read from file http://mycompanyhost:8082/flowable-rest/docs/specfile/dmn/flowable.json"}]}

Thanks

**Comment by mgrouch** [comment]
Or could be this

http://stackoverflow.com/questions/32188386/cant-read-from-file-issue-in-swagger-ui

**Comment by mgrouch** [comment]
I've run it in FireBug and I could see swagger doing this request

http://online.swagger.io/validator?url=http://mycompanyhost:8082/flowable-rest/docs/specfile/dmn/flowable.json

Which is bad idea to do. There should be a way to disable it.

Thanks

**Comment by mgrouch** [comment]
I think this is the solution:

http://stackoverflow.com/questions/27808804/swagger-ui-shows-error-validation-when-deployed



To turn off swagger validator add validatorUrl : null, in dist/index.html in

```
  window.swaggerUi = new SwaggerUi({
    url: url,
    validatorUrl : null,
    dom_id: "swagger-ui-container",

```

**Comment by tijsrademakers** [comment]
Closing the issue because we didn't get any similar feedback until now.
