### ISSUE TITLE
Swagger client generated out of provided flowable.yaml/flowable.json files doesn't send basic authentication

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#222]
Swagger client generated out of provided flowable.yaml/flowable.json files doesn't send basic authentication. 
Looks like those specs are incorrect for authentication.

Thanks

**Comment by mgrouch** [comment]
@Api

annotation is missing 'authorizations' parameter everywhere.

Thanks

**Comment by mgrouch** [comment]
, authorizations = {@Authorization("basic")}

**Comment by tijsrademakers** [comment]
The annotation has been added, thanks
