### ISSUE TITLE
"TASK_CREATED" event received but userTask Submission failed

### ISSUE THREAD

**Issue by winterzhuang** [flowable/flowable-engine#2221]
please see my attach diagram, user task2 has flowable:skipExpression="${age == 20}", when I completed user task1 without variable "age", then completed failed, that's right,  but user task2 "TASK_CREATED" event received in MyListener. Below is my listener code: 

// LISTENER CODE
class MyListener implements FlowableEventListener {
      
    @Override
     public void onEvent(FlowableEvent event) {
           if (event.getType() == FlowableEngineEventType.TASK_CREATED) {
                   // do something
           }
     }
}
![sample](https://user-images.githubusercontent.com/22721385/76497953-ef2f6280-6476-11ea-8507-acd793f747c6.png)

**Comment by tijsrademakers** [comment]
@winterzhuang are you using Flowable version 6.5.x? Can you create a PR with a unit test showing this issue?

**Comment by winterzhuang** [comment]
@tijsrademakers  I can't reproduce the issue. but I find another problem. see my diagram. 
![Uploading sample.png…]

user task1 completed failed without timer variable 'timeDate', but user task2 create event listener received.
my diagram xml is 
![diagram](https://user-images.githubusercontent.com/22721385/77385599-896e9f00-6dc3-11ea-8437-6335a6f4ff35.png)

**Comment by winterzhuang** [comment]
@tijsrademakers I will create PR with a unit test if necessary

**Comment by tijsrademakers** [comment]
@winterzhuang this is the expected behaviour because the event listener is invoked when user task 2 is created, but then creating the timer boundary event fails because of the missing variable. And then the whole transaction will rollback, but still the create task listener was already invoked.
