### ISSUE TITLE
TaskQuery: scope is not available when including variables

### ISSUE THREAD

**Issue by DavidPLamas** [flowable/flowable-engine#2223]
Hi, 
I just found out that when calling .includeTaskLocalVariables() or .includeProcessVariables(), the response does not contain any of the scope attributes. It happens when using both ProcessEngine and CmmnEngine.
Why does this happen?

Example bellow:
![image](https://user-images.githubusercontent.com/8373746/76636323-c07dbe80-6540-11ea-87cb-8840a5b1caf5.png)

![image](https://user-images.githubusercontent.com/8373746/76636346-cbd0ea00-6540-11ea-89f4-de92b9757222.png)

**Comment by tijsrademakers** [comment]
Hi @DavidPLamas , I've added a unit test to try and reproduce the issue. But the unit test works ok. On which database are you testing this?

**Comment by DavidPLamas** [comment]
Hi @tijsrademakers ,

I'm using SQLServer.

**Comment by tijsrademakers** [comment]
Thanks for reporting the issue, it should be fixed now.

**Comment by DavidPLamas** [comment]
Hi @tijsrademakers ,
I've just noticed it is also happening in the history counterpart. Does your commit fix the issue in the history services as well ?

**Comment by tijsrademakers** [comment]
Hi @DavidPLamas, no for the history it's not solved yet. I'll have a look there as well, thanks.

**Comment by DavidPLamas** [comment]
@tijsrademakers  I know this issue has been closed for a while, but did you have time to add this fix to the history counterpart?
