### ISSUE TITLE
How to get a user's group info by rest-api?

### ISSUE THREAD

**Issue by GerryLon** [flowable/flowable-engine#2228]
**Describe the bug**
I can not get user's group info by rest-api.

**Expected behavior**

**Code**
If applicable, add the code that you are using when having the issue.

**Additional context**
I'm using flowable 6.5.0,
call api from flowable-rest app:(http://localhost:8080/flowable-rest/docs/?url=specfile/process/flowable.json#!/Users/getUser)

Many thanks!

**Comment by tijsrademakers** [comment]
Please check the following REST API documentation:

https://flowable.com/open-source/docs/bpmn/ch15-REST/#get-a-list-of-groups

You can get a list of groups where the provided member parameter is a member of.

**Comment by GerryLon** [comment]
Very helpful, Thanks!
