### ISSUE TITLE
Import APP logic in flowable-modeler seems broken

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#224]
If I import same app over and over
 it creates a new app on each import. 
(Instead of saving same app with a new version)

Thanks

**Comment by paulhh** [comment]
Are you importing from the App list page, or the details page of the app?  It only should work when you import from the details page of the app you want.  

I will also retest on a couple of builds.

Cheers
Paul.

**Comment by filiphr** [comment]
Closing due to lack of feedback. If there is more information we can reopen the issue
