### ISSUE TITLE
Delete an application in flowable-modeler leaves its process workflow behind

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#225]
Delete an application in flowable-modeler leaves its process workflow behind.

If a process workflow was deployed as a part of application bundle
deleting that application bundle should remove its process workflow

(at least perform 'logical' delete as opposed to physical
by marking it 'deleted' in the database)

Thanks

**Comment by tijsrademakers** [comment]
This is by design. A deployed application bundle is actually a deployment in the Flowable Engine. You can delete it using the RepositoryService or doing a Rest call or using the Flowable Admin application.
