### ISSUE TITLE
run  spring-boot-example  ,curl 404 error

### ISSUE THREAD

**Issue by abao2016** [flowable/flowable-engine#2253]
run  github 's spring-boot-example,

curl http://localhost:8080/flowable-rest/service/management/engine

return 404

{"timestamp":"2020-03-29T15:12:19.661+0000","status":404,"error":"Not Found","message":"No message available","path":"/flowable-rest/service/management/engine"}
![Lark20200329-231442](https://user-images.githubusercontent.com/20501382/77852804-2346a980-7213-11ea-996b-2c26d9134f41.png)

**Comment by filiphr** [comment]
If you read the [README](https://github.com/flowable/flowable-examples/tree/master/spring-boot-example) for the example you will see that Process Engine Endpoints are under the `process-api` path and if you look at the [application.properties](https://github.com/flowable/flowable-examples/blob/master/spring-boot-example/src/main/resources/application.properties) you'll see that there is no context path for the application. So the endpoint that you should be curling is:

```
curl http://localhost:8080/process-api/management/engine
```
