### ISSUE TITLE
Unable to access groups with privileges section in Flowable (With LDAP)

### ISSUE THREAD

**Issue by ankit45621** [flowable/flowable-engine#2254]
Hi All,

I am new to flowable and successfully integrated flowable with Ldap using below configuration in my docker-compose.yml:
environment:
- SERVER_PORT=9090
- SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
- SPRING_DATASOURCE_URL=<>
- SPRING_DATASOURCE_USERNAME=<>
- SPRING_DATASOURCE_PASSWORD=<>
#Default LDAP Admin User
- FLOWABLE_IDM_APP_ADMIN_USER_ID=<>
- FLOWABLE_IDM_APP_ADMIN_PASSWORD=<>
- FLOWABLE_IDM_APP_ADMIN_FIRST_NAME=<>
- FLOWABLE_COMMON_APP_IDM_ADMIN_USER=<>
- FLOWABLE_COMMON_APP_IDM_ADMIN_PASSWORD=<>
#FLowable-Ldap Configuration
- FLOWABLE_IDM_LDAP_ENABLED=true
- FLOWABLE_IDM_LDAP_SERVER=
- FLOWABLE_IDM_LDAP_PORT=389
- FLOWABLE_IDM_LDAP_USER=<>
- FLOWABLE_IDM_LDAP_PASSWORD=<>
- FLOWABLE_IDM_LDAP_BASE_DN=<>
#Users
- FLOWABLE_IDM_LDAP_USER_BASE_DN=<>
- FLOWABLE_IDM_LDAP_QUERY_USER_BY_FULL_NAME_LIKE=(&(objectClass=inetOrgPerson)(|({0}={1})({2}={3})))
- FLOWABLE_IDM_LDAP_QUERY_USER_BY_ID=(&(objectClass=inetOrgPerson)(uid={0}))
- FLOWABLE_IDM_LDAP_QUERY_ALL_USERS=(objectClass=inetOrgPerson)
- FLOWABLE_IDM_LDAP_ATTRIBUTE_USER_ID=uid
- FLOWABLE_IDM_LDAP_ATTRIBUTE_FIRST_NAME=cn
- FLOWABLE_IDM_LDAP_ATTRIBUTE_LAST_NAME=sn
#Groups
- FLOWABLE_IDM_LDAP_GROUP_BASE_DN=<>
- FLOWABLE_IDM_LDAP_QUERY_GROUPS_FOR_USER=(&(objectClass=posixGroup)(gidNumber={0}))
- FLOWABLE_IDM_LDAP_QUERY_ALL_GROUPS=(objectClass=posixGroup)
- FLOWABLE_IDM_LDAP_QUERY_GROUP_BY_ID=(&(objectClass=posixGroup)(gidNumber={0}))
- FLOWABLE_IDM_LDAP_ATTRIBUTE_GROUP_ID=gidNumber
- FLOWABLE_IDM_LDAP_ATTRIBUTE_GROUP_NAME=cn
- FLOWABLE_IDM_LDAP_CACHE_GROUP_SIZE=10000
- FLOWABLE_IDM_LDAP_CACHE_GROUP_EXPIRATION=180000

Problem statement:
Inside Ldap I have each user assigned to a group. These groups are visible on my flowable. But while giving privileges to groups inside flowable-idm, users dont get the desired access. I have to individually assign each user to flowable-modeler,workflow.

Example:

1. User “ankit” having group “admin” in ldap.

2. In flowable if “admin” group is given access to “Access the workflow application”, ankit must implicitly have access to it.

3. Currently in my setUp it doesn’t happen.

4. User “ankit” has to be explicitly added to be given “Access the workflow application”

Any help on this is highly appreciated.

**Comment by filiphr** [comment]
Hey @ankit45621,

Please do not cross post your questions. You posted both here on GitHub and [here](https://forum.flowable.org/t/flowable-ldap-integration/5190/4) to the forum.

**Comment by ankit45621** [comment]
> Hey @ankit45621,
> 
> Please do not cross post your questions. You posted both here on GitHub and [here](https://forum.flowable.org/t/flowable-ldap-integration/5190/4) to the forum.

Can you please help me to solve my issue? anywhere github or [https://forum.flowable.org/t/flowable-ldap-integration/5190/3](https://forum.flowable.org/t/flowable-ldap-integration/5190/3)?
