### ISSUE TITLE
flowable-springboot-rest  how to deploy cloud?

### ISSUE THREAD

**Issue by abao2016** [flowable/flowable-engine#2255]
hai,we want use deploy flowable-springboot-rest  to provider common restfull, can it deploy Multi machine?
is it Horizontal expansion and stateless?  has Timer Task problem?

**Comment by filiphr** [comment]
Hey @abao2016,

Please use our [Forum](https://forum.flowable.org/) for asking questions.

Flowable is stateless and can easily be scaled horizontally.
