### ISSUE TITLE
flowable-ui-admin needs to be refactored to split java classes into different libraries

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#226]
flowable-ui-admin needs to be refactored to split java classes into different libraries.

It needs to be consistent with otherflowable web applications.

Thanks

**Comment by dpratt** [comment]
I don't actually understand why this needs to be done. 

What benefit is gained from breaking out into individual modules?

**Comment by tijsrademakers** [comment]
Done for consistency reasons + easier customization options
