### ISSUE TITLE
Usage of Send Event Task

### ISSUE THREAD

**Issue by RedzRedz** [flowable/flowable-engine#2268]
**Describe the bug**
I use the modeler to try a send event task, it tell me `One of the attributes 'class', 'delegateExpression', 'type', 'operation', or 'expression' is mandatory on serviceTask`.
![image](https://user-images.githubusercontent.com/45602777/78621312-e59dec80-78b4-11ea-8ecc-5f58a1387f78.png)
![image](https://user-images.githubusercontent.com/45602777/78621382-0b2af600-78b5-11ea-97eb-0a509b5bd67a.png)
But when I upload the bpmn20.xml file to admin, the send event task missed.
![image](https://user-images.githubusercontent.com/45602777/78621425-1ed65c80-78b5-11ea-9e8b-c393c2da6565.png)

And Can I get the bpmn20.xml file of [demo](https://blog.flowable.org/2020/02/08/introducing-the-flowable-event-registry/).

**Comment by tijsrademakers** [comment]
Are you sure you are using the send event task, and not the send task? The send event task should have  quite a number of event configuration options in the Modeler and you should then not get this error message.

**Comment by RedzRedz** [comment]
I just want to send a rabbit mq in flowable after a user task and i have read the blog [INTRODUCING THE FLOWABLE EVENT REGISTRY](https://blog.flowable.org/2020/02/08/introducing-the-flowable-event-registry/).
By the way can i get the bpmn20.xml of the demo `INTRODUCING THE FLOWABLE EVENT REGISTRY`

**Comment by filiphr** [comment]
I think that there was a link in the blog. Anyways the app used in the blog is [here](https://github.com/flowable/flowable-examples/blob/master/blog/EventApp.zip)

**Comment by V01d3m0rt** [comment]
a bit late to the party but it seems an issue to me too, although if I export xml from modeler and use it in my java program, I don't see any problem.
