### ISSUE TITLE
Why getEmail() is used to set userID in UserDetailsService?

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#228]
```
    User user = cachedUser.getUser();
    String actualUserId = user.getEmail();

    return new FlowableAppUser(cachedUser.getUser(), actualUserId, cachedUser.getGrantedAuthorities());

```

Looks like a bug to me.

I noticed when I just change admin email in properties file

admin.email=admin

to my email I start getting errors.

Should it be 

`String actualUserId = user.getId();`

?

Thanks

**Comment by tijsrademakers** [comment]
I think this can be changed to getId(), but the admin.email property is used for both the id as well as the email field in the database currently. Please be more detailed than "I start getting errors", can you explain the errors you are seeing?

**Comment by mgrouch** [comment]
It is changing user id after its details are loaded.
Everyone would assume that user ID stays same after login.
But this code is switching it from ID to email.

**Comment by mgrouch** [comment]
BTW as a result 
'remember me' authentication is broken

**Comment by mgrouch** [comment]
and also in org.flowable.app.conf.Bootstrapper

instead of     

`User admin = identityService.newUser(adminEmail);
`
it should be 
`
    User admin = identityService.newUser("admin");
`
or better

have a new property
`
admin.user=admin
`
and 
```

   String adminUser= env.getRequiredProperty("admin.user");
    User admin = identityService.newUser(adminUser);


```With current implementation it is not possible to set email to admin user.

Thanks

**Comment by tijsrademakers** [comment]
Added additional admin.userid property
