### ISSUE TITLE
flowable-bpmn-extensions.xsd wrongly assumes ServiceTask has resultVariable field

### ISSUE THREAD

**Issue by travishaagen** [flowable/flowable-engine#2285]
**Describe the bug**
[flowable-bpmn-extensions.xsd](https://github.com/flowable/flowable-engine/blob/flowable-6.5.0/modules/flowable-bpmn-converter/src/main/resources/org/flowable/impl/bpmn/parser/flowable-bpmn-extensions.xsd#L243) wrongly assumes BPMN `ServiceTask` has `resultVariable` field, but it instead has [resultVariableName](https://github.com/flowable/flowable-engine/blob/flowable-6.5.0/modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/ServiceTask.java#L61) field

**Expected behavior**
Think that `resultVariableName` field needs to be added to `flowable-bpmn-extensions.xsd`

**Code**
N/A

**Additional context**
Observed in Flowable 6.5.0

**Comment by filiphr** [comment]
Thanks for raising the issue @travishaagen. Would you be interested in providing a PR to add the missing `resultVariableName` in the `flowable-bpmn-extensions.xsd`?

**Comment by travishaagen** [comment]
done!
