### ISSUE TITLE
Localization Task nodes

### ISSUE THREAD

**Issue by jisqaqov** [flowable/flowable-engine#231]
Hello. Could you consider localization of task nodes in bpmn engine. For example i want to show diagrams in native language. It is recommended to add name_xxx fields in process definition, process instance, user task, service task and etc. In my opinion it is crucial, because i live in multilingual country.

**Comment by roberthafner** [comment]
Hi, The Flowable engine supports localization for tasks already. Please see the "testLocalizeTasks" method in the following test class as well as the BPMN definition as I don't think this feature has been documented yet. 

https://github.com/flowable/flowable-engine/blob/master/modules/flowable-engine/src/test/java/org/flowable/engine/test/api/task/TaskQueryTest.java

https://github.com/flowable/flowable-engine/blob/master/modules/flowable-engine/src/test/resources/org/flowable/engine/test/api/task/TaskQueryTest.testProcessDefinition.bpmn20.xml

Tijs/Yvo, will this functionality be exposed in the modeler's UI at some point?

**Comment by tijsrademakers** [comment]
Hi Robert, indeed. We want the functionality to be exposed in the modeler UI, probably after we did the first 6.0.0 release.
