### ISSUE TITLE
Postgres schema spring boot, table name prefix

### ISSUE THREAD

**Issue by jisqaqov** [flowable/flowable-engine#232]
Hi. During spring boot startup flowable engine creates tables in public schema of postgres by default. I want to deliberately create it in another schema, for instance in bpm schema. 
I think it would be great to add configuration file to set schema options. I know that i can configure database parameters, but there is no available option for shema. 
I hope it is available in MyBatis, because before i suggested you to move to JPA. 
In addition, table names looks like start from ACT_ prefix. Possibly, it is better to rename to another prefix name. For intance, FLW_

**Comment by tijsrademakers** [comment]
There is a databaseSchema property available on the process engine configuration that should provide the ability to use a different schema. We can't just rename every table due to backward compatibility reasons.
