### ISSUE TITLE
UI Modeler App: Cannot update key for an existing Case/Process

### ISSUE THREAD

**Issue by MitchB09** [flowable/flowable-engine#2328]
**Describe the bug**
Edits to an existing model's key or name is not reflected in the generated xml output

**Expected behavior**
Updates to the key of a Case/Process should be reflected in the xml for that Case/Process

**Steps to Reproduce**
1. Open the details screen existing process/case model
1. Edit the key for the model
1. Download the xml for the model
1. Open the xml and see that the id of the process/case is not the updated key from step 2

**Code**
N/A

**Additional context**
Flowable version: 6.4.2

**Comment by tijsrademakers** [comment]
Hi,
Did you also try this on the latest version of Flowable (6.5.0) ?
Thanks

**Comment by tijsrademakers** [comment]
Hi,
On the current master branch this is working fine. Would be good to check if 6.5.0 has a different result for you. Closing the issue because it's working ok on the master branch.
Best regards
