### ISSUE TITLE
Exclusive & async flags are lost on flowNode (e.g. gateways) export-import

### ISSUE THREAD

**Issue by martin-grofcik** [flowable/flowable-engine#2344]
**Description**
When you export/import a model with non default async and exclusive flags, values are ignored.

**Expected behavior**
Properly set async and exclusive values.

**Pull request**
https://github.com/flowable/flowable-engine/pull/2345

**Comment by sebastianblesgen** [comment]
Hi,
Using v6.6.0 the import/export feature keeps the async property set but is it normal that I can't edit the field in the UI ? Field looks disabled (not edit mode on click)

**Comment by filiphr** [comment]
Closing this as the PR has been fixed with https://github.com/flowable/flowable-engine/pull/2345.

@sebastianblesgen the problem you are seeing has been fixed as part of https://github.com/flowable/flowable-engine/pull/2662 and will be there in the 6.6.1 release
