### ISSUE TITLE
FlowableFormElContext does not resolve spring context beans

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#236]
FlowableFormElContext does not resolve spring context beans

same beans resolve fine in FlowableElContext

Thanks

**Comment by chrismcbride76** [comment]
I've observed this same bug.  Any thoughts from the flowable team?  If someone could point me in the right direction, I may have time to investigate this and submit a PR with a fix.

**Comment by tijsrademakers** [comment]
The reason is that there's no SpringExpressionManager yet for the Form engine. That class creates an ApplicationContextElResolver in the BPMN Engine. A similar EL resolver is needed for the form engine Spring module.

**Comment by tijsrademakers** [comment]
Fixed, a SpringFormExpressionManager is introduced and now Spring beans can be resolved in JUEL expressions in the Form Engine when the FormEngineFactoryBean ior the SpringFormEngineConfigurator is used.
