### ISSUE TITLE
Controlling number of jobs picked by async executor

### ISSUE THREAD

**Issue by apoorvam** [flowable/flowable-engine#2371]
Hi there, firstly, thanks for the great tool. 

Is there a way to filter how many async jobs of a particular type(of same element_id) can be executed by async executor simultaneously? This is so that my async executor is not occupied fully by only one type of async job, a large number of which is present. 

As I found no such feature available, I tried overriding the `executeAsyncJob` method of `AbstractAsyncExecutor`. Seems like it will help, but I need a way to figure out how many jobs of an element type are currently running so I can filter jobs based on that. 

`new JobQueryImpl().elementId(elementId).locked()`

Above query gives count of all jobs that are being acquired by async executor. But this is not accurate because all of it might not be executed by it. This is because by default all the jobs are locked and is tried to execute. Is there a way I can get how many jobs of a certain elementId are currently running, so I can not pick that job? 
This will get me to final goal of running only x number of jobs of a certain type at a time, controlling it. Any ideas would be useful.

**Comment by tijsrademakers** [comment]
Hi @apoorvam ,

In this commit you can see a new feature that we added in April:

https://github.com/flowable/flowable-engine/commit/4191a3efa2378e6e02130f3a60b6a0e79ac9d712

This allows you to configure which job categories should be executed by an async executor instance. In this way you can distribute the execution of different categories across multiple engine instances.

To allow only a certain amount of jobs of a specific type to be executed at the same time by the async executor is currently beyond the use cases covered by the async executor.

Best regards
