### ISSUE TITLE
There are high-risk vulnerabilities in the plug-in included 6.5 version of flowable

### ISSUE THREAD

**Issue by fox0741** [flowable/flowable-engine#2375]
Use Blackduck to scan the flowable and find that the low version of **netty, tomcat, commons-fileupload** have CVE high-risk vulnerabilities, please upgrade them
![netty](https://user-images.githubusercontent.com/16645871/83601784-d92bcc80-a5a3-11ea-951f-41d9157d1524.png)
![tomcat](https://user-images.githubusercontent.com/16645871/83601851-011b3000-a5a4-11ea-8145-66d672f3dc6e.png)
![commons-fileupload](https://user-images.githubusercontent.com/16645871/83601946-31fb6500-a5a4-11ea-8236-c7f156d875fa.png)

**Comment by filiphr** [comment]
@fox0741 which plugin are you talking about? Can you please what did you give to Blackduck for scanning?

Flowable has no dependency on netty or commons-fileupload in its dependency tree. As for the tomcat dependency, that is only in the Flowable UI applications and is used only when you use them as standalone jar. If you deploy them to your own Tomcat then you can use whichever version you want. 

If you are using Flowable embedded, then it is your responsibility to upgrade to the latest versions of dependencies like netty, commons-fileupload, tomcat.

**Comment by fox0741** [comment]
Actually they exist in the ui-edge jar package of flowable, I don't know if they are called by flowable, or whether flowable uses their function, please investigate

**netty-common-4.1.43.Final.jar**
flowable-6.5.0/libs/flowable-ui-edge-6.5.0.jar
--BOOT-INF/lib/netty-codec-http-4.1.43.Final.jar
---- io/netty/handler/codec

**nio-multipart-parser-1.1.0.jar**
flowable-6.5.0/libs/flowable-ui-edge-6.5.0.jar
-- BOOT-INF/lib/nio-multipart-parser-1.1.0.jar
----org/synchronoss/cloud/nio/multipart/util
