### ISSUE TITLE
How can I use flowable-ui-idm with springboot in V6.5.0+ ?

### ISSUE THREAD

**Issue by ProLeung** [flowable/flowable-engine#2384]
Do you know how to choose dependencies in POM.xml?
Do you know how to write the idm-conf or other conf?
I can't solve the problem "Idm engine has not been initialized"

**Comment by revertXC** [comment]
I use V6.5.0 source code, flowable- UI-IDM.abnormal。

`Field identityService in org.flowable.ui.idm.conf.Bootstrapper required a bean of type 'org.flowable.idm.api.IdmIdentityService' that could not be found.`

**Comment by revertXC** [comment]
How do you solve this?

**Comment by revertXC** [comment]
Solved this problem by opening Flowable - UI-IDM with idea alone.
解决了，单独用idea打开flowable-ui-idm。

**Comment by tijsrademakers** [comment]
Hi @ProLeung ,
Please use the Flowable forum for questions. It's also helpful to provide context information on what you are trying to do.
Best regards

**Comment by duansheli** [comment]
@tijsrademakers the same problem revertXc

open flowable-source-6.4.2 project by idea 

run FlowableIdmApplication.main 
will also get IdmIdentityService not found
![image](https://user-images.githubusercontent.com/8579595/89312484-e3ed0580-d6a9-11ea-87f2-6f72c004bdf7.png)


but  use idea open flowable-ui-idm directory as root 
it runs successfully

why ??

**Comment by revertXC** [comment]
> @tijsrademakers the same problem revertXc
> 
> open flowable-source-6.4.2 project by idea
> 
> run FlowableIdmApplication.main
> will also get IdmIdentityService not found
> ![image](https://user-images.githubusercontent.com/8579595/89312484-e3ed0580-d6a9-11ea-87f2-6f72c004bdf7.png)
> 
> but use idea open flowable-ui-idm directory as root
> it runs successfully
> 
> why ??

应该是idea加载那个项目配置问题
