### ISSUE TITLE
Allow to restrict access for app on modeler UI

### ISSUE THREAD

**Issue by sibok666** [flowable/flowable-engine#241]
There will be a nice feature, that the modeler can create an app, and restrict the access on the task viewer app, because In an organization there will be certain apps only visibles for human resources, operation, or a combination of departaments, I think the main idea of this feature, is to provide the modeler the control over who can interact with the aplication.

**Comment by mickeydonkey** [comment]
+1for this feature

**Comment by sibok666** [comment]
Im working on this feature, I already added the field on the app definition form, and the fields are persisted correctly, but when Im triying to get the saved values, I cant.

@tijsrademakers  I will create a pull request and in this way you can see the code that I have done until today.

Best regards

**Comment by tijsrademakers** [comment]
Feature has been added (https://github.com/flowable/flowable-engine/commit/f8d542cbc04df4507dacfe202cf85e9e7aa35678)
