### ISSUE TITLE
flowable replace mysql to postgresql error

### ISSUE THREAD

**Issue by imzhudi0528** [flowable/flowable-engine#2416]
org.springframework.dao.DataIntegrityViolationException: Error attempting to get column 'thumbnail' from result set.  Cause: org.postgresql.util.PSQLException: 不良的类型值 long : \x89504e470d0a1a0a0000000d494844520000002d0000002d08060000003a1ae29a000002e04944415478daed58df6b526118dec52efa23ba080aeacff08f48747a5051f157f3d74c10744ca6178a8c5d0b42188b2e4236314b6585919814132744b46a3936e7c19b31aa63fec8aff71d79135dcc73bef38de03c7038777ecf7978bee77d5e1716142850f0ff821072addd6edbb3d9ecab442271eef178c626938968b55ac271dcd4e9740ec3e1f0613299dc82e7f69593cde5720f63b1d8d8e7f391743a4d1a8d06e976bb6430181004befbfd3ed9dbdb23f051c4ebf54efd7e7fc766b35999130672e6783cfe33180c5e109a4c26e4b268b55a24140a4dec76fb07b55a7d8b85ba8bf97cfea5c3e1208542612eb27fa3542a11b3d92cc8aa3a12ae56ab6fdd6e373938382034d0e97408082058add67bb290468591307a9426f0f740ed6f4b4b4b1c750fa3256829fc2fc50d06c31910bf432d25d6d7d787e86139512c1605bd5eff860ae9ededed479812a3d188c80d97cbc54bb609aa8c398cb1c602fbfbfb43c96ae3a4c3cb2725dae605c4200fd3f48668d2389a33990c6189cdcdcd1690be2f9a3476091ccd2c51afd73b40ba209a34969f5eafc79434cff37d207d2c9a34b6b559f961053c0f480f4493c67a7915c0734593361a8d53d64a0b82c04b521ae26ec8dad3a7a7a71f25797a7575f513ebf42897cbcf24a5472a95cab0cee9b5b5b5a2a49c8e4422379797977f319c88039d4ef745d24444acacac7c66d53dc01a5b40f8b5e49667b158d4814060cc40ed3350b9496d198025b42d779fc6fb832aab54aa452aa4d163b884cab5b9409bccc3193d6a9bcb0c1cc7e941f11fb477c49393931ad8e288fa8e38031474332ea1b414478591b046a309c9fadf071ca005d5cf777676be4bb89c671b1b1b0fd012f09898fcc3841e07855e805df866b329cc93c3954ae5317cf43bbc74d43d7c49f277913c54d83e2c0cef6bb5da51b7dbedcd4a16961fec12bbbbbb4fa3d1e873b0d721924575a9a58404af5f07d57c40e6093c5fb1a561bdfcf33ec62e81a359f2a453a0408102050ae4c66fb109509232650d3b0000000049454e44ae426082
; 不良的类型值 long : \x89504e470d0a1a0a0000000d494844520000002d0000002d08060000003a1ae29a000002e04944415478daed58df6b526118dec52efa23ba080aeacff08f48747a5051f157f3d74c10744ca6178a8c5d0b42188b2e4236314b6585919814132744b46a3936e7c19b31aa63fec8aff71d79135dcc73bef38de03c7038777ecf7978bee77d5e1716142850f0ff821072addd6edbb3d9ecab442271eef178c626938968b55ac271dcd4e9740ec3e1f0613299dc82e7f69593cde5720f63b1d8d8e7f391743a4d1a8d06e976bb6430181004befbfd3ed9dbdb23f051c4ebf54efd7e7fc766b35999130672e6783cfe33180c5e109a4c26e4b268b55a24140a4dec76fb07b55a7d8b85ba8bf97cfea5c3e1208542612eb27fa3542a11b3d92cc8aa3a12ae56ab6fdd6e373938382034d0e97408082058add67bb290468591307a9426f0f740ed6f4b4b4b1c750fa3256829fc2fc50d06c31910bf432d25d6d7d787e86139512c1605bd5eff860ae9ededed479812a3d188c80d97cbc54bb609aa8c398cb1c602fbfbfb43c96ae3a4c3cb2725dae605c4200fd3f48668d2389a33990c6189cdcdcd1690be2f9a3476091ccd2c51afd73b40ba209a34969f5eafc79434cff37d207d2c9a34b6b559f961053c0f480f4493c67a7915c0734593361a8d53d64a0b82c04b521ae26ec8dad3a7a7a71f25797a7575f513ebf42897cbcf24a5472a95cab0cee9b5b5b5a2a49c8e4422379797977f319c88039d4ef745d24444acacac7c66d53dc01a5b40f8b5e49667b158d4814060cc40ed3350b9496d198025b42d779fc6fb832aab54aa452aa4d163b884cab5b9409bccc3193d6a9bcb0c1cc7e941f11fb477c49393931ad8e288fa8e38031474332ea1b414478591b046a309c9fadf071ca005d5cf777676be4bb89c671b1b1b0fd012f09898fcc3841e07855e805df866b329cc93c3954ae5317cf43bbc74d43d7c49f277913c54d83e2c0cef6bb5da51b7dbedcd4a16961fec12bbbbbb4fa3d1e873b0d721924575a9a58404af5f07d57c40e6093c5fb1a561bdfcf33ec62e81a359f2a453a0408102050ae4c66fb109509232650d3b0000000049454e44ae426082; nested exception is org.postgresql.util.PSQLException: 不良的类型值 long : \x89504e470d0a1a0a0000000d494844520000002d0000002d08060000003a1ae29a000002e04944415478daed58df6b526118dec52efa23ba080aeacff08f48747a5051f157f3d74c10744ca6178a8c5d0b42188b2e4236314b6585919814132744b46a3936e7c19b31aa63fec8aff71d79135dcc73bef38de03c7038777ecf7978bee77d5e1716142850f0ff821072addd6edbb3d9ecab442271eef178c626938968b55ac271dcd4e9740ec3e1f0613299dc82e7f69593cde5720f63b1d8d8e7f391743a4d1a8d06e976bb6430181004befbfd3ed9dbdb23f051c4ebf54efd7e7fc766b35999130672e6783cfe33180c5e109a4c26e4b268b55a24140a4dec76fb07b55a7d8b85ba8bf97cfea5c3e1208542612eb27fa3542a11b3d92cc8aa3a12ae56ab6fdd6e373938382034d0e97408082058add67bb290468591307a9426f0f740ed6f4b4b4b1c750fa3256829fc2fc50d06c31910bf432d25d6d7d787e86139512c1605bd5eff860ae9ededed479812a3d188c80d97cbc54bb609aa8c398cb1c602fbfbfb43c96ae3a4c3cb2725dae605c4200fd3f48668d2389a33990c6189cdcdcd1690be2f9a3476091ccd2c51afd73b40ba209a34969f5eafc79434cff37d207d2c9a34b6b559f961053c0f480f4493c67a7915c0734593361a8d53d64a0b82c04b521ae26ec8dad3a7a7a71f25797a7575f513ebf42897cbcf24a5472a95cab0cee9b5b5b5a2a49c8e4422379797977f319c88039d4ef745d24444acacac7c66d53dc01a5b40f8b5e49667b158d4814060cc40ed3350b9496d198025b42d779fc6fb832aab54aa452aa4d163b884cab5b9409bccc3193d6a9bcb0c1cc7e941f11fb477c49393931ad8e288fa8e38031474332ea1b414478591b046a309c9fadf071ca005d5cf777676be4bb89c671b1b1b0fd012f09898fcc3841e07855e805df866b329cc93c3954ae5317cf43bbc74d43d7c49f277913c54d83e2c0cef6bb5da51b7dbedcd4a16961fec12bbbbbb4fa3d1e873b0d721924575a9a58404af5f07d57c40e6093c5fb1a561bdfcf33ec62e81a359f2a453a0408102050ae4c66fb109509232650d3b0000000049454e44ae426082
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440) ~[mybatis-spring-2.0.3.jar:2.0.3]
	at com.sun.proxy.$Proxy114.selectOne(Unknown Source) ~[?:?]
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:159) ~[mybatis-spring-2.0.3.jar:2.0.3]
	at org.flowable.ui.modeler.repository.ModelRepositoryImpl.get(ModelRepositoryImpl.java:42) ~[flowable-ui-modeler-logic-6.4.1.jar:6.4.1]
	at org.flowable.ui.modeler.service.ModelServiceImpl.getModel(ModelServiceImpl.java:112) ~[flowable-ui-modeler-logic-6.4.1.jar:6.4.1]
	at org.flowable.ui.modeler.service.ModelServiceImpl$$FastClassBySpringCGLIB$$93d99e9b.invoke(<generated>) ~

when i use api(app/rest/models)  show this error

**Comment by tijsrademakers** [comment]
Hi @imzhudi0528 ,
Can you elaborate on what you are trying to do and why in the title MySQL and Postgres are referenced? Let's continue the discussion on the Flowable forum.
Best regards
