### ISSUE TITLE
Please consider using your own namespace rather than `spring.flowable`

### ISSUE THREAD

**Issue by snicoll** [flowable/flowable-engine#244]
As described [in our documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming) please do not use the `spring` namespace for 3rd party contributions.

**Comment by tijsrademakers** [comment]
Thanks for the feedback. Are you referring to the FlowableProperties spring.flowable definition? Or also to the package naming of the flowable-spring-boot-starter-basic project? Would just flowable be ok to use instead in FlowableProperties?

**Comment by snicoll** [comment]
I am refering to the properties namespace, yes. We've asked you to change the package naming back in the Activity's days but I unfortunately didn't realize the configuration namespace was also affected by the problem. 

`flowable.*` sounds good to me.

**Comment by tijsrademakers** [comment]
Thanks, changed it

**Comment by snicoll** [comment]
wow, that was quick. Thanks!
