### ISSUE TITLE
Missing scopeDefinitionId for sentries in session logging

### ISSUE THREAD

**Issue by tiffmaelite** [flowable/flowable-engine#2458]
**Describe the bug**
NPE in `LoggingSessionUtil` line 76 (`loggingNode.put("scopeDefinitionId", itemNode.get("scopeDefinitionId").asText());`) when enabling session logging on a case with sentries.
Reason: for sentries, the `scopeDefinitionId` is not added to `loggingData`. I think it may also happen for other CMMN elements.

**Expected behavior**
- No exception
- The scopeDefinitionId is logged in addition to the scopeDefinitionKey for all CMMN elements

**Additional context**
Flowable engine version: 6.5.0

**Comment by tijsrademakers** [comment]
Merged the PR, thanks
