### ISSUE TITLE
NPE in session logging for variables having null value

### ISSUE THREAD

**Issue by tiffmaelite** [flowable/flowable-engine#2461]
**Describe the bug**
NPE in `VariableLoggingSessionUtil` line 133(`loggingNode.put(variableValueName, variableValue.toString())`) when enabling session logging and there are variables with a `null` value.

**Expected behavior**
- No exception
- Logged value is the String "null"

**Additional context**
Flowable engine version: 6.5.0

**Comment by tijsrademakers** [comment]
Merged the PR, thanks
