### ISSUE TITLE
ProcessDefinitionUtil.getBpmnModel will make NPE

### ISSUE THREAD

**Issue by ccoke** [flowable/flowable-engine#2480]
```
// ProcessDefinitionUtil.java
public static BpmnModel getBpmnModel(String processDefinitionId) {
        if (CommandContextUtil.getProcessEngineConfiguration() == null) {
            // when processEngineConfiguration() is null
            return Flowable5Util.getFlowable5CompatibilityHandler().getProcessDefinitionBpmnModel(processDefinitionId);
        } 
       // ...
 }
```
```
// Flowable5Util.java
public static Flowable5CompatibilityHandler getFlowable5CompatibilityHandler() {
        // this will throw NPE
        Flowable5CompatibilityHandler flowable5CompatibilityHandler = CommandContextUtil.getProcessEngineConfiguration().getFlowable5CompatibilityHandler(); 
        // ...
}
```

**Comment by iamKyun** [comment]
You must use this Util under a context that holding `CommandContext`. Because `CommandContextUtil.getProcessEngineConfiguration()` will try to get a  `CommandContext` in the thread.

**Comment by ccoke** [comment]
> You must use this Util under a context that holding `CommandContext`. Because `CommandContextUtil.getProcessEngineConfiguration()` will try to get a `CommandContext` in the thread.

I think you're right, but I mean there's a logic problem with the code itself.

**Comment by tijsrademakers** [comment]
Please use the RepositoryService getBpmnModel method instead.

Best regards
