### ISSUE TITLE
Script Task don't support skipExpression property?

### ISSUE THREAD

**Issue by GerryLon** [flowable/flowable-engine#2481]
![WXWorkCapture_15936561728763](https://user-images.githubusercontent.com/25873611/86308961-18a21300-bc4d-11ea-9b4e-67833b6bbcfe.png)

As picture above described, can not set "skip expression" property on script task.

**Comment by iamKyun** [comment]
It seems to be. I can't  find any skip checking in ScriptTaskActivityBehavior. I am afraid you have to extends it yourself if you want to do so.

**Comment by filiphr** [comment]
Thanks for the PR @4gsim
