### ISSUE TITLE
Create a new Event Registry deployment from REST api

### ISSUE THREAD

**Issue by thinkingmik** [flowable/flowable-engine#2484]
I'm using Flowable 6.5.0 with Apache Tomcat 9 and I'm trying to use `flowable-rest` for creating a new event registry deployment `/flowable-rest/event-registry-api/event-registry-repository/deployments`.

This is the raw request from Postman:
```
POST /flowable-rest/event-registry-api/event-registry-repository/deployments?deploymentName=myEvent HTTP/1.1
Host: localhost:8080
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Basic YWRtaW46dGVzdA==

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="/C:/temp/myEvent.event"
Content-Type: <Content-Type header here>

(data)
----WebKitFormBoundary7MA4YWxkTrZu0gW
```

I have used the [offcial documentation](https://flowable.com/open-source/docs/eventregistry/ch07-REST/#create-a-new-event-registry-deployment) for make the call, but the service gives me a `400` error:
```json
{
    "message": "Bad request",
    "exception": "File must be of type .event, .channel"
}
```

I have tried also directly with the `flowable-rest` swagger but it still the same result.

The uploaded file have the correct extension `.event`, Why I get this error? I'm missing something in the request header?

**Comment by filiphr** [comment]
Thanks for the issue @thinkingmik.

This has already been fixed on master with https://github.com/flowable/flowable-engine/commit/f5df25d5f4b74eb095fc498c48dc391514cb0573.

In the meantime you can use the BPMN API to create a deployment. Have a look at [this](https://flowable.com/open-source/docs/bpmn/ch15-REST/#create-a-new-deployment). You'll need to put your event in a `.zip` or `.bar` archive and deploy it.
