### ISSUE TITLE
execution.setVariable will change integer type to double type

### ISSUE THREAD

**Issue by leonal** [flowable/flowable-engine#2485]
**Describe the bug**
in script task , if you do "execution.setVariable('myVar',int1); " 
the myVar will be stored as double , here int1 is integer.

**Expected behavior**
the myVar should be integer , it should not convert to double type

**Comment by filiphr** [comment]
If `int1` is an integer then `myVar` cannot be a `double` type. Can you please create a small test cases showing the problem?

Are you using Javascript or Groovy in your Script Task? Perhaps the script converts integers to doubles

**Comment by leonal** [comment]
found the reason here : 

```
        case JSTYPE_NUMBER:
            if (type == ScriptRuntime.StringClass) {
                return ScriptRuntime.toString(value);
            }
            **else if (type == ScriptRuntime.ObjectClass) {
                return coerceToNumber(Double.TYPE, value);
            }**
            else if ((type.isPrimitive() && type != Boolean.TYPE) ||
                     ScriptRuntime.NumberClass.isAssignableFrom(type)) {
                return coerceToNumber(type, value);
            }
            else {
                reportConversionError(value, type);
            }
            break;
```

**Comment by filiphr** [comment]
So this is not a problem of Flowable, right?

**Comment by leonal** [comment]
yes, but need some way to avoid it.

**Comment by leonal** [comment]
the script judge the type according to type of argument in java method , but the setVariable only take the value parameters as Object. so the script think it should be Object type, by default the Object type for number is Double.

`public void setVariable(String variableName, Object value, boolean fetchAllVariables)`

any workaround for this problem ?

**Comment by filiphr** [comment]
Perhaps you can do something like: `execution.setVariable('myVar',java.lang.Integer.valueOf(int1))`.

Closing this since there isn't anything that we can do about this. Feel free to start a discussion on our [forum](https://forum.flowable.org/). Maybe someone from the community will have a better idea there.
