### ISSUE TITLE
Optimize code 

### ISSUE THREAD

**Issue by guyuegan** [flowable/flowable-engine#2488]
### hi, here is one extra db query can be optimized:

class path: org.flowable.ui.modeler.service.ModelService

![image](https://user-images.githubusercontent.com/33271199/86758890-bdba5280-c076-11ea-8548-7c3a4663268c.png)

**Comment by tijsrademakers** [comment]
Hi @guyuegan,
Are you referring to the List<ModelHistory> history = modelHistoryRepository.findByModelId(model.getId()); line?
Thanks

**Comment by guyuegan** [comment]
Yes exactly, by the way,  why design the code as follow, it does not make any sense 
![image](https://user-images.githubusercontent.com/33271199/86886543-b6a04c80-c129-11ea-837d-97223fa081fb.png)

tips: The two problems I mentioned start from here
![image](https://user-images.githubusercontent.com/33271199/86887424-164b2780-c12b-11ea-99f6-3bdea2108fee.png)

**Comment by 4gsim** [comment]
Pull request #2974

**Comment by filiphr** [comment]
Closing this, since it is invalid
