### ISSUE TITLE
6.5.0 JAR file's (Oracle) create SQL is missing several tables

### ISSUE THREAD

**Issue by mikezerosix** [flowable/flowable-engine#2497]
In 6.5.0 JAR file's create SQL file has references to several missing tables : 

* ACT_RU_IDENTITYLINK
* ACT_RU_TASK
* ACT_RU_VARIABLE
* ACT_RU_JOB
* ACT_RU_TIMER_JOB
* ACT_RU_SUSPENDED_JOB
* ACT_RU_DEADLETTER_JOB
* ACT_HI_VARINST
* ACT_HI_TASKINST

Given the amount of these missing tables identifyable by just references in the SQL file itself I suspect there are dozens more  missing tables as for example there is nothing related to identity managemnt in the SQL; Users or Groups. 

I mainly checked Oracle create script but at least some of the tables are missing from mysql create SQL too. 

I expect the 6.5.0 SQL create to be complete with all needed tables to run this  Floable version. 

**Source:** 
 .m2\repository\org\flowable\flowable-engine\6.5.0\flowable-engine-6.5.0.jar\org\flowable\db\create\flowable.oracle.create.engine.sql

**Duplicates (regresssion) bug in 6.4.0** : https://github.com/flowable/flowable-engine/issues/1763

**Comment by jbarrez** [comment]
The tables you are referencing are 'owned' by the respective service (task / job / variable / etc service).
For example, the task service sql can be found here: https://github.com/flowable/flowable-engine/tree/master/modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/create

When the databaseSchemaUpdate property is set to true, the engines + each service will create the tables automatically on bootup (using those .sql files).

In case you are looking for the combined sql scripts, these are part of the release zip in the sql folder.

**Comment by tijsrademakers** [comment]
Hi @mikezerosix ,

You are looking in the wrong place for the SQL scripts for these tables. We provide SQL scripts on a wider level in the Flowable distro download you can find here https://flowable.com/open-source/downloads/, but you can also find it here https://github.com/flowable/flowable-engine/tree/flowable-6.5.0/distro/sql/create. If you would to use the Flowable BPMN engine only, then you need the common sql script and the bpmn sql script. If you want all tables, including the CMMN engine and DMN engine tables you can also use the all sql script that has everything in one script.

Best regards

**Comment by mikezerosix** [comment]
tijsrademakers, Thank you very much for swift reply. 
D'oh ! 
I have gotten so used to bundling everything into the artifact that I jsut assumed it would be there and did not even think to look for elsewhere. Thanks again, you are a lifesaver.
