### ISSUE TITLE
Unnecessary png files committed to repository

### ISSUE THREAD

**Issue by dbmalkovsky** [flowable/flowable-engine#252]
In the [main .gitignore file](https://github.com/dbmalkovsky/flowable-engine/blob/master/.gitignore) the `userguide-dmn/src/en/output` directory is ignored but in the repository there are 3 png files committed to that directory:

* [li-chevron.png](https://github.com/dbmalkovsky/flowable-engine/blob/master/userguide-dmn/src/en/output/images/li-chevron.png)
* [logo.png](https://github.com/dbmalkovsky/flowable-engine/blob/master/userguide-dmn/src/en/output/images/logo.png)
* [logo@2x.png](https://github.com/dbmalkovsky/flowable-engine/blob/master/userguide-dmn/src/en/output/images/logo%402x.png)

In fact the whole directory should be removed.

**Comment by tijsrademakers** [comment]
removed folder, thanks
