### ISSUE TITLE
multiInstanceLoopCharacteristics use setCollectionString method, but the bpmn model not generated  flowable:collection

### ISSUE THREAD

**Issue by misskter** [flowable/flowable-engine#2528]
**Describe the bug**
I am using java code to create a flowable. After generating BPMN in this way, I have not generated the corresponding tag attribute in XML.multiInstanceLoopCharacteristics lose collection 

**Expected behavior**
I hope the collection property can be generated

Code:
    MultiInstanceLoopCharacteristics multiInstanceLoopCharacteristics = new MultiInstanceLoopCharacteristics();
    multiInstanceLoopCharacteristics.setSequential(false);
    multiInstanceLoopCharacteristics.setCollectionString("userSigns");
    multiInstanceLoopCharacteristics.setElementVariable("userSign");
    multiInstanceLoopCharacteristics.setCompletionCondition(CONDITION_AND_SIGN);
    UserTask userTask = new UserTask();
    userTask.setLoopCharacteristics(multiInstanceLoopCharacteristics);

<userTask id="UserTask1287926316116512770" name="审批1287926316124901377" flowable:assignee="${userSign}">
      <multiInstanceLoopCharacteristics isSequential="false" flowable:elementVariable="userSign">
        <completionCondition>${nrOfCompletedInstances/nrOfInstances &gt;= 1}</completionCondition>
      </multiInstanceLoopCharacteristics>
 </userTask>

**Additional context**
<flowable.version>6.4.2</flowable.version>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.1.1.RELEASE</version>
  </parent>

postgresql: 11

**Comment by tijsrademakers** [comment]
Hi,

You can use setInputDataItem instead of the setCollectionString method.
The collectionString is only used in very specific implementations where also a collection handler is set to do custom logic on the collection variable provided.

Best regards
