### ISSUE TITLE
Process Instance migration does not migrate User Tasks

### ISSUE THREAD

**Issue by travishaagen** [flowable/flowable-engine#2539]
**Describe the bug**
Process Instance migration does not appear to migrate User Tasks. I tested migration of Process Instances created in Activiti 5, which are then migrated in Flowable 6.5.0.

After invoking `org.flowable.engine.migration.ProcessInstanceMigrationBuilder#migrate`, records in `ACT_RU_TASK` show the old Process Definition ID in the `PROC_DEF_ID_` column.

Appears that `ACT_RU_IDENTITYLINK` table records are not being updated too, because I changed a `flowable:candidateGroups` element, on a `userTask`, and the change was not reflected. There could be other tables that need to be updated related to tasks.

Also, since `TaskDefinition` was removed in the past, but not in Activiti 5, we still needed the `formKey` field to be set in the `Task`, but it is somehow lost as well.

**Expected behavior**
When Process Instances are migrated to new Process Definitions, the Tasks associated with the Process Instance should also be migrated.

**Code**
I was able to find a (partial) work-around by doing the following:

```
...
                    migrationBuilder.migrate(processInstanceId);

                    FormService formService = processEngine.getFormService();
                    TaskService taskService = processEngine.getTaskService();
                    List<Task> tasks = taskService.createTaskQuery().processInstanceId(processInstanceId).list();
                    for (Task task : tasks) {
                        if (!processDefinitionId.equals(task.getProcessDefinitionId())) {
                            TaskEntityImpl taskEntity = (TaskEntityImpl) task;
                            taskEntity.setProcessDefinitionId(processDefinitionId);
                            if (taskEntity.getFormKey() == null) {
                                TaskFormData taskFormData = formService.getTaskFormData(task.getId());
                                taskEntity.setFormKey(taskFormData.getFormKey());
                            }
                            taskService.saveTask(taskEntity);
                        }
                    }
```

**Additional context**
Flowable 6.5.0

**Comment by tijsrademakers** [comment]
Hi @travishaagen,

The process instance migration support doesn't include Activiti / Flowable 5 process instances. It only supports process instance that are created with the v6 version of the Engine. 

Best regards

**Comment by travishaagen** [comment]
@tijsrademakers how can you assume this works for v6? has the database schema actually changed for `ACT_RU_TASK`?
