### ISSUE TITLE
Password typo in helm chart prevents modeler to communicate with idm

### ISSUE THREAD

**Issue by groundnuty** [flowable/flowable-engine#2540]
When you remove `xt` from the beginning of the value it works fine:
https://github.com/flowable/flowable-engine/blob/fc22b74913701b8c9246f0d88de0783cd2f16c95/k8s/flowable/templates/modeler.yaml#L121

**Comment by yvoswillens** [comment]
thanks for letting us know @groundnuty 
is fixed on master
