### ISSUE TITLE
DMN  DeployCmd does not consider latest date when checking for existing deployments - leading to unnecessary new DMN table versions

### ISSUE THREAD

**Issue by VonDerBeck** [flowable/flowable-engine#2551]
**Describe the bug**
Restarting a Spring Boot Application with the DMN Engine and DMN resources on classpath redeploys DMN tables, even if nothing has changed.

**Expected behavior**
Existing DMN tables are only redeployed, if the content differs from it's **latest** (!) version.

**Code**
Existing code of DeployCmd of DMN Engine:

        @Override
        public DmnDeployment execute(CommandContext commandContext) {

          DmnDeploymentEntity deployment = deploymentBuilder.getDeployment();

          deployment.setDeploymentTime(CommandContextUtil.getDmnEngineConfiguration().getClock().getCurrentTime());

          if (deploymentBuilder.isDuplicateFilterEnabled()) {

              List<DmnDeployment> existingDeployments = new ArrayList<>();
              if (deployment.getTenantId() == null || DmnEngineConfiguration.NO_TENANT_ID.equals(deployment.getTenantId())) {
                  List<DmnDeployment> deploymentEntities = new DmnDeploymentQueryImpl(CommandContextUtil.getDmnEngineConfiguration().getCommandExecutor()).deploymentName(deployment.getName()).listPage(0, 1);

The following query is incomplete:

    new DmnDeploymentQueryImpl(CommandContextUtil.getDmnEngineConfiguration().getCommandExecutor()).deploymentName(deployment.getName()).listPage(0, 1);

It should include ``orderByDeploymentTime().desc()`` and work similiar to the DeployCmd of the BPMN Engine:

    new DeploymentQueryImpl(processEngineConfiguration.getCommandExecutor())
                        .deploymentName(deployment.getName())
                        .orderByDeploymentTime().desc()
                        .listPage(0, 1);

**Additional context**
Flowable 6.5.0 including ``flowable-dmn-engine-6.5.0.jar``

**Comment by tijsrademakers** [comment]
Hi @VonDerBeck ,

Thanks for reporting the issue. This has been fixed with this commit now https://github.com/flowable/flowable-engine/commit/61c66fd9d3355f5dd739a7a9a220447cc99222e0

Best regards
