### ISSUE TITLE
when two or more engine run at the same time, local cache makes process definition no consistence

### ISSUE THREAD

**Issue by YJFinBJ** [flowable/flowable-engine#2555]
I deploy rest API and UI at the same time, when I use rest api to update process definition, because of local cache, process definition cached in UI engine doesn't be removed, so if visit from web ui, the process definition is still old status. for example, i suspend a process definition from rest api engine, but on the web ui, it is still active，but it indeed has been update to suspend status, there is a consistence trouble.  The same, if I deploy a HA cluster engine, separate spring container also has this problems, what's more ,the local cache do not has any evict strategy, that is, 
it will not expire

**Comment by tijsrademakers** [comment]
Hi,
When retrieving the latest process definition when starting a process instance by key (for example), the logic always checks the database if a new version has been deployed. So in the case of the separate REST API and UI applications like you are describing, still the correct latest process definition will be retrieved.
You refer to the local cache. Are you using the local cache directly in your code?

**Comment by YJFinBJ** [comment]
starting a process instance is always checks the db,  but when i get process  definition by definitionId，the logic will be first retrieve from the cache.  For detail, I show the code snippet as below, which in the flowable-engine module

```
public ProcessDefinition findDeployedProcessDefinitionById(String processDefinitionId) {
        if (processDefinitionId == null) {
            throw new FlowableIllegalArgumentException("Invalid process definition id : null");
        }

        // first try the cache, but it will never expire in another engine
        ProcessDefinitionCacheEntry cacheEntry = processDefinitionCache.get(processDefinitionId);
        ProcessDefinition processDefinition = cacheEntry != null ? cacheEntry.getProcessDefinition() : null;

        if (processDefinition == null) {
            processDefinition = processDefinitionEntityManager.findById(processDefinitionId);
            if (processDefinition == null) {
                throw new FlowableObjectNotFoundException("no deployed process definition found with id '" + processDefinitionId + "'", ProcessDefinition.class);
            }
            processDefinition = resolveProcessDefinition(processDefinition).getProcessDefinition();
        }
        return processDefinition;
    }
```

**Comment by tijsrademakers** [comment]
Correct, but getting a process definition by id means that you know exactly which definition you would like to retrieve. Often you first query for the latest process definitions and then start by id from this list. Then still you will have the correct latest process definition. Can you explain for which use case you see an issue?

**Comment by YJFinBJ** [comment]
one case.  I have start a process,  and then I use the suspend action api for this definition by Rest API engine,  and the db update the definition to suspend ,that's which we expected.

but I also deploy UI application use the same db with Rest API , they are flowable-ui-task and flowable-ui-admin,  as we know, flowable-ui-task will start another engine, but when I query this definition from UI， the processDefinition cannot be query correctly, because of the cache cannot be expire

![image](https://user-images.githubusercontent.com/9456217/91013586-7aae4180-e61a-11ea-99a7-9b17f12afc47.png)

**Comment by tijsrademakers** [comment]
I'm not able to read the information shared in the image I'm afraid. But the definition information shown in the Admin and Task UI won't come from the cache but from the database. So it's still not clear to me which problem you are describing.

**Comment by YJFinBJ** [comment]
sorry for shared image with chinese language, I share the image in English

![image](https://user-images.githubusercontent.com/9456217/91015909-826fe500-e61e-11ea-9fd2-d4e9328de05c.png)

as you can see ,   i have suspend this definition ,  but the 'Suspended' is still 'No' which is not consistent with db

**Comment by YJFinBJ** [comment]
sorry for shared image with chinese language, I share the image in English

![image](https://user-images.githubusercontent.com/9456217/91015909-826fe500-e61e-11ea-9fd2-d4e9328de05c.png)

as you can see ,   i have suspend this definition ,  but the 'Suspended' is still 'No' which is not consistent with db

**Comment by tijsrademakers** [comment]
Thanks for sharing the English version. Can you share an image of the database content showing that the suspended value of this process definition is different?

**Comment by YJFinBJ** [comment]
![image](https://user-images.githubusercontent.com/9456217/91115944-e3022f00-e6bd-11ea-978b-ea2a84ffd369.png)

![image](https://user-images.githubusercontent.com/9456217/91116130-3f654e80-e6be-11ea-97af-92b08d29ce58.png)

the first image shows the UI applications state, the second image shows the suspend vaule in db, '1' means not suspended, since UI application and Rest API are not the same engine,which another engine load from its cache

**Comment by YJFinBJ** [comment]
@tijsrademakers

**Comment by tijsrademakers** [comment]
Please have a look at the SuspensionState interface which is used for the suspended value:

https://github.com/flowable/flowable-engine/blob/89e7e42de1ca63d2fe574b20a381d3a29d837eb0/modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/db/SuspensionState.java#L20

The suspended_state column value is not a boolean or a 0,1 enum value. 1 means that the process definition is active just like it is displayed in the Flowable Admin tool.
