### ISSUE TITLE
Flowable email task : Email to should not be mandatory if email cc or email bcc is provided

### ISSUE THREAD

**Issue by hemalprajapati0312** [flowable/flowable-engine#2561]
**Describe the bug**
We are using flowable email task. We have one of the requirement where we are allowing user to provide only bcc  options. 
How ever flowable is throwing error that email to is mandatory.

**Expected behavior**
Email to should not b mandatory if Email cc or Email bcc is provided.

**Comment by dbmalkovsky** [comment]
One option would be to populate the "to" field with some address like `noreply@mycompany.com`.

If the team makes the decision to support this use case I think the code that needs to be modified is in `ExternalInvocationTaskValidator` around this [line](https://github.com/flowable/flowable-engine/blob/8fd551beaf27719bee48c70c87b62791b55afa5a/modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/impl/ExternalInvocationTaskValidator.java#L35).
```java
            if (fieldExtension.getFieldName().equals("to")) {
                toDefined = true;
            }
```
