### ISSUE TITLE
Read elementText of ExtensionElement is truncated

### ISSUE THREAD

**Issue by xausky** [flowable/flowable-engine#2568]
**Describe the bug**
Add ExtensionElement to the model Read elementText of ExtensionElement is truncated during the process

**Expected behavior**
elementText should be fully available

**Code**
```java
    public static void setAction(FlowElement flowElement, JsonNode action){
        ExtensionElement extensionElement = new ExtensionElement();
        extensionElement.setNamespace("workflow");
        extensionElement.setName("action");
        extensionElement.setNamespacePrefix("buildrun");
        extensionElement.setElementText(action.toString());
        flowElement.addExtensionElement(extensionElement);
    }

    public static JsonNode getAction(FlowElement flowElement){
        String actionJson = flowElement.getExtensionElements().get("action")
                .stream().findFirst().map(ExtensionElement::getElementText)
                .orElseThrow(() -> new CommonException("error.action.notFound"));
        try {
            return MAPPER.readTree(actionJson);
        } catch (IOException e) {
            throw new CommonException(e);
        }
    }
```

I use the above two methods to set and read additional JSON data. When creating the model, I used the setAction method and deployed the model. I hope that the data set by the setAction method can be correctly obtained in the getAction method during the process execution.

**Additional context**
Below is the version I used.
```xml
        <dependency>
            <groupId>org.flowable</groupId>
            <artifactId>flowable-spring-boot-starter</artifactId>
            <version>6.5.0</version>
        </dependency>
```

The actual JSON data is about 4k in size. Guess is related to this question https://github.com/FasterXML/woodstox/issues/22
The temporary solution is to modify the following code: org/flowable/bpmn/converter/util/BpmnXMLUtil.java:194
```java
                if (StringUtils.isNotEmpty(xtr.getText().trim())) {
                    extensionElement.setElementText(xtr.getText().trim());
                }
```
to
```java
                if (StringUtils.isNotEmpty(xtr.getText().trim())) {
                    if (extensionElement.getElementText() != null){
                        extensionElement.setElementText(extensionElement.getElementText() + xtr.getText().trim());
                    } else {
                        extensionElement.setElementText(xtr.getText().trim());
                    }
                }
```

**Comment by filiphr** [comment]
I think that this happens only when using the woodstox parser. If you remove that parser from the classpath then I think it works correctly. Can you please try that?

**Comment by xausky** [comment]
The test found that it was indeed a problem that occurred after the introduction of woodstox-core dependency, but this was introduced indirectly by com.netflix.eureka, and I don't know how to better solve this compatibility problem.

**Comment by lxl20200830** [comment]
We have the problem?How to reslove last?

**Comment by xausky** [comment]
@lxl20200830 The com.alibaba:fastjson dependency can cause this problem. If the com.alibaba:fastjson dependency can be removed, if not, the above patch can be used to fix it.

The temporary solution is to modify the following code: org/flowable/bpmn/converter/util/BpmnXMLUtil.java:194
```java
                if (StringUtils.isNotEmpty(xtr.getText().trim())) {
                    extensionElement.setElementText(xtr.getText().trim());
                }
```
to
```java
                if (StringUtils.isNotEmpty(xtr.getText().trim())) {
                    if (extensionElement.getElementText() != null){
                        extensionElement.setElementText(extensionElement.getElementText() + xtr.getText().trim());
                    } else {
                        extensionElement.setElementText(xtr.getText().trim());
                    }
                }
```

**Comment by tijsrademakers** [comment]
Closing the issue.
