### ISSUE TITLE
ACT_DE_MODEL and ACT_RE_MODEL Inconsistent 

### ISSUE THREAD

**Issue by boleixiongdi** [flowable/flowable-engine#2581]
**Describe the bug**

![2](https://user-images.githubusercontent.com/5225951/93663520-36885280-fa9b-11ea-99a2-884f14255e4d.png)
![1](https://user-images.githubusercontent.com/5225951/93663530-43a54180-fa9b-11ea-90d0-c94eeea853a8.png)

**Comment by tijsrademakers** [comment]
The ACT_DE_MODEL table is used by the Flowable Modeler to store the models. ACT_RE_MODEL is a legacy table and not used for any Engine or Modeler logic. So not sure why it's important that they are inconsistent. Closing the issue therefore, please provide more info if needed.
