### ISSUE TITLE
how to loop task for several user

### ISSUE THREAD

**Issue by sendreams** [flowable/flowable-engine#2582]
```
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:activiti="http://activiti.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath" targetNamespace="http://www.activiti.org/test">
  <process id="loopProcess" name="loopProcess" isExecutable="true">
    <startEvent id="startevent1" name="Start"></startEvent>
    <endEvent id="endevent1" name="End"></endEvent>
    <userTask id="loopTask" name="loopTask" activiti:async="true" activiti:candidateUsers="zn1,zn2,zn3"></userTask>
    <exclusiveGateway id="exclusivegateway1" name="Exclusive Gateway"></exclusiveGateway>
    <sequenceFlow id="flow1" sourceRef="loopTask" targetRef="exclusivegateway1"></sequenceFlow>
    <sequenceFlow id="flow2" sourceRef="exclusivegateway1" targetRef="endevent1">
      <conditionExpression xsi:type="tFormalExpression"><![CDATA[${feedback}]]></conditionExpression>
    </sequenceFlow>
    <sequenceFlow id="flow3" sourceRef="exclusivegateway1" targetRef="loopTask">
      <conditionExpression xsi:type="tFormalExpression"><![CDATA[${!feedback}]]></conditionExpression>
    </sequenceFlow>
    <sequenceFlow id="flow4" sourceRef="startevent1" targetRef="loopTask"></sequenceFlow>
  </process>
```

i have a loop task which should running by several user. then i set the task's candidateUsers to 'zn1,zn2,zn3', 
the below code to create users.
```
        @Override
	protected void createMembership(){
		IdentityService identityService = rule.getIdentityService();
		
		User zn1 = identityService.newUser("zn1");
		zn1.setFirstName("zn");
		zn1.setLastName("1");
		zn1.setDisplayName("zn1");
		zn1.setEmail("dianxin@126.com");
		identityService.saveUser(zn1);
		
		User zn2 = identityService.newUser("zn2");
		zn2.setFirstName("zn");
		zn2.setLastName("2");
		zn2.setDisplayName("zn2");
		zn2.setEmail("liantong@126.com");
		identityService.saveUser(zn2);
		
		User zn3 = identityService.newUser("zn3");
		zn3.setFirstName("zn");
		zn3.setLastName("3");
		zn3.setEmail("tieta@126.com");
		zn3.setDisplayName("zn3");
		identityService.saveUser(zn3);
		
		Group znbm = identityService.newGroup("WF_ZNBM");
		znbm.setName("职能部门");
		znbm.setType("znbm");
		identityService.saveGroup(znbm);
		
		identityService.createMembership(zn1.getId(), znbm.getId());
		identityService.createMembership(zn2.getId(), znbm.getId());
		identityService.createMembership(zn3.getId(), znbm.getId());
	}
```

```
	@Test
	public void testForLoop() {
		Map<String, Object> vars = new HashMap<>();
		vars.put("id", "1");

//		zn1,zn2,zn3
		ProcessInstance ins = runtimeService.startProcessInstanceByKey("loopProcess", "1", vars);
		List<String> ids = runtimeService.getActiveActivityIds(ins.getId());
		System.out.println(String.join(",", ids));

		String[] usrIds = new String[] { "zn1", "zn2", "zn3" };    // userids 
		for (int i = 0; i < 3; i++) {
			List<Task> list = taskService.createTaskQuery().taskCandidateUser(usrIds[i]).list();
			System.out.println(list.size());
//			taskService.complete(zn.getId());
		}
		
		Task tFinish = taskService.createTaskQuery().taskCandidateGroup("WF_XXW").singleResult();
		if (tFinish != null) {
			taskService.complete(tFinish.getId());
		}
	}
```

after start process, then query each user's task , the query result is always empty, i don't understand for it. is any wrong here?

using 6.5.0.  Any help will be gratefully received.

**Comment by sendreams** [comment]
` <process id="loopProcess" name="loopProcess" isExecutable="true">
    <startEvent id="startevent1" name="Start"></startEvent>
    <endEvent id="endevent1" name="End"></endEvent>
    <userTask id="loopTask" name="循环任务" activiti:async="true" activiti:assignee="${assignee}">
      <multiInstanceLoopCharacteristics isSequential="false" activiti:collection="assigneeList" activiti:elementVariable="assignee"></multiInstanceLoopCharacteristics>
    </userTask>
    <sequenceFlow id="flow3" sourceRef="startevent1" targetRef="loopTask"></sequenceFlow>
    <sequenceFlow id="flow4" sourceRef="loopTask" targetRef="endevent1"></sequenceFlow>
  </process>`

i change the userTask to  add multiInstanceLoopCharacteristics, 

start process with variable.
`Map<String, Object> vars = new HashMap<>();
		String[] usrIds = new String[] { "zn1", "zn2", "zn3" };
		vars.put("assigneeList", Arrays.asList(usrIds));
//		zn1,zn2,zn3
		ProcessInstance ins = runtimeService.startProcessInstanceByKey("loopProcess", "1", vars);
		List<String> ids = runtimeService.getActiveActivityIds(ins.getId());
		System.out.println(String.join(",", ids));
		
		for (int i = 0; i < 3; i++) {
			Task t = taskService.createTaskQuery().taskCandidateUser(usrIds[i]).singleResult();   // the task always return null.
			taskService.complete(t.getId());    
		}`

**Comment by sendreams** [comment]
Task t = taskService.createTaskQuery().taskAssignee(usrIds[i]).singleResult();   // task always null.

**Comment by sendreams** [comment]
Very weird, the unit test code can't working, but if move the code to spring controller,  the process is ok. It's the first time I've come across such a thing

**Comment by sendreams** [comment]
using junit5, the test result is same to junit4,  i think there has some bug here.

`@FlowableTest
//@ConfigurationResource("flowable.cfg.xml")
@SuppressWarnings("unused")
public class LoopJUnit5Test {
	private ProcessEngine processEngine;
	private RuntimeService runtimeService;
	private TaskService taskService;
	private RepositoryService repositoryService;
	private IdentityService identityService;

	@BeforeEach
	public void setUp(ProcessEngine processEngine) {
		this.processEngine = processEngine;
		this.runtimeService = processEngine.getRuntimeService();
		this.taskService = processEngine.getTaskService();
		this.repositoryService = processEngine.getRepositoryService();
		this.identityService = processEngine.getIdentityService();
		
		createMembership();
	}
	
	protected void createMembership(){
		User zn1 = identityService.newUser("zn1");
		zn1.setFirstName("zn");
		zn1.setLastName("1");
		zn1.setDisplayName("zn1");
		zn1.setEmail("dianxin@126.com");
		identityService.saveUser(zn1);
		
		User zn2 = identityService.newUser("zn2");
		zn2.setFirstName("zn");
		zn2.setLastName("2");
		zn2.setDisplayName("zn2");
		zn2.setEmail("liantong@126.com");
		identityService.saveUser(zn2);
		
		User zn3 = identityService.newUser("zn3");
		zn3.setFirstName("zn");
		zn3.setLastName("3");
		zn3.setEmail("tieta@126.com");
		zn3.setDisplayName("zn3");
		identityService.saveUser(zn3);
		
		Group znbm = identityService.newGroup("WF_ZNBM");
		znbm.setName("职能部门");
		znbm.setType("znbm");
		identityService.saveGroup(znbm);
		
		identityService.createMembership(zn1.getId(), znbm.getId());
		identityService.createMembership(zn2.getId(), znbm.getId());
		identityService.createMembership(zn3.getId(), znbm.getId());
	}

	@Test
	@Deployment(resources = { "processes/loopProcess.bpmn" })
	public void testLoop() {
//		String deploymentId = repositoryService.createDeploymentQuery().singleResult().getId();
//		List<String> deploymentResources = repositoryService.getDeploymentResourceNames(deploymentId);

		Map<String, Object> vars = new HashMap<>();
		String[] usrIds = new String[] { "zn1", "zn2", "zn3" };
		vars.put("assigneeList", Arrays.asList(usrIds));
		ProcessInstance ins = runtimeService.startProcessInstanceByKey("loopProcess", "1", vars);
		List<String> ids = runtimeService.getActiveActivityIds(ins.getId());
		System.out.println(String.join(",", ids));

		for (int i = 0; i < 3; i++) {
			Task t = taskService.createTaskQuery().taskAssignee(usrIds[i]).singleResult();  // always null, and the ACT_RU_TASK table in h2 is absolutely empty.
			taskService.complete(t.getId());
		}
	}
}`

**Comment by filiphr** [comment]
Please don't use the issue tracker for asking questions. Please use the [Flowable OSS Forum](https://forum.flowable.org/) for that.

The reason why it is not working for you is because you have marked the user task as `async`. This means that the user task will be created in another thread, after the process instance has been started. I would suggest removing that from there. It might be that the async executor is disabled during your tests. 

Please try out without the async flag and continue your discussion on the Forum if it isn't working.
