### ISSUE TITLE
Can not execute 'move' and 'moveToHistoryJob' on BPMN and CMMN job resource

### ISSUE THREAD

**Issue by reva** [flowable/flowable-engine#2584]
**Describe the bug**
The JobResource (REST API) for BPMN and CMMN does not allow to execute the 'move' or 'moveToHistoryJob' action anymore

**Expected behavior**
Dead letter jobs should be movable through the rest api

PR follows

**Comment by tijsrademakers** [comment]
Merged the PR, thanks Valentin
