### ISSUE TITLE
IdentityService does not correctly create membership when used in TaskListener::notify()

### ISSUE THREAD

**Issue by oberlatz** [flowable/flowable-engine#26]
This is my first issue report on github. I hope the description contains enough details and is structured in a way to add value to your project.

I have recently migrated a project from activiti 6.0.0.Beta2 to 6.0.0.Beta3. The new version breaks a functionality which is using the _IdentityService_ to create groups and group memberships from within the _notify(DelegateTask delegateTask)_ function of a _TaskListener_.

The attached test project ([reproduce-issue.tar.gz](https://github.com/flowable/flowable-engine/files/550498/reproduce-issue.tar.gz)) reproduces the issue. 
The test project:
- is a spring-boot project integrating activiti 6.0.0.Beta4 with a H2 database.
- contains a test class showing that using the _IdentityService_ directly to create a group and group memberships **is working as expected**.
- contains a test class showing that creating a group and group memberships through a _TaskListener::notify(DelegateTask delegateTask)_ **does not persist all group members**.
- can be executed with "mvn clean verify"

It seems to me that, if calling IdentityService::createMembership(), only the last member is persisted in the failing scenario.

**Comment by jbarrez** [comment]
Hi @oberlatz : perfect issue. If all issues were this detailed ... life would be a lot easier ;-)

I do indeed see that it fails with beta4. However, it doesn't fail on the current master branch. I'll investigate what has changed there (as I don't see a particular commit in this area) and report back here.

**Comment by oberlatz** [comment]
Hi @jbarrez, thanks for the fast feedback! I appreciate the activiti fork and look forward to flowable 6.0.0.Beta5!

**Comment by jbarrez** [comment]
@oberlatz : added your tests to the Spring test suite (we were working in the area of identities and transactions), see https://github.com/flowable/flowable-engine/commit/8dccb0c588acb47b324a914e05da22d12f282b19. Will be added to master soon.
