### ISSUE TITLE
Spring boot separate datasource

### ISSUE THREAD

**Issue by jisqaqov** [flowable/flowable-engine#261]
Hello. Currently flowable bpm uses default database of my application in spring boot. What i want is to point bpm that it should work in separate datasource.
Earlier you already faced this problem : https://community.alfresco.com/thread/224893-activiti-with-spring-boot-and-two-datasources;

---------------------------------------------------------
trademak
26.08.2015 8:59
In the process engine configuration you can specify the datasource name. But in combination with Spring Boot I don't know the answer immediately. Did you look into the source code, how the Activiti process engine configuration is created with Activiti Spring Boot?
---------------------------------------------------------

**Comment by tijsrademakers** [comment]
Indeed, by default the datasource of the Spring boot application is used. You can override this with a SpringProcessEngineConfiguration that points to another data source. But, that would mean that you need JTA transactions because you are working with multiple data sources.

**Comment by jisqaqov** [comment]
Thanks. But i have a problem my spring beans is not injected by @Autowired when i use application context file with flowable configurations. At lease could you please provide any example.
Another way is to scan for configuration file when spring boot starts.
