### ISSUE TITLE
Spring Boot bug

### ISSUE THREAD

**Issue by jisqaqov** [flowable/flowable-engine#262]
Good day. I could launch my app with activiti bpm. Unfortunately can not lunch with flowable bpm.
Below is my stack trace:

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/zhandos.zharilkasynu/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-log4j12/1.7.21/7238b064d1aba20da2ac03217d700d91e02460fa/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/zhandos.zharilkasynu/.m2/repository/ch/qos/logback/logback-classic/1.1.7/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Detected both log4j-over-slf4j.jar AND bound slf4j-log4j12.jar on the class path, preempting StackOverflowError. 
SLF4J: See also http://www.slf4j.org/codes.html#log4jDelegationLoop for more details.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:72)

**Comment by jisqaqov** [comment]
**My dependencies in gradle:**

compile('org.flowable:flowable-spring-boot-starter-basic:6.0.0')
compile('org.flowable:flowable-spring-boot-starter-rest-api:6.0.0')
compile('org.flowable:flowable-spring-boot-starter-actuator:6.0.0')
compile('org.flowable:flowable-spring-boot-starter-jpa:6.0.0')

**Comment by tijsrademakers** [comment]
Should be fixed with this commit: https://github.com/flowable/flowable-engine/commit/d094a5dd2f5ec91888cca0a20a65a8cba998ac4a
