### ISSUE TITLE
Postgres UI applications problem

### ISSUE THREAD

**Issue by jisqaqov** [flowable/flowable-engine#263]
Hello.
When i started working with h2 database in ui applications like task, admin everything was fine.
Unfortunately, when i changed default database to postgres i could not make applications to work.
I can see that engine created tables though. I placed jdbc postgres driver also.
I think i made all correct.
My logs from Tomcat:

23-Feb-2017 11:04:17.784 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive C:\BSB\Program Files\apache-tomcat-8.5.5\webapps\flowable-idm.war
23-Feb-2017 11:04:17.784 WARNING [localhost-startStop-1] org.apache.catalina.startup.SetContextPropertiesRule.begin [SetContextPropertiesRule]{Context} Setting property 'debug' to '100' did not find a matching property.
23-Feb-2017 11:04:20.234 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
23-Feb-2017 11:04:20.234 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/flowable-idm] startup failed due to previous errors

Finally my flowable-ui-app.properties file:

datasource.driver=org.postgresql.Driver
datasource.url=jdbc:postgresql://localhost:5432/sp?currentSchema=flowable

datasource.username=flowable
datasource.password=flowable

By the way. You also can see that engine creates tables in two different schemas in "flowable" and "public".
I hope you will fix bugs.

![flowable postgres](https://cloud.githubusercontent.com/assets/20530024/23257465/2d0016fa-f9ee-11e6-9814-3eb65ee608e5.png)

**Comment by tijsrademakers** [comment]
Fixed by commit https://github.com/flowable/flowable-engine/commit/a04e07622f226181f90cc548159f252410e91dd0

**Comment by jisqaqov** [comment]
Could you tell me when this fix will be released?

**Comment by tijsrademakers** [comment]
We plan to release a 6.0.1 within a couple of weeks.
