### ISSUE TITLE
about signalcatchevent lifecycle

### ISSUE THREAD

**Issue by impl1874** [flowable/flowable-engine#2642]
![image](https://user-images.githubusercontent.com/11623035/95559235-07398580-0a4a-11eb-9411-208cb0880adf.png)

when A evnet trigger complete,B run complete,C runing.I can still trigger A.
i  want to know the usage scenarios designed in this way, I think it is better for A to be triggered only once

**Comment by impl1874** [comment]
like camunda Message Intermediate Catching Event

**Comment by filiphr** [comment]
Can you please share your BPMN XML?

**Comment by tijsrademakers** [comment]
Hi @impl1874 ,
You can make the service task async and then the message event will not be available anymore even if the service task is taking seconds to complete.
Best regards

**Comment by impl1874** [comment]
@filiphr thanks,format youself please.
`<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:activiti="http://activiti.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath" targetNamespace="http://www.activiti.org/test">`
`  <signal id="APP.START" name="APP.START"></signal>`
`  <signal id="APP.SAYYES" name="APP.SAYYES"></signal>`
`  <signal id="APP.SAYHI" name="APP.SAYHI"></signal>`
`  <process id="startupChild" name="startupChild" isExecutable="true">`
`    <startEvent id="startevent1" name="Start"></startEvent>`
`    <serviceTask id="servicetask1" name="sayHi" activiti:expression="${startService.sayHi()}"></serviceTask>`
`    <intermediateCatchEvent id="signalintermediatecatchevent1" name="SignalCatchEvent">`
`      <signalEventDefinition signalRef="APP.SAYHI"></signalEventDefinition>`
`    </intermediateCatchEvent>`
`    <sequenceFlow id="flow1" sourceRef="startevent1" targetRef="signalintermediatecatchevent1"></sequenceFlow>`
`    <sequenceFlow id="flow2" sourceRef="signalintermediatecatchevent1" targetRef="servicetask1"></sequenceFlow>`
`    <sequenceFlow id="flow3" sourceRef="servicetask1" targetRef="servicetask2"></sequenceFlow>`
`    <serviceTask id="servicetask2" name="sleep" activiti:expression="${startService.sleep(10)}"></serviceTask>`
`    <endEvent id="endevent1" name="End"></endEvent>`
`    <sequenceFlow id="flow8" sourceRef="servicetask2" targetRef="endevent1"></sequenceFlow>`
`  </process>`
`  <bpmndi:BPMNDiagram id="BPMNDiagram_startupChild">
    <bpmndi:BPMNPlane bpmnElement="startupChild" id="BPMNPlane_startupChild">
      <bpmndi:BPMNShape bpmnElement="startevent1" id="BPMNShape_startevent1">
        <omgdc:Bounds height="35.0" width="35.0" x="99.0" y="300.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="servicetask1" id="BPMNShape_servicetask1">
        <omgdc:Bounds height="55.0" width="105.0" x="300.0" y="290.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="signalintermediatecatchevent1" id="BPMNShape_signalintermediatecatchevent1">
        <omgdc:Bounds height="35.0" width="35.0" x="220.0" y="300.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="servicetask2" id="BPMNShape_servicetask2">
        <omgdc:Bounds height="55.0" width="105.0" x="460.0" y="290.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="endevent1" id="BPMNShape_endevent1">
        <omgdc:Bounds height="35.0" width="35.0" x="610.0" y="300.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="flow1" id="BPMNEdge_flow1">
        <omgdi:waypoint x="134.0" y="317.0"></omgdi:waypoint>
        <omgdi:waypoint x="220.0" y="317.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow2" id="BPMNEdge_flow2">
        <omgdi:waypoint x="255.0" y="317.0"></omgdi:waypoint>
        <omgdi:waypoint x="300.0" y="317.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow3" id="BPMNEdge_flow3">
        <omgdi:waypoint x="405.0" y="317.0"></omgdi:waypoint>
        <omgdi:waypoint x="460.0" y="317.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow8" id="BPMNEdge_flow8">
        <omgdi:waypoint x="565.0" y="317.0"></omgdi:waypoint>
        <omgdi:waypoint x="610.0" y="317.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>`

**Comment by impl1874** [comment]
> Hi @impl1874 ,
> You can make the service task async and then the message event will not be available anymore even if the service task is taking seconds to complete.
> Best regards

thanks,testing.

**Comment by impl1874** [comment]
@tijsrademakers 
service task async,like this:
`<serviceTask id="servicetask1" name="sayHi" activiti:async="true" activiti:expression="${startService.sayHi()}"></serviceTask>`

but,add async after,the service task can't execute.
I used the same method to test in ac5.15 and 5.23, the event can be invalid after trigger

my config file
## activiti5.15:jobExecutor
<bean id="taskExecutor" class="org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor">
		<property name="corePoolSize" value="4" />
		<property name="maxPoolSize" value="8" />
		<property name="threadNamePrefix" value="task-thread-pool-" />
	</bean>
	<bean id="jobExecutor" class="org.activiti.spring.SpringJobExecutor">
		<property name="taskExecutor" ref="taskExecutor" />
		<property name="waitTimeInMillis" value="999" />
	</bean>

	<bean id="activitiTransactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
		<property name="dataSource" ref="activitiDataSource" />
	</bean>

	<bean id="activitiJdbcTemplate" class="org.springframework.jdbc.core.JdbcTemplate">
		<property name="dataSource" ref="activitiDataSource" />
	</bean>

	<bean id="processEngineConfiguration" class="org.activiti.spring.SpringProcessEngineConfiguration">
		<property name="jobExecutor" ref="jobExecutor" />
		<property name="dataSource" ref="activitiDataSource" />
		<property name="transactionManager" ref="activitiTransactionManager" />
		<property name="jobExecutorActivate" value="true" />
		<property name="databaseSchemaUpdate" value="true" />
		<property name="createDiagramOnDeploy" value="false" />
		<property name="enableSafeBpmnXml" value="false" />
		<property name="history" value="audit" />
	</bean>

	<bean id="processEngine" class="org.activiti.spring.ProcessEngineFactoryBean">
		<property name="processEngineConfiguration" ref="processEngineConfiguration" />
	</bean>

	<bean id="repositoryService" factory-bean="processEngine" factory-method="getRepositoryService" />
	<bean id="runtimeService" factory-bean="processEngine" factory-method="getRuntimeService" />
	<bean id="taskService" factory-bean="processEngine" factory-method="getTaskService" />
	<bean id="historyService" factory-bean="processEngine" factory-method="getHistoryService" />
	<bean id="managementService" factory-bean="processEngine" factory-method="getManagementService" />


## activiti5.23:asyncExecutor
<bean id="activitiTransactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
		<property name="dataSource" ref="activitiDataSource" />
	</bean>

	<bean id="activitiJdbcTemplate" class="org.springframework.jdbc.core.JdbcTemplate">
		<property name="dataSource" ref="activitiDataSource" />
	</bean>

	<bean id="processEngineConfiguration" class="org.activiti.spring.SpringProcessEngineConfiguration">
		<property name="dataSource" ref="activitiDataSource" />
		<property name="transactionManager" ref="activitiTransactionManager" />
		<property name="jobExecutorActivate" value="false" />
		<property name="asyncExecutorEnabled" value="true" />
		<property name="asyncExecutorActivate" value="true" />
		<property name="createDiagramOnDeploy" value="false" />
		<property name="enableSafeBpmnXml" value="false" />
		
		<property name="history" value="none" />
		<property name="asyncExecutor" ref="asyncExecutor" />
		<property name="databaseSchemaUpdate" value="true" />
	</bean>

	<bean id="asyncExecutor" class="org.activiti.engine.impl.asyncexecutor.DefaultAsyncJobExecutor">
		<property name="corePoolSize" value="10" />
		<property name="maxPoolSize" value="5000" />
		<property name="keepAliveTime" value="3000" />
		<property name="queueSize" value="20000" />
		<property name="maxTimerJobsPerAcquisition" value="2" />
		<property name="maxAsyncJobsDuePerAcquisition" value="2" />
		<property name="defaultAsyncJobAcquireWaitTimeInMillis" value="1000" />
		<property name="defaultTimerJobAcquireWaitTimeInMillis" value="1000" />
		<property name="timerLockTimeInMillis" value="60000" />
		<property name="asyncJobLockTimeInMillis" value="60000" />
	</bean>

	<bean id="processEngine" class="org.activiti.spring.ProcessEngineFactoryBean">
		<property name="processEngineConfiguration" ref="processEngineConfiguration" />
	</bean>

	<bean id="repositoryService" factory-bean="processEngine" factory-method="getRepositoryService" />
	<bean id="runtimeService" factory-bean="processEngine" factory-method="getRuntimeService" />
	<bean id="taskService" factory-bean="processEngine" factory-method="getTaskService" />
	<bean id="historyService" factory-bean="processEngine" factory-method="getHistoryService" />
	<bean id="managementService" factory-bean="processEngine" factory-method="getManagementService" />


## flowable6.5:asyncExecutor
<bean id="activitiTransactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
		<property name="dataSource" ref="activitiDataSource" />
	</bean>

	<bean id="activitiJdbcTemplate" class="org.springframework.jdbc.core.JdbcTemplate">
		<property name="dataSource" ref="activitiDataSource" />
	</bean>

	<bean id="processEngineConfiguration" class="org.flowable.spring.SpringProcessEngineConfiguration">
		<property name="dataSource" ref="activitiDataSource" />
		<property name="transactionManager" ref="activitiTransactionManager" />
		<property name="asyncExecutorActivate" value="true" />
		<property name="createDiagramOnDeploy" value="false" />
		<property name="enableSafeBpmnXml" value="false" />
		<property name="history" value="audit" />
		<property name="asyncExecutor" ref="asyncExecutor" />
		<property name="databaseSchemaUpdate" value="true" />
	</bean>

	<bean id="asyncExecutor" class="org.flowable.job.service.impl.asyncexecutor.DefaultAsyncJobExecutor">
		<property name="corePoolSize" value="10" />
		<property name="maxPoolSize" value="5000" />
		<property name="keepAliveTime" value="3000" />
		<property name="queueSize" value="20000" />
		<property name="maxTimerJobsPerAcquisition" value="2" />
		<property name="maxAsyncJobsDuePerAcquisition" value="2" />
		<property name="defaultAsyncJobAcquireWaitTimeInMillis" value="1000" />
		<property name="defaultTimerJobAcquireWaitTimeInMillis" value="1000" />
		<property name="timerLockTimeInMillis" value="60000" />
		<property name="asyncJobLockTimeInMillis" value="60000" />
	</bean>

	<bean id="processEngine" class="org.flowable.spring.ProcessEngineFactoryBean">
		<property name="processEngineConfiguration" ref="processEngineConfiguration" />
	</bean>

	<bean id="repositoryService" factory-bean="processEngine" factory-method="getRepositoryService" />
	<bean id="runtimeService" factory-bean="processEngine" factory-method="getRuntimeService" />
	<bean id="taskService" factory-bean="processEngine" factory-method="getTaskService" />
	<bean id="historyService" factory-bean="processEngine" factory-method="getHistoryService" />
	<bean id="managementService" factory-bean="processEngine" factory-method="getManagementService" />

## BPMN
`<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:activiti="http://activiti.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath" targetNamespace="http://www.activiti.org/test">`
`  <signal id="APP.START" name="APP.START"></signal>`
`  <signal id="APP.SAYYES" name="APP.SAYYES"></signal>`
`  <signal id="APP.SAYHI" name="APP.SAYHI"></signal>`
`  <process id="startupChild" name="startupChild" isExecutable="true">`
`    <startEvent id="startevent1" name="Start"></startEvent>`
`    <serviceTask id="servicetask1" name="sayHi" activiti:async="true" activiti:expression="${startService.sayHi()}"></serviceTask>`
`    <intermediateCatchEvent id="signalintermediatecatchevent1" name="SignalCatchEvent">`
`      <signalEventDefinition signalRef="APP.SAYHI"></signalEventDefinition>`
`    </intermediateCatchEvent>`
`    <sequenceFlow id="flow1" sourceRef="startevent1" targetRef="signalintermediatecatchevent1"></sequenceFlow>`
`    <sequenceFlow id="flow2" sourceRef="signalintermediatecatchevent1" targetRef="servicetask1"></sequenceFlow>`
`    <sequenceFlow id="flow3" sourceRef="servicetask1" targetRef="servicetask2"></sequenceFlow>`
`    <serviceTask id="servicetask2" name="sleep" activiti:expression="${startService.sleep(10)}"></serviceTask>`
`    <endEvent id="endevent1" name="End"></endEvent>`
`    <sequenceFlow id="flow8" sourceRef="servicetask2" targetRef="endevent1"></sequenceFlow>`
`  </process>`
`  <bpmndi:BPMNDiagram id="BPMNDiagram_startupChild">
    <bpmndi:BPMNPlane bpmnElement="startupChild" id="BPMNPlane_startupChild">
      <bpmndi:BPMNShape bpmnElement="startevent1" id="BPMNShape_startevent1">
        <omgdc:Bounds height="35.0" width="35.0" x="99.0" y="300.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="servicetask1" id="BPMNShape_servicetask1">
        <omgdc:Bounds height="55.0" width="105.0" x="300.0" y="290.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="signalintermediatecatchevent1" id="BPMNShape_signalintermediatecatchevent1">
        <omgdc:Bounds height="35.0" width="35.0" x="220.0" y="300.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="servicetask2" id="BPMNShape_servicetask2">
        <omgdc:Bounds height="55.0" width="105.0" x="460.0" y="290.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="endevent1" id="BPMNShape_endevent1">
        <omgdc:Bounds height="35.0" width="35.0" x="610.0" y="300.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="flow1" id="BPMNEdge_flow1">
        <omgdi:waypoint x="134.0" y="317.0"></omgdi:waypoint>
        <omgdi:waypoint x="220.0" y="317.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow2" id="BPMNEdge_flow2">
        <omgdi:waypoint x="255.0" y="317.0"></omgdi:waypoint>
        <omgdi:waypoint x="300.0" y="317.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow3" id="BPMNEdge_flow3">
        <omgdi:waypoint x="405.0" y="317.0"></omgdi:waypoint>
        <omgdi:waypoint x="460.0" y="317.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow8" id="BPMNEdge_flow8">
        <omgdi:waypoint x="565.0" y="317.0"></omgdi:waypoint>
        <omgdi:waypoint x="610.0" y="317.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>`
