### ISSUE TITLE
ACT RU ENTITY LINK Select Slow read

### ISSUE THREAD

**Issue by urwah1996** [flowable/flowable-engine#2654]
**Problem:**
Recently we enabled entity link in process engine configuration as we are using call activities in alot of our processes. After enabling the entity link every thing was working fine for a few days. Then we started getting reports from our users about the slow responses of flowable when they tried to get the next task. After doing some rnd we saw that the entity link select query is taking a lot time as can be seen in the screen shot below:
![image](https://user-images.githubusercontent.com/25527900/95881384-f6fb1080-0d91-11eb-8d8d-4a28443e8eb7.png)
we have peak times during 4-8pm, during this time the query is taking more than 1 second. 

**Solution**
We checked and found out that entitylink table doesnt have indexes on `ref_scope_id_` and `ref_scope_type` which is causing a full table scan. Currently the table has more than 300,000 rows. As more rows will come in future so this response time will keep increasing. **An index on the above two field will solve our problem.** **So we want to have an index in the migrations, so that when we upgrade to the latest version, we will get the index.**

**Describe alternatives you've considered**
We are currently thinking of truncating the table to decrease response times. And we are also thinking to create cron jobs for deleting process instances which were not solved by our users for more than 2 hours (our usecase dont have long lived instances).
But still an index on the table will solve the problem for future.
Any other alternatives which can help us will be highly appreciated.

**Additional context**
Explain plan:
![image](https://user-images.githubusercontent.com/25527900/95882268-ebf4b000-0d92-11eb-9495-21b20efa8d84.png)

other performance metrics:
![image](https://user-images.githubusercontent.com/25527900/95882332-03cc3400-0d93-11eb-8db3-71bd6d7ebe1b.png)

**Comment by filiphr** [comment]
Good job on spotting this @urwah1996 and thanks for the detailed report.

We added indices on the `REF_SCOPE_ID, REF_SCOPE_TYPE and LINK_TYPE` in https://github.com/flowable/flowable-engine/commit/0d1168ce0ffa239f859638e26babb79c5b3dcab2
