### ISSUE TITLE
release 6.6.0 flowable-ui-modeler ExclusiveGateWay 

### ISSUE THREAD

**Issue by weweibuy** [flowable/flowable-engine#2661]
ExclusiveGateWay missed a default folw checkbox.
There is the message content 'Exclusive gateway has at least one outgoing sequence flow without a condition (which isn't the default one)' when we check the model.
![image](https://user-images.githubusercontent.com/43676605/96471280-bdc71280-1261-11eb-8b35-077c990aac40.png)

**Comment by douglascrp** [comment]
I am facing the same problem with the 6.6.0 version.

There is no way to set the value, as the checkbox is not present.

![image](https://user-images.githubusercontent.com/5930258/102806310-66e1d480-439b-11eb-8889-82359f3beb97.png)

**Comment by filiphr** [comment]
The 6.6.0 version does not have the fix from PR #2662. I believe that this PR will fix this problem as well. Therefore, I am closing this issue
