### ISSUE TITLE
Excuse me? version6.6 ModelServiceImpl  Why not autowired

### ISSUE THREAD

**Issue by laterw** [flowable/flowable-engine#2666]
org.flowable.ui.modeler.service.ModelServiceImpl

**Comment by laterw** [comment]
[https://github.com/flowable/flowable-engine/blob/flowable-release-6.6.0/modules/flowable-ui/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/ModelImageService.java](url)

**Comment by tijsrademakers** [comment]
Thank you for your comments. If you want to discuss certain class implementations then we are happy to discuss it on the Flowable forum.
