### ISSUE TITLE
Flowable 6.6 UI - Missing "<omgdi:waypoint" when using receiveEventTask

### ISSUE THREAD

**Issue by olekkosma** [flowable/flowable-engine#2668]
**Describe the bug**
When I export .bpmn the file is missing one part of the waypoints that describes the line between tasks only in case od receive event task. When I switch the same task for other one like sendEventTask that doesn't heppen. 

**Expected behavior**
The generated .bpmn code  should have all needed waypoints. Generated with flowable modeler.
**Code**
Wrong code * currently exists":
![image](https://user-images.githubusercontent.com/16398511/97430414-258ff400-1919-11eb-8f9b-c05dd1aeb591.png)
Expected code:
![image](https://user-images.githubusercontent.com/16398511/97430483-3ccee180-1919-11eb-882d-3f0e8439fca4.png)

**Additional context**
Flowable 6.6. Only heppens with new type of task - receive event task.

**Comment by tijsrademakers** [comment]
Issue is fixed, thanks for reporting.
