### ISSUE TITLE
Flowable ui not responsive

### ISSUE THREAD

**Issue by josersleal** [flowable/flowable-engine#2670]
**Describe the bug**

The flowable ui is not responsive

**Expected behavior**

The UI shows all elements correctly after changing browser size
![flowabl-ui non responsive](https://user-images.githubusercontent.com/3142072/97671758-8a6e5a00-1a91-11eb-9c18-b2f91fb7bcaa.png)

**Code**
If applicable, add the code that you are using when having the issue.

**Additional context**
Add the version of Flowable that you are using, the database vendor and if you are using Flowable within Spring Boot, the Flowable Task application etc.

**Comment by tijsrademakers** [comment]
Hi,
The Flowable UI is provided as demo applications to show the functionality and capabilities of the Engines. We would welcome any community contribution to make the applications responsive of course, but it's not a priority for the Flowable project.
Best regards
