### ISSUE TITLE
Flowable UI Modeler - Processes and Apps not displayed when using an Oracle database and no tenant

### ISSUE THREAD

**Issue by PascalSchumacher** [flowable/flowable-engine#2674]
Flowable UI Modeler version `6.6.0` (using either `flowable-spring-boot-starter-ui-modeler` or `flowable-ui-app`) does no longer display processes and apps when it is used in combination with an Oracle database and no tenant is configured (the default).

This was working in previous version like `6.5.0` etc. It is still possible to create processes and apps.

The problem is that Oracle database saves empty strings as null.

The `tenant_id` column is `null` and and the SQL statements used by Flowable Modeler (selecting rows where `tenant_id` is `''`):

`select * from ACT_DE_MODEL WHERE model_type = 0 and tenant_id = '' order by last_updated desc`
`select * from ACT_DE_MODEL WHERE model_type = 3 and model_key = 'testapp' and tenant_id = ''`

do not find any entries.

Using `h2` as a database everything works fine.

**Comment by filiphr** [comment]
Fixed in #2965
