### ISSUE TITLE
BusinessKey is not set when starting a process instance by message

### ISSUE THREAD

**Issue by paulstapleton** [flowable/flowable-engine#268]
In Flowable-engine 6.0.0 when I start a new process instance by a message then the business key I send in is not set in the process instance.
This is both when using the Java API and Rest API.

I have attached a small unit test displaying the problem.

I Think the problem occurs in org.flowable.engine.impl.cmd.StartProcessInstanceByMessageCmd#execute(CommandContext commandContext). The businessKey is set here but not actually passed on to the ProcessInstanceHelper when the process instance is created.
Process instances created using a process definition key set the business key correctly.

[BusinessKeyNotSetTest.zip](https://github.com/flowable/flowable-engine/files/799482/BusinessKeyNotSetTest.zip)

**Comment by tijsrademakers** [comment]
Thanks, fixed the issue based on the unit test you provided.
