### ISSUE TITLE
Error When Querying Data Obejcts

### ISSUE THREAD

**Issue by johnpaulquijano** [flowable/flowable-engine#2682]
We have a data object model linked to a database service model. The database table is setup and we can insert data to it using the DataObjectRuntimeService api. However, we are getting an error when fetching data:
**Cause: org.apache.ibatis.reflection.ReflectionException: There is no getter for property named ‘externalId’ in 'class com.flowable.dataobject.engine.impl.runtime.DataObjectInstanceQueryImpl’**

Indeed DataObjectInstanceQueryImpl doesn’t have externalId property unlike its master data counterpart MasterDataInstanceQueryImpl.

For replication:
**List<DataObjectInstance> instances = dataObjectRuntimeService
.createDataObjectInstanceQuery()
.definitionKey(“myDataObjectDefinitionKey”)
.list();**

We are using Flowable Enterprise version 3.7.2 and H2 Database (embedded) on Spring Boot.

**Comment by tijsrademakers** [comment]
Hi,
Thanks for reporting the issue but the issue list on Github is only for Flowable open source issues. For issues with the enterprise offering you can use the forum (https://forum.flowable.com/), or report issues via the service desk.
Best regards
