### ISSUE TITLE
UserTask happen to get started but not assigned to anyone

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#269]
UserTask happen to get started but not assigned to anyone.
I login as admin and I can't claim or reassign it. Seems no one can claim it.

Thanks

**Comment by yvoswillens** [comment]
Hi.

Please provide more info on this. 

Regards,

Yvo

**Comment by tijsrademakers** [comment]
A user task doesn't have to be assigned. But in the Flowable Task app that currently means that no user is able to claim / complete the task. We could a Flowable Task admin user to the privileges and give this privilege the rights to do something with these tasks.

**Comment by mgrouch** [comment]
At least admin should be able to claim it. Or it is totally orphan. 
Thanks

**Comment by tijsrademakers** [comment]
A task without assignee can be claimed and completed now.
