### ISSUE TITLE
Azure AD SSO Integration with flowable/ui

### ISSUE THREAD

**Issue by hegde89** [flowable/flowable-engine#2702]
we are looking for Azure AD SSO Integration

**Comment by tijsrademakers** [comment]
Ok, the Flowable UI application uses Spring Security so it's possible to develop such an integration. It's not something we have planned to provide out-of-the-box.

**Comment by hegde89** [comment]
Can you share any successful implementation of SAML based SSO ?? if any documentation available will be more helpful
