### ISSUE TITLE
Messy table in REST-API docs

### ISSUE THREAD

**Issue by verheyenkoen** [flowable/flowable-engine#2703]
The parameters section of the [get a list of jobs API documentation](https://flowable.com/open-source/docs/bpmn/ch15-REST/#get-a-list-of-jobs) is messed up from "tenantId".

![image](https://user-images.githubusercontent.com/599538/98934184-fca75b80-24e1-11eb-8fe6-dfc9224851ee.png)

**Comment by dbmalkovsky** [comment]
Should be fixed when this [PR](https://github.com/flowable/flowable-engine/pull/2713) is committed.

**Comment by tijsrademakers** [comment]
PR merged, thanks
