### ISSUE TITLE
flowable 6.6.0 modeler Visual editor issue

### ISSUE THREAD

**Issue by Chakib-DAII** [flowable/flowable-engine#2712]
**Describe the bug**
checkboxes does not appear in flowable 6.6.0 bpmn modeler (Exclusive, asynchronous activities, compensation, default gateway,...) which are necessary for modeling instead of defining these properties in bpmn files.

**Expected behavior**
Set most of activities properties using modeler.

**Additional context**
 flowable 6.6.0; PostgreSQL; Spring Boot;

**Comment by tijsrademakers** [comment]
Hi @Chakib-DAII , this is already fixed on master, the issue was already reported.
