### ISSUE TITLE
REST API for content-api not available in the flowable-rest application. Flowable 6.6

### ISSUE THREAD

**Issue by douglascrp** [flowable/flowable-engine#2723]
**Describe the bug**
We have a custom interface that we use to interact with flowable using the REST API, and one of the APIs we use is the content-api.
With Flowable 6.5 we used to use the flowable-task to access it, but now that we are moving to 6.6, we thought about using the flowable-rest application, but the content-api seems not to be available there.

**Expected behavior**
It would be nice to have the content-api available through flowable-rest application.

**Code**
If applicable, add the code that you are using when having the issue.

**Additional context**
Flowable 6.6

**Comment by tijsrademakers** [comment]
The content-api REST API is available in the Flowable REST application. You can check this with the flowable-rest/content-api/content-service/content-items url for example.
