### ISSUE TITLE
Wrong BPMN symbol for event gateway used

### ISSUE THREAD

**Issue by pieterclaeys** [flowable/flowable-engine#273]
On the ORYX canvas, a wrong BPMN icon is rendered for the 'Event-based Gateway': the currently used symbol is actually a "**parallel** event-based gateway).

Expected: the same symbol as in the left tree-pane is used for the Event-Based gateway (the pentagon-in-circle-in-diamond icon).

See forum thread
http://forum.flowable.org/t/wrong-bpmn-symbol-for-event-gateway/369

**Comment by mlippens** [comment]
Hi, 

I've made this icon in SVG for the stencilset, I'll send a pull request soon. 
Attached see two screenshots
![screenshot from 2017-02-28 11-12-46](https://cloud.githubusercontent.com/assets/738409/23401147/f0164e32-fda6-11e6-8552-42d36a52c051.png)
![screenshot from 2017-02-28 11-13-12](https://cloud.githubusercontent.com/assets/738409/23401149/f18f2860-fda6-11e6-8aa0-2c3aea0e7631.png)

**Comment by mlippens** [comment]
See pull request #274

**Comment by tijsrademakers** [comment]
Merged PR, thanks
