### ISSUE TITLE
Dead lock in DB Connection acquiring

### ISSUE THREAD

**Issue by zhudongdong** [flowable/flowable-engine#2733]
**Describe the bug**
The process engine will stuck since there is dead lock in acqurie db connection when doing performence test for startAsync.

**Expected behavior**
close the connection since there are no actions after the transaction commited.

**Code**
org.flowable.common.engine.impl.cfg.standalone.StandaloneMybatisTransactionContext
@Override
    public void commit() {

        LOGGER.debug("firing event committing...");
        fireTransactionEvent(TransactionState.COMMITTING, false);

        LOGGER.debug("committing the ibatis sql session...");
        dbSqlSession.commit(); 
        LOGGER.debug("firing event committed...");
        fireTransactionEvent(TransactionState.COMMITTED, true); 
    }

**Additional context**
after dbSqlSession.commit() , the connection is not closed because the closing behavior is trigger by the method caller.
when start a new transaction during fireTransactionEvent(TransactionState.COMMITTED, true) , if there are no connections avaliable, the method will stuck here , and casue to not able to close the previous connection.then the dead lock is created.

**Comment by tijsrademakers** [comment]
Hi @zhudongdong ,

For every application it's important that the DB connection pool is configured with enough connections available to service the load. Can you maybe elaborate more in the solution you are proposing? Maybe with a PR so that we can have a look at the proposed changes and test if it breaks anything?

Best regards

**Comment by zhudongdong** [comment]
Sure ,I will submit a test PR.

**Comment by zhudongdong** [comment]
Hi

**Comment by tijsrademakers** [comment]
Closing the issue, due to no response.
