### ISSUE TITLE
When deploy flowable-engine in a form of independent service, how to guarantee business callback in an transaction

### ISSUE THREAD

**Issue by dayforward** [flowable/flowable-engine#2735]
I am new in using flowable and not quite clear how to deploy flowable , integrated in business service or independently deployed.
If deployed independently , business service will communicate with flowable engine through restful api frequently, which must
be slower than integrated in business service running in the same jvm. Meanwhile business callback and listeners will be implemented though http , how can we guarantee transaction between flowable engine and business service?
A clear and concise description of what the problem is.

**Comment by tijsrademakers** [comment]
Hi,

Can you use the forum https://forum.flowable.org/ for these kind of discussions instead? If transactions are important then an integrated or embedded setup is often better suited.

Best regards
