### ISSUE TITLE
modeler save name not correct

### ISSUE THREAD

**Issue by duansheli** [flowable/flowable-engine#2742]
**Describe the bug**
![image](https://user-images.githubusercontent.com/8579595/102004818-32449c00-3d4f-11eb-8574-48c41dfaefa9.png)

**Expected behavior**

Under the main editing area, 
the name of the process is renamed through attribute editing.
After clicking the Save button, 
the dialog box should display the modified process name

**Comment by duansheli** [comment]
If you directly click the Save button 
and re-enter the edit page, 
you can find that the process name property just did not update to bb-v2

**Comment by tijsrademakers** [comment]
Hi, you have to update both values for now. There's currently no plan to sync the values.
