### ISSUE TITLE
Docker Image for Release 6.6

### ISSUE THREAD

**Issue by srinathganesh** [flowable/flowable-engine#2747]
**Is your feature request related to a problem? Please describe.**
- Docker Hub is missing tag for 6.6 Release
- Search URL: https://hub.docker.com/r/flowable/all-in-one/tags?page=1&ordering=last_updated&name=6.6
- Flowable 6.6.0 released this on 13 Oct 2020

**Describe the solution you'd like**
- Someone to push latest tag in Dockerhub

**Describe alternatives you've considered**
- Alternative is to docker build itfrom source

**Comment by yvoswillens** [comment]
As of release 6.6.0 there is Flowable UI (flowable/flowable-ui). Flowable all-in-one is deprecated.
