### ISSUE TITLE
Flowable modeler: export/import of BPMN diagram loses escalation references

### ISSUE THREAD

**Issue by Sinimane** [flowable/flowable-engine#2748]
I have a very basic BPMN with an intermediate escalation throwing event with the reference set to “escalationId”:
![image](https://user-images.githubusercontent.com/49920707/102493217-c625a900-406a-11eb-8360-a2c9eb40f6aa.png)

Exporting the diagram from the modeler, and importing it again results in the escalation reference losing its value:
![image](https://user-images.githubusercontent.com/49920707/102493241-cde54d80-406a-11eb-8c19-c128c583a4f6.png)

Here is the diff between the BPMN at creation and the BPMN after exporting and importing it again:
![image](https://user-images.githubusercontent.com/49920707/102493256-d50c5b80-406a-11eb-82ea-382435858c55.png)

I attach the 2 BPMN diagrams:

[Escalation ref issue.zip](https://github.com/flowable/flowable-engine/files/5815349/Escalation.ref.issue.zip)

**Comment by tijsrademakers** [comment]
Issue should be fixed now, thanks for reporting
