### ISSUE TITLE
 How to turn on timed boundary events？

### ISSUE THREAD

**Issue by baobaozhou** [flowable/flowable-engine#2752]
**Describe the bug**
No matter how I do it, the timed boundary event does not take effect, although the trigger time is reached

**Expected behavior**

**Code**
I tried to enable asynchronous tasks in the configuration file。

flowable.async.executor.activate=true

But the task is still not triggered

**Additional context**
Add the version of Flowable that you are using, the database vendor and if you are using Flowable within Spring Boot, the Flowable Task application etc.

**Comment by filiphr** [comment]
Which version of Flowable are you using?

**Comment by baobaozhou** [comment]
6.4.2
Thank you very much for your help. Regarding this problem, I have solved it. The yml configuration file is invalid due to the configuration of the ProcessEngine class. This problem was previously ignored.

**Comment by filiphr** [comment]
Closing this issue, since you've resolved the problem
