### ISSUE TITLE
which ways cloud help me to define bpmn ui ?i just need a simple example

### ISSUE THREAD

**Issue by yunnuoyang** [flowable/flowable-engine#2754]
**Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is. 
Ex. I have the following process or case definition and calling this API, the following exception happens [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Models, if applicable, always help to clarify a problem. Ideally, a unit test makes reproducing things easier.

**Comment by tijsrademakers** [comment]
Please don't create issues with a question without any additional information or context. For questions it's also better to use our Flowable forum https://forum.flowable.org/

**Comment by yunnuoyang** [comment]
ok，thanks.
