### ISSUE TITLE
flowable.modeler.app.deployment-api-url =https://hostname/flowable-task/app-api. While publishing app it says HTTP/1.1 200 . Failed to publish

### ISSUE THREAD

**Issue by raaz438** [flowable/flowable-engine#2764]
Deployment url with https not pushing app to flowable work from modeler it gives error. Failed to publish.
. if we give http://hostname:8080/flowable-task/app-api ..it wil publish app successfully.

Do I need add any configuration in flowable-task module or  need to change in code..pls suggest me

**Comment by dbmalkovsky** [comment]
If you really are using Flowable Work then you are using the Enterprise version of Flowable and you are asking in the wrong forum. Questions about the enterprise products should be done in the Enterprise Forum or through your account managers and the Service Desk.

**Comment by raaz438** [comment]
Yes, am using enterprise version of flowable work . Let me post it other there ..thank you
