### ISSUE TITLE
Security issue: after the default user admin changes the password or deletes the cookie, it is still valid and valid for 31 days

### ISSUE THREAD

**Issue by rv0p111** [flowable/flowable-engine#2767]
**Describe the bug**
Security issue: after the default user admin changes the password or deletes the cookie, it is still valid and valid for 31 days
**Expected behavior**
Cookie does not expire, the user can still enter the system
**Code**
If applicable, add the code that you are using when having the issue.

**Additional context**
Add the version of Flowable that you are using, the database vendor and if you are using Flowable within Spring Boot, the Flowable Task application etc.

**Comment by rv0p111** [comment]
This problem is specific to Flowable UI Web systems

**Comment by tijsrademakers** [comment]
Hi, this can be configured with the common app cookie property, see:

https://github.com/flowable/flowable-engine/blob/master/modules/flowable-ui/flowable-ui-common/src/main/java/org/flowable/ui/common/properties/FlowableCommonAppProperties.java#L416
