### ISSUE TITLE
Issue when using Flowable-Rest instead of Flowable-Control

### ISSUE THREAD

**Issue by AnisGitRepo** [flowable/flowable-engine#2769]
Hi Team, 

When i tried to use flowable rest api instead of flowable control api i faced an issue about using a special endpoint.
In fact, i didn't found in flowable rest api documentation an equivalent endpoint in flowable-rest that do the same thing than this one "/rest/admin/process-instances/{processInstanceId}/history-model-json" in flowable-control.

Do you have an idea or any suggestion ?

Thank you in advance for your help

**Comment by yvoswillens** [comment]
Hi @AnisGitRepo 

You refer to Flowable Control. This is part of the commercial stack. Please use the enterprise forum for questions related to the commercial offering. (https://forum.flowable.com)

The resource you're referring to is also part of Flowable Admin. The code is available here;

https://github.com/flowable/flowable-engine/blob/master/modules/flowable-ui/flowable-ui-admin-rest/src/main/java/org/flowable/ui/admin/rest/client/DisplayJsonClientResource.java#L173

The APIs used here are available in Flowable REST. The additional JSON processing not.
