### ISSUE TITLE
Sequenceflows are not stored correctly when they belong to subprocess who is inside a collapsed subprocess.

### ISSUE THREAD

**Issue by ddpardo** [flowable/flowable-engine#277]
Hi all,

There is a problem with the storage of sequenceflows json generated by the bpmn modeler (javascript)

It is reproduceable with the following steps:

1) in the root process add a colapsed subprocess.
2) inside the collapsed subprocess add a subprocess.
3) inside the subprocess add an startevent -> sequenceflow -> endevent.

The sequence flow should be a child of sub process but the modeler saves it as a child of the collapsed subprocess. This leads to problems when deploying. The sequence flows are duplicated by the json -> java. 

@tijsrademakers I am investigating and attempting to fix this.

**Comment by ddpardo** [comment]
Here are my research notes:

Root problem:
Sequence flows are always stored as a child of a canvas. Since a collapsed subprocess is a canvas, all sequence flows inside an collapsed subprocess canvas are stored as children of the collapsed sub process.

When converting a model.json to java BPMNModel the sequence flows are moved to the correct parent. If the converter detected that a sequence flow belongs to a sub process the sequenceflow is removed from the process and added to the subprocess.
If the sequenceflow belongs to a subprocess inside collapsed subprocess the sequenceflow is not removed from the collapsed subprocess. This dupplicates the sequenceflow object!

Fix in PR #285
If an sequenceflow belongs to an expanded subprocess an additional check is now performed to remove the sequenceflow from the collapsed subprocess.

It is not possible to make the modeler assign the sequenceflow as a child of the subprocess. Inside the ORYX code there are internal checks who prevent putting sequenceflows (aka edges) as childs of a canvas.

**Comment by mlippens** [comment]
This issue can be closed? pull request #285 has already been accepted.

**Comment by tijsrademakers** [comment]
Yes thanks
