### ISSUE TITLE
flowable-jmx work not well

### ISSUE THREAD

**Issue by leesonwei** [flowable/flowable-engine#2770]
**Describe the bug**
I can access jmx server with same machine but other machine not work.

**Expected behavior**
jmx server can access by remote.

**Code**
ref. the official doc, add maven flowable-jmx.jar

**Additional context**
flowable version:6.6.0 flowable-jmx version: 6.6.0

**Comment by tijsrademakers** [comment]
Hi, this should not be related to Flowable. If you think something needs to be changed in Flowable then reopen the issue pointing to the code that should be changed.
