### ISSUE TITLE
46/5000  Where do I modify the source code of the official front end so that all RESTful requests have a token from the header?

### ISSUE THREAD

**Issue by 1797890817** [flowable/flowable-engine#2773]
I am now adapting Flowable6.6.0 to my OAuth2.0 project, and I want the front end of Flowable to have a place to set the global interceptor,
This way I can get all the RESTful interfaces of Flowable to pull out of LocalStorege with my own Token, so I can use this Token on the back end to know which user it is.

Now I don't know where I should change the front-end source code to have this effect, who can tell me? Thank you very much

**Comment by tijsrademakers** [comment]
Hi, please use the Flowable forum to ask questions. Closing this issue.
