### ISSUE TITLE
How can I deploy the flowable-UI with SQL server database?

### ISSUE THREAD

**Issue by 49047570** [flowable/flowable-engine#2778]
**Describe the bug**
I have unzip the flowable-ui.war with jar and updated the flowable-default.properties with SQL server conneciton.
Then, I used the jar to zip the flowable-ui.war again and released war into tomcat server. 
After I started the tomcat. I found the app still connect with H2 database.  What's the cause?
Could you provide help for me? Thanks.

**Expected behavior**

**Code**
If applicable, add the code that you are using when having the issue.

**Additional context**
Add the version of Flowable that you are using, the database vendor and if you are using Flowable within Spring Boot, the Flowable Task application etc.

**Comment by tijsrademakers** [comment]
Hi, please don't use the Github issues to ask questions. Did you also add a SQL Server driver JAR file to the classpath of Tomcat or the lib folder of the Flowable UI application?

**Comment by smile2014** [comment]
Statement.executeQuery(select version()) select version()
