### ISSUE TITLE
Flowable upgrade from 6.5 to 6.6

### ISSUE THREAD

**Issue by SHARMASWA** [flowable/flowable-engine#2779]
Hello Colleagues,

We are using flowable 6.4.2 currently. We want to move to 6.6 version

Therefore, we followed the staggered approach on our sandbox system to first upgrade it to 6.5 and then later from 6.5 to 6.6.

After performing an upgrade from version 6.5 to 6.6, we lost all the apps created in flowable.

Is this a normal behaviour? or did we miss some pre-requisite towards the upgrade?

Regards,
Swapnil Sharma

**Comment by filiphr** [comment]
Hey @SHARMASWA, we just saw that you also create [this](https://forum.flowable.org/t/flowable-upgrade-from-6-5-to-6-6/7369) forum post. There is really no need to cross post as we are monitoring both here and the forum.

In any case the forum is the place to ask this questions and you just got an answer there.
