### ISSUE TITLE
Sleuth not working with flowable

### ISSUE THREAD

**Issue by DekateSainath** [flowable/flowable-engine#2781]
I have added the sleuth dependency is spring boot flowable project. But sleuth tracing in not working.
API request from flowable don't have any trace and slot derails in request header

**Comment by buksvdl** [comment]
Your Delegates need to be Spring Beans.

**Comment by tijsrademakers** [comment]
Closing the issue. Please use the Flowable forum to discuss to provide more context to the issue you are facing and maybe share an example project etc.
