### ISSUE TITLE
DMN Decision Table Date related collection functions

### ISSUE THREAD

**Issue by yvoswillens** [flowable/flowable-engine#2788]
When using a Date input variable in the DMN decision table and creating a rule use collection related operators an exception can occur while executing the decision table.

This is should not be the case.

There is transformation logic in place which can instantiate collection during runtime based on the strings in the rule expression. This provides the flexibility to create collections with string literals in the decision table editor.
In the current transformation logic the case of using a Date object is not covered. It always tries to convert based on the `.toString` value. This is incorrect and should be fixed.

**Comment by umeshinflowsol** [comment]
i was using the decision table collection all of its not working properly i will ping screen shot to u
![ummi](https://user-images.githubusercontent.com/120621911/234206172-2e5270ad-d7b1-4854-ab8e-2b02161915e4.jpg)
