### ISSUE TITLE
Error using the git repository on windows, because test resource filename is too long

### ISSUE THREAD

**Issue by PascalSchumacher** [flowable/flowable-engine#2792]
Updating/cloning the flowable repository on windows results in an error:

`error: cannot stat 'modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/multiinstance/MultiInstanceVariableAggregationTest.testParallelMultiInstanceSubProcessWithParallelMultiInstanceUserTaskWithCustomAggregator.bpmn20.xml': Filename too long`

It seem that therefore pull requests pushed from windows are displayed as having a conflict, even when there are no conflicting changes (see: https://github.com/flowable/flowable-engine/pull/2791).

It would be great if the filename would be shortened a bit.

**Comment by filiphr** [comment]
Thanks for the issue @PascalSchumacher. Unfortunately none of the core developers use Windows and something like this can slip up. We just added a Windows build in our Main GitHub build in order to catch such an issue in the future.

**Comment by PascalSchumacher** [comment]
No problem. :)

Thank you very much for fixing this!

**Comment by filiphr** [comment]
@PascalSchumacher can you by any chance check locally if running the tests in the `flowable-form-json-converter` work when running from the command line?

For some reason the Windows build is failing there. See https://github.com/flowable/flowable-engine/runs/1848814911#step:6:1597

**Comment by dbmalkovsky** [comment]
@filiphr I have a Window machine and the `flowable-form-json-converter` module runs fine both in IntelliJ and using mvn from the command line.   When I try `mvn clean test` for the entire project it runs clean but then there are test failures latter on in the engine (which if memory serves me is not atypical). 

See:
![image](https://user-images.githubusercontent.com/1105445/107260623-4d105580-6a0c-11eb-8e57-49bb08b78c23.png)

**Comment by filiphr** [comment]
Thanks for checking @dbmalkovsky. It is really weird the Windows build on GitHub fails consistently on the same place. Did you run this with powershell through the Windowss Command line or is this a bash terminal? Can you perhaps also try with `./mwnw.cmd`?

**Comment by dbmalkovsky** [comment]
@filiphr The first test was using the git bash shell.  Then I tried `mwnw.cmd` in a command shell with the same results; failures in the engine module.  Finally I tried `mwnw.cmd` in PowerShell and you can guess the outcome: same as the other two.

**Comment by filiphr** [comment]
Thanks a lot for the checks @dbmalkovsky. It seems I'll need to spin up a VM to get to the bottom of this :)
