### ISSUE TITLE
includeTaskLocalVariables=true but task local variables are not returned

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#280]
includeTaskLocalVariables=true but task local variables are not returned

Here is query URL
/flowable-task/process-api/runtime/tasks?includeTaskLocalVariables=true&includeProcessVariables=true

Thanks,
--MG

**Comment by tijsrademakers** [comment]
Have a look at the unit test in the commit, task local variables are returned as well in this unit test. Please provide a unit test showing the issue if the problem is still there.

**Comment by mgrouch** [comment]
The problem is still there.
Also when I use URL 
/flowable-task/process-api/runtime/tasks/38/variables

(I just picked one of the tasks IDs from the result of 
/flowable-task/process-api/runtime/tasks?includeTaskLocalVariables=true&includeProcessVariables=true)

it returns more variables than in /flowable-task/process-api/runtime/tasks?includeTaskLocalVariables=true&includeProcessVariables=true

Thanks

**Comment by tijsrademakers** [comment]
Nothing has been changed in the code, I've only added a unit test to test the issue. Please provide a step by step description on how to reproduce the issue with an example BPMN XML. Or show with a unit test that there's an issue.

**Comment by mgrouch** [comment]
If this helps the task in question is a Multi-Instance UserTask.
Thanks

**Comment by tijsrademakers** [comment]
Yes that's important information, and which variables are not returned by /flowable-task/process-api/runtime/tasks?includeTaskLocalVariables=true&includeProcessVariables=true which are returned by /flowable-task/process-api/runtime/tasks/38/variables? Is it random, or can you see something different with these missing variables?

**Comment by mgrouch** [comment]
To reproduce I run a process with multi-instance user task. The process created number of user tasks
assigned to several users.
Then I queried using /flowable-task/process-api/runtime/tasks?includeTaskLocalVariables=true&includeProcessVariables=true

no local variables were returned.

then I picked one task instance from the result of first query and
did /flowable-task/process-api/runtime/tasks/38/variables

there were no variables with local scope either in second result, but I got more variables.

Thanks

**Comment by mgrouch** [comment]
loopCounter, nrOfCompletedInstances, nrOfInstances were missing in list, but are the in drill down query

**Comment by mgrouch** [comment]
but no local task variables in either case

**Comment by tijsrademakers** [comment]
Did you add local task variables then? How did you add these local task variables?
loopCounter, nrOfCompletedInstances and nrOfInstances is expected to be missing because they are execution local variables of the multi instance executions. So they are not local task variables and not global process variables, and therefor not returned in the /flowable-task/process-api/runtime/tasks?includeTaskLocalVariables=true&includeProcessVariables=true query result.

**Comment by mgrouch** [comment]
Another observation: (In my case local variable is 'approver') it is a loop variable of multi-instance task

query /flowable-task/process-api/runtime/tasks/38/variables/approver/data
returns data. Strangely it is binary instead of Json

Thanks
