### ISSUE TITLE
TaskQueryRequest.java taskVariables, processInstanceVariables are never set from request

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#281]
TaskQueryRequest.java taskVariables, processInstanceVariables are never set from request.

Seems they are designed to specify which variables to query for, but the code is not complete.

Thanks,
--MG

**Comment by tijsrademakers** [comment]
in TaskBaseResource line 267 the taskVariables are set in the task query , same for processInstanceVariables.

**Comment by mgrouch** [comment]
request.getTaskVariables() would always return null.
I do not see it being set
