### ISSUE TITLE
Slow response while fetching first form after deployment

### ISSUE THREAD

**Issue by urwah1996** [flowable/flowable-engine#2813]
We use flowable apps to create flows which helps our customers to resolve their issues. On average our apps contain 2 process definitions and 50+ form definitions. Whenever we deploy an app after a change it takes alot of time to fetch the first form. This causes timeouts for our customers and they keep retrying until the form cache gets populated. Upon investigation I found out that the following query is executed to get the form resource from db: 

``select * from `act_fo_form_resource` where `deployment_id_`=? order by `name_` asc``

this is the explain plan for the query:

```
{
  "query_block": {
    "cost_info": {
      "query_cost": "2310297.01"
    },
    "ordering_operation": {
      "cost_info": {
        "sort_cost": "714926.01"
      },
      "table": {
        "access_type": "ALL",
        "attached_condition": "(`workflow`.`ACT_FO_FORM_RESOURCE`.`DEPLOYMENT_ID_` = 'cc****************')",
        "cost_info": {
          "data_read_per_join": "534M",
          "eval_cost": "142985.20",
          "prefix_cost": "1595371.00",
          "read_cost": "1452385.80"
        },
        "filtered": "10.00",
        "rows_examined_per_scan": 7149260,
        "rows_produced_per_join": 714926,
        "table_name": "ACT_FO_FORM_RESOURCE",
        "used_columns": [
          "ID_",
          "NAME_",
          "DEPLOYMENT_ID_",
          "RESOURCE_BYTES_"
        ]
      },
      "using_filesort": true
    },
    "select_id": 1
  },
  "ExplainType": "mysql/json/1",
  "ExplainWarnings": []
}
```
Due to no index present on `deployment_id` field the query uses simple `where` filtering instead of index based filtering. Apart from that the `sort` further increases time. The query spends major amount of time to create sort index.
![image](https://user-images.githubusercontent.com/25527900/107878267-329a1880-6ef3-11eb-9a73-70294849ff99.png)
 
I went through the code of form-engine to understand the significance of this `sort`. But I was unable to find any. I am not sure where is this sort being used and how is it helping the engine. 

A solution I was thinking was perhaps to remove the sort and also create an index on deployment_id field. Since we have ~7 million rows in form resource so an index would definitely help.

**Comment by tijsrademakers** [comment]
Hi, adding an index to deployment_id_ is something you can definitely do to optimize it for your database. Removing the sorting on name could be an optimization to improve the performance.

**Comment by tijsrademakers** [comment]
Closing the issue because of lack of response. Please reopen when there's more info to share.
