### ISSUE TITLE
Flowable UI IDM app password policy

### ISSUE THREAD

**Issue by arun-s-b** [flowable/flowable-engine#2815]
I am using Flowable UI 6.6.0 docker image. In the IDM App when I create a new user it is accepting even one character passwords. There is no default password policy which forces admin to enter user password in certain format e.g. at least x number and x uppercase and lowercase letter, and at least x or more characters.

We need properties (may be in flowable-default.properties) which will allow us to customise the password policy as per each organisation's need.

**Comment by filiphr** [comment]
Hey @arun-s-b, the Flowable UI applications are example applications which show case the Flowable functionality. We are accepting PRs that will improve this UI applications at any time.
