### ISSUE TITLE
Flowable-UI：i18n(Japanese) is not enough

### ISSUE THREAD

**Issue by delhicurry** [flowable/flowable-engine#2818]
**Describe the bug**

For example, 
these two "APP.MODELER.TITLE", "APP.MODELER.DESCRIPTION" are 
NOT included below.

https://github.com/flowable/flowable-engine/blob/master/modules/flowable-ui/flowable-ui-modeler-frontend/src/main/resources/static/modeler/i18n/ja-JP.json

**Comment by tijsrademakers** [comment]
Hi, we are not maintaining the Japanse translations, this is done by community contributions. Therefore I'm closing this issue.
