### ISSUE TITLE
Incorrect anchor links in REST API docs

### ISSUE THREAD

**Issue by verheyenkoen** [flowable/flowable-engine#2825]
The REST API docs page contains two anchor hyperlink instances (in [query process instances](https://flowable.com/open-source/docs/bpmn/ch15-REST/#query-process-instances) and [query executions](https://flowable.com/open-source/docs/bpmn/ch15-REST/#query-executions)) that should link to the [json query variable format section](https://flowable.com/open-source/docs/bpmn/ch15-REST/#json-query-variable-format), but have this hyperlink instead "https://flowable.com/open-source/docs/bpmn/ch15-REST/restQueryVariable". However later in the same page the correct link is rendered. Tried to create a pull request for this but couldn't see the problem and I'm new to the asciidoc format.

**Comment by dbmalkovsky** [comment]
See [PR](https://github.com/flowable/flowable-engine/pull/2826) for attempt to fix your issue.

**Comment by verheyenkoen** [comment]
Not sure if that is the fix since these markdown files seem to be generated from the adoc files, but I might be wrong.

Also just now noticed the same bug is there for the paging and sorting options, linking to "https://flowable.com/open-source/docs/bpmn/ch15-REST/restPagingAndSort".

**Comment by dbmalkovsky** [comment]
I believe they were generated once and now the markdown files using `docusaurus` are the latest and greatest.   But then I could very well be corrected by the team.

**Comment by dbmalkovsky** [comment]
And I think I corrected the `Paging and sort` links too.
