### ISSUE TITLE
flowable usage

### ISSUE THREAD

**Issue by liduanwen** [flowable/flowable-engine#2827]
Hello, we are currently working on a low code platform. I have seen some things on the official website of flowable, and I don't know if I can do them. That is, we will define multiple nodes on a page, such as start node, new node (which has been assigned in the input parameter), query node and end node. I want to realize this process, each process does not need approval, but in my opinion, flowable goes through the process node one by one, and it needs approval to go to the next node. Hope you can guide, look forward to your reply, thank you

**Comment by tijsrademakers** [comment]
Hi, it's easier to get in contact through the Flowable forum. Maybe you can elaborate a bit more on what you are trying to do and what your question is?
