### ISSUE TITLE
flowable6.6 Mysql Introduction to Database Table

### ISSUE THREAD

**Issue by zhang1995632** [flowable/flowable-engine#2828]
hello，I am Chinese,My English is not good. I would like a description of the database table, an introduction. mysql 
My email : 15213238256@163.com
thank you.

**Comment by qiudaoke** [comment]
ProcessEngineConfiguration.createProcessEngineConfigurationFromResourceDefault().setDatabaseSchemaUpdate(ProcessEngineConfigurationImpl.DB_SCHEMA_UPDATE_CREATE).buildProcessEngine();
@zhang1995632
