### ISSUE TITLE
Upgrade mysql-jdbc-drivers 8.0.23, liquibase threw exceptions

### ISSUE THREAD

**Issue by jayzch** [flowable/flowable-engine#2836]
liquibase.changelog.StandardChangeLogHistoryService#getRanChangeSets threw java.lang.ClassCastException: java.time.LocalDateTime cannot be cast to java.lang.String

**Comment by jayzch** [comment]
https://github.com/liquibase/liquibase/issues/1657

**Comment by tijsrademakers** [comment]
Hi, you are correct that the mysql jdbc driver 8.0.23 is not working right now. But using 8.0.22 or a lower version works fine. When there is a bug fix in Liquibase we'll make sure to also start using it. For now just use the 8.0.22 driver version.

**Comment by jayzch** [comment]
https://github.com/liquibase/liquibase/pull/1664

**Comment by tijsrademakers** [comment]
Ok thanks, we'll check it

**Comment by sarojpurbey** [comment]
I am also facing similar issue. I don't have option to upgrade to 8.0.22 as my RDS is AWS managed. How to resolve the issue?
