### ISSUE TITLE
Setting formKey for completed tasks in elasticsearch query

### ISSUE THREAD

**Issue by patrykWianecki** [flowable/flowable-engine#2837]
**Describe the bug**
Bug appears when I was trying to set formKey in TasksIndexQueryRequest for tasks with filterId 'completed' (issue does not appear in tasks with filterId set to 'open'). FormKey is being set in TasksIndexQueryRequest, but is does not appear in query prepared for elasticsearch.

**Expected behavior**
FormKey should appear in query.

**Code**
For filterId=open
`{
  "query": {
    "bool": {
      "must": [],
      "filter": {
        "bool": {
          "must": [
            {
              "term": {
                "formKey": "formKeyValue"
              }
            }
          ]
        }
      }
    }
  }
}`

For filterId=completed
`{
  "query": {
    "bool": {
      "must": []
    }
  }
}`

**Additional context**
Bug has started to appear after upgraded from 3.7.2.83 to 3.8.2.2

**Comment by tijsrademakers** [comment]
Hi,

You have created an issue in the Flowable open source project which looks like an issue you faced with the Flowable Work product. Please share the issue in the support channel for Flowable Work.

Best regards
