### ISSUE TITLE
BPMN supports use with CMMN

### ISSUE THREAD

**Issue by zhaowanda** [flowable/flowable-engine#2840]
In the actual business scenario, pure BPMN cannot describe the specific business. It needs to be combined with CMMN to describe it. Looking at the corresponding documents and source code, there is no BPMN call to CMMN. Is there a corresponding plan to support this function?

**Comment by paulhh** [comment]
Hi,

The place for questions like this is the forums (https://forum.flowable.org/), not raising it as an issue here.

There is the CMMN/Case task that BPMN can invoke.

Regards
Paul.

**Comment by zhaowanda** [comment]
> Hi,
> 
> The place for questions like this is the forums (https://forum.flowable.org/), not raising it as an issue here.
> 
> There is the CMMN/Case task that BPMN can invoke.
> 
> Regards
> Paul.

Hi,  
Is there a specific example？
Thanks

**Comment by paulhh** [comment]
Looks like the open source docs are missing it.  It should be the same as documented in the enterprise version: https://documentation.flowable.com/latest/user/design/bpmn-editor/#case-task

**Comment by zhaowanda** [comment]
> Looks like the open source docs are missing it. It should be the same as documented in the enterprise version: https://documentation.flowable.com/latest/user/design/bpmn-editor/#case-task

No implementation of case-task was found in the open source version

**Comment by paulhh** [comment]
It is there in the engine - I don't think it's exposed in the open source Modeler.
