### ISSUE TITLE
We have a web based Modeler that can be used in your web browser. There's no roadmap for an idea plugin.

### ISSUE THREAD

**Issue by a871545252** [flowable/flowable-engine#2842]
We have a web based Modeler that can be used in your web browser. There's no roadmap for an idea plugin.

_Originally posted by @tijsrademakers in https://github.com/flowable/flowable-engine/issues/1879#issuecomment-518609637_

Question: How to use the web design?can you give me a link? Are the web-design open source?

**Comment by tijsrademakers** [comment]
Please don't use github issues to ask questions, but use the forum instead.
The Flowable Modeler is part of the Flowable UI application --> https://github.com/flowable/flowable-engine/tree/master/modules/flowable-ui
