### ISSUE TITLE
Poorly Named `addDefaultAsyncExceptionHandler` Engine Configuration

### ISSUE THREAD

**Issue by unamanic** [flowable/flowable-engine#2849]
The accessors in the following section of `ProcessEngineConfigurationImpl` are poorly named.  The name implies that it adds or removes the default exception handling for the entire engine.  In reality or only enables/disables the default `AsyncRunnableExecutionExceptionHandler`.  This accessor and variable should be deprecated and renamed in favor of one that clearly states its purpose, example: `setAddDefaultAsyncExceptionHandler` or `setAddDefaultRunnableExceptionHandler`

```
    public boolean isAddDefaultExceptionHandler() {
        return addDefaultExceptionHandler;
    }

    public ProcessEngineConfigurationImpl setAddDefaultExceptionHandler(boolean addDefaultExceptionHandler) {
        this.addDefaultExceptionHandler = addDefaultExceptionHandler;
        return this;
    }
```

https://github.com/flowable/flowable-engine/blob/07af1f724ab5b680172a44c1e1f6c45c84b0b5af/modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/ProcessEngineConfigurationImpl.java#L4361

**Comment by tijsrademakers** [comment]
This is a property that should only be overridden with a lot of knowledge about the engine. You might be right that the naming could be better, but deprecating it and introducing a new property is not something that we want to do at this point.
