### ISSUE TITLE
tenantId can not be insert

### ISSUE THREAD

**Issue by slivloon** [flowable/flowable-engine#2851]
**Describe the bug**
when I use the TaskService.saveTask method to create a new task, tenantId cannot insert into the database. You can insert only if you set variables and start an instance (startProcessInstanceById).

**Expected behavior**
tenantid can be inserted.

**Code**
`       Task task = this.taskService.createTaskBuilder().create();
         task.setTenantId("123");
         this.taskService.saveTask(task)`

**Additional context**
Version of Flowable: flowable-spring-boot-starter(6.6.0).

**Comment by filiphr** [comment]
The tenant id cannot be updated and that is like that by design.

You can create a task with a tenant id by using

```
this.taskService.createTaskBuilder().tenantId("123").create()
```
