### ISSUE TITLE
Missing API to obtain activity start time in execution listener

### ISSUE THREAD

**Issue by franck102** [flowable/flowable-engine#2887]
**Is your feature request related to a problem? Please describe.**

I am using an execution listener to track activity execution times as a Prometheus histogram, in flowable 6.6.0. The listener is a class delegate registered with the "end" event, added to every Activity flow node in the process.

The implementation needs to calculate now() - activity.getStartTime(); however there is no obvious API to obtain the ActivityInstance that holds the start time. I am currently using

ActivityInstanceEntity
                    activity = config.getActivityInstanceEntityManager().findUnfinishedActivityInstance((ExecutionEntity)execution);

which requires downcasting the delegate execution.

I can use config.getActivityInstanceEntityManager().findActivityInstancesByExecutionAndActivityId(...) but that returns a list,
what should I make of this if more than one unfinished activity is returned?

**Describe the solution you'd like**

A clear and concise API ( :) ) to obtain the startTime of the activity for which the event is firing, that does not hit the DB unless absolutely necessary.

**Comment by tijsrademakers** [comment]
The ExecutionListener gives you a DelegateExecution which can be casted to an Execution. You can get the start time from the Execution instance.

**Comment by franck102** [comment]
It would be nice not to have to downcast, this usually means maintenance down the line.

More importantly, the execution start time is not the same as the activity start time, is it? If several activities have synchronous continuations they will all be executed by the same execution?
