### ISSUE TITLE
Missing process definition key & name in ProcessInstance in PROCESS_STARTED event listener

### ISSUE THREAD

**Issue by franck102** [flowable/flowable-engine#2888]
**Describe the bug**
In a Flowable event typed listener registered against PROCESS_COMPLETED, using this query to obtain the process instance:

`CommandContextUtil.getProcessEngineConfiguration().getRuntimeService().createProcessInstanceQuery().processInstanceId(instanceId).singleResult();`

returns a ProcessInstance where neither the process key nor the name are set.

**Expected behavior**
Those fields should be populated from the process definition.

**Comment by tijsrademakers** [comment]
The process instance has a process definition id value and with that definition id value you can lookup the process definition to get the key and name values.

**Comment by franck102** [comment]
Yes, that is the workaround I am using.

I still don’t think that a public API should work sometimes and sometimes not: that is not a useful contract for an API, so the API can’t be used and it may just as well be removed...

**Comment by paulstapleton** [comment]
I've been caught out by this as well.

The processDefinitionKey seems to only be set directly after creating the execution/process instance and in the same transaction.
There is no field in the DB for the processDefintionKey and it has nowhere to be persisted for the execution. When you read it from the DB afterwards the processDefinitionKey is then empty.

This is inconsistent when using it, as depending on where you query it in the process it can give different results.

I would agree that it should be at least moved from the `ProcessInstance` interface and up to the `ExecutionEntity` interface, or possibly removed completely (as it is not persisted).

**Comment by filiphr** [comment]
I think that this is now fixed by https://github.com/flowable/flowable-engine/commit/62bbf9e214348307bb96bb157a2d5afb91449681. We spotted this a while ago and fixed it. It will be part of the next release.

**Comment by paulstapleton** [comment]
That commit though only seems to change the history process instances and not the runtime process instances.
There was no similar fix for the runtime tables?

**Comment by filiphr** [comment]
You are right @paulstapleton. That has been resolved with https://github.com/flowable/flowable-engine/commit/e43101f1aaa2b463d6a71a21419c8ada69b70663
