### ISSUE TITLE
Use BpmnAutoLayout thrown the execute API Java. Lang. NullPointerException:Null at org. Flowable. BPMN. BpmnAutoLayout. GenerateSequenceFlowDiagramInterchangeElements (BpmnAutoLayout. Java: 385)

### ISSUE THREAD

**Issue by RClown** [flowable/flowable-engine#2891]
**Describe the bug**
![空指针截图](https://user-images.githubusercontent.com/52712940/114653574-ea447e80-9d1a-11eb-8cf9-cab60bac7e37.png)
以下是debug
![QQ空指针截图](https://user-images.githubusercontent.com/52712940/114653597-f7fa0400-9d1a-11eb-87a2-5b653d89042c.png)

**Expected behavior**

**Code**
If applicable, add the code that you are using when having the issue.

**Additional context**
Add the version of Flowable that you are using, the database vendor and if you are using Flowable within Spring Boot, the Flowable Task application etc.

**Comment by tijsrademakers** [comment]
Hi,

With this information it's not possible to understand why the NPE is occurring. Please provide a unit test showing the issue so that we can reproduce it and look for the cause.

Best regards

**Comment by RClown** [comment]
[test.txt](https://github.com/flowable/flowable-engine/files/6309023/test.txt)

The code and some ideas have been uploaded to the TXT file,
You can download and copy my code for testing!

**Comment by RClown** [comment]
Param is JSON and generates a BPNM file based on JOSN ！
You can copy my code and test it！！！  Thanks

**Comment by filiphr** [comment]
Hey @RClown,

I had a look at your TXT file and I cannot run it. There are classes missing. Can you please create a minimal Java project and share it with us? Otherwise, we won't be able to help you out.

Something else that you might do is to share the BPMN XML that is generated and we could look into it as well.

**Comment by tijsrademakers** [comment]
Closing the issue due to lack of response. Please reopen with more info when there's more to share.
