### ISSUE TITLE
flowable-ui-common Version6.4.2 Start parameter problem

### ISSUE THREAD

**Issue by liuming950305** [flowable/flowable-engine#2896]
**Describe the bug**
The data source will be overwritten when the dev test environment is started

**Expected behavior**
There should not be an operation to initialize the data source in the source code, even in the dev environment

**Code**
package org.flowable.ui.common.conf;
import javax.sql.DataSource;
import org.springframework.boot.jdbc.DataSourceBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import org.springframework.context.annotation.Profile;

@Configuration
@Profile({"dev"})
public class DevelopmentConfiguration {
    protected static final String DATASOURCE_DRIVER_CLASS_NAME = "com.mysql.jdbc.Driver";
    protected static final String DATASOURCE_URL = "jdbc:mysql://127.0.0.1:3306/flowable?characterEncoding=UTF-8";
    protected static final String DATASOURCE_USERNAME = "flowable";
    protected static final String DATASOURCE_PASSWORD = "flowable";

    public DevelopmentConfiguration() {
    }

    @Bean
    @Primary
    public DataSource developmentDataSource() {
        return DataSourceBuilder.create().driverClassName("com.mysql.jdbc.Driver").url("jdbc:mysql://127.0.0.1:3306/flowable?characterEncoding=UTF-8").username("flowable").password("flowable").build();
    }
}

**Additional context**
Flowable-ui-common Version6.4.2
I hope you guys will fix this verision, Just remove that code. It set the test datasource into the primary datasource, so the configuration of mine will be override.

**Comment by MasterLover** [comment]
just exclude configuration

**Comment by liuming950305** [comment]
I just fix it in my local env. And i saw Version 6.6.0 already remove this configuration file. Thanks anyway.

**Comment by liuming950305** [comment]
> just exclude configuration

I just fix it in my local env. And i saw Version 6.6.0 already remove this configuration file. Thanks anyway.

**Comment by MasterLover** [comment]
@tijsrademakers  now you can close this issue

**Comment by tijsrademakers** [comment]
Thanks @MasterLover
