### ISSUE TITLE
Conflict between flowable 6.6 and mysql-connector-java8.0.23

### ISSUE THREAD

**Issue by kwongting** [flowable/flowable-engine#2899]
#### Environment
org.flowable:flowable-engine:jar:6.6.0
mysql:mysql-connector-java:jar:8.0.23

#### Steps to Reproduce the Issue
When i start demo, it appears in mysql-connector-java8.0.23 java.lang.ClassCastException : java.time.LocalDateTime cannot be cast to java.lang.String , and found that the database datetime field is mapped to localdatetime in mysql-connector-java8.0.23, but the code does not judge the localdatetime and fails to Type Cast

#### Supplementary comments
when i change mysql-connector-java version to 5.1.49，it was compiled
`Caused by: java.lang.ClassCastException: java.time.LocalDateTime cannot be cast to java.lang.String
	at liquibase.changelog.StandardChangeLogHistoryService.getRanChangeSets(StandardChangeLogHistoryService.java:328)`

**Comment by MasterLover** [comment]
you can see #2836

**Comment by tijsrademakers** [comment]
Closing issue because of duplicate.
