### ISSUE TITLE
Can't run flowable-ui.war apps standalone with oralce driver

### ISSUE THREAD

**Issue by zeng-weijin** [flowable/flowable-engine#2900]
**Describe the bug**
When running the UI as a standalone application the database driver can be added by using the loader.path property.

java -Dloader.path=/location/to/your/driverfolder -jar flowable-ui.war

**Expected behavior**
Caused by: java.lang.IllegalStateException: Cannot load driver class: oracle.jdbc.OracleDriver.

The loader.path need PropertiesLauncher,but  flowable-ui.war META-INF\MANIFEST.MF Main-Class is 
org.springframework.boot.loader.WarLauncher.
so,can't run flowable-ui.war apps standalone.
**Code**
Manifest-Version: 1.0
Created-By: Maven Archiver 3.4.0
Build-Jdk-Spec: 13
Implementation-Title: flowable-ui-app
Implementation-Version: 6.6.0
Implementation-Vendor: Flowable
Main-Class: org.springframework.boot.loader.WarLauncher
Start-Class: org.flowable.ui.application.FlowableUiApplication
Spring-Boot-Version: 2.3.4.RELEASE
Spring-Boot-Classes: WEB-INF/classes/
Spring-Boot-Lib: WEB-INF/lib/

**Comment by filiphr** [comment]
You can't use the loader path with the war. You'll have to deploy your application in an application container like Tomcat and add the driver to the tomcat libs folder or patch the war and add the driver to it.
