### ISSUE TITLE
flowable-ui/admin/#/process-instances error accurred

### ISSUE THREAD

**Issue by toalaska** [flowable/flowable-engine#2919]
when i open https://127.0.0.1/flowable-ui/admin/#/process-instances

and then an error occurred
 the http request is:

Request URL: https://127.0.0.1/flowable-ui/admin-app/rest/admin/process-instances
Request Method: POST
Status Code: 400 
Remote Address: 127.0.0.1:443
Referrer Policy: strict-origin-when-cross-origin

and the response is :

{"message":"An error occurred while calling Flowable: HTTP/1.1 302 ","messageKey":"GENERAL.ERROR.BAD-REQUEST"}

**Comment by toalaska** [comment]
![image](https://user-images.githubusercontent.com/6500094/116819798-3b21f700-aba4-11eb-975a-a4b97cbdce5d.png)

**Comment by yvoswillens** [comment]
Hi,

How are you starting the Flowable UI app?
Can you provide some additional server logging?
And can you verify that the Flowable Admin endpoints are valid (by executing the Check REST endpoint).

Regards

Yvo

**Comment by filiphr** [comment]
Closing this due to lack of response. If we get some more feedback we can reopen it
