### ISSUE TITLE
Method for passing custom bindings to script engines used for scripting tasks

### ISSUE THREAD

**Issue by tck42** [flowable/flowable-engine#2923]
**Is your feature request related to a problem? Please describe.**
I'm trying to use graaljs on openjdk (as a library) as a scripting provider to Flowable. By default the js environment provided is heavily locked down on purpose. Methods are provided via the graaljs specific api to decrease these lockdowns; there are workarounds for the jsr223 route, but they are not options when using for Flowable ScriptTasks (as far as I can see). Please see https://github.com/oracle/graaljs/blob/master/docs/user/ScriptEngine.md for details. Specifically, I think I will need to tweak Host and Classloader access to true in order to call execution.setVariable from inside a script.

**Describe the solution you'd like**
I suppose unless there's a better way, it'd be nice to be able to postprocess engines and bindings before use. That way i could check the engine type, verify that it's graaljs, and add the bindings described in the article. It might also be useful to have this so that I can add other custom bindings that the all my scripts could use.

**Describe alternatives you've considered**
I was thinking maybe I could somehow get a handle to the script engine before it's used via runtimeservices but I'm not seeing the way there, and even so I'd need to process the bindings which are generated each evaluation.

Only other workarounds are alternate scripting providers, and just using a java ServiceTask instead (which is what I will have to do in this case).

If there's some other workaround I'm missing, I'm happy to use that instead.

**Additional context**
Nothing i can think of.

**Comment by filiphr** [comment]
Have you looked into the [`ResolverFactory`](https://github.com/flowable/flowable-engine/blob/master/modules/flowable5-engine/src/main/java/org/activiti/engine/impl/scripting/ResolverFactory.java) and [`ScriptEngines`](https://github.com/flowable/flowable-engine/blob/master/modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/scripting/ScriptingEngines.java)?

In addition to those, have you thought about contributing a fully fledged graaljs support to Flowable?

**Comment by tck42** [comment]
I had not, I had pretty much just looked at ScriptEngines enough to see that the existing version didn't seem to present a way for me to pass those values; thanks for pointing me in the right direction. I'll spend some time getting familiar with all of org.flowable.common.engine.impl.scripting and create a PR. 

Will close this for now; Thanks!
