### ISSUE TITLE
Translation to spanish

### ISSUE THREAD

**Issue by sibok666** [flowable/flowable-engine#293]
@tijsrademakers @yvoswillens 
Hi there, currently Im working on the translation of the UI Apps to spanish language.

Currently I have the next apps, translated:

1. modeler-app
2. idm-app
3. task-app

Im working on the next translations:

1. modeler-app-editor
2. admin-app

In the next few days I will send a PR to upload the es.json files of that modules.

If you have any suggestions about translation tell me.

Best regards.

**Comment by tijsrademakers** [comment]
Merged the PR of @yvoswillens https://github.com/flowable/flowable-engine/pull/292. Now your Spanish language files should automatically be picked up when present.

**Comment by sibok666** [comment]
Merged the first version of the translation in spanish.

Tested with browser locale config and work ok.

Committed on 
https://github.com/flowable/flowable-engine/commit/f8d542cbc04df4507dacfe202cf85e9e7aa35678
