### ISSUE TITLE
Could not get a result from taskService.createTaskQuery() after start a process instance in a custom command

### ISSUE THREAD

**Issue by iamKyun** [flowable/flowable-engine#2934]
**Describe the bug**
I had got some problems when I tried to use  `ManagementService#executeCommand()` .
Here is my process, just a simple process with one **UserTask** :

```xml
<process id="holidayRequest" name="Holiday Request" isExecutable="true">

    <startEvent id="startEvent"/>
    <sequenceFlow sourceRef="startEvent" targetRef="firstTask"/>
    <userTask id="firstTask" name="First"/>
    <sequenceFlow sourceRef="firstTask" targetRef="endEvent"/>
    <endEvent id="endEvent"/>

</process>
```

and my test cases are:

```java
@SpringBootTest(classes = ExampleApplication.class)
class ExampleApplicationTests {

    @Autowired
    private RuntimeService runtimeService;
    @Autowired
    private TaskService taskService;
    @Autowired
    private ManagementService managementService;

    @Test
    @FormDeploymentAnnotation
    public void test() {
        ProcessInstance processInstance 
                = runtimeService.startProcessInstanceByKey("holidayRequest");

        Task firstTask = taskService.createTaskQuery()
                                    .processInstanceId(processInstance.getId())
                                    .singleResult();
        
        taskService.complete(firstTask.getId());

        assertNotNull(firstTask);
        assertEquals("firstTask", firstTask.getTaskDefinitionKey());

    }

    @Test
    @FormDeploymentAnnotation
    public void test2() {
        managementService.executeCommand(commandContext -> {
            RuntimeService runtimeService = CommandContextUtil
                    .getProcessEngineConfiguration(commandContext)
                    .getRuntimeService();
            TaskService taskService = CommandContextUtil
                    .getProcessEngineConfiguration(commandContext)
                    .getTaskService();

            ProcessInstance processInstance 
                    = runtimeService.startProcessInstanceByKey("holidayRequest");

            Task firstTask = taskService.createTaskQuery()
                                        .processInstanceId(processInstance.getId())
                                        .singleResult();

            assertNotNull(firstTask);
            assertEquals("firstTask", firstTask.getTaskDefinitionKey());

            return null;
        });
    }
}
```
**Expected behavior**
The method  `test1()`  was passed.
I thought method `test2()`  would pass, but it was failed with a NullPointerException because  `firstTask`  was null.

What I want is to do the same things like test1()， but in a Command.
How am I surpose to do ?

**Additional context**
Flowable version:
```xml
<dependency>
   <groupId>org.flowable</groupId>
   <artifactId>flowable-spring-boot-starter</artifactId>
   <version>6.6.0</version>
</dependency>
```
Database:
MySQL 8.0.22 running in docker
```bash
docker run -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=mysql -d mysql --lower_case_table_names=1
```

**Comment by 4gsim** [comment]
During the execution of the command by the management service there exists a command context and it can be reused, this means for your case nothing is flushed to the database. 
When you try get the task from the task service it tries to get it from the database, where it does not exist. 

You could configure the engine with a command config that does not allow reuse of context.

`new StandaloneProcessEngineConfiguration().setDefaultCommandConfig(new CommandConfig(false));`

Or you could close and remove the context after the process is started.

`commandContext.close();
 Context.removeCommandContext();`

**Comment by iamKyun** [comment]
> During the execution of the command by the management service there exists a command context and it can be reused, this means for your case nothing is flushed to the database.
> When you try get the task from the task service it tries to get it from the database, where it does not exist.
> 
> You could configure the engine with a command config that does not allow reuse of context.
> 
> `new StandaloneProcessEngineConfiguration().setDefaultCommandConfig(new CommandConfig(false));`
> 
> Or you could close and remove the context after the process is started.
> 
> `commandContext.close(); Context.removeCommandContext();`

Thanks! It helps a lot.
