### ISSUE TITLE
Build scripts not updated

### ISSUE THREAD

**Issue by phxgbl** [flowable/flowable-engine#2976]
**Describe the bug**
Though there was a project structure change in the last release, build scripts like start-idm.sh or start-ui.sh not updated

**Expected behavior**
Script execution should run successfully. Only build-all.sh is working correctly.

**Code**
```
#!/bin/bash
cd ../modules/flowable-ui-task
./start.sh
```
**Additional context**
master branch

**Comment by tijsrademakers** [comment]
Hi @phxgbl , the start-idm.sh and start-ui.sh scripts don't exist anymore.
