### ISSUE TITLE
Flowable Turn off flowable version check and flowable database table creation field check

### ISSUE THREAD

**Issue by zhang1995632** [flowable/flowable-engine#2977]
The workflow checks the database and generates the database table statement configuration file does not have, 
currently using Flowable 6.4.2 I how to check the database and create the table to remove.
      Do we need to re-implement this part of the AppEngine that automatically injects AppEngineFactoryBean into the
 initial database?

**Comment by zhang1995632** [comment]
@filiphr

**Comment by filiphr** [comment]
@zhang1995632 there is really no need to ping anyone. In addition to this you can use the [Flowable Forum](https://forum.flowable.org/) for asking questions.

There are different ways you can turn of the version check and table creation. You'll need to set the `databaseSchemaUpdate` to `none` or `ignore` in order for that to be done. When using Spring Boot you can se `flowable.database-schema-update` to `none` or `ignore` for that to take effect

**Comment by zhang1995632** [comment]
When Spring Boot Flowable starts, close the table that created the flowable.

I have checked the database-schema-update configuration without any relevant configuration to turn off database table creation。
spring boot flowable 启动时, 关闭启动创建flowable的表。
我查看了database-schema-update 的配置 都没有相关配置关闭数据库表创建
我英文不太好， 通过翻译软件翻译过来的话有问题。  sorry  问题没有阐述清楚。

**Comment by filiphr** [comment]
@zhang1995632 if you set the `database-schema-update` to `ignore` or `none` it should not create the tables and will not do a verification check

**Comment by zhang1995632** [comment]
appliction.yaml 
flowable:
  database-schema-update : ignore # 第一次启动设置false
  async-executor-activate: false #关闭定时任务

![image](https://user-images.githubusercontent.com/41946899/125009001-4444ae00-e096-11eb-8989-f0232afa9dad.png)

![image](https://user-images.githubusercontent.com/41946899/125009044-5cb4c880-e096-11eb-93d0-d0e24de2197d.png)


I get the same error when I configure database-schema-update to None or Ignore

**Comment by filiphr** [comment]
You get the error because you have not created the tables. Flowable needs the tables to be present in order for the application to work. Otherwise, you can't use Flowable.

This query is done at the start of the application because it tries to deploy some app that you hve.

**Comment by zhang1995632** [comment]
At present, I do not need to check tables and create tables when the project starts. Because my project has multiple data sources, which data source flowable uses will not be determined at the start-up stage. So you need to get rid of the flowable checklist and the steps of creating a table.

**Comment by zhang1995632** [comment]
If flowable does not have a closed configuration, can I only find each engine to modify the code to close it?
