### ISSUE TITLE
Entity too large 

### ISSUE THREAD

**Issue by cholarajaa** [flowable/flowable-engine#2984]
**Describe the bug**

API: {URL}/modeler-app/rest/models/{id}/editor/json

when I am trying to save a large model which has a request size of 1.1MB(json_xml), I am getting entity too large response.
Nginx is configured to take 20MB of request payload. 

**Expected behavior**

It should save the data.

**Additional context**
Flowable version: 6.6.0
Database: Postgres 9.6

**Comment by filiphr** [comment]
Can you please share your model so we can try it out?

Have you tried increasing the request size on the Spring Boot application?

**Comment by cholarajaa** [comment]
tryied to set below config in flowable-default.properties
server.max-http-header-size=5MB
did not work!

I have added a test model renamed at .txt to upload here.
[gati_interest_reopen.txt](https://github.com/flowable/flowable-engine/files/6832885/gati_interest_reopen.txt)

**Comment by cholarajaa** [comment]
Also updated the tomcat properties, no luck

server.tomcat.max-swallow-size=5MB
server.tomcat.max-http-post-size=5MB

**Comment by cholarajaa** [comment]
This was an issue with ingress controller on kubernetes. I updated the proxy-body-size to 5MB.

This resolved the issue.
