### ISSUE TITLE
The use of flowable in jhipster results in the invalidation of liquibase

### ISSUE THREAD

**Issue by fengmingzi** [flowable/flowable-engine#2985]
flowable version 6.4.1, Jhipster uses liquibase and flowable also uses liquibase, which leads to the invalidation of liquibase in jhipster, but the flowable table can be generated. How can I solve this problem?

**Comment by filiphr** [comment]
Please use the [Flowable Forum](https://forum.flowable.org/) for asking questions.

If you check the logs you should see the following warning:


>Liquibase has not been explicitly enabled or disabled. Overriding default from Spring Boot from `true` to `false`. Flowable pulls in Liquibase, but does not use the Spring Boot configuration for it. If you are using it you would need to set `spring.liquibase.enabled` to `true` by yourself
