### ISSUE TITLE
flowable-modeler not login success

### ISSUE THREAD

**Issue by jizhengdaling** [flowable/flowable-engine#299]
Hi:
I use admin user login flowable-idm is ok。but with The same user name and password ，I can't log in flowable-modeler。 I'm sure I've been authorized 
Can you help me
 Thank you 
![1](https://cloud.githubusercontent.com/assets/17612111/23823791/20d2a3b6-06a5-11e7-9b36-8ba7cfc3d221.png)

**Comment by zhguokai** [comment]
why closed ? and how to soluve

**Comment by verheyenkoen** [comment]
Same issue. Can't get into flowable-modeler using the example scripts on both docker readme pages.

**Comment by verheyenkoen** [comment]
It's basically the same issue as this one: https://forum.flowable.org/t/docker-image-woes/566/3

```
docker run -p8080:8080 flowable/flowable-idm
docker run -p8888:8888 -e FLOWABLE_COMMON_APP_IDM-URL=http://<host-ip>:8080/flowable-idm -e FLOWABLE_COMMON_APP_IDM-ADMIN.USER=admin -e FLOWABLE_COMMON_APP_IDM-ADMIN.PASSWORD=test flowable/flowable-modeler
```

(Please note these are the exact commands as described in the docker README pages; not a single char altered).

Then logging into http://localhost:8080/flowable-idm with admin/test works. When I go to http://localhost:8888/flowable-modeler it redirects to the login, and can't get past that.

**Comment by yvoswillens** [comment]
As described in the docker hub readme the env variable FLOWABLE_COMMON_APP_IDM-URL is 'used for server to server communication'. That means the isolated docker Modeler container will use this URL to communicate with the isolated IDM container. 
So; use the IP of the docker host with the exposed port; for example 192.168.1.1:8080/flowable-idm (not localhost:8080/flowable-idm).
Or use something like Docker Compose or Kubernetes that let you configure the communication between containers. 
See https://github.com/flowable/flowable-engine/tree/master/docker for examples using Docker Compose.

Again; Please use the forum (https://forum.flowable.org) for support questions like this.
