### ISSUE TITLE
ScriptingEngines fails to cache Groovy engine instance

### ISSUE THREAD

**Issue by franck102** [flowable/flowable-engine#2993]
**Describe the bug**
org.flowable.common.engine.impl.scripting.ScriptingEngines#getEngineByName is supposed to cache engines by name, but it fails to do so because of an implementation defect.

**Expected behavior**
if the cache flag is enabled an engine used from multiple threads should only instantiate one Groovy scripting engine

ScriptingEngines uses a regular HashMap for the cache; and doesn't lock it:
`cachedEngines = new HashMap<>();`

**Comment by filiphr** [comment]
I guess that this is linked to https://forum.flowable.org/t/concurrency-defect-in-scriptingengines/8164. @jbarrez and myself have left some comments there. Can you please help us understand what the actual problem is?
