### ISSUE TITLE
ContentItemEntityImpl is missing id (contentId)

### ISSUE THREAD

**Issue by mhvtrung** [flowable/flowable-engine#2998]
**Describe the bug**
I use endpoint `/cmmn-runtime/tasks/{taskId}/variables/{variableName}/data` to get variable data and then deserialize  but the data is missing the id

**Expected behavior**
The content id is should be included after serialize
(ContentItemEntityImpl have to add protected String id);

**Code**
[https://github.com/flowable/flowable-engine/blob/master/modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/task/TaskVariableDataResource.java](url)
![image](https://user-images.githubusercontent.com/38240321/127433206-1a7f5601-6eab-4155-bb9d-fede14fee549.png)

The data before serialize
![image](https://user-images.githubusercontent.com/38240321/127432889-3aa97da3-ede9-404b-ad60-d8af36380683.png)

The data after serialize and it is been deserialize 
![image](https://user-images.githubusercontent.com/38240321/127432845-3ccf2a63-fbd6-4873-bfc8-e12dbd7df55e.png)

**Comment by filiphr** [comment]
The ContentItemEntity is not meant to be serialised as a variable in such a way. You will need to find a different way to store the information.
