### ISSUE TITLE
If multiple databases in an instance of a MySQL database need to store a flowable engine, only the first database can automatically create a table successfully.

### ISSUE THREAD

**Issue by chengshengru** [flowable/flowable-engine#3011]
**Describe the bug**
Assuming that your application configures the A database first and then starts, then the table required by the flowable engine can be automatically generated normally in the A database, and then the A database will be changed to a B database to restart the application. At this time, the B database will not be able to automatically generate the table required for flowable, prompting that "Table 'B.act_ge_property' is not't exist". If all the tables in the A database are cleared, B can automatically generate the table successfully.

**Expected behavior**
A and B databases can automatically create tables independently of each other.

**Comment by tijsrademakers** [comment]
When booting the Flowable engine a check is done (by default) if tables need to be created. When switching from database A to B the tables will be created in the B database.

**Comment by chengshengru** [comment]
> When booting the Flowable engine a check is done (by default) if tables need to be created. When switching from database A to B the tables will be created in the B database.


In the same MySQL instance, if the required tables of Flowable already exists in data A, after switching to the B database, the B database cannot automatically successfully generate the corresponding tables.

**Comment by tijsrademakers** [comment]
Hi @chengshengru, the problem is that the user has access to both databases and therefore Flowable thinks that the schema is already created. An easy solution is to allow the user only access to one database. So to have specific users per database, then it will work fine
