### ISSUE TITLE
Migration guide not on flowable.org

### ISSUE THREAD

**Issue by aaronkavlie-wf** [flowable/flowable-engine#302]
[This migration guide](https://github.com/flowable/flowable-engine/blob/a105489f29185008dd864370b93dec7eea229bbf/userguide/src/en/migration.adoc) is a useful document, but I can't find it anywhere on flowable.org. It should be exposed somewhere.

**Comment by sibok666** [comment]
if you clone o download the repo from github, the doc are in the next dir:

flowable-root\userguide\src\en

**Comment by yvoswillens** [comment]
Thanks for reporting.

Link to migration site is added to the site.
