### ISSUE TITLE
Only Service Task in workflow is possible

### ISSUE THREAD

**Issue by Vinoth1116** [flowable/flowable-engine#303]
i new to this concept. I tried to create workflow with only service task(Java task). I am able to deploy the bpmn xml file but not able to get the task list. the below code is returning 0 task. Can any one help me here.

<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:flowable="http://flowable.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath" targetNamespace="http://www.flowable.org/processdef">
  <process id="sampleProcessWithoutUser" name="Sample Process Without User" isExecutable="true">
    <documentation>Sample Process Without User</documentation>
    <startEvent id="startFlow" name="Start Flow"></startEvent>
	<sequenceFlow id="fCSAssociation" name="FCSAssociation" sourceRef="startFlow" targetRef="feasibilityCheckService"></sequenceFlow>
    <serviceTask id="feasibilityCheckService" name="Feasibility Check Service" flowable:async="true" flowable:class="org.flowable.FeasibilityCheckService"></serviceTask>   
	<sequenceFlow id="endFlowAsso" name="End Flow Asso" sourceRef="feasibilityCheckService" targetRef="endFlow"></sequenceFlow>	
    <endEvent id="endFlow" name="EndFlow"></endEvent>    
  </process>
</definitions>

List<Task> tasks = taskService.createTaskQuery().processInstanceId(processInstance.getId()).list();
		System.out.println("You have " + tasks.size() + " tasks:");
		for (int i=0; i<tasks.size(); i++) {
		  System.out.println((i+1) + ") " + tasks.get(i).getName());
		  
		}

**Comment by yvoswillens** [comment]
Hi.

Could you please use the forums (http://forum.flowable.org/) for a question like this.

Regards Yvo

**Comment by tijsrademakers** [comment]
Like Yvo already mentioned, please use the Flowable forum. When you have deployed a BPMN XML not user tasks are created automatically. You first need to start a new process instance of the deployed BPMN, and then a user task is created (when part of the process model).
