### ISSUE TITLE
timer boundary event does not trigger

### ISSUE THREAD

**Issue by baobaozhou** [flowable/flowable-engine#3037]
**Describe the bug**
When I upgraded from version 4.2 to version 5.0, I found that the timer will not trigger even if the time has expired

**Expected behavior**
Even if I turn on the asynchronous switch in the process engine configuration, the timer still does not trigger
[督导处理流程.bpmn20.zip](https://github.com/flowable/flowable-engine/files/7089089/bpmn20.zip)

**Code**
SpringProcessEngineConfiguration cfg = new SpringProcessEngineConfiguration();、
cfg.setAsyncExecutorActivate(Boolean.TRUE);

**Additional context**
flowable-spring-boot-starter-process   v6.5.0
jdk 1.8
spring-boot-starter-parent 2.3.5.RELEASE
mapper-spring-boot-starter(mybatis) 2.1.5

**Comment by tijsrademakers** [comment]
Hi @baobaozhou , can you try with the latest version of Flowable, which is 6.7.0? The timer handling works out of the box, so it should be necessary to do any additional configuration when using the Spring Boot starter.
