### ISSUE TITLE
org.flowable.ui.common.security.ApiHttpSecurityCustomizer in your configuration

### ISSUE THREAD

**Issue by liuqingshuai** [flowable/flowable-engine#3041]
**Describe the bug**

**Expected behavior**

**Code**
If applicable, add the code that you are using when having the issue.

**Additional context**
Add the version of Flowable that you are using, the database vendor and if you are using Flowable within Spring Boot, the Flowable Task application etc.

**Comment by tijsrademakers** [comment]
Closing because of lack of issue description.
