### ISSUE TITLE
using nodeport service type instead of cluster-ip

### ISSUE THREAD

**Issue by JudeNiroshan** [flowable/flowable-engine#3042]
In the k8s deployment structure, it mentioned to expose the rest unit through a `nodeport` type service. However, this service `rest-service` is already backed by an ingress object. So, my question is, why not used a `cluster-ip` service type which will not expose the k8s nodes to outside world?

https://github.com/flowable/flowable-engine/blob/96b92bfe822d4a950122694154ceacc822e7e136/k8s/resources/flowable-rest.yaml#L36

**Comment by yvoswillens** [comment]
Hi @JudeNiroshan .

Thanks for the feedback. 
Yes. Seems like a valid point.
Will have a more in depth look to evaluate this. 

Regards,

Yvo

**Comment by yvoswillens** [comment]
I'm going to close this issue.
The provided Kubernetes configuration resources are standalone examples. They are not referenced in the context of the example describing a deployment with an ingress.
In that context the Helm deployment is mentioned. The service type(s) in the Helm chart do not use `nodeport`.

But nevertheless your point is valid. When exposing these services with an load balancer / ingress it would be advised to not use `nodeport`.

Thanks for the feedback.
