### ISSUE TITLE
I want to know How assignee set value of $INITIATOR replace to available value

### ISSUE THREAD

**Issue by shanbiaozhao** [flowable/flowable-engine#3049]
I want to know How assignee set value of $INITIATOR replace to available value. Thank you!

module:  flowable-json-converter
class: UserTaskJsonConverter

![image](https://user-images.githubusercontent.com/13025746/134024857-11e92e1b-75da-41bc-808c-f3d190159e75.png)

**Comment by tijsrademakers** [comment]
Hi @shanbiaozhao,

Please use the Flowable forum for questions. Here you can see how this is used:

https://github.com/flowable/flowable-engine/blob/main/modules/flowable-ui/flowable-ui-modeler-logic/src/main/java/org/flowable/ui/modeler/service/BaseAppDefinitionService.java#L172
