### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by zidingz** [flowable/flowable-engine#3060]
Hey there!

I belong to an open source security research community, and a member (@0xamal) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by filiphr** [comment]
Hey @zidingz,

Feel free to contact me on my email address, it is in one of my commits. In the meantime we are going to look into adding a `SECURITY.md` file with needed information for the future.

**Comment by 0xAmal** [comment]
@filiphr  i have mailed you please have a look thank you

**Comment by filiphr** [comment]
Thanks for reaching out. I have reviewed the report and it is not a security issue, it is a matter of how you configure the application as an end user. Therefore, I am closing this issue.
