### ISSUE TITLE
set management.endpoint.flowable.enabled=true does not work

### ISSUE THREAD

**Issue by paigeman** [flowable/flowable-engine#3066]
**Describe the bug**
I am new guy to flowable. Recently I  had followed the [document](https://flowable.com/open-source/docs/bpmn/ch05a-Spring-Boot/#flowable-actuator-endpoints) to write an example. When I added the `management.endpoint.flowable.enabled=true` to my configuration file, I got a "404" message. But when I use `management.endpoints.web.exposure.include=*`, it worked.

**Expected behavior**
Got message below:
```
{
    "completedTaskCountToday": 0,
    "deployedProcessDefinitions": [
        "oneTaskProcess (v1)",
        "oneTaskProcess (v2)",
        "oneTaskProcess (v3)"
    ],
    "processDefinitionCount": 3,
    "cachedProcessDefinitionCount": 0,
    "runningProcessInstanceCount": {
        "oneTaskProcess (v1)": 0,
        "oneTaskProcess (v2)": 0,
        "oneTaskProcess (v3)": 1
    },
    "completedTaskCount": 0,
    "completedActivities": 2,
    "completedProcessInstanceCount": {
        "oneTaskProcess (v1)": 0,
        "oneTaskProcess (v2)": 0,
        "oneTaskProcess (v3)": 0
    },
    "openTaskCount": 1
}
```

**Code**
simply add `management.endpoint.flowable.enabled=true` to my configuration file. You can see the whole code at [here](https://github.com/FadeDemo/FlowableDemo/tree/main/spring-boot)

**Additional context**
The version of flowable is `6.7.0`
* `flowable-spring-boot-starter`
* `flowable-spring-boot-starter-actuator`

**Comment by paigeman** [comment]
@filiphr  
Hi filiphr, as you said at the end of reply:
```properties
management.endpoint.flowable.enabled=false
management.endpoints.web.exposure.include=*
```
add code below to my configuration file, I still can get message from the flowable endpoint.
In fact, in [Spring Boot Actuator document](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.enabling), there is a saying like this:

> Disabled endpoints are removed entirely from the application context. If you want to change only the technologies over which an endpoint is exposed, use the include and exclude properties instead. 

Is this saying means that I just need to set `management.endpoints.web.exposure.include` if I would like to visit the flowable endpoint through web. If so the words in [flowable user guide](https://www.flowable.com/open-source/docs/bpmn/ch05a-Spring-Boot/#flowable-actuator-endpoints) make me confused, it is easy to make readers to think that setting `management.endpoint.flowable.enabled=true` is enough already.
And this words in user guide - `Spring Boot by default only exposes the info and health endpoints.` seem to be wrong, the `flowable-spring-boot-starter-actuator:6.7.0` use `spring-boot-actuator:2.5.4` [which the info endpoint is no longger being exposed by default](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator).
Thanks for your reply :) .

**Comment by filiphr** [comment]
Seems like I have been mistaken. In Open Source we are not using `ConditionalOnAvailableEndpoint`. Which means that `management.endpoint.flowable.enabled` is not working.

In order to exclude the Flowable endpoint you need to use `management.endpoints.web.exposure.exclude=flowable`. Seems like the docs need an update about that.

>Spring Boot by default only exposes the info and health endpoints.

That seems to have indeed changed on Spring Boot side. Everything we say about Spring Boot defaults should be taken with grain of salt, since our information might be outdated. Would you like to provide a PR updating our docs?
