### ISSUE TITLE
Add option to serialize process variables as JSON

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#307]
Add option to serialize process variables as JSON into history.
Right now it seems it serializes as binary so if class structure changes it breaks.

Thanks

**Comment by tijsrademakers** [comment]
There's already a JsonType VariableType. When using a Jackson JsonNode it will get persisted as text (if not bigger than 4000 characters).

**Comment by mgrouch** [comment]
I'm not sure how can I use it.
Let's say I have serializable java bean stored in process variable and I need to make sure that
it is serialized as JSON in DB.
How would I use JsonType for it?

Thanks
