### ISSUE TITLE
Add marker interface to serialize process variables beans as JSON

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#309]
JsonType is not the option which applies to regular beans.
I'm not sure how can I use it.
Let's say I have serializable java bean stored in process variable and I need to make sure that
 it is serialized as JSON in DB.
 How would I use JsonType for it?

Thanks

**Comment by tijsrademakers** [comment]
Better to discuss this on the forum. But you can use Jackson to serialize a Java bean to a JsonNode and this will be persisted as a JSON string in the variable table.
