### ISSUE TITLE
mistake by method getRanChangeSets() of StandardChangeLogHistoryService，has  anyone met?

### ISSUE THREAD

**Issue by xushuqiang** [flowable/flowable-engine#3092]
in class: liquibase.changelog.StandardChangeLogHistoryService  method: getRanChangeSets() there is a piece of code like:
Object tmpDateExecuted = rs.get("DATEEXECUTED");
                    Date dateExecuted = null;
                    if (tmpDateExecuted instanceof Date) {
                        dateExecuted = (Date) tmpDateExecuted;
                    } else {
                        DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                        try {
                            dateExecuted = df.parse((String) tmpDateExecuted);
                        } catch (ParseException e) {
                            // Ignore ParseException and assume dateExecuted == null instead of aborting.
                        }
                    }
but the real type is java.time.LocalDateTime,makes mistake，can you add a judge of LocalDateTime？

**Comment by tijsrademakers** [comment]
Hi @xushuqiang , this class is not part of the Flowable codebase but of Liquibase. Can you open a ticket in that project instead?
