### ISSUE TITLE
startEvent with timerEventDefinition use crontab can't runnig??

### ISSUE THREAD

**Issue by github24518** [flowable/flowable-engine#3093]
startEvent with timerEventDefinition use crontab can't runnig??

this file content: 
 <startEvent id="sid-73DCB310-AB98-4566-B139-0E8CAC8D4A4A" isInterrupting="false">
      <timerEventDefinition>
        <timeCycle>0 /1 * * * ?</timeCycle>
      </timerEventDefinition>
    </startEvent>

After the workflow definition file is deployed, the instance is not executed immediately every minute, but after a long time!
Does anyone know why?

**Comment by tijsrademakers** [comment]
Hi, can you please provide a BPMN example or file that shows the issue for you? What do you mean with a "after a long time" ?

**Comment by tijsrademakers** [comment]
Closing the issue for now, but please reopen with more information when possible.
