### ISSUE TITLE
Support thrown BPMN error in triggerable Service Task

### ISSUE THREAD

**Issue by martin-grofcik** [flowable/flowable-engine#3094]
**Description:**
When triggerable service task throws BpmnError during the trigger execution, the exception is not handled by any event subprocess.

**Expected behavior**
When BpmnError is thrown in the trigger method of the triggerable service task, any event subprocess can handle error.

**Code**
https://github.com/martin-grofcik/flowable-engine/commit/27d6f23d422c0c728546f36c9b86465915baf56f
https://github.com/martin-grofcik/flowable-engine/tree/%233094_triggerableBpmnError

The proposed solution (jUnit test covers only one case) is to add try/catch blocks to all trigger calls.

**Comment by martin-grofcik** [comment]
@tijsrademakers, @jbarrez : What is your opinion?
I can contribute with the  fix for all cases.

**Comment by tijsrademakers** [comment]
@martin-grofcik , if this doesn't work right now for handling the BpmnError in event sub processes then it's a bug and good to fix.
