### ISSUE TITLE
The instance ID has been returned, but the database has not been saved successfully, and there is no exception log.

### ISSUE THREAD

**Issue by zhangxuexiang** [flowable/flowable-engine#3096]
The instance ID has been returned, but the database has not been saved successfully, and there is no exception log.

**Comment by tijsrademakers** [comment]
Flowable is fully transactional and if an instance id is returned the instance should also have been created in the database. And otherwise an exception should be available in the application log. Please provide full details on how we can reproduce the issue that you are facing with an example process definition.

**Comment by zhangxuexiang** [comment]
This kind of problem occurs occasionally, may not occur when, the version used is 6.4.2

        ProcessInstance instance;
        TransactionStatus status = transactionManager.getTransaction(new DefaultTransactionDefinition());
        try {
            ProcessInstanceBuilder instanceBuilder = runtimeService.createProcessInstanceBuilder();
            instanceBuilder.processDefinitionKey(request.getProcessDefinitionKey());
            instanceBuilder.name(request.getProcessInstanceName());
            instanceBuilder.businessKey(request.getBusinessId());
            instanceBuilder.variables(map);
            instance = instanceBuilder.start();
            if (!request.isUseRealTimeRender()) {
                bpmProcessHtmlDao.saveProcessHtml(instance.getProcessInstanceId(), request.getHtml(), request.getContent());
            }
            transactionManager.commit(status);
            log.info("createProcess：start instance success: {}", request);
        } catch (Exception ex) {
            log.error("createProcess: failed! {}", request, ex);
            transactionManager.rollback(status);
            return Result.fail(GeneralCodes.InternalError, "failed");
        }

**Comment by tijsrademakers** [comment]
You are using your own transaction handling. Flowable hooks into the Spring transaction handler if you run within a Spring environment or it uses the JDBC transaction if ran outside of Spring. If you do your own transaction handling please validate if you are covering all exception cases, but this is not a Flowable problem.
