### ISSUE TITLE
@github24518 , when a task listener throws an exception, the current transaction will be rolled back. If you want to keep the process instance then you can make the start event async for example, because then the exception will result in rolling back only until the start event and the process instance will be available in the database because it was created in another transaction.

### ISSUE THREAD

**Issue by github24518** [flowable/flowable-engine#3117]
@github24518 , when a task listener throws an exception, the current transaction will be rolled back. If you want to keep the process instance then you can make the start event async for example, because then the exception will result in rolling back only until the start event and the process instance will be available in the database because it was created in another transaction.

_Originally posted by @tijsrademakers in https://github.com/flowable/flowable-engine/issues/3116#issuecomment-976335568_

**Comment by github24518** [comment]
how start event async?

**Comment by tijsrademakers** [comment]
Please stop creating new issues for the same question, you can use the Flowable forum  to ask questions. You can define a start event to be async similar to a service task as explained here https://wwv.flowable.com/open-source/docs/bpmn/ch07b-BPMN-Constructs/#asynchronous-continuations.

**Comment by github24518** [comment]
runtimeService .startProcessInstanceByKey();   Does runtimeService  has async start method??
