### ISSUE TITLE
Add service interface to update a comment please

### ISSUE THREAD

**Issue by kernelogic** [flowable/flowable-engine#313]
See http://forum.flowable.org/t/update-comment-query-not-mapped/434

Right now getting org.apache.ibatis.exceptions.PersistenceException:

Error updating database. Cause: java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for updateComment

**Comment by tijsrademakers** [comment]
Added updateComment mapping + saveComment method in the TaskService.
