### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by yuyinhao** [flowable/flowable-engine#3136]
version: flowable-6.7.1
Execution function：runtimeService.createProcessInstanceBuilder().start()
when initializing the process, table act_ru_execution occasionally only init a piece of data。
when query task list, function VariableScopeImpl.collectVariables.getParentVariableScope Always recursive
StackOverFlowError: at org.flowable.engine.impl.persistence.entity.ExecutionEntityImpl.getParent

**Comment by yuyinhao** [comment]
![无标题](https://user-images.githubusercontent.com/30718475/144582697-2ebb8357-74bd-49a3-b8fc-5a39b5769512.png)
![无标题1](https://user-images.githubusercontent.com/30718475/144582720-abb9a941-5f76-4341-85f4-59903efe6acf.png)

**Comment by tijsrademakers** [comment]
Can you provide an example / unit test that shows the issue?

**Comment by yuyinhao** [comment]
> Can you provide an example / unit test that shows the issue?

yes，this is bpmn.xml file on the process，you only need to focus on starting the task.
execution function：

Map<String, Object> variables = new HashMap<>();
variables.put("inquiryId", "123");
runtimeService.createProcessInstanceBuilder().processDefinitionkey("inquiry").businessKey("test-key").startFormVariables(variables);

After starting a few tasks，It is possible that the situation I described above will occur

Get task list
taskService.createTaskQuery().listPage(1, 10);
Then get the task variables in a loop
taskService.getVariables("taskId")

**Comment by yuyinhao** [comment]
hello&nbsp;gangster，&nbsp;this is bpmn.xml file on the process


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flowable/flowable-engine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 晚上6:16
***@***.***&gt;;
抄送:&nbsp;"Indigo ***@***.******@***.***&gt;;
主题:&nbsp;Re: [flowable/flowable-engine] StackOverflowError (Issue #3136)





 
Can you provide an example / unit test that shows the issue?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuyinhao** [comment]
It is caused by the duplication of my id generation
