### ISSUE TITLE
Flowable v6.0.0 Download is wrong

### ISSUE THREAD

**Issue by sainwind** [flowable/flowable-engine#316]
Flowable v6.0.0 download button doesn't work well.I can't download it!Check it Please!

**Comment by yvoswillens** [comment]
Hi.

What download button are you referring to?

Regards,

Yvo

**Comment by sainwind** [comment]
http://www.flowable.org/downloads.html     "Download Flowable v6.0.0" button

**Comment by yvoswillens** [comment]
It links to 
`https://github.com/flowable/flowable-engine/releases/download/flowable-6.0.0/flowable-6.0.0.zip
`

which seems to be accessible. 
Please verify that this isn't an issue on your side. Can you access this page?

`https://github.com/flowable/flowable-engine/releases/
`

I'll close it for now. Please report back if you have this issue after verifying it from another location.

Regards,

Yvo

**Comment by tijsrademakers** [comment]
Can you download directly from the https://github.com/flowable/flowable-engine/releases/ page?
