### ISSUE TITLE
Error creating task in 6.5.0

### ISSUE THREAD

**Issue by zywhmj** [flowable/flowable-engine#3242]
**Describe the bug**
![ddcea988a87743438cef2294e36d5ae](https://user-images.githubusercontent.com/15363766/159433981-9482702c-d2bd-4f48-9a6a-0b783a1485c5.png)
![2d70030174b63a3e9588da729687a76](https://user-images.githubusercontent.com/15363766/159434039-ad0d1af7-a887-4d6f-b3e1-a5b8b9a12295.png)

Please tell me why???
**Expected behavior**

**Code**
If applicable, add the code that you are using when having the issue.

**Additional context**
Add the version of Flowable that you are using, the database vendor and if you are using Flowable within Spring Boot, the Flowable Task application etc.

**Comment by tijsrademakers** [comment]
Hi, it's important to reference the right concepts in your bug report. This is not about the number of tasks, but the number of identity links that are created. Please make a small unit test showing your issue and attach it to this issue, then we can look into it. With only some screenshots we can't give any feedback.

**Comment by zywhmj** [comment]
yes，you are right. It's actually an error in the number of links，but，why???
![1647936897(1)](https://user-images.githubusercontent.com/15363766/159437706-2760b074-636b-4a00-b12f-462347b8231d.png)
![1647937151(1)](https://user-images.githubusercontent.com/15363766/159437729-64dc4348-a8e8-4de7-8747-69e6b8f9fff4.png)

**Comment by tijsrademakers** [comment]
Like mentioned in my previous comment: "Please make a small unit test showing your issue and attach it to this issue, then we can look into it. With only some screenshots we can't give any feedback."

**Comment by zywhmj** [comment]
I'm sorry，This bug only occurs on Linux , I can't provide the code。

**Comment by zywhmj** [comment]
I'm sorry，This bug only occurs on Linux , I can't provide the code。

**Comment by zywhmj** [comment]
I'm sorry，This bug only occurs on Linux , I can't provide the code。

**Comment by tijsrademakers** [comment]
ok, I'm closing the issue then, I'm really wondering why this would be a linux specific issue since it's a Java based engine.

**Comment by zywhmj** [comment]
but，This is fine in Windows！
