### ISSUE TITLE
includeProcessVariable didn't return complete data

### ISSUE THREAD

**Issue by SabinShree** [flowable/flowable-engine#3263]
I am using flowable rest API.

``history/historic-process-instances?finished=true&processDefinitionKey=<key>&size=8000``
return all 8k data.
but when i call with params : includeProcessVariables=true, it only return 2200 data.
`` history/historic-process-instances?includeProcessVariables=true&finished=true&processDefinitionKey=<key>&size=8000
``

**Comment by tijsrademakers** [comment]
Hi @SabinShree, which version are you using?

**Comment by SabinShree** [comment]
6.6.0

**Comment by tijsrademakers** [comment]
Ok was expecting that, this is fixed in version 6.7.x with the improved paging support for process and case instances including variables.
