### ISSUE TITLE
"Mail task" may be due to the exception of the third-party upper limit, how to ignore this exception

### ISSUE THREAD

**Issue by ContinueZhang** [flowable/flowable-engine#3266]
**Exception information**
org.flowable.common.engine.api.FlowableException: Could not send e-mail in execution f005363d-b668-11ec-9de7-0242ac120002

**Desired result**
Ignore the exception and let the instance complete

**Comment by tijsrademakers** [comment]
The mail task will result in an exception in case of an error. If this is not desired a custom service task can be implemented to catch the exception and just continue the process flow.
