### ISSUE TITLE
Merge user guide chapter "BPMN Introduction" with "Getting Started"

### ISSUE THREAD

**Issue by zwets** [flowable/flowable-engine#327]
I think the Flowable user guide is excellent, almost as good as the product itself ;-). However I have a restructuring suggestion.

Chapter 7 (BPMN 2.0 Introduction) is confusingly named and placed. Firstly, it isn't really about BPMN. It focuses on Java calls (create engine, deploy process, start instance, ...), and these were already covered in chapter 2. Also, the Financial Report model it uses is somewhat 'underpowered' for a BPMN introduction, certainly when compared to the Holiday Request model introduced in chapter 2, which at least had some exciting gateways!

I suggest either moving chapter 7 into chapter 2, or remove it altogether and port the novelties it introduced (notably, the Task UI) to chapter 2. Chapter 2 could then be organised along the three modus operandi: Java API, REST API, GUI. The BPMN introduction could then precede the three by producing the shared Holiday Request model (strictly graphically; no XML or Java).

As for sequencing of the material: now that Modeler and Task are stand-alone full-featured tools, I'd do the "codeless way" before  the Javi API way. For instance,
1. BPMN Introduction: design the Holiday Request model with Modeler UI
2. Executing the model (deploy, start, claim, complete using the UI tools only)
3. Building a CLI that does the same thing (plus introduce Eclipse Modeler plugin, and write unit test) 
4. Doing the same using the REST API
5. Fitting it all together: BPMN plus Java delegates plus REST plus UI tools "all-in-one" deployment on Tomcat, plus CLI connecting to the same engine.

**Comment by zwets** [comment]
Note I wouldn't at all mind doing some work on this issue, but won't have time for it in the coming month.

**Comment by tijsrademakers** [comment]
Thanks for the ideas, makes sense indeed.

**Comment by tijsrademakers** [comment]
We added some additional getting started articles, but didn't do all the suggestions you made yet. The whole documentation can use some rethinking and rewriting. So closing this issue, but we do want to improve the documentation in the next releases.
