### ISSUE TITLE
TimerStartEnent is invalid

### ISSUE THREAD

**Issue by lxl20200830** [flowable/flowable-engine#3270]
XML config:
 `<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:flowable="http://flowable.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.flowable.org/processdef">
  <process id="Process_171f56e" name="定时启动">
    <extensionElements>
      <flowable:processText>{"pcStart":true,"appStart":true,"centerFlag":"T"}</flowable:processText>
    </extensionElements>
    <startEvent id="StartEvent_f45ec7a">
      <timerEventDefinition>
        <timeCycle>R3/PT36S</timeCycle>
      </timerEventDefinition>
    </startEvent>
    <userTask id="UserTask_1s4145j" name="定时发起">
      <extensionElements>
        <flowable:performer id="b65a3514-191d-4f17-bea8-0b50d59a98cf" routeName="账户/与流程申请人相关" routeType="USER_PROCESS_APPLICANT">{"performerType":"assignee","times":null,"exitRule":null}</flowable:performer>
      </extensionElements>
    </userTask>
    <sequenceFlow id="SequenceFlow_12yb23e" sourceRef="StartEvent_f45ec7a" targetRef="UserTask_1s4145j" />
    <userTask id="UserTask_0vcbj8k" name="定时审批">
      <extensionElements>
        <flowable:performer id="fb782e9f-132e-42be-b8ca-7581dd3bc6f7" routeName="账户/与上个节点办理人相关" routeType="USER_PREVIOUS_ACTIVITY">{"performerType":"taskAssignee","times":null,"exitRule":null}</flowable:performer>
      </extensionElements>
    </userTask>
    <sequenceFlow id="SequenceFlow_0xqc4i3" sourceRef="UserTask_1s4145j" targetRef="UserTask_0vcbj8k" />
    <endEvent id="EndEvent_0s1l53f" />
    <sequenceFlow id="SequenceFlow_1ohif05" sourceRef="UserTask_0vcbj8k" targetRef="EndEvent_0s1l53f" />
  </process>`
but actual process is not start,I try timer boundaryEvent and Timer intermediateCatchEvent ,they are OK.only timer StartEvent is invalid.

**Comment by tijsrademakers** [comment]
It's impossible to understand the problem you are raising from the provided input. Do you see an error when deploying this process definition, or does it just not start? When it's not starting, are you sure you have enabled the async executor in Flowable?

**Comment by lxl20200830** [comment]
act_ru_job will has rocord after process deploy? maybe,I want to see deploy process's deal logic...

**Comment by lxl20200830** [comment]
I upgrade process version,it's ok! if update process in current version,it will be invalid? is there method let xml change but start process by Timer Start Event?

**Comment by tijsrademakers** [comment]
Please use the Flowable forum to ask questions or discuss possible solutions to a challenge you are facing. Will close this issue now.
