### ISSUE TITLE
Insert dB and delete DB cannot guarantee the order, so the data I want to insert is deleted because the order cannot be guaranteed

### ISSUE THREAD

**Issue by fangliji** [flowable/flowable-engine#3285]
![image](https://user-images.githubusercontent.com/86839680/164728590-8e445167-b1e5-4338-9203-d5a07a390f63.png)

Insert dB and delete DB cannot guarantee the order, so the data I want to insert is deleted because the order cannot be guaranteed

**Comment by fangliji** [comment]
I mentioned this issue a few days ago. Who deleted it for me

**Comment by tijsrademakers** [comment]
Please stop creating these issues with these background pictures, it's really not appropriate. We will delete it now again.
