### ISSUE TITLE
When flowable ui and mybatis plus in one spring boot project , SqlSessionFatory conflict error will be reported

### ISSUE THREAD

**Issue by HorbieHuo** [flowable/flowable-engine#3293]
**Describe the bug**
Description:

file [F:\workspace\project\target\classes\com\***\account\dao\AccountDao.class] required a single bean, but 2 were found:
 - sqlSessionFactory: defined by method 'sqlSessionFactory' in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]
 - modelerSqlSessionFactory: defined by method 'modelerSqlSessionFactory' in class path resource [org/flowable/ui/modeler/conf/ModelerDatabaseConfiguration.class]

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

**Code**
```xml
         <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.flowable</groupId>
            <artifactId>flowable-spring-boot-starter</artifactId>
            <version>6.7.2</version>
        </dependency>
        <dependency>
            <groupId>org.flowable</groupId>
            <artifactId>flowable-spring-boot-starter-ui-idm</artifactId>
            <version>6.7.2</version>
        </dependency>
        <dependency>
            <groupId>org.flowable</groupId>
            <artifactId>flowable-spring-boot-starter-ui-modeler</artifactId>
            <version>6.7.2</version>
        </dependency>
```

**Additional context**
The flowable ui will be imported in the old peoject, and mybatis plus cannot be removed. During the start-up of the project, the error will be reported.

**Comment by duansheli** [comment]
也可以到 mybatis plus 那边的 boot  建议他们做兼容处理
