### ISSUE TITLE
Is there a way to disable the history execution of DMNs?

### ISSUE THREAD

**Issue by gustavodaquino** [flowable/flowable-engine#3353]
Good afternoon! I am using the Spring integration package, and executing a bunch of processes BPMN with DMN together.
For my purpose I disabled the history processes using the property configuration:

```
flowable:
  history-level: none
```

But, despite that, every process run executes an `INSERT INTO ACT_DMN_HI_DECISION_EXECUTION`, causing a database overflow in a huge process execution scenario.

There is a way to avoid this insertion just as process history cleanup?

Flowable version used: `org.flowable:flowable-spring-boot-starter:6.5.0`

**Comment by yvoswillens** [comment]
Hi.

When using the Spring Boot starters you can disable persisting the DMN history setting the property
`flowable.dmn.history-enabled` to `false`.

Regards,

Yvo
