### ISSUE TITLE
Flowable ：Lock wait timeout exceeded; try restarting transaction，死锁卡在自动节点不能执行

### ISSUE THREAD

**Issue by lkzlee** [flowable/flowable-engine#3357]
**Describe the bug**
![77b3f146114b478f3005aef893f56023_86831](https://user-images.githubusercontent.com/5390035/176818302-08bd4e09-0b80-4884-94fd-c62ac1521ce2.png)

**Expected behavior**

**Code**
If applicable, add the code that you are using when having the issue.

**Additional context**
Add the version of Flowable that you are using, the database vendor and if you are using Flowable within Spring Boot, the Flowable Task application etc.

**Comment by tijsrademakers** [comment]
This is not an issue with Flowable but with your database. Are you inserting a lot of jobs on a MySQL database that is not scaled for this purpose?
