### ISSUE TITLE
See to-do tasks in done tasks

### ISSUE THREAD

**Issue by luoxiaofeng1029** [flowable/flowable-engine#3359]
**Describe the bug**
See to-do tasks in done tasks

**Expected behavior**
To-do tasks should not be included in your done  list

**Code**
` HistoricProcessInstanceQuery processInstanceQuery = historyService.createHistoricProcessInstanceQuery()
                .includeProcessVariables()
                .involvedUser(SystemUtil.getStrUserId())
                .orderByProcessInstanceStartTime()
                .desc();`
**Additional context**
Can you show me how to modify this query to achieve my purpose

**Comment by luoxiaofeng1029** [comment]
@filiphr

**Comment by filiphr** [comment]
@luoxiaofeng1029 I am not sure that I understand what kind of bug you are facing.

Looking at what you wrote it feels like a question. Please use our [forum](https://forum.flowable.org/) for asking questions.
