### ISSUE TITLE
Duplicate variables occurs in the database when using parallel gateway

### ISSUE THREAD

**Issue by zwexcelwang** [flowable/flowable-engine#3361]
When I update a process variable in the two branches of the parallel gateway, there are duplicate variables in the database.
I use flowable 6.7.2 and mysql 5.7

**Comment by tijsrademakers** [comment]
Please share a unit test showing the problem.

**Comment by 107295472** [comment]
> Please share a unit test showing the problem.

https://github.com/flowable/flowable-engine/issues/3354

**Comment by zwexcelwang** [comment]
I am sorry.
I have encountered this twice in flowable6.7.2, but I can’t reproduce it, it happens occasionally. In flowable6.4.2, is reproducible, You can reproduce it with this flowchart.
I use this api : @PostMapping(value = “/runtime/tasks/{taskId}/variables”
Let me know if you need any other info
















At 2022-07-01 17:45:13, "Tijs Rademakers" ***@***.***> wrote:

Please share a unit test showing the problem.
