### ISSUE TITLE
About DmnDecisionService two bug

### ISSUE THREAD

**Issue by linlinjie** [flowable/flowable-engine#3381]
I found two bug，about  about the use of dmn.
---------------------------------
One fo them is when i deploy Dmn model,i found if set 'tenantId', when use DmnDecisionService execute,DmnDecisionService can't find DecisionKey. I debug it, i find this sql may be a problem,

org.flowable.dmn.engine.impl.persistence.entity.data.impl.MybatisDecisionDataManager#findLatestDecisionByKeyAndTenantId

select *
from ACT_DMN_DECISION 
where KEY_ = ? and
(TENANT_ID_ = ''  or TENANT_ID_ is null) and
          VERSION_ = (select max(VERSION_) from ACT_DMN_DECISION where KEY_ = ? and (TENANT_ID_ = '' or TENANT_ID_ is null))
Thsi query sql request tenantId is '' or null.I wonder about that。
my deploy dmn model code:
        DmnDeployment deploy = dmnRepositoryService.createDeployment()
                .name(fileName)
                // Don't set 'tenantId'，otherwise when use DmnDecisionService execute,DmnDecisionService can't find DecisionKey
                //.tenantId(tenantId)
                .addDmnModel("DEC_TABLE_001" + ".dmn", dmnDefinition)
                .category("dmn-test")
                .deploy();

My demo code:
Map<String, Object> stringObjectMap = dmnDecisionService.createExecuteDecisionBuilder()
                .decisionKey("DEC_TABLE_001")
                .variable("customerCat", "gold")
                .executeWithSingleResult();
----------------------------
The second question，i don't set tenantId,Then i use dmnDecisionService to executed,the following error will appear
org.flowable.common.engine.api.FlowableException: deployment 'be452e96-fd18-11ec-b8bb-bee68ec73c78' didn't put decision 'be50a048-fd18-11ec-b8bb-bee68ec73c78' in the cache

source code
org.flowable.dmn.engine.impl.parser.DmnParse#execute  102line,

                     DecisionEntity decisionEntity = CommandContextUtil.getDmnEngineConfiguration().getDecisionDataManager().create();
                        decisionEntity.setKey(decision.getId());
                        decisionEntity.setName(decision.getName());
                        decisionEntity.setResourceName(name);
                        decisionEntity.setDeploymentId(deployment.getId());
                        decisionEntity.setDescription(decision.getDescription());
                        decisionEntity.setDecisionType(DecisionTypes.DECISION_TABLE);
                        decisions.add(decisionEntity);
                        
no initialization id

**Comment by linlinjie** [comment]
flowable-dmn-engine-6.7.2-sources.jar!/org/flowable/dmn/engine/impl/parser/DmnParse.java:103

**Comment by yvoswillens** [comment]
Hi @linlinjie 

Thanks for the feedback.
Could you provide a PR (including unit tests)?
That would be great.

Regards,

Yvo

**Comment by tijsrademakers** [comment]
Hi @linlinjie ,

When a tenant id is set at deployment and no tenant id is used when executing the decision key it's by design that the decision can not be found. You need to be consistent and always use a tenant id or not use a tenant id at all.
