### ISSUE TITLE
Async parallel gateway createcreates duplicate outgoing executions

### ISSUE THREAD

**Issue by zwexcelwang** [flowable/flowable-engine#3404]
Helo, I have a similar problem to this one, the node behind the async join gateway would execute twice.
https://forum.flowable.org/t/async-inclusive-joining-gateway-creates-duplicate-outgoing-executions/7122/2
https://github.com/flowable/flowable-engine/commit/ffa4e4ada905f3a37b7aa172f15d014b2f876d15
 I find that you have fixed it in 6.7.0, but I encounter this problem in 6.7.2, you can reproduce it with this.

![image](https://user-images.githubusercontent.com/32516174/180953186-9fb18bb3-8601-46e8-b8d6-3abb3ebdbca4.png)

**Comment by jbarrez** [comment]
Can you share the BPMN XML? Have you made the joining gateway exclusive, as in the test linked to that forum post: https://github.com/flowable/flowable-engine/commit/ffa4e4ada905f3a37b7aa172f15d014b2f876d15#diff-547f285c6b565c5009e0a2d6cc02127c6359cc70fd43dd0b1e2cf138de560e6dR23 ?

**Comment by zwexcelwang** [comment]
Oh！I'm sorry, I forgot to add the exclusive attribute. Thanks for your reply. Finally, my apologies to you again.




---- Replied Message ----
| From | Joram ***@***.***> |
| Date | 07/26/2022 16:23 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [flowable/flowable-engine] Async parallel gateway createcreates duplicate outgoing executions (Issue #3404) |

Can you share the BPMN XML? Have you made the joining gateway exclusive, as in the test linked to that forum post: ffa4e4a#diff-547f285c6b565c5009e0a2d6cc02127c6359cc70fd43dd0b1e2cf138de560e6dR23 ?
