### ISSUE TITLE
Test Smell: it is not a good practice to use nondeterministic random generators in test cases

### ISSUE THREAD

**Issue by TestSmell** [flowable/flowable-engine#3433]
Hi!
we notice that you use a random string generator in your test case.
For example, testUpdateFromSmallToLongJsonValue() in JsonTest.java
<img width="856" alt="image" src="https://user-images.githubusercontent.com/110402847/184865348-4839dca9-39df-44e3-a434-f3637d11f26f.png">

However, it is not a good practice to use the nondeterministic random generator in test cases since
1. using random values means the test isn't truly repeatable (which also means that if the test can randomly fail, it can do so on the build server and break the build)
2. if it's a random value and the test fails, we need to a) fix the object and b) force ourselves to test for that value every time, so we know it works, but since it's random we don't know what the value was
3. If you are testing an exception, random values will not ensure that the test ends up in the expected state.

potential solution:
you can use'' java.lang.String.hashCode()'' to generate deterministic random string in your test code. Thanks.

**Comment by filiphr** [comment]
The goal of the test is to test a string with a particular size. We do not care about the randomness of the test. Therefore, this test is doing its job properly.
