### ISSUE TITLE
JobQueryImpl is missing getHandlerTypes()

### ISSUE THREAD

**Issue by ikaakkola** [flowable/flowable-engine#3437]
While prototyping alternative DataManagers, I noticed that JobQueryImpl does not expose getHandlerTypes().

This means that a custom JobDataManager cannot fully implement the JobQuery (without reflection or similar tricks to access the protected handlerTypes field) as it cannot get the value of the possibly configured handlerTypes (https://github.com/flowable/flowable-engine/blob/main/modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/JobQueryImpl.java#L266-L272)

**Comment by filiphr** [comment]
Thanks for the raising the issue and the PR @ikaakkola. It will be merged once the tests run. Just FYI, the DataManagers are not part of the public API and thus things might change in a patch release.

**Comment by ikaakkola** [comment]
@filiphr Thanks, I'm aware that they are not public API and am taking precautions to notice any changes they might have.
Remember
