### ISSUE TITLE
Help how to use “variableType” in resultMap 

### ISSUE THREAD

**Issue by camellia57** [flowable/flowable-engine#3445]
![image](https://user-images.githubusercontent.com/68042888/186398912-0e93bd84-6c5a-4228-b018-610c198a5ab4.png)

<result property="variableType" column="VAR_TYPE_" javaType="org.flowable.variable.service.impl.types.VariableType" typeHandler="org.flowable.variable.service.impl.db.IbatisVariableTypeHandler"  jdbcType="VARCHAR" />

run error：
org.flowable.variable.service.impl.db.IbatisVariableTypeHandler.<init>()

**Comment by filiphr** [comment]
@camellia57 this looks like a question for how to use MyBatis. Please use our [Forum](https://forum.flowable.org/) for asking questions.
