### ISSUE TITLE
flowable-idm fails to start: relation "act_id_user" does not exist

### ISSUE THREAD

**Issue by zwets** [flowable/flowable-engine#345]
Using Tomcat 8 with PostgreSQL configured using JNDI data source.

When deploying the four UI apps (task,admin,modeler,idm) on Tomcat 8, having created the database beforehand with the distributed database scripts, the first three apps start fine but the IDM fails with a PersistenceException: `### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: relation "act_id_user" does not exist`

See attached catalina.out
[catalina.out.txt](https://github.com/flowable/flowable-engine/files/914656/catalina.out.txt)

**Comment by tijsrademakers** [comment]
Did you run the IDM database scripts as well? Are you talking about the database scripts that are provided as part of the Flowable 6.0.0 release zip file?

**Comment by zwets** [comment]
When I ran the IDM database script (from the sources) everything was fine. The IDM database scripts aren't included in the release zip file. Adding the appropriate fileset to the `copy.sql` target in `distro/build.xml` fixes this. I didn't file a pull request because I wasn't sure whether the omission was intentional.

**Comment by tijsrademakers** [comment]
Added the IDM database scripts to the distribution as well now, thanks.
