### ISSUE TITLE
Npe error occurred when obtaining process variables after using changeState Api

### ISSUE THREAD

**Issue by llliu000** [flowable/flowable-engine#3472]
![image](https://user-images.githubusercontent.com/37445155/191432457-1c2f3874-0890-4b02-bc10-f0a32b7fe3b8.png)
![image](https://user-images.githubusercontent.com/37445155/191432610-f8a2e1c4-98a3-4a96-8103-c7bd44f00492.png)
![image](https://user-images.githubusercontent.com/37445155/191432665-4b4192ed-dfa1-4ae9-9f27-81f2574a4ef3.png)

**Comment by tijsrademakers** [comment]
Hi, please create a unit test showing the issue and add it to this ticket.

**Comment by llliu000** [comment]
![image](https://user-images.githubusercontent.com/37445155/191446178-fb342b62-720b-4399-be15-dbbbbb7a9a6c.png)
@tijsrademakers 
I found in the main branch that this problem has been solved, but the latest version 6.7.2 I used did not solve this problem. Thank you
