### ISSUE TITLE
Event JOB_EXECUTION_SUCCESS is dispatched before the job is executed

### ISSUE THREAD

**Issue by thomasulllrich** [flowable/flowable-engine#3480]
Hi!

in the logfile I see that the JOB_EXECUTION_SUCCESS event is already raised but the related job is a bit later executed.
We faced in class ExecuteAsyncRunnableJobCmd the behavior seen at first in the logfile. 

Our expectation is that the job/servicetask is executed at first and afterwards the event is raised. Please correct me if I am wrong.

Best regards,
Thomas

**Comment by tijsrademakers** [comment]
Hi Thomas, in the ExecuteAsyncRunnableJobCmd first the following line is executed:

jobServiceConfiguration.getJobManager().execute(job);

This means that the job handler is invoked to executed the job logic. Can you share why you came to the conclusion that the job is then not executed yet?

**Comment by thomasulllrich** [comment]
Hi Tijs,

the call jobServiceConfiguration.getJobManager().execute(job);
ends here 
AsyncContinuationJobHandler.execute
and here it seems to be queued:
CommandContextUtil.getAgenda(commandContext).planContinueProcessSynchronousOperation(executionEntity);

Then the success event is raised and a bit later this is called:
AbstractEngineConfiguration ->
    protected AgendaOperationRunner agendaOperationRunner = (commandContext, runnable) -> runnable.run();

and here the real execution of the ServiceTask takes place.

Do you need more details?

BR,
Thomas

**Comment by tijsrademakers** [comment]
Hi Thomas,

Ok I get what you mean now :-) When this is planned on the agenda it basically means that the job itself has succeeded and planned the next step to be executed. So from our point of view the event is correct. 

Best regards

**Comment by thomasulllrich** [comment]
Hi Tijs,

ok I see but isn't the name of the event wrong then. Shouldn't it be something like JOB_EXECUTION_PLANNED and what is the name of the successful execution event?

BR,
Thomas
