### ISSUE TITLE
Doubt regarding fetching of all variables

### ISSUE THREAD

**Issue by shameekagarwal** [flowable/flowable-engine#3482]
About [all variables being fetched from the database](https://github.com/flowable/flowable-engine/blob/flowable-6.7.2/docs/docusaurus/docs/bpmn/ch04-API.md#:~:text=For%20historical%20(and%20backwards%2Dcompatibility%20reasons))
1. is it for that particular process instance?
2. if so, then using the caching behavior and not passing the boolean is preferable right, assuming our bpmn would be limited to approx 10 or so variables?

**Comment by tijsrademakers** [comment]
Yes this is for a specific process instance, not for more than one. It's fine to just use the api like described, you should not experience any issues.
