### ISSUE TITLE
taskService complete report the error 

### ISSUE THREAD

**Issue by JobHu** [flowable/flowable-engine#3483]
cannot delete or update a parent row:foreign ley constraint fails(ACT_RU_IDENTITY constraint ACT_RU_TASK),
when  taskService.complete(tid, variables).

**Comment by tijsrademakers** [comment]
This means that an identity link still exists for a task that you are deleting / completing. Please share a unit test showing the issue so we can try to reproduce it.

**Comment by JobHu** [comment]
flowable support deploy multiple services?

**Comment by JobHu** [comment]
not only one machine

**Comment by JobHu** [comment]
Micro service support high availability?

**Comment by JobHu** [comment]
@tijsrademakers
