### ISSUE TITLE
Spring Boot Auto-configuration Registration has changed

### ISSUE THREAD

**Issue by ningpp** [flowable/flowable-engine#3489]
**Describe the bug**
flowable still use META-INF/spring.factories file for Registration.

**Expected behavior**
use META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports.

**Code**
If applicable, add the code that you are using when having the issue.

**Additional context**

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7.0-M2-Release-Notes#changes-to-auto-configuration

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes#auto-configuration-registration

**Comment by filiphr** [comment]
@ningpp you are right that spring has deprecated the auto configuration registration. Currently, we have a policy of supporting multiple Spring Boot versions. This means that we will have to use the deprecated approach in 2.7. Once we switch to Spring Boot 3.0 we are going to update the registration

**Comment by ningpp** [comment]
thank you

**Comment by ningpp** [comment]
commit 961a68981dd21f78b6d0171eb4770509583c28f8
