### ISSUE TITLE
Multiple bugs in error propagation 

### ISSUE THREAD

**Issue by explorer566** [flowable/flowable-engine#350]
When a sub process element has two error boundary events, one with a specific error code and one without, the first one should be chosen, when the error codes match.

In my case during execution of the sub process an error end event is executed calling method _propagateError_ of class _org.flowable.engine.impl.bpmn.helper.ErrorPropagation_. In method _findCatchingEventsForProcess_  both error boundary events of the parent process are correctly found and returned in the same list as value of the returned event map but in method _executeCatch_  (line 157) simply the first error boundary event in the list (in my case the one without error code) is chosen and propagated without checking the other error boundary event in the list for a matching error code.

I attached a small example to demonstrate the error.
[example.zip](https://github.com/flowable/flowable-engine/files/950640/example.zip)

I also found out that the complete error propagation fails, when in method _propagateError_ the first call of method _findCatchingEventsForProcess_ returns an eventMap with irrelevant error boundary events and then method _executeCatch_ is called. In case of a call activity you get a "No matching parent execution for error code" exception because the search for catching events only includes parent executions but not super executions.

I attached a small example for this type of error too.
[error_example.zip](https://github.com/flowable/flowable-engine/files/950712/error_example.zip)

**Comment by tijsrademakers** [comment]
Fixed the propagation issue with the empty and filled-in error code. For the exception case I don't see it's causing real issues other than a misleading error message, or am I missing something?

**Comment by explorer566** [comment]
Hi Tijs,

 

in the exception case the thrown exeption leads to the result that the error code of the error end event is not caught at all by the error boundary event of the sub process, so it does matter for me.

Did you run my example?

 

Cheers

Ralf



Gesendet: Mittwoch, 26. April 2017 um 12:26 Uhr
Von: "Tijs Rademakers" <notifications@github.com>
An: flowable/flowable-engine <flowable-engine@noreply.github.com>
Cc: "Ralf Fritsche" <explore_life@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [flowable/flowable-engine] Multiple bugs in error propagation (#350)


Fixed the propagation issue with the empty and filled-in error code. For the exception case I don't see it's causing real issues other than a misleading error message, or am I missing something?

**Comment by tijsrademakers** [comment]
Hi Ralf,

Thanks for the additional information, now I understood the issue.
I've done some rework on the ErrorPropagation class and it should work now.

Thanks,

Tijs

**Comment by explorer566** [comment]
Good job, Tijs. I tested your fix and it works in our application.

Sorry to bother you with our apparently rare approach, but our application generates BPMs and thus we are using these kinds of use cases.

Thanx
Ralf

**Comment by explorer566** [comment]
Hi Tijs,

I had a second look at your fix. In method _propagateError_ you collect all catching events of the entire super execution hierarchy in one event map. I know that it seems very unlikely, but what will happen if the same id is used for sub processes with catching events in two ore more of the involved process definitions? Then only the catching events of the last visited process definition is included in the event map.
I think it would be better to determine the event map in method _executeCatch_ after you resolve the super execution in statement _if (parentExecution.getProcessInstanceId().equals(parentExecution.getRootProcessInstanceId()) == false)_ like I proposed in my second post above.

Greetings
Ralf
