### ISSUE TITLE
Unable to use custom delete operation from Data Object service via REST API

### ISSUE THREAD

**Issue by danielpmichalski** [flowable/flowable-engine#3503]
I have a Data Object model with multiple fields. I’ve defined a custom lookup operation in the corresponding service and am able to use it via REST API.

I’ve tried adding a custom delete operation that requires several input parameters, but I’m unable to figure out how to invoke it via REST API.

The service specifies the below custom delete operation:
- key: deleteByIdKeyAndType
- type: delete
- filter parameters:
   - id: string, required, equals to corresponding DO field
   - key: string, required, equals to corresponding DO field
   - type: string, required, equals to corresponding DO field

I’ve published the app with that new operation.

Tried sending HTTP DELETE requests in the below variants, but I’ve got the same error in each case (used ‘undefined’ for id, as I want to delete all that match the filter params):

- `DELETE /dataobject-api/dataobject-runtime/data-object-instances/undefined?dataObjectOperationKey=deleteByIdKeyAndType&dataObjectDefinitionKey=myDataObjects&id=PRC-bc52b033-42b6-11ed-a56c-005056a55d9b&key=someKey&type=reject`
- `DELETE /dataobject-api/dataobject-runtime/data-object-instances/undefined?dataObjectOperationKey=deleteByIdKeyAndType&dataObjectDefinitionKey=myDataObjects`
<pre>
{
  “id”: “PRC-bc52b033-42b6-11ed-a56c-005056a55d9b”,
  “key”: “someKey”,
  “type”: “reject”
}
</pre>

Error:
<pre>
{
    "message": "Bad request",
    "exception": "To invoke the service definition My Data Objects, the input parameter id (id) is required, but there is no value provided (did you map it in the service invocation?)."
}
</pre>

**Comment by ayushdubey755** [comment]
@danielpmichalski can i work on this issue?

**Comment by filiphr** [comment]
This issue is for the enterprise product of Flowable. The `dataobject-api` is not part of Open Source. @danielpmichalski if something isn't working for you I would suggest you to open an issue through the Flowable Support Desk.

@ayushdubey755, there isn't much that you can do about this.
