### ISSUE TITLE
Password is stored in clear text in ACT_ID_USER table PWD column

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#354]
Password is stored in clear text in ACT_ID_USER.
It shouldn't even store encrypted password, it should only store its crypto hash.

Thanks

**Comment by faizal-manan** [comment]
Hi,

Currently I'm working on this issue. Instead of implement password hashing, I decided to reuse existing library. So far I've added support for Spring Security, Apache Common Codec, Jasypt and jBrypt
Let me know if I miss out any other library

Cheers,
Faizal

#419

**Comment by tijsrademakers** [comment]
Thansk Faizal, there's now an option to use password encoders.

**Comment by wirob** [comment]
Where can these options be found when one is using Docker?

I can't seem to find any documentation about this for any of the Docker images.

Thanks

**Comment by gwendew** [comment]
Hi !
Is there an update to this subject ? 
Where can these options be found when one is using Docker?
I can't seem to find any documentation about this for any of the Docker images.

**Comment by yvoswillens** [comment]
Please use the forum for asking questions like this.
This issue was closed almost 5 years ago.

You can provide configuration properties when starting a container using environment variables or as runtime arguments.

F.e.

```
docker run -e flowable.idm.password-encoder=spring_delegating_bcrypt -p8080:8080 flowable/flowable-ui:6.7.2
```

or 
```
docker run -p8080:8080 flowable/flowable-ui:6.7.2 --flowable.idm.password-encoder=spring_delegating_bcrypt 
```
