### ISSUE TITLE
Is there a plan to support spring-boot 3?

### ISSUE THREAD

**Issue by hberrayana** [flowable/flowable-engine#3548]
Spring Boot 3 was released last month and many projects are migrating towards that version to align with long-term spring boot support.

I'm aware that Flowable team is waiting for third party libraries to align with new requirement such as jakarta vs javax such as this one: https://github.com/liquibase/liquibase/issues/2991
I'd like to know if the migration of the OSS version is planned or not yet discussed?

Thanks in advance

**Comment by tijsrademakers** [comment]
Hi, yes we are actively working on a version of Flowable with Spring Boot 3 support, we will make announcements in the next few weeks. Best regards
