### ISSUE TITLE
unable to get process variables

### ISSUE THREAD

**Issue by Yojay97** [flowable/flowable-engine#3549]
hi, 

I am using spring boot test to get process variables, but it returns null. As shown in the figure below.
![image](https://user-images.githubusercontent.com/49464867/207619122-e8e562bf-6afe-468e-923f-a2cffa509a61.png)

But we can find the  process variables from the database.
![image](https://user-images.githubusercontent.com/49464867/207619510-93e35c5e-0bf0-4e19-941c-c6922ca1ab63.png)

**Comment by Yojay97** [comment]
![image](https://user-images.githubusercontent.com/49464867/207625998-e2abeb09-61e7-446a-9ee4-a9012c32971a.png)
This is the original sql I captured

**Comment by tijsrademakers** [comment]
Hi, please use the runtimeService.getVariables(processInstanceId) method to get the variables instead of directly getting them from the processInstance entity.
