### ISSUE TITLE
Add support for managing deadletter (and other) job tables in flowable-admin app

### ISSUE THREAD

**Issue by paulstapleton** [flowable/flowable-engine#355]
The flowable-admin app does not currently support looking at entries in the job deadletter table (act_ru_deadletter_job) and requeuing them in the job table (act_ru_job) when the underlying reason for the failure has been fixed.
Currently we have to do this directly in the database (or using the Java API).

It would be very useful if the deadletter queue could be managed directly from the flowable-admin app. Additionally if it was possible to view the underlying stacktrace in the flowable-admin GUI this would be a useful feature, as the server log would not need to be examined.

Support may also be needed for the other job tables like act_ru_suspended_job or act_ru_timer_job. But I have not investigated if this is the case when creating this issue.

See the forum thread here - https://forum.flowable.org/t/managing-job-deadletter-table-with-flowable-admin-app/479

**Comment by tijsrademakers** [comment]
Implemented support for other job types in admin app
