### ISSUE TITLE
SQL scripts for mysql contain explicit and incorrect charset and collation

### ISSUE THREAD

**Issue by RadekWikturna** [flowable/flowable-engine#3550]
**Describe the bug**
We are using Flowable in our SpringBoot project. 

When Flowable Spring Boot starter auto-configures Flowable, it automatically creates its database tables using SQL scripts which are part of the jar files. E.g. for MariaDB, this script is used to create the ACT_RU_TASK table:

![image](https://user-images.githubusercontent.com/120576514/207616722-ef185955-84fe-4299-ba9a-d76ce92c41c3.png)

The problem is that is explicitly includes the charset and collation `DEFAULT CHARSET=utf8 COLLATE utf8_bin` , which is the wrong one (utf8 is in fact utf8mb3 which supports only limited number of characters). So, even though our database was created with the correct charset and collation ( `CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci`), some Flowable tables (but not all) override this charset and collation. As a result, it is not possible to store some characters (e.g. emoticons) in tasks, variables etc (exception is thrown when INSERT statement is executed:

`Caused by: java.sql.SQLSyntaxErrorException: (conn=903) Incorrect string value: '\xF0\x9F\x94\x981....' for column...`

I have downloaded the full Flowable zip file which contains a complete set of scripts to create all database tables and it too contains some tables with explicit charset and collation (see the attached file).

**Expected behavior**
No explicit charset and collation is specified in any SQL files for mysql.

**Additional context**
SpringBoot 2.7.5
Flowable 6.7.1
OS: Windows 10 /Linux
Database: MariaDB 10.3 (=mysql)

[flowable.mysql.all.create.sql.zip](https://github.com/flowable/flowable-engine/files/10228526/flowable.mysql.all.create.sql.zip)

**Comment by omg1492** [comment]
There is a similar complaint on 
https://forum.flowable.org/t/utf-8-instead-of-utf8mb4-creating-problem-for-vietnamese-characters/2032?u=omg1492

**Comment by tijsrademakers** [comment]
You can adjust the default SQL files and run it against your MariaDB database directly. Then the engine will just use the already created db schema.

**Comment by RadekWikturna** [comment]
Yes, I spotted that forum complaint some time ago. And what you suggest is our current workaround - the manually corrected SQL script is executed by Liquibase and since we support MariaDB, Oracle and H2 for tests, then we need to copy 3 files and put them to a Liquibase changelog. This unnecessarily complicates our code and processes - e.g. when we upgrade to new Flowable version, then we need to extract the upgrade scripts (times 3 for 3 DB platforms) and again put them to our Liquibase changelog.  

What's worse, we also use Flowable-UI (i docker) which too automatically creates all Flowable engine tables and plus several UI related tables, which are executed by Liquibase xml changesets. So we need to make sure Flowable-UI  starts after our service or find some other workarounds. This is a pain!

Why there are DB scripts for each DB platform when you can you one Liquibase changelog and let Liquibase generate the DB platform specific SQL statements? You already do this with Flowable-UI.

**Comment by RadekWikturna** [comment]
I understand. But PLEASE, at least adjust the scripts for mysql. 
They are not consistent - 40 tables are created with explicit incorrect charset and 40 are created without it.
