### ISSUE TITLE
Process variable doesn't include JsonTypeInfo.Id.CLASS property.

### ISSUE THREAD

**Issue by jy006** [flowable/flowable-engine#3553]
I'm not sure where to post question or request for help, so for the mean time I'm gonna post here and hope someone can point me in the right direction.

Here is roughly how my process looks like:
![Screenshot from 2022-12-15 18-28-51](https://user-images.githubusercontent.com/23431933/207848311-b300586e-ef4a-4b8c-a41d-006eaad8fedc.png)

I'm starting the process by a message:
```
runtimeService.createProcessInstanceBuilder()
            .messageName("IncomingSalesOrder")
            .variable("salesOrder", salesOrderRepository.save(newSalesOrder))
            .start();
return newSalesOrder;
```
From this code, I expect to have a process variable `salesOrder` with a `SalesOrder` entity in it. Note that `SalesOrder` is a JPA Entity and it has `@JsonTypeInfo` annotation:
```
@Entity
@Data
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS)
public class SalesOrder {
            
```
Now I expect the `salesOrder` variable to have a `class` property detailing the packages `SalesOrder` class came from e.g. `com.example.model.SalesOrder`, and normally it does too!! This time I'm not sure what I missed or what changed but the `class` property is missing when getting the user tasks. The missing property is causing service tasks to not recognize the variable as an Entity, they are recognized as I believe to be LinkedHashMap, based on this error message:
```
org.flowable.common.engine.impl.javax.el.ELException: Cannot coerce .... of class java.util.LinkedHashMap to class com.example.model.SalesOrder (incompatible type)
```

One weird thing, `SalesOrder` has a `List<SalesOrderEntry>` in it, all of the order entries still have its `class` property and behaving as expected. It's only the parent SalesOrder that's missing the class property.

**Comment by filiphr** [comment]
@jy006 it seems like you are mixing JPA and Jackson. As far as I know `@JsonTypeInfo` is a Jackson annotation. We do not support persisting any object when you do something like ` .variable("salesOrder", salesOrderRepository.save(newSalesOrder))`.

We do support JPA variables by using the JPA Entity Manager, so for you need to make sure that your `@Entity` has `@Id`  (`javax.persistence.Id`) in order for the fetching to properly work.

Do you by any chance have some custom `VariableType`?

**Comment by jy006** [comment]
I guess I am mixing JPA and Jackson, my problem is probably more on Jackson and less on JPA. Flowable seems to recognize the `SalesOrder` entity, it can fetch and save.

To clarify the problem: I saved a JPA entity as a process variable and somewhere along the way it's no longer recognized as a JPA, it's recognized as a `Map<String, Object>` instead.

I'm not really familiar with custom VariableType, I don't think I have deliberately defined a custom VariableType.

**Comment by filiphr** [comment]
Flowable doesn't transform the variables. You should inspect your model and services that you are calling in order to figure out why it is being changed.

**Comment by jy006** [comment]
Okay, thanks for your help. I'm gonna call it a day and narrow it down tomorrow.
