### ISSUE TITLE
Want to add process instances that have been restarted

### ISSUE THREAD

**Issue by sgs98** [flowable/flowable-engine#3564]
Want to add process instances that have been restarted

**Comment by filiphr** [comment]
@sgs98 can you please be a bit more specific. Perhaps provide an example of what you are trying to achieve

**Comment by sgs98** [comment]
For example, my current process instance has ended, but for some reasons, I want to approve a phase again

**Comment by filiphr** [comment]
We currently do not support and do not plan to support re-starting completed process instances. 

We do have a concept of reactivation for a case instance. I would suggest trying that out instead.
