### ISSUE TITLE
About reassigning the handler function

### ISSUE THREAD

**Issue by tuke-code** [flowable/flowable-engine#3566]
Has the function of reassigning handlers been implemented? For example, I am the one who submitted the process and designated you as the handler, we used a timer for 5 minutes, and you did not process it, and then ended it directly. However, I can start a new process on the process sent to you, and the form content is the same as the content given to you. Except I can choose someone else to start the process for the handler

**Comment by tijsrademakers** [comment]
This looks like question to be asked on our user forum instead of reporting it as an issue. Can you use the forum https://forum.flowable.org/ instead? In addition, please be more precise in what you are looking for, because that's not clear right now.
