### ISSUE TITLE
ldap support not included in the official website download package

### ISSUE THREAD

**Issue by microspaze** [flowable/flowable-engine#357]
Hi,

I download the flowable package from the official website, but it does not include the ldap support which has been specified on the official website documents (http://www.flowable.org/docs/userguide/index.html#flowableUIApps).

The package download page: http://www.flowable.org/downloads.html
The package download link: https://github.com/flowable/flowable-engine/releases/download/flowable-6.0.0/flowable-6.0.0.zip

Anyone who can give a new download link to the package which support the ldap intergration?

Thanks a lot!

**Comment by tijsrademakers** [comment]
Hi,

The LDAP changes are part of the current master, and will be part of the upcoming 6.0.1. We had to publish an intermediate state of the docs recently and that's why it includes the LDAP 6.0.1 changes. So it will be available soon ;-)

Thanks
