### ISSUE TITLE
How to config log file path with flowable-ui in docker?

### ISSUE THREAD

**Issue by yaodwwy** [flowable/flowable-engine#3576]
I wanna config `logging.file.name` and `logging.pattern.rolling-file-name` with flowable-ui app.

but I can not find any way to config it.

**Comment by yvoswillens** [comment]
Closing this because this is not a Flowable issue.
Please use the forum (forum.flowable.org) for questions like this.

Flowable UI is a Spring Boot app. Use the various Spring properties mechanisme to set for example `logging.file.name`.
For example in a .properties file.
