### ISSUE TITLE
Filename too long issue in Windows Vscode.

### ISSUE THREAD

**Issue by Abhijeetmishr** [flowable/flowable-engine#3584]
**Describe the bug**
Filename too long issue in Windows  while cloning into VsCode.

**Expected behavior**
Results in deletion of file while cloning and gives unexpected errors

**Code**
```
error: unable to create file modules/flowable-eventsubscription-service/src/java/org/flowable/eventsubscription/service/impl/persistence/entity/data/iachematcher/EventSubscriptionsByScopeDefinitionIdAndTypeAndNullScopeIdMatchva: Filename too long
Updating files: 100% (15776/15776), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
```

**Additional context**
platform :- WIndows
tool :- Vs Code

**Comment by WelschChristopher** [comment]
Hey, this is not flowable a bug. Please check your git config if you set the `longpaths` setting.

**Comment by filiphr** [comment]
Closing because @WelschChristopher explained what needs to be done

**Comment by Abhijeetmishr** [comment]
> Hey, this seems to be not related to flowable. Please check your git config. DId you set the `longpaths` setting?

@WelschChristopher Hey thank you for the reply.
If you can elaborate it a bit that would be helpful.
Regards
