### ISSUE TITLE
Dynamic countersignature and no blocking of the main process

### ISSUE THREAD

**Issue by FengYue99** [flowable/flowable-engine#3597]
Please ask flowable how to implement dynamic add-signature, add-signature node does not block the main process, add-signature before the node can also be approved after the add-signature. If it is approved by the pre-signature node, then it will skip the sign-up. Need to implement multi-signer

**Comment by tijsrademakers** [comment]
Hi, sorry but the description is missing some information to make it possible to respond, and please use the Flowable forum to ask questions like this.
