### ISSUE TITLE
Flowable has bug when delete his data in postgresql

### ISSUE THREAD

**Issue by flowbalUser** [flowable/flowable-engine#3598]
**Describe the bug**
Flowable has bug when delete his data in postgresql, when  exe  PROC_INST_ID_ != '' , can not delete

**Code**
this bug all exist   ACT_HI_ACTINST  和 ACT_HI_VARINST  和 ACT_HI_TASKINST  and  ACT_HI_IDENTITYLINK   when exe delete

<delete id="bulkDeleteHistoricTaskInstancesForNonExistingProcessInstances" parameterType="java.util.Map">
delete <if test="_databaseId != 'postgres' and _databaseId != 'cockroachdb' and _databaseId != 'db2'"> TASK </if> from ${prefix}ACT_HI_TASKINST TASK where TASK.PROC_INST_ID_ is not null and TASK.PROC_INST_ID_ != '' and
NOT EXISTS (select PROCINST.ID_ from ${prefix}ACT_HI_PROCINST PROCINST where TASK.PROC_INST_ID_ = PROCINST.ID_)
</delete>

**Comment by tijsrademakers** [comment]
Please provide a unit test showing the issue. We'll close the issue for now, but please reopen when you have a unit test.
