### ISSUE TITLE
When a GET request is made to "management/tables", it returns an "Internal server error".

### ISSUE THREAD

**Issue by xiaohundun** [flowable/flowable-engine#3602]
**Describe the bug**
When a GET request is made to "management/tables", it returns an "Internal server error".

**Expected behavior**

**Code**
If applicable, add the code that you are using when having the issue.

**Additional context**
Log：
org.flowable.common.engine.api.FlowableException: couldn't get table counts

Cause: java.sql.SQLSyntaxErrorException: Table 'act2.act_ru_integration' doesn't exist

Version：6.8.0.0

**Comment by Abhijeetmishr** [comment]
@xiaohundun Can I pick this up ?

**Comment by filiphr** [comment]
@Abhijeetmishr I am not sure that this is an actual problem. How do you think to fix this?

@xiaohundun where is the `act_ru_integration` table coming from? Flowable doesn't have a table with that name. The endpoint will get all the tables that are prefixed with `act_` and `flw_`. 

Can you please share a minimal reproducible example for this?

**Comment by xiaohundun** [comment]
> @Abhijeetmishr I am not sure that this is an actual problem. How do you think to fix this?
> 
> @xiaohundun where is the `act_ru_integration` table coming from? Flowable doesn't have a table with that name. The endpoint will get all the tables that are prefixed with `act_` and `flw_`.
> 
> Can you please share a minimal reproducible example for this?

Sure. 
[example](https://github.com/xiaohundun/example-flowable)

**Comment by Abhijeetmishr** [comment]
@filiphr @xiaohundun what can we conclude from this i think error is obvious right ?
 **Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Table 'act2.act_ru_integration' doesn't exist**

**Comment by xiaohundun** [comment]
@Abhijeetmishr yes 😕

**Comment by Abhijeetmishr** [comment]
> @Abhijeetmishr yes 😕

@xiaohundun if your doubts are clear we can close this issue right ?

**Comment by xiaohundun** [comment]
> > @Abhijeetmishr yes 😕
> 
> @xiaohundun if your doubts are clear we can close this issue right ?

Have you tried the 'example' I posted？Isn't that a bug？
