### ISSUE TITLE
nested exception is java.lang.StackOverflowError

### ISSUE THREAD

**Issue by tony2y** [flowable/flowable-engine#3615]
**Describe the bug**
xml:
 <bpmn2:userTask id="Activity_1g65lke" name="审批啊14" flowable:assignee="${approver}" flowable:candidateGroups="2317,2347" flowable:category="CHECK">
      <bpmn2:extensionElements>
        <flowable:executionListener class="***.listens.MultiInstanceListen" event="start" />

      </bpmn2:extensionElements>
      <bpmn2:incoming>Flow_1666168081285</bpmn2:incoming>
      <bpmn2:outgoing>Flow_03sldqb</bpmn2:outgoing>

      <bpmn2:multiInstanceLoopCharacteristics flowable:collection="Activity_1g65lke_approverList" flowable:elementVariable="approver">
        </bpmn2:extensionElements>
        <bpmn2:completionCondition>${nrOfCompletedInstances>=1}</bpmn2:completionCondition>
      </bpmn2:multiInstanceLoopCharacteristics>

</bpmn2:userTask>

add  ExecutionListener Start process instance ，The following error occurred：

org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.StackOverflowError
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1082)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)

**Expected behavior**

**Code**
runtimeService.startProcessInstanceById(procDefId, variables);

**Additional context**
 Spring Boot 2.5.14
 Flowable 6.7.2

**Comment by tijsrademakers** [comment]
Hi, the provided stacktrace is incomplete and just shows the very first part of the exception. Please provide a full stacktrace with all details. For now we'll close this issue, but please reopen with the full stacktrace when you have it.
