### ISSUE TITLE
Can I approve in batches？

### ISSUE THREAD

**Issue by sgs98** [flowable/flowable-engine#3616]
**Is your feature request related to a problem? Please describe.**
Can I approve in batches？
A clear and concise description of what the problem is. 
Ex. I have the following process or case definition and calling this API, the following exception happens [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Models, if applicable, always help to clarify a problem. Ideally, a unit test makes reproducing things easier.

**Comment by filiphr** [comment]
Hey @sgs98, please use our [forum](https://forum.flowable.org/) for asking questions.
