### ISSUE TITLE
Instances Ending Immediately After Submission in Spring Boot and Flowable

### ISSUE THREAD

**Issue by lunxian8** [flowable/flowable-engine#3620]
Environment:

Spring Boot 2.1.7
Flowable 6.6.0
Oracle 11g
MyBatis 3.5.5

Deployment: Converted the JAR to a WAR package and deployed to Tomcat 8.5.

Occasionally, I find that instances end immediately after submission when started. Restarting the Tomcat service or republishing a new process definition results in normal instance startup. This issue occurs sporadically, with the last instance happening 3 to 4 months ago. Copying the Oracle database and code from the production server to the development environment for testing works perfectly, and the issue cannot be replicated.

After starting, querying the database with the process instance ID returns no data.

`select distinct RES.* from ACT_RU_TASK RES WHERE RES.ID_ = '9c393132-c79d-11ed-ad8b-00ff6fb26b56' order by RES.ID_ asc;
`

The main concern is that this issue occurs occasionally and resolves after a restart. Has anyone encountered this situation before, or has this bug been fixed already?

**Comment by lunxian8** [comment]
Supplement: There are no exception data in the logs.  The problem analysis shows that there are no tasks, and the instance ends immediately after starting and submitting.  The data cannot be found even with a separate query statement.  The service can run normally after restarting.  Is this a cache issue, or is there something else that needs to be configured?  Please help me with a troubleshooting approach.  Thank you.

**Comment by tijsrademakers** [comment]
Flowable uses database transactions to make sure that the process instances run in a consistent and transactional manner. If you are experiencing that process instances end after starting, then it looks like this is a process model issue, or the starting of the process instance failed and the database transaction is rolled back. Flowable is used in a lot of high volume use cases and we never encountered this issue, so it looks to be an issue in your application / process model / environment. If it can be reproduced please let us know and provide ways to reproduce the issue.

**Comment by lunxian8** [comment]
Thank you.
