### ISSUE TITLE
 The table ACT_GE_BYTEARRAY is too large. Can the records whose DEPLOYMENT_ID_ field is empty be cleared? Will it affect the running process?

### ISSUE THREAD

**Issue by niushaoda** [flowable/flowable-engine#3621]
The table ACT_GE_BYTEARRAY is too large. Can the records whose DEPLOYMENT_ID_ field is empty be cleared? Will it affect the running process?

**Comment by niushaoda** [comment]
The NAME_ fields of the records whose DEPLOYMENT_ID_ is empty all start with "hist.detail" or "hist.var". Can these records be cleaned up?

**Comment by tijsrademakers** [comment]
These are the historic variable values that are stored for the process instances you run. This include running and completed instances. The runtime execution of the process instances will not be influenced if you delete the entries with hist.detail or hist.var.
