### ISSUE TITLE
When will V7.0 be released?

### ISSUE THREAD

**Issue by kaoding** [flowable/flowable-engine#3623]
**Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is. 
Ex. I have the following process or case definition and calling this API, the following exception happens [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Models, if applicable, always help to clarify a problem. Ideally, a unit test makes reproducing things easier.

**Comment by tijsrademakers** [comment]
There is no fixed date defined yet, we will announce the timeline when it's available.
