### ISSUE TITLE
Version upgrade in flowable.all.upgradestep.6723.to.6800.batch.sql

### ISSUE THREAD

**Issue by mtraj** [flowable/flowable-engine#3624]
Should the upgrade version in the following file https://github.com/flowable/flowable-engine/blob/main/modules/flowable-batch-service/src/main/resources/org/flowable/batch/service/db/upgrade/flowable.all.upgradestep.6723.to.6800.batch.sql

set the new version to `6.8.0.0`?

**Expected behavior**
After upgrade to 7.0.0.M1 the whole schema should get migrated
currently on each restart there is the following log:
`Upgrade needed: 6723 -> 6800. Looking for schema update resource for component 'batch'`

**Code**
https://github.com/flowable/flowable-engine/blob/main/modules/flowable-batch-service/src/main/resources/org/flowable/batch/service/db/upgrade/flowable.all.upgradestep.6723.to.6800.batch.sql

**Additional context**
- version of Flowable: 7.0.0.M1
- database postgresql
- using Flowable with Spring Boot

**Comment by tijsrademakers** [comment]
Hi @mtraj , thanks for pointing this out, it's indeed not correct, we will change this now.
