### ISSUE TITLE
deadlock issue

### ISSUE THREAD

**Issue by hanhx** [flowable/flowable-engine#3626]
Describe the bug
We use this service to complete userTasks. When multiple task streams operate simultaneously, a deadlock will occur.
The error message for deadlock is as follows

2023-03-29 14:43:31 0x7f5f10e90700
*** (1) TRANSACTION:
TRANSACTION 1569773, ACTIVE 0 sec
mysql tables in use 1, locked 1
LOCK WAIT 19 lock struct(s), heap size 1136, 12 row lock(s), undo log entries 10
MySQL thread id 4776222, OS thread handle 140045345871616, query id 131337582 10.131.192.143 taskflow_stg_rw updating
delete from ACT_RU_VARIABLE where EXECUTION_ID_ = 'b3882509-cdfc-11ed-bd3e-361bc84998b5'

*** (1) HOLDS THE LOCK(S):
RECORD LOCKS space id 96 page no 165 n bits 168 index PRIMARY of table `taskflow_stg`.`act_ru_variable` trx id 1569773 lock_mode X locks rec but not gap
Record lock, heap no 99 PHYSICAL RECORD: n_fields 17; compact format; info bits 32
 0: len 30; hex 30343639363831632d636466642d313165642d626433652d333631626338; asc 0469681c-cdfd-11ed-bd3e-361bc8; (total 36 bytes);
 1: len 6; hex 00000017f3ed; asc       ;;
 2: len 7; hex 01000001351e64; asc     5 d;;
 3: len 4; hex 80000001; asc     ;;
 4: len 6; hex 737472696e67; asc string;;
 5: len 8; hex 7461736b54797065; asc taskType;;
 6: len 30; hex 62333838323530662d636466632d313165642d626433652d333631626338; asc b388250f-cdfc-11ed-bd3e-361bc8; (total 36 bytes);
 7: len 30; hex 62333838323530392d636466632d313165642d626433652d333631626338; asc b3882509-cdfc-11ed-bd3e-361bc8; (total 36 bytes);
 8: len 30; hex 30343637653137622d636466642d313165642d626433652d333631626338; asc 0467e17b-cdfd-11ed-bd3e-361bc8; (total 36 bytes);
 9: SQL NULL;
 10: SQL NULL;
 11: SQL NULL;
 12: SQL NULL;
 13: SQL NULL;
 14: SQL NULL;
 15: len 6; hex 73797374656d; asc system;;
 16: SQL NULL;

*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 96 page no 165 n bits 168 index PRIMARY of table `taskflow_stg`.`act_ru_variable` trx id 1569773 lock_mode X locks rec but not gap waiting
Record lock, heap no 100 PHYSICAL RECORD: n_fields 17; compact format; info bits 32
 0: len 30; hex 30343766336131312d636466642d313165642d626433652d333631626338; asc 047f3a11-cdfd-11ed-bd3e-361bc8; (total 36 bytes);
 1: len 6; hex 00000017f3ef; asc       ;;
 2: len 7; hex 02000001b906a3; asc        ;;
 3: len 4; hex 80000001; asc     ;;
 4: len 6; hex 737472696e67; asc string;;
 5: len 8; hex 7461736b54797065; asc taskType;;
 6: len 30; hex 62333933343861632d636466632d313165642d626433652d333631626338; asc b39348ac-cdfc-11ed-bd3e-361bc8; (total 36 bytes);
 7: len 30; hex 62333933343861362d636466632d313165642d626433652d333631626338; asc b39348a6-cdfc-11ed-bd3e-361bc8; (total 36 bytes);
 8: len 30; hex 30343765303139302d636466642d313165642d626433652d333631626338; asc 047e0190-cdfd-11ed-bd3e-361bc8; (total 36 bytes);
 9: SQL NULL;
 10: SQL NULL;
 11: SQL NULL;
 12: SQL NULL;
 13: SQL NULL;
 14: SQL NULL;
 15: len 6; hex 73797374656d; asc system;;
 16: SQL NULL;

*** (2) TRANSACTION:
TRANSACTION 1569775, ACTIVE 0 sec
mysql tables in use 1, locked 1
LOCK WAIT 19 lock struct(s), heap size 1136, 12 row lock(s), undo log entries 10
MySQL thread id 4776229, OS thread handle 140045419271936, query id 131337583 10.131.192.143 taskflow_stg_rw updating
delete from ACT_RU_VARIABLE where EXECUTION_ID_ = 'b39348a6-cdfc-11ed-bd3e-361bc84998b5'

*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 96 page no 165 n bits 168 index PRIMARY of table `taskflow_stg`.`act_ru_variable` trx id 1569775 lock_mode X locks rec but not gap
Record lock, heap no 100 PHYSICAL RECORD: n_fields 17; compact format; info bits 32
 0: len 30; hex 30343766336131312d636466642d313165642d626433652d333631626338; asc 047f3a11-cdfd-11ed-bd3e-361bc8; (total 36 bytes);
 1: len 6; hex 00000017f3ef; asc       ;;
 2: len 7; hex 02000001b906a3; asc        ;;
 3: len 4; hex 80000001; asc     ;;
 4: len 6; hex 737472696e67; asc string;;
 5: len 8; hex 7461736b54797065; asc taskType;;
 6: len 30; hex 62333933343861632d636466632d313165642d626433652d333631626338; asc b39348ac-cdfc-11ed-bd3e-361bc8; (total 36 bytes);
 7: len 30; hex 62333933343861362d636466632d313165642d626433652d333631626338; asc b39348a6-cdfc-11ed-bd3e-361bc8; (total 36 bytes);
 8: len 30; hex 30343765303139302d636466642d313165642d626433652d333631626338; asc 047e0190-cdfd-11ed-bd3e-361bc8; (total 36 bytes);
 9: SQL NULL;
 10: SQL NULL;
 11: SQL NULL;
 12: SQL NULL;
 13: SQL NULL;
 14: SQL NULL;
 15: len 6; hex 73797374656d; asc system;;
 16: SQL NULL;

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 96 page no 165 n bits 168 index PRIMARY of table `taskflow_stg`.`act_ru_variable` trx id 1569775 lock_mode X locks rec but not gap waiting
Record lock, heap no 99 PHYSICAL RECORD: n_fields 17; compact format; info bits 32
 0: len 30; hex 30343639363831632d636466642d313165642d626433652d333631626338; asc 0469681c-cdfd-11ed-bd3e-361bc8; (total 36 bytes);
 1: len 6; hex 00000017f3ed; asc       ;;
 2: len 7; hex 01000001351e64; asc     5 d;;
 3: len 4; hex 80000001; asc     ;;
 4: len 6; hex 737472696e67; asc string;;
 5: len 8; hex 7461736b54797065; asc taskType;;
 6: len 30; hex 62333838323530662d636466632d313165642d626433652d333631626338; asc b388250f-cdfc-11ed-bd3e-361bc8; (total 36 bytes);
 7: len 30; hex 62333838323530392d636466632d313165642d626433652d333631626338; asc b3882509-cdfc-11ed-bd3e-361bc8; (total 36 bytes);
 8: len 30; hex 30343637653137622d636466642d313165642d626433652d333631626338; asc 0467e17b-cdfd-11ed-bd3e-361bc8; (total 36 bytes);
 9: SQL NULL;
 10: SQL NULL;
 11: SQL NULL;
 12: SQL NULL;
 13: SQL NULL;
 14: SQL NULL;
 15: len 6; hex 73797374656d; asc system;;
 16: SQL NULL;

*** WE ROLL BACK TRANSACTION (2)

**Expected behavior**
We hope to avoid deadlock as much as possible

**Code**
We have added the following index to solve this problem

ALTER TABLE `act_ru_variable`
    ADD INDEX `idx_EXECUTION_ID`(`EXECUTION_ID_`);

ALTER TABLE `act_ru_task`
    ADD INDEX `idx_EXECUTION_ID`(`EXECUTION_ID_`);

**Additional context**

**Comment by tijsrademakers** [comment]
A deadlock in a MySQL database often means the database is not sized appropriately, because MySQL is then struggling to execute the SQL statements. Adding an index is sometimes a solution to resolve this, but also depends on how the Flowable engine is used and the kind of process models that you run with it. It's also difficult to give feedback without seeing a process model. Therefore we'll close this issue for now, but please reopen when there is more information to be shared.
