### ISSUE TITLE
Requested business calendar null does not exist. Allowed calendars are [duration, dueDate, cycle]

### ISSUE THREAD

**Issue by siyi-09** [flowable/flowable-engine#3629]
**Describe the bug**
When completing or changing a useTask node, occasionally an error is reported:"Requested business calendar null does not exist. Allowed calendars are [duration, dueDate, cycle]".Debugging found that the program converted the value of dueDate to 'null', but it should actually be null，not a string.

**Code**
UserTaskActivityBehavior.java,Method handleDueDate, third line:
if (dueDate != null)
<img width="732" alt="微信图片_20230410091032" src="https://user-images.githubusercontent.com/54696609/230807000-2f239b43-0a61-4d9e-aa24-655271cae225.png">
<img width="913" alt="微信图片_20230410091045" src="https://user-images.githubusercontent.com/54696609/230807014-c67627f1-49fc-42ff-a911-85c522432684.png">

**Additional context**
batch.schema.version=6.7.2.0
flowable.version=6.7.2

**Comment by siyi-09** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<definitions
    xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
    xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC"
    xmlns:bioc="http://bpmn.io/schema/bpmn/biocolor/1.0"
    xmlns:flowable="http://flowable.org/bpmn"
    xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.flowable.org/processdef">
    <process id="process_n74woxec" name="二级-动态审核人-微信通知事件" flowable:processCategory="1001">
        <documentation>二级-动态审核人-微信通知事件</documentation>
        <startEvent id="startNode1" name="开始" flowable:formKey="3">
            <outgoing>Flow_0zbxvrh</outgoing>
        </startEvent>
        <userTask id="Activity_14ixg2v" name="发起人审核" flowable:formKey="5" flowable:dataType="dynamic" flowable:userType="assignee" flowable:assignee="${approval}">
            <extensionElements>
                <flowable:taskListener class="org.flowable.dataAudit.TaskEvent" event="complete">
                    <flowable:field name="status" stringValue="AUDIT_PASS" />
                </flowable:taskListener>
                <flowable:taskListener class="org.flowable.dataAudit.TaskEvent" event="delete">
                    <flowable:field name="status" stringValue="AUDIT_FAILD" />
                </flowable:taskListener>
                <flowable:executionListener class="org.flowable.dataAudit.SentMsgEvent" event="end" />
            </extensionElements>
            <incoming>Flow_06qrsa5</incoming>
            <outgoing>Flow_0ymm3p2</outgoing>
        </userTask>
        <endEvent id="Event_035t3kd" name="结束">
            <incoming>Flow_0ymm3p2</incoming>
        </endEvent>
        <sequenceFlow id="Flow_0zbxvrh" sourceRef="startNode1" targetRef="Activity_0zsp8tv" />
        <sequenceFlow id="Flow_0ymm3p2" sourceRef="Activity_14ixg2v" targetRef="Event_035t3kd" />
        <userTask id="Activity_0zsp8tv" name="申请" flowable:dataType="fixed" flowable:userType="assignee" flowable:assignee="${INITIATOR}">
            <extensionElements>
                <flowable:taskListener class="org.flowable.dataAudit.TaskEvent" event="complete">
                    <flowable:field name="status" stringValue="AUDITING" />
                </flowable:taskListener>
                <flowable:executionListener class="org.flowable.dataAudit.SentMsgEvent" event="end">
                    <flowable:field name="msg" stringValue=" " />
                </flowable:executionListener>
            </extensionElements>
            <incoming>Flow_0zbxvrh</incoming>
            <outgoing>Flow_0t4b6js</outgoing>
        </userTask>
        <userTask id="Activity_18o3sgg" name="动态审核人" flowable:formKey="5" flowable:dataType="dynamic" flowable:userType="assignee" flowable:assignee="${approval}">
            <extensionElements>
                <flowable:taskListener class="org.flowable.dataAudit.TaskEvent" event="complete">
                    <flowable:field name="status" stringValue="AUDITING" />
                </flowable:taskListener>
                <flowable:taskListener class="org.flowable.dataAudit.TaskEvent" event="delete">
                    <flowable:field name="status" stringValue="AUDIT_FAILD" />
                </flowable:taskListener>
                <flowable:executionListener class="org.flowable.dataAudit.SentMsgEvent" event="end" />
            </extensionElements>
            <incoming>Flow_0t4b6js</incoming>
            <outgoing>Flow_06qrsa5</outgoing>
        </userTask>
        <sequenceFlow id="Flow_0t4b6js" sourceRef="Activity_0zsp8tv" targetRef="Activity_18o3sgg" />
        <sequenceFlow id="Flow_06qrsa5" sourceRef="Activity_18o3sgg" targetRef="Activity_14ixg2v" />
    </process>
    <bpmndi:BPMNDiagram id="BPMNDiagram_flow">
        <bpmndi:BPMNPlane id="BPMNPlane_flow" bpmnElement="process_n74woxec">
            <bpmndi:BPMNEdge id="Flow_06qrsa5_di" bpmnElement="Flow_06qrsa5">
                <di:waypoint x="270" y="190" />
                <di:waypoint x="370" y="190" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="Flow_0t4b6js_di" bpmnElement="Flow_0t4b6js">
                <di:waypoint x="60" y="190" />
                <di:waypoint x="170" y="190" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="Flow_0ymm3p2_di" bpmnElement="Flow_0ymm3p2">
                <di:waypoint x="470" y="190" />
                <di:waypoint x="572" y="190" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="Flow_0zbxvrh_di" bpmnElement="Flow_0zbxvrh">
                <di:waypoint x="-145" y="190" />
                <di:waypoint x="-40" y="190" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNShape id="BPMNShape_startNode1" bpmnElement="startNode1" bioc:stroke="">
                <omgdc:Bounds x="-175" y="175" width="30" height="30" />
                <bpmndi:BPMNLabel>
                    <omgdc:Bounds x="-172" y="212" width="22" height="14" />
                </bpmndi:BPMNLabel>
            </bpmndi:BPMNShape>
            <bpmndi:BPMNShape id="Activity_18flibn_di" bpmnElement="Activity_14ixg2v">
                <omgdc:Bounds x="370" y="150" width="100" height="80" />
            </bpmndi:BPMNShape>
            <bpmndi:BPMNShape id="Event_035t3kd_di" bpmnElement="Event_035t3kd">
                <omgdc:Bounds x="572" y="172" width="36" height="36" />
                <bpmndi:BPMNLabel>
                    <omgdc:Bounds x="579" y="215" width="22" height="14" />
                </bpmndi:BPMNLabel>
            </bpmndi:BPMNShape>
            <bpmndi:BPMNShape id="Activity_0oq71n0_di" bpmnElement="Activity_0zsp8tv">
                <omgdc:Bounds x="-40" y="150" width="100" height="80" />
            </bpmndi:BPMNShape>
            <bpmndi:BPMNShape id="Activity_0qh3gp9_di" bpmnElement="Activity_18o3sgg">
                <omgdc:Bounds x="170" y="150" width="100" height="80" />
            </bpmndi:BPMNShape>
        </bpmndi:BPMNPlane>
    </bpmndi:BPMNDiagram>
</definitions>

**Comment by siyi-09** [comment]
this is process xml file
[二级.bpmn20.xml.txt](https://github.com/flowable/flowable-engine/files/11186832/bpmn20.xml.txt)

**Comment by tijsrademakers** [comment]
Hi, can you share what the due date expression is that you are using? If the value is 'null' instead of null then this could be the reason for the issue. Make sure the expression returns null.

**Comment by siyi-09** [comment]
Thank you. I did not set a value for dueDate in my process design. Later, I tried to set (flow: dueDate="") and temporarily resolved the issue. But I still don't understand why the attribute is null when put into 'processDefinitionCache', but becomes' null 'when taken out.

error xml:
`<userTask id="Activity_14ixg2v" name="发起人审核" flowable:formKey="5" flowable:dataType="dynamic" flowable:userType="assignee" flowable:assignee="${approval}">`

latest xml:
`<userTask id="Activity_14ixg2v" name="发起人审核" flowable:formKey="5" flowable:dataType="dynamic" flowable:priority="5" flowable:skipExpression="" flowable:dueDate="" flowable:userType="assignee" flowable:assignee="${approval}">`

**Comment by siyi-09** [comment]
I first clear the "processDefinitionCache" every time I use "repositoryService. getBpmnModel". the issue is solved.But I always feel like it's a serialization issue. I'm not sure if I made any configuration changes, so I'll record it first and delve deeper into the reason when I have the ability.
