### ISSUE TITLE
Problem with cancelling boundary events

### ISSUE THREAD

**Issue by explorer566** [flowable/flowable-engine#364]
In our application we have a sub process with a signal boundary event using cancelActivity="true".
Within this sub process we create a sub process instance using a service task with a Java delegate (`entityManager.createSubprocessInstance`).
During execution of this sub process the signal for the signal boundary event is thrown.

This leads to a database error because the sub process with the signal boundary event is deleted in method _deleteChildExecutions_ of class _BoundaryEventActivityBehavior_ but not the created sub process that references the deleted one as super execution.

If the statement 
`if (parentExecution.getCurrentFlowElement() instanceof CallActivity)`
would be ommited in method _deleteChildExecutions_ all would be fine, because then the created sub process (that was not created by a call activity) would be deleted too.

Thanx in advance
Ralf

**Comment by tijsrademakers** [comment]
Hi Ralf,

Ok, that check was there to prevent an unnecessary sql query, but your case shows that it's needed anyways. Changed the logic according to your suggestion.

Thanks
