### ISSUE TITLE
How do I dynamically insert or remove 'assignee' to Sequential Multi-Instance ??

### ISSUE THREAD

**Issue by funnydevelop** [flowable/flowable-engine#3642]
Hello , 
I got a troble on  Sequential Multi-Instance for dynamically insert or delete 'Users', 
For Parallel Multi-instance i used addMultiInstanceExecution/deleteMultiInstanceExecution  to insert or remove users,
But it looks like doesn't work  to SequentialMultiInstance.... the user wasn't be added by the interface 'addMultiInstanceExecution'.
So , What shoud i do ????? ,please help me ... thanks.

Best regards

**Comment by filiphr** [comment]
@funnydevelop I see that you also posted your question in our forum https://forum.flowable.org/t/how-do-i-dynamically-insert-or-remove-assignee-to-sequential-multi-instance/10445. I would suggest you not to cross post and wait for an answer in the forum post
