### ISSUE TITLE
Flowable-ui discontinued?

### ISSUE THREAD

**Issue by jfgpimpollo** [flowable/flowable-engine#3654]
Hi, sorry for the question if it has been announced, but I haven't found anything.

I've noticed that flowable-ui has been removed from the main branch of flowable/flowable-engine. Has it been discontinued from the open source project in favor of the cloud modeler or the enterprise version? or is it still available in other project/branch...

Thanks in advance.

Best Regards

**Comment by tijsrademakers** [comment]
Hi, in the Flowable 6 branch you can still find the UI applications (https://github.com/flowable/flowable-engine/tree/flowable6.x). For the Flowable 7 main branch we added some more information in the release notes of the milestone 1 release https://github.com/flowable/flowable-engine/releases/tag/flowable-7.0.0.M1.

Best regards
