### ISSUE TITLE
Create or Update detection not reliable with multiple DB's on one DB Server with MySQL/MariaDB

### ISSUE THREAD

**Issue by efc-mw** [flowable/flowable-engine#3656]
**Describe the bug**
We have multiple DB schemas on our DB server (testing, developemnt, ...). On MariaDB the intial creation of the DB model of flowable fails, the system seems to want update an exisiting schema and fails with SQL: insert into ACT_GE_PROPERTY values because the table don't exists. I analyze a little bit, there seems during startup a query to the information_schema: 
`SELECT TABLE_SCHEMA TABLE_CAT, NULL  TABLE_SCHEM,  TABLE_NAME, IF(TABLE_TYPE='BASE TABLE' or TABLE_TYPE='SYSTEM VERSIONED', 'TABLE', TABLE_TYPE) as TABLE_TYPE, TABLE_COMMENT REMARKS, NULL TYPE_CAT, NULL TYPE_SCHEM, NULL TYPE_NAME, NULL SELF_REFERENCING_COL_NAME,  NULL REF_GENERATION FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE 'ACT_GE_PROPERTY' AND  TABLE_TYPE IN ('BASE TABLE','SYSTEM VERSIONED') ORDER BY TABLE_TYPE, TABLE_SCHEMA, TABLE_NAME`

This results in our db:
```
"TABLE_CAT"	"TABLE_SCHEM"	"TABLE_NAME"	"TABLE_TYPE"	"REMARKS"	"TYPE_CAT"	"TYPE_SCHEM"	"TYPE_NAME"	"SELF_REFERENCING_COL_NAME"	"REF_GENERATION"
"efc"	\N	"act_ge_property"	"TABLE"	""	\N	\N	\N	\N	\N
"efcdemo"	\N	"act_ge_property"	"TABLE"	""	\N	\N	\N	\N	\N
"efcempty"	\N	"act_ge_property"	"TABLE"	""	\N	\N	\N	\N	\N
"efcstarter"	\N	"act_ge_property"	"TABLE"	""	\N	\N	\N	\N	\N
"efcstarter_demo"	\N	"act_ge_property"	"TABLE"	""	\N	\N	\N	\N	\N
"efc_kem"	\N	"act_ge_property"	"TABLE"	""	\N	\N	\N	\N	\N
"efc_knl_starter"	\N	"act_ge_property"	"TABLE"	""	\N	\N	\N	\N	\N
"efc_pfk"	\N	"act_ge_property"	"TABLE"	""	\N	\N	\N	\N	\N

```
All seems fine, our new schema, "efc_knl", where flowable should create its tables, is not listed, but the test seems looking only at the number of entries?, not searching for the new schema name. So it thinks the flowable tables exists and want's to upgrade the db model, which is wrong in a new schema.
All is functioning fine, if there is no schema with flowable tables on the db server, then the creation is running fine.

**Expected behavior**
Initial creation of flowable tables is running also when other schemas exists on the db server, where the flowable db model already exists.

**Comment by tijsrademakers** [comment]
To overcome this a db user should be used for the db connection that has only access to the Flowable database. Then this will work correctly.
