### ISSUE TITLE
Dynamic node name

### ISSUE THREAD

**Issue by MiaCutie** [flowable/flowable-engine#3663]
I want to use dynamic node names, using expression (${taskName}) failed to achieve, is there any other way?

**Comment by tijsrademakers** [comment]
${taskName} should work for dynamic task names, can you share the BPMN XML that you tested with?

**Comment by MiaCutie** [comment]
<bpmn2:userTask id="Activity_1t6nsu4"
		                name="${taskName}">
			<bpmn2:incoming>Flow_1kzww03</bpmn2:incoming>
			<bpmn2:outgoing>Flow_0wctb08</bpmn2:outgoing>
		</bpmn2:userTask>

**Comment by MiaCutie** [comment]
Thanks

Best Regards
