### ISSUE TITLE
The rational behind multi tenancy db model 

### ISSUE THREAD

**Issue by musthafa-yubi** [flowable/flowable-engine#3666]
Can anyone please explain why tables related to user and multi-tenancy designed like this ?
-> There is no separate table for tenant ids 
-> Every table has a tenant_id column which is just a string (not even a foreign key)

**Comment by tijsrademakers** [comment]
The tenant id concept in Flowable is done in a flexible way so that it's easy to use Flowable without multi tenancy and with. If a tenant table is useful for your use case, it's easy to add your own tenant table and if needed add a foreign key to the tables having a tenant id column.
