### ISSUE TITLE
Flowable Designer Cloud Edition does not include Timer event during in the downloaded BPMN file

### ISSUE THREAD

**Issue by Joey-Wang-Imprivata** [flowable/flowable-engine#3668]
**Describe the bug**
Using Flowable Designer Cloud Edition to create a process definition. Add timer event to the diagram. Say, create a user service and create a timer boundary event for the service. Set timer duration. Save and download the diagram. Now if you open up the downloaded file, duration element is missing in the downloaded XML file. 

**Expected behavior**
Expected behavior: timer duration element should exist in the BPMN file if it is defined in the designer.

**Code**
If applicable, add the code that you are using when having the issue.

**Additional context**
Clearly the duration is saved internally since you can view it on the designer. It is only missing in the downloaded BPMN file. It is possible other fields such as cycle might be missing as well, but my diagram did not contain them.

**Comment by tijsrademakers** [comment]
Hi, thank you for the message, we will verify and update this issue.

**Comment by tijsrademakers** [comment]
This should now be fixed.
