### ISSUE TITLE
flowable can add shentongdata database support

### ISSUE THREAD

**Issue by shenfengzhusheng** [flowable/flowable-engine#3677]
**Is your feature request related to a problem? Please describe.**
The work can only use the Shentongdata database, and I need to support the flowable I want to use, i try but failed.

**Comment by tijsrademakers** [comment]
Please be as verbose as possible when creating issues. Can you explain in more detail what your request / issue is?

**Comment by tijsrademakers** [comment]
Closing issue due to no response.
