### ISSUE TITLE
Cover old value

### ISSUE THREAD

**Issue by fangliji** [flowable/flowable-engine#3681]
**Describe the bug**
When the VariableByteArrayEntity is updated,Values will be overwritten back and forth
I found that the program execution stack code he covered appears here

java.lang.Thread.getStackTrace() 1,559 <- \norg.flowable.variable.service.impl.persistence.entity.VariableByteArrayEntityImpl.printThreadStack() 113 <- \norg.flowable.variable.service.impl.persistence.entity.VariableByteArrayEntityImpl.setBytes() 75 <- \norg.flowable.variable.service.impl.persistence.entity.VariableByteArrayRef.setBytes() 73 <- \norg.flowable.variable.service.impl.persistence.entity.VariableByteArrayRef.setValue() 58 <- \norg.flowable.variable.service.impl.persistence.entity.VariableInstanceEntityImpl.setBytes() 113 <- \norg.flowable.variable.service.impl.types.DeserializedObject.verifyIfBytesOfSerializedObjectChanged() 48 <- \norg.flowable.variable.service.impl.types.VerifyDeserializedObjectCommandContextCloseListener.closing() 40 <- 

**Expected behavior**
What I am looking forward to is ACT_ RU_ No overwriting updates occur for VARIABLE

**Code**
If I delete this code, the result is true; otherwise, it is false. I would like to understand the original purpose of this design. Please help me correct any grammar or lexical errors while maintaining the same meaning
the code is :
class:DeserializedObject
public void verifyIfBytesOfSerializedObjectChanged() {
     
        // this first check verifies if the variable value was not overwritten with another object
        if (deserializedObject == variableInstanceEntity.getCachedValue() && !variableInstanceEntity.isDeleted()) {
            byte[] bytes = type.serialize(deserializedObject, variableInstanceEntity);
            if (!Arrays.equals(originalBytes, bytes)) {

                // Add an additional check to prevent byte differences due to JDK changes etc
                Object originalObject = type.deserialize(originalBytes, variableInstanceEntity);
                byte[] refreshedOriginalBytes = type.serialize(originalObject, variableInstanceEntity);

                if (!Arrays.equals(refreshedOriginalBytes, bytes)) {
                    variableInstanceEntity.setBytes(bytes);
                }
            }
        }
    }

**Additional context**
version is 6.4.1

**Comment by fangliji** [comment]
Bug Description:
When the VariableByteArrayEntity is updated, the values are being overwritten repeatedly. The code execution stack indicates that the issue is present in the VariableByteArrayEntityImpl class and its related methods.

Expected Behavior:
The desired outcome is to prevent overwriting updates for the VARIABLE, ensuring that values are not overwritten back and forth.

Code:
If the mentioned code is removed, the result is true; otherwise, it is false. I would like to understand the original purpose of this design. Please assist me in correcting any grammar or lexical errors while maintaining the intended meaning.

The code in question is as follows:

Class: DeserializedObject

scss
Copy code
public void verifyIfBytesOfSerializedObjectChanged() {

    // This first check verifies if the variable value was not overwritten with another object
    if (deserializedObject == variableInstanceEntity.getCachedValue() && !variableInstanceEntity.isDeleted()) {
        byte[] bytes = type.serialize(deserializedObject, variableInstanceEntity);
        if (!Arrays.equals(originalBytes, bytes)) {

            // Add an additional check to prevent byte differences due to JDK changes, etc.
            Object originalObject = type.deserialize(originalBytes, variableInstanceEntity);
            byte[] refreshedOriginalBytes = type.serialize(originalObject, variableInstanceEntity);

            if (!Arrays.equals(refreshedOriginalBytes, bytes)) {
                variableInstanceEntity.setBytes(bytes);
            }
        }
    }
}
Additional Context:
The reported issue is present in version 6.4.1.

**Comment by tijsrademakers** [comment]
Please provide a unit test showing the issue. Also note that version 6.4.1 is very old and it would be a good time to upgrade to a later version.

**Comment by fangliji** [comment]
ok，Let me compare the new version of the code, which version has the highest stability?

**Comment by fangliji** [comment]
> Please provide a unit test showing the issue. Also note that version 6.4.1 is very old and it would be a good time to upgrade to a later version.

Let me compare the new version of the code, which version has the highest stability?

**Comment by tijsrademakers** [comment]
Flowable has no stability issues. The latest release is 6.8.0.

**Comment by fangliji** [comment]
”Flowable has no stability issues“This joke is not funny

**Comment by tijsrademakers** [comment]
Closing the issue due to no response, please reopen when new information is available.
