### ISSUE TITLE
ProcessMigrationService is not saving the data after the migration 

### ISSUE THREAD

**Issue by MarijaPopova** [flowable/flowable-engine#3686]
Migration service is not working in flowable. 

I want to migrate the process, specifying  new variables . However that is not happening and after the migration they stay the same  as they were before. There is no exception or something .. so it's very hard to figure out what is happening.  I am using the latest version 7.0.0-M1 with the latest version of Spring boot 3.1.1

 migrationService.createProcessInstanceMigrationBuilder()
           .withProcessInstanceVariables(variables)
           .migrateToProcessDefinition(
            latestProjectWorkflowDef.getId())
            .migrate(execution.getId());

**Comment by tijsrademakers** [comment]
Ok, can you provide a unit test showing the issue?

**Comment by sgs98** [comment]
I have the same problem as you

**Comment by filiphr** [comment]
Closing this due to lack of feedback. We can reopen this once we have an example showing the problem.
