### ISSUE TITLE
May I ask if a new designer will be released later?

### ISSUE THREAD

**Issue by sgs98** [flowable/flowable-engine#3689]
**Is your feature request related to a problem? Please describe.**
May I ask if a new designer will be released later?

A clear and concise description of what the problem is. 
Ex. I have the following process or case definition and calling this API, the following exception happens [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Models, if applicable, always help to clarify a problem. Ideally, a unit test makes reproducing things easier.

**Comment by tijsrademakers** [comment]
Hi, to which new designer are you referring to? You can register for the Flowable cloud design application here https://www.flowable.com/trial/work. Also what do you mean with a release?

**Comment by sgs98** [comment]
@tijsrademakers New Model Designer

**Comment by tijsrademakers** [comment]
Ok, but I just gave a link on how you can use this Design application already. So can you not go ahead with this?

**Comment by sgs98** [comment]
Thank you

**Comment by jlmorard** [comment]
With the new version of flowable, no modeler is provided with the open source package. Instead we have a cloud design application (see above). Is it possible to design models in this cloud application and then to import them in the open source solution? Is compatibility between the two guaranteed? Thanks for a feedback.

**Comment by filiphr** [comment]
Hey @jlmorard,

Yes it is possible to use the Cloud Design Application to model models for the open source. You can use the Orchestrate palette for that.

Cheers,
Filip

**Comment by jlmorard** [comment]
Thanks Filip, this is very helpful. Three more questions if I may:

1. Even if possible, do you see any possible compatibility problem when importing models from the cloud design application?
2. Can I import models from the modeler version 7.x in the 8.x open source version? (Flowable documentation tends to say yes)
3. Does the API of the open source solution offers the same functionality as the one of the enterprise solution?

Would be great if you can give me a feedback.
Enjoy your day!

Cheers,
JL

**Comment by filiphr** [comment]
>1. Even if possible, do you see any possible compatibility problem when importing models from the cloud design application?

There shouldn't be any compatibility problems when using the Orchestrate palette. The idea of that palette is to be used with Open Source. If there is something that isn't working, the it is most likely a bug that we need to look into.

>2. Can I import models from the modeler version 7.x in the 8.x open source version? (Flowable documentation tends to say yes)

Flowable does not have an 8.x version. Can you explain a bit more what you mean with this?

>3. Does the API of the open source solution offers the same functionality as the one of the enterprise solution?

For BPMN, CMMN and DMN the API is the same between the open source and enterprise solution. Our enterprise solution builds on top of the open source solution. We have extra REST and Java APIs under the `com.flowable` namespace, but everything under the `org.flowable` namespace is also here in our enterprise solution.

**Comment by jlmorard** [comment]
Thanks Filip. Concerning question 2, sorry, I used the wrong releases:

- Can I import models from the modeler of the version 6.8 in the version 7.x (open source)? Flowable documentation tends to say yes, arguing of the backward compatibility of the models.

**Comment by filiphr** [comment]
In theory importing models from the 6.8 modeler in the 7.x version should work. However, there might be features in 7.x that you cannot model with 6.8
