### ISSUE TITLE
in JavaDelegate，Unable to obtain task ID

### ISSUE THREAD

**Issue by ennwgz** [flowable/flowable-engine#3698]
public class MyJavaDelegate  implements JavaDelegate {

   public void execute(DelegateExecution execution){
     // Unable to obtain task ID(taskInstId) here
   }
}

**Comment by filiphr** [comment]
Why are you using a `JavaDelegate`? Why don't you use `TaskListener`?

**Comment by ennwgz** [comment]
@filiphr Thank you very much

I am using
`
ServiceTask serviceTask = new ServiceTask()
`

**Comment by filiphr** [comment]
This looks like a question to me. Please use the [Forum](https://forum.flowable.org/) for asking questions.

After the explanation, I am not sure what exactly you are looking for @ennwgz. What is the "task ID" for you in your code? If you are using a Service Task then there is no task id (there is no user task), unless "task ID" is something else for you.
