### ISSUE TITLE
Can I dynamically switch data source

### ISSUE THREAD

**Issue by zengyunhua1111** [flowable/flowable-engine#3699]
Recently, in a project, I found that the business method has switched data sources, but the flowable engine cannot switch dynamically. Do I think there is any way to do this?

exp:
    @DataSource
    private void triggerStartProcess(ProcessDefinition procDef, Map<String, Object> variables, LoginUser loginUser) {
        if (ObjectUtil.isNotNull(procDef) && procDef.isSuspended()) {
            throw new ServiceException("flowable exception");
        }
      
        String userIdStr = String.valueOf(loginUser.getUserId());
        identityService.setAuthenticatedUserId(userIdStr);
        variables.put(BpmnXMLConstants.ATTRIBUTE_EVENT_START_INITIATOR, userIdStr);
       
        variables.put(ProcessConstants.PROCESS_STATUS_KEY, ProcessStatus.RUNNING.getStatus());

        //In this line，executing the default data source
        ProcessInstance processInstance = runtimeService.startProcessInstanceById(procDef.getId(), variables);
       
        wfTaskService.triggerStartFirstTask(processInstance, variables, loginUser);
    }

**Comment by zhenchuan9r** [comment]
I cannot fully understand what you are expressing, maybe you can try to write in Chinese.

**Comment by zengyunhua1111** [comment]
No question

**Comment by zengyunhua1111** [comment]
> I cannot fully understand what you are expressing, maybe you can try to write in Chinese.

项目里有用到flowable 流程引擎，数做多数据源的，动态切换到不同的租户，但是涉及到流程引擎的都切不了

**Comment by zengyunhua1111** [comment]
> I cannot fully understand what you are expressing, maybe you can try to write in Chinese.

flowable 怎么去做到动态切换数据源，多租户场景下，数据库是物理隔离的，目前我们的其他业务系统可以切换到数据源，但是流程没法跟着切换到

**Comment by filiphr** [comment]
In order to be able to use different `DataSource` based on a multi tenant scenario something like the [`MultiSchemaMultiTenantProcessEngineConfiguration`](https://github.com/flowable/flowable-engine/blob/main/modules/flowable-engine/src/main/java/org/flowable/engine/impl/cfg/multitenant/MultiSchemaMultiTenantProcessEngineConfiguration.java) can be used
