### ISSUE TITLE
Product Planning

### ISSUE THREAD

**Issue by zc888168** [flowable/flowable-engine#3701]
Is there any plan to separate the design of the form center and the process center? They can be integrated, but also can be separated. That is, you can use business-customized forms combined with Flowable's processes, or use Flowable's form design combined with Flowable's process design

**Comment by tijsrademakers** [comment]
Not sure I'm following the question. Can you elaborate a bit more on what you mean exactly and give some use cases?

**Comment by zhenchuan9r** [comment]
I think what @zc888168 wanted is to use bpmn itself without the necessarity to design or use a form.
This can be achieved by some customized API call routines actually.

**Comment by filiphr** [comment]
I am not sure that I completely understand what is being asked here. Please provide some examples with what you are looking for and we can reopen this.
