### ISSUE TITLE
 Remove Flowable UI Applications

### ISSUE THREAD

**Issue by 110117** [flowable/flowable-engine#3702]
why 
Remove Flowable UI Applications

**Comment by tijsrademakers** [comment]
You can find the explanation in the 7.0.0 M1 release notes https://github.com/flowable/flowable-engine/releases/tag/flowable-7.0.0.M1

**Comment by CollectBugs** [comment]
> You can find the explanation in the 7.0.0 M1 release notes https://github.com/flowable/flowable-engine/releases/tag/flowable-7.0.0.M1

This decision is somewhat unfavorable.
