### ISSUE TITLE
REST API Documentation For GET Historic Process Instance Shows Wrong Response

### ISSUE THREAD

**Issue by chaserb** [flowable/flowable-engine#3706]
**Describe the bug**
The following link describes the "GET Historic Process Instance" REST API Request:

https://www.flowable.com/open-source/docs/bpmn/ch15-REST#get-a-process-instance

The response object in the documentation shows a page of 1 result:
```
{
  "data": [
    {
      "id" : "5",
      "businessKey" : "myKey",
      ...
      "tenantId":null
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "name",
  "order": "asc",
  "size": 1
}
```

**Expected behavior**
Expecting an unpaged, single result from this request:
```
{
   "id" : "5",
   "businessKey" : "myKey",
   ...
   "tenantId":null
}
```

**Code**
N/A

**Additional context**
N/A

**Comment by filiphr** [comment]
Thanks for reporting this @chaserb
