### ISSUE TITLE
Could I deploy flowable-task in multi-instances for single data source in technically speaking?

### ISSUE THREAD

**Issue by soiff** [flowable/flowable-engine#371]
English is not my native language; please excuse typing errors.

We are looking for a method for deploying multiple instances of `flowable-task`. However, it seems not clearly about this kind of possibility in the documentation of `flowable-engine` 6.0 release. Would you please help to give me any advice about doing this?

My question is the potential problems in this scenario. Such as data consistency in cache if flowable cache data in DAO or lack of optimistic lock in SQL.

Any suggestion would be appreciate. Thanks ahead!

I'm new to flowable and I know I could get any detail in source code thanks to this wanderful opensource project. However, I'm eager to know whether flowable support this kind of scenario. Of course, I'll keep finding the solution to support this if it could not support this feature temporarily. Thanks again!

**Comment by tijsrademakers** [comment]
Hi,

Best to ask these kind of questions on the Flowable forum (https://forum.flowable.org/).
Yes, Flowable is designed to work with multiple instances on a single database. It has a stateless architecture and the state is all stored in the database. There are revision columns in the database to ensure that an update is done on the correct revision and if there was another instance doing an update on the same entity in between, Flowable will throw an optimistic lock exception.

**Comment by soiff** [comment]
Ok, sorry for that!

**Comment by soiff** [comment]
The link about this feature is posted on [forum](https://forum.flowable.org/):
https://forum.flowable.org/t/a-few-question-about-depolying-multiple-instances-of-flowable-task/518
