### ISSUE TITLE
WHYHitPolicyAny not only ask for same key， also ask for same value

### ISSUE THREAD

**Issue by kirayunfei** [flowable/flowable-engine#3718]
**Describe the issue**
When I use the DMN engine With flowable, I want to choose the HitPolicyAny strategy. But I couldn't understand that What does ANY mean in flowable DMN.
In my sense, ANY could be random one of all the hit ruleResults, or one of all the hit ruleResults which key of outputs is same. But ANY of flowable DMN neither. It validate the value of output，the values of outputs must be same then can be work. Otherwise, the result will show "failed".
I couldn't think the user scenary of this ANY strategy.
Looking for reply, sincere thanks

**Expected behavior**
A RANDOMstrategy of HitPolicy, which could select random one of all the hit ruleResults.
HitPolicyAny should not validate value of output, 

**Code**
HitPolicyAny.class

**Comment by yvoswillens** [comment]
Hi,

it's described here; https://www.flowable.com/open-source/docs/dmn/ch06-DMN-Introduction
With ANY one or more rules can be true but if there are more they must have the same result.
If multiple rules hit and the they have different outcomes the execution will be marked as failed.

This is conform the DMN spec. 

Can you provide an example were this behaviour is not the case?

Regards,

Yvo

**Comment by filiphr** [comment]
Closing this since no example has been provided. We can reopen it if we get an example.
