### ISSUE TITLE
Documentation issue with IdentityService.setAuthenticatedUserId

### ISSUE THREAD

**Issue by aaronkavlie-wf** [flowable/flowable-engine#372]
The docs [say](http://www.flowable.org/docs/userguide/index.html#historyFormAuditPurposes):

> If you’ve set the authenticated user before calling the submit methods with 
IdentityService.setAuthenticatedUserId(String) then that authenticated user who submitted the form will be accessible in the history as well with HistoricProcessInstance.getStartUserId() for start forms and HistoricActivityInstance.getAssignee() for task forms.

The latter part is incorrect; `HistoricActivityInstance.getAssignee()` returns the string set in the process definition with `flowable:assignee`, or `null` if not present.

The only result I've found of a call to `IdentityService.setAuthenticatedUserId()` before`formService.submitTaskFormData()` is in the event log — `EventLogEntry.getUserId()` returns the value.

**Comment by tijsrademakers** [comment]
It's also used in the BasicAuthenticationProvider Flowable REST module class for example. We also use Authentication.setAuthenticatedUserId in some code as well (which does the same). The assignee value is set to the flowable:assignee attribute value when it's there in the BPMN XML. But when there's candidate group and a user claims the user task, the value will be filled with the user claiming the task (when the IdentityService.setAuthenticatedUserId(String) or Authentication.setAuthenticatedUserId method is used). So the documentation is correct in my opinion.

**Comment by aaronkavlie-wf** [comment]
> But when there's candidate group and a user claims the user task, the value will be filled with the user claiming the task (when the IdentityService.setAuthenticatedUserId(String) or Authentication.setAuthenticatedUserId method is used).

That's an important condition, and I think it would help if it were explained.
Aside from candidate groups, is there any way `HistoricActivityInstance.getAssignee()` will return the authenticated user ID?
