### ISSUE TITLE
How do I add a dataobject to process in my code

### ISSUE THREAD

**Issue by Swiftlyfisher** [flowable/flowable-engine#3720]
```java
DataObject dataObject = new DataObject();
dataObject.setName("rhl");
dataObject.setItemSubjectRef(new ItemDefinition());

process.addFlowElement(dataObject);
```
error report:
org.flowable.bpmn.exceptions.XMLException: No converter for class org.flowable.bpmn.model.DataObject found

**Comment by tijsrademakers** [comment]
You can set a list of DataObjects on Process or SubProcess, like shown in this link for Process https://github.com/flowable/flowable-engine/blob/135a859fa8800d1c822ba4f3e97ac732609aadc4/modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/Process.java#L454. Adding it as a FlowElement won't work.
