### ISSUE TITLE
Wrong SQL script for h2 on Table ACT_HI_TSK_LOG

### ISSUE THREAD

**Issue by deepls** [flowable/flowable-engine#3729]
**Describe the bug**
When  use **h2** database,  can't create table ACT_HI_TSK_LOG。 
error prompt 
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Unknown data type: "IDENTITY"; SQL statement:

I review the sql  source code， found 
![image](https://github.com/flowable/flowable-engine/assets/89894580/73297a54-1308-40c0-b2c7-a52f82121bfd)

I think，maybe the keywords "identity" is wrong, use " varchar(64) not null" to replace。

**Additional context**
version: 6.8.0
database: h2

**Comment by deepls** [comment]
table ACT_EVT_LOG has the same bug。 
after i replace  "identity" to " varchar(64) not null" ， application startup success

**Comment by deepls** [comment]
H2 version: 2.1.214. And the database url is  jdbc:h2:mem:test;MODE=MySQL

**Comment by tijsrademakers** [comment]
Ok but then the issue is the mode you are running it on, please remove the MODE=MySQL part

**Comment by deepls** [comment]
thanks！
