### ISSUE TITLE
The JaxB binding file of flowable-cxf must be updated to use Jakarta EE 9/10

### ISSUE THREAD

**Issue by cdeneux** [flowable/flowable-engine#3755]
**Describe the bug**
The JaxB binding file introduced with ACT-4012 was not updated when moving to Jakarta EE 9/10

**Expected behavior**
This file must be updated to declare the right JaxB version and the right namespaces provided by Jakarta EE 9/10

**Additional context**
Flowable 7.0.0

**Comment by cdeneux** [comment]
Fix available with PR #3757

**Comment by filiphr** [comment]
The PR for this has been done. Thanks @cdeneux
