### ISSUE TITLE
jgraphx version upgrade

### ISSUE THREAD

**Issue by zhangyenull** [flowable/flowable-engine#3762]
**Describe the bug**
when i set jgraphx version to
 
<dependency>
    <groupId>org.tinyjee.jgraphx</groupId>
    <artifactId>jgraphx</artifactId>
    <version>3.4.1.3</version>
</dependency>
find 
<img width="735" alt="image" src="https://github.com/flowable/flowable-engine/assets/13203670/3a42cefe-f71b-4d24-a02e-25227e82403a">
        boundaryEdgeStyle.put(mxConstants.STYLE_EDGE, mxEdgeStyle.orthConnector);
mxEdgeStyle.orthConnector o have changed Upper O

**Expected behavior**

        boundaryEdgeStyle.put(mxConstants.STYLE_EDGE, mxEdgeStyle.OrthConnector);

**Comment by zhangyenull** [comment]
the flow version is 7.0.0

**Comment by tijsrademakers** [comment]
Flowable uses a specific version of jgraphx, so you can't change this version without potential issues.
