### ISSUE TITLE
What are the prerequisites to install Flowable open source version ?

### ISSUE THREAD

**Issue by Tuxman2** [flowable/flowable-engine#3775]
Hello,

what are the prerequisites to install Flowable open source version 6 or 7 ?

- JDK 17.x or JDK 21.x ?
- Maven 3.9.5 ?
- Apache Tomcat 10.x ?
- MySQL 8.x ?

Does flowable have a gui interface in flowable version 7  ? Or do I have to use flowable version 6 if I want to use flowable with a graphical interface ? Can I install flowable on a Linux server (for example : Ubuntu) and use it through an internet browser ?

Thanks.

Regards.

**Comment by tijsrademakers** [comment]
Hi. Flowable 6 has a minimum requirement of Java 8 and Flowable 7 has a minimum requirement of Java 17. The Maven, Tomcat and MySQL driver versions are not relevant, Flowable can work with them independent of the version. As described in the docs you can use Flowable 7 with a free to use Design application which you registry for on flowable.com. You can install Flowable on a Linux server without issues.

**Comment by Tuxman2** [comment]
>As described in the docs you can use Flowable 7 with a free to use Design application which you registry for on flowable.com.

Sorry but I don't understand your reply. Does Flowable 7 have the same items as Flowable 6 (login screen, ui interface to manage users, modeler interface, ....) ? I saw some information that Flowable UI applications were removed in version 7. What does it means ?

Regards.

**Comment by tijsrademakers** [comment]
Like mentioned in the 7.0.0 release notes, you can find a blog post about your question here:
https://www.flowable.com/blog/engineering/flowable-open-source-7-0-0-release
