### ISSUE TITLE
if support batch completing instance?

### ISSUE THREAD

**Issue by chendeheng** [flowable/flowable-engine#3780]
**Describe the bug**

**Expected behavior**

**Code**
If applicable, add the code that you are using when having the issue.

**Additional context**
Add the version of Flowable that you are using, the database vendor and if you are using Flowable within Spring Boot, the Flowable Task application etc.

**Comment by tijsrademakers** [comment]
You can create your own batch job implementation, but completing instances in batch is not support out of the box.
