### ISSUE TITLE
who know how to use module of batch-service? which version? thanks!!!

### ISSUE THREAD

**Issue by chendeheng** [flowable/flowable-engine#3781]
**Describe the bug**

**Expected behavior**

**Code**
If applicable, add the code that you are using when having the issue.

**Additional context**
Add the version of Flowable that you are using, the database vendor and if you are using Flowable within Spring Boot, the Flowable Task application etc.

**Comment by filiphr** [comment]
Please use our [Forum](https://forum.flowable.org/) for asking questions
