### ISSUE TITLE
"Data component is Json" option in data tables is not working well oustide of Flowable Work

### ISSUE THREAD

**Issue by quentingigon** [flowable/flowable-engine#3805]
**Describe the bug**
I have a button in a data table added as a "Data component" and when I click on it in a custom frontend, the click doesn't register on the button but on the row of the data table. If I click on it in Flowable Work, the click is correctly registered on the button.

**Expected behavior**
The click should be correctly registered on the button regardless of the frontend 

**Code**
The code of my button:
`{
  "type": "scriptButton",
  "value": "{{$payload.data.tiers.pp.$temp.openModal}}",
  "primary": false,
  "extraSettings": {
    "text": "Open",
    "script": "{{true}}"
  }
}`

**Additional context**
Flowable 3.14

**Comment by tijsrademakers** [comment]
This is not a Flowable OSS issue, but for Flowable Work. Please use your customer service desk or your sales contact person to raise this issue.
