### ISSUE TITLE
Document get TypeHandler tag is 'tagHandler',why not 'typeHandler'?

### ISSUE THREAD

**Issue by youxiaxiaomage** [flowable/flowable-engine#3811]
I'm confused with org.flowable.common.engine.impl.AbstractEngineConfigurator in the line 126( NodeList typeHandlerList = document.getElementsByTagName("tagHandler");)

correct :  NodeList typeHandlerList = document.getElementsByTagName("typeHandler");
![图片](https://github.com/flowable/flowable-engine/assets/18155578/ef3f0501-7caf-474d-8a24-971c01a4ef0e)

![图片](https://github.com/flowable/flowable-engine/assets/18155578/81088275-8a86-4655-8cab-87d0c01a990e)

**Comment by filiphr** [comment]
This is indeed a mistake @youxiaxiaomage. We'll look into it and fix it.

**Comment by filiphr** [comment]
@youxiaxiaomage I've started into looking into this and I am considering in removing the code for that parsing completely. Can you please let us know why you needed that in the first place? How you found the problem?

**Comment by youxiaxiaomage** [comment]
> @youxiaxiaomage I've started into looking into this and I am considering in removing the code for that parsing completely. Can you please let us know why you needed that in the first place? How you found the problem?

I stumbled upon it by chance while reading the source code,
