### ISSUE TITLE
How to verify whether the user who needs to sign already exists in the task?

### ISSUE THREAD

**Issue by tony2y** [flowable/flowable-engine#3812]
How to verify whether the user who needs to sign already exists in the task?

https://github.com/flowable/flowable-engine/blob/07b74967af223da271a42136fb8c7c3b23aec15f/modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/multiinstance/DynamicMultiInstanceTest.java#L95

**Comment by tony2y** [comment]
@jbarrez

**Comment by filiphr** [comment]
@tony2y please use the [Forum](https://forum.flowable.org/) for asking questions and no need to ping anyone from the time.
