### ISSUE TITLE
why add a runtime activity instance table in 6.4.1 version?

### ISSUE THREAD

**Issue by chanyixialex** [flowable/flowable-engine#3839]
A runtime activity instance table has been added to allow you to query for the activity instances that have been executed for a running process instance without needing to go to the history tables. But I think it can also achieve this by history tables，What is the value of adding this runtime table？thanks.

**Comment by tijsrademakers** [comment]
The history table can grow very big in size, so using a runtime activity instance table to query on activity instance data is more efficient.

**Comment by chanyixialex** [comment]
> The history table can grow very big in size, so using a runtime activity instance table to query on activity instance data is more efficient.

By the way, in the case of upgrade from 6.4.0 to 6.4.1, Will the new feature(add a new runtime table) affect the normal use of the process?
