### ISSUE TITLE
ACT_HI_TASK table field completed_ by_query method not provided

### ISSUE THREAD

**Issue by Swiftlyfisher** [flowable/flowable-engine#3858]
Notice that 7.0.0 act_hi_task table added the completed_by_ but HistoricTaskInstanceQuery does not provide query methods

**Comment by tijsrademakers** [comment]
As can be seen here, there is a query method provided https://github.com/flowable/flowable-engine/blob/main/modules/flowable-task-service-api/src/main/java/org/flowable/task/api/history/HistoricTaskInstanceQuery.java#L78
