### ISSUE TITLE
Why is JDK 21 still not supported, and when will JDK 21 be supported?'

### ISSUE THREAD

**Issue by chozee** [flowable/flowable-engine#3869]
Why is JDK 21 still not supported, and when will JDK 21 be supported?'

**Comment by filiphr** [comment]
@chozee why are you saying that JDK 21 is not supported? The test suites run with JDK 17 and JDK 21 and they are passing.

**Comment by chozee** [comment]
> @chozee why are you saying that JDK 21 is not supported? The test suites run with JDK 17 and JDK 21 and they are passing.

Thank you for your response.I tested it myself and it indeed works. I just didn't find a clear explanation in the documentation and release notes.
