### ISSUE TITLE
realease6.8.1 has a bug ,because The rollback Cannot roll back correctly in the case of multiple instances，please fix soon

### ISSUE THREAD

**Issue by loveqqz** [flowable/flowable-engine#3878]
1.this is rollback operation,but 6.8.1 release Cannot roll back correctly
        runtimeService.createChangeActivityStateBuilder()
                            // 绑定到具体的流程实例
                            .processInstanceId("95e67c6a-01ea-11ef-b769-00d0f8000001")
                            // 从 A 跳转到 B
                            .moveActivityIdTo("Activity_04a817a","Activity_076f3c4")
                            .changeState(); // 执行跳转的操作

**Comment by tijsrademakers** [comment]
Please be elaborate in your issue description and be very precise about the issue. This issue description is not something that is understandable and can be be used to solve any potential issue. Therefore closing the issue.
