### ISSUE TITLE
Delay in seconds before script condition executed

### ISSUE THREAD

**Issue by MichalHecko** [flowable/flowable-engine#3880]
**Describe the bug**
Our solution use Flowable as BPMN engine. We migrated few times from 5.X and ended up to 6.8.0 over two years. I have seen a strange behaviour recently. Maybe it is still there for at least a half of year but i dont know it for sure when it has started.

Long story short:

There is a delay in seconds before execution a script condition in ExclusiveGatewayActivityBehavior when it has to determine sequence flow to take. I have a simple script condition in Groovy which get and compare a variable of current execution. Take a look at the logs i provided

This kind of strange behaviour occurs every time on almost every BPMN process with exclusive gateway on the path. It's almost deterministic and it occurs mostly on script condition rarely somewhere after script condition but still remain on that transition in process.

It might has something to do with human tasks submited before because this kind of strange behaviour doesn't occur on other script in a flow executed in a same transaction.

It concern almost all processes with exclusive gateways. I dont have a clue, why this is happening, but only after human task was submitted. If it has something to do with script compilation or not i dont know.

**Expected behavior**
There is no delay after submitting human task, exclusive gateway and script condition within it.

**Code**

Script condition groovy code is simple lookup on execution's variables, that's why SQL comming out in logs.

![flowable-bug](https://github.com/flowable/flowable-engine/assets/15719078/1ef2b2b2-5b67-4e5c-94e7-31666c3c5a21)

![obrázok](https://github.com/flowable/flowable-engine/assets/15719078/0d7e4f7b-af97-4272-a86d-91cd82b58b45)

**Additional context**
Using Flowable 6.8.0 with Postgres, but i have seen this behaviour on releases before.

**Comment by tijsrademakers** [comment]
Hi Michal, please attach the full debug logging of a process instance run so we can do an analysis on the possible reasons for the delay that you are seeing.

**Comment by MichalHecko** [comment]
Hi,

sure, there are log of submiting task via my REST API over Flowable Service API.

This is kinda interesting, most of the time, the delay is inside ExclusiveGatewayActivityBehavior before script condition and rarely somewhere right after that activity.

![obrázok](https://github.com/flowable/flowable-engine/assets/15719078/b73443bb-e964-4cbd-96c6-c0eb5ae46544)

[Explore-logs-2024-04-29 12 10 33.txt](https://github.com/flowable/flowable-engine/files/15147882/Explore-logs-2024-04-29.12.10.33.txt)

Let me know if i can submit you something more specific, but i dont know, what i am looking for... Maybe there is some lock mechanism inside ContinueProcessOperation, or something like that.

**Comment by MichalHecko** [comment]
In this case the delay must be somewhere inside this code in ContinueProcessOperation right after that log message:

There is an event dispatched but i got no logs what's going on before first line of my log in ScriptTask.

![obrázok](https://github.com/flowable/flowable-engine/assets/15719078/147652ed-62c9-46f6-a169-9171804d8755)

**Comment by filiphr** [comment]
I don't think that the delay is in there @MichalHecko. It could be related to the script parsing (although your script looks really simple).

Is it possible for you to test this by swapping the script task with a service task with an expression like `vyhodnoteniePoziadavkyProcessScript.ulozenieVyhodnoteniaDoKP(execution)`?

Just to rule out whether it is something specific with the Script engine parsing or it is something else.

>There is an event dispatched but i got no logs what's going on before first line of my log in ScriptTask.

Do you have some event listeners perhaps? We are not logging anything, but perhaps you have a custom event listener that is doing something?

**Comment by filiphr** [comment]
Thanks for checking it @MichalHecko
