### ISSUE TITLE
task complete before report NoSuchMethodError: org.flowable.bpmn.model.UserTask.getTaskCompleterVariableName() , flowable version: 7.0.1

### ISSUE THREAD

**Issue by shining-lee** [flowable/flowable-engine#3882]
taskService.complete(taskId)  -> completeTask method in TaskHelper class  report NoSuchMethodError.

problem method code: 
protected static void storeTaskCompleter(TaskEntity taskEntity, ExecutionEntity execution, ProcessEngineConfigurationImpl processEngineConfiguration) {
        if (taskEntity.getProcessDefinitionId() != null) {
            FlowElement flowElement = execution.getCurrentFlowElement();
            if (flowElement instanceof UserTask) {
                UserTask userTask = (UserTask) flowElement;
                String taskCompleterVariableName = userTask.getTaskCompleterVariableName();
                if (StringUtils.isNotEmpty(taskCompleterVariableName)) {
                    ExpressionManager expressionManager = processEngineConfiguration.getExpressionManager();
                    Expression expression = expressionManager.createExpression(userTask.getTaskCompleterVariableName());
                    String completerVariableName = (String) expression.getValue(execution);
                    String completer = Authentication.getAuthenticatedUserId();
                    if (StringUtils.isNotEmpty(completerVariableName)) {
                        execution.setVariable(completerVariableName, completer);
                    }
                }
            }
        }
    }

line String taskCompleterVariableName = userTask.getTaskCompleterVariableName();  is red color .

**Comment by shining-lee** [comment]
![image](https://github.com/flowable/flowable-engine/assets/168972047/1c921d0b-9e3f-42a4-ac53-1a2eb9e52f6a)
![image](https://github.com/flowable/flowable-engine/assets/168972047/32895e42-b342-4c62-9069-2fa71f827d9a)

**Comment by tijsrademakers** [comment]
Hi, not sure why you are creating this issue here, as you can see this method is present in the UserTask class:

https://github.com/flowable/flowable-engine/blob/3f8058b47c5b36eb45d01f812f02580735a974a4/modules/flowable-bpmn-model/src/main/java/org/flowable/bpmn/model/UserTask.java#L228
