### ISSUE TITLE
Add support for Exception Mapping in the flowable-modeler

### ISSUE THREAD

**Issue by paulstapleton** [flowable/flowable-engine#389]
In the documentation there is reference to the ability to map Java exceptions to BPMN errors - i.e. http://www.flowable.org/docs/userguide/index.html#exceptionMapping

Setting this up in the BPMN using the flowable-modeler web-app is not currently supported and this needs adding.

This applies to at least ServiceTasks, but may also possibly apply to cases like CamelTask, MuleTask, MailTask, etc which are special cases of ServiceTask.

This was initially discussed in https://forum.flowable.org/t/support-for-exception-mapping-in-flowable-modeler/568

**Comment by Blikingor** [comment]
Can be closed with https://github.com/flowable/flowable-engine/pull/1840

**Comment by filiphr** [comment]
Thanks @Blikingor
