### ISSUE TITLE
Process migration cannot migrate processes

### ISSUE THREAD

**Issue by sgs98** [flowable/flowable-engine#3893]
**Describe the bug**

**Expected behavior**
After modifying the node name, switching through process migration was unsuccessful
**Code**
If applicable, add the code that you are using when having the issue.
processMigrationService.createProcessInstanceMigrationBuilder()
                .migrateToProcessDefinition(currentProcessDefinitionId)
                .migrateProcessInstances(fromProcessDefinitionId);
**Additional context**
Add the version of Flowable that you are using, the database vendor and if you are using Flowable within Spring Boot, the Flowable Task application etc.
7.0

**Comment by tijsrademakers** [comment]
Hi, please create issues with a clear description and steps on how to reproduce it. This issue has no information about the migration that you are trying to perform, therefore closing it. Please reopen with full info when you have it available.
