### ISSUE TITLE
Process definition id of an async external worker service task job is not updated after direct migration

### ISSUE THREAD

**Issue by basclaessen** [flowable/flowable-engine#3894]
**Describe the bug**
When a process instance with an async external worker service task is migrated using direct migration, the process definition id of the external worker service task job is not updated with the process definition id of the new process definition.

**Expected behavior**
The process definition id of the migrated external worker service task job should contain the process definition id of the new process definition.

**Code**
I'll add a pull request with a test case.

**Additional context**
main branch
flowable-release-7.0.0 branch
flowable-release-7.1.0 branch

caused by
e82e4d4859a05431489657192f16f49e27f71e1b Add support for direct migration for async service tasks in process migration
9cf6db198f6f0150dd47a1a64c5480e11ac0c3e0 Add support for direct migration for async service tasks in process migration

**Comment by basclaessen** [comment]
@tijsrademakers Can you take a look at my PR and if you agree merge it before the next Flowable release please?

**Comment by tijsrademakers** [comment]
@basclaessen , thanks for providing the PR, we've merged it
