### ISSUE TITLE
是否有审批人驳回到上级，上级修改后在发起继续审批流程

### ISSUE THREAD

**Issue by zxgit139** [flowable/flowable-engine#3896]
比如发起一个员工-主管-部门主管-总经理-董事长的任务审批流程， 在部门主管进行了驳回，在主管那边可以进行调整审批的内容，在发起流程继续让部门主管审批，继续走流程，不用重头开始发起审批。

**Comment by tijsrademakers** [comment]
Issues need to be created with full explanation and in English for the Flowable team to be able to work on this. Therefore closing this issue.
