### ISSUE TITLE
startProcessInstanceByKey does not always trigger the process

### ISSUE THREAD

**Issue by Sbruk** [flowable/flowable-engine#3910]
Hello flowable team,

**Describe the bug**
We have embedded the flowable engine 7.0.1 in a maven project with custom re-usable Delegates, Processes, etc... so that it can be imported as a maven dependency and re-used in several applications of ours. The implementation details and usage can be found in the section **Code** below.
Basically, what happens is that we sometimes need to call 2-3-4 times our REST endpoint calling the method **getRuntimeService().startProcessInstanceByKey()** for the process instance to actually be triggered. Also note that, even when it's not triggered, the method returns an instance of **ProcessInstance** with a proper UUID, but we cannot find it in the DB.
This problem seems to happen since we switched from **StandaloneProcessEngineConfiguration** to **JtaProcessEngineConfiguration**. We re-did some tests in the context of the creation of this issue and we cannot reproduce the problem with **StandaloneProcessEngineConfiguration**.

**Expected behavior**
We would expect a process instance to be triggered every single time **getRuntimeService().startProcessInstanceByKey()** is called.

**Code**
You'll find attached the basic code we use to use/trigger a process instance via this maven project.

- ProcessEngineSingleton is part of the **imported** project and acts as a Singleton proxy. It calls **ProcessEngineConfiguration**, which simply maps some Quarkus properties so I didn't bother including it here.
- FlowProcessInstanceService is part of the **imported** project and encapsulates methods related to Flowable process instances. Its content has been reduced to the scope of this issue.
- FlowableResource is part of the **importing** project and simply exposes a REST endpoint to trigger a process instance based on the processDefinitionId.

[Flowable.zip](https://github.com/user-attachments/files/15862713/Flowable.zip)

**Additional context**
Flowable 7.0.1
Quarkus 3.10.2
Postgres 16.1
Java temurin 17

Thanks in advance for your help!

**Comment by Sbruk** [comment]
Hello,

Note that the issue also occurs when creating a variable in a custom delegate. No error is raised but sometimes it's actually created, sometimes it's not.

Thanks!

**Comment by tijsrademakers** [comment]
Hi,

Note that you are using a JTA configuration with a JTA transaction manager, but the data source is configured with setting a jdbc url etc. Here it's expected to set a XA data source instead, that's managed by your application server.

Best regards

**Comment by Sbruk** [comment]
Hello @tijsrademakers,

Thanks for your prompt response, it seems to be properly working now!
For anyone using the same stack and being in the same situation, here is what we went with:

```
final JtaProcessEngineConfiguration cfg = new JtaProcessEngineConfiguration();
final AgroalDataSource defaultDataSource = Arc.container().instance(AgroalDataSource.class).get();
cfg.setDataSource(defaultDataSource).setDatabaseSchema(FlowEngineConfiguration.getDatabaseSchema());
cfg.setTransactionManager(Arc.container().instance(TransactionManager.class).get());
cfg.setIdGenerator(new StrongUuidGenerator()).setJdbcDriver(FlowEngineConfiguration.getJdbcDriver())
        .setDatabaseSchemaUpdate(FlowEngineConfiguration.getDatabaseSchemaUpdate())
        .setAsyncExecutorActivate(FlowEngineConfiguration.getAsyncExecutorActivate())
        .setAsyncFailedJobWaitTime(FlowEngineConfiguration.getAsyncFailedJobWaitTime())
        .setHistory(HistoryLevel.FULL.getKey());
```

Thanks!
