### ISSUE TITLE
reject problem

### ISSUE THREAD

**Issue by lichengliang1** [flowable/flowable-engine#3919]
![9AE39A76-FC30-4a94-AAAD-DFAC53CCA790](https://github.com/flowable/flowable-engine/assets/52151812/a77780ed-4e2e-40c3-ac78-76fd229a7969)
Execution sequence 1->3->4: Return from 4 to 1 1->2->21->4
When the second execution reaches 4, refuting from 4 to 3 cannot be rejected. 4 can only be refuted back to 1, 2, 21
My question is: How can I determine whether a refutation from 4 to 3 cannot be rejected?

**Comment by tijsrademakers** [comment]
Hi, can you please describe the issue in a more concise way? Rejected and refutation are not very clear in the context that you are using it. Can you maybe give code examples to show what you are trying to do?

**Comment by lichengliang1** [comment]
runtimeService.createChangeActivityStateBuilder().processInstanceId(processInstanceId)
                .processVariables(map)
                .moveExecutionsToSingleActivityId(realExecutionIds, targetRealActivityId).changeState();
This is the rejection code, but I want to check whether the targetRealActivityId can be rejected before executing this code. As described above, when it is rejected for the second time from 4 to 3, it cannot be rejected. How can I determine whether the targetRealActivityId can perform the rejection operation

**Comment by tijsrademakers** [comment]
This is no rejection logic, this is moving multiple executions into one execution with a certain state. When you say that it doesn't work beyond a certain point, can you explain what that means? Do you get an error?

**Comment by lichengliang1** [comment]
There are no errors, but the business logic is incorrect
Process execution sequence 1->3->4: Fallback from 4 to 1, and then execute 1->2->21->4 again. If we go back from 4 to 3 at this time, it is logically incorrect because the new flow direction of the process is 1->2->21->4, so going back from 4 to 3 cannot be rolled back. How can I determine if going back from 4 to 3 is not possible?

**Comment by lichengliang1** [comment]
There are no errors, but the business logic is incorrect
Process execution sequence 1->3->4: Fallback from 4 to 1, and then execute 1->2->21->4 again. If we go back from 4 to 3 at this time, it is logically incorrect because the new flow direction of the process is 1->2->21->4, so going back from 4 to 3 cannot be rolled back. How can I determine if going back from 4 to 3 is not possible?

**Comment by lichengliang1** [comment]
There are no errors, but the business logic is incorrect
Process execution sequence 1->3->4: Fallback from 4 to 1, and then execute 1->2->21->4 again. If we go back from 4 to 3 at this time, it is logically incorrect because the new flow direction of the process is 1->2->21->4, so going back from 4 to 3 cannot be rolled back. How can I determine if going back from 4 to 3 is not possible?
