### ISSUE TITLE
Event subscription is missing after migration of an active embedded sub process

### ISSUE THREAD

**Issue by basclaessen** [flowable/flowable-engine#3928]
**Describe the bug**
When a process instance with an active embedded non interrupting event sub process is migrated, the subscription is missing.
For a signal, message or event register event the event subscription is missing.
For a timer event the timer job is missing.

**Expected behavior**
Event subscriptions and timer jobs should not be missing after migration of a process instance with an active embedded event sub process.

**Code**
I'll add a pull request with test cases and a fix.

**Additional context**
main branch
flowable-release-6.8.1 branch
flowable-release-7.1.0 branch
flowable-release-7.2.0 branch

**Comment by basclaessen** [comment]
@tijsrademakers Can you take a look at my PR and if you agree merge it before the next Flowable release please?

**Comment by tijsrademakers** [comment]
@basclaessen thanks, I've merged the PR
