### ISSUE TITLE
historyService.createHistoricTaskInstanceQuery().taskInProgressStartedBy("*****").list() throws an exception

### ISSUE THREAD

**Issue by jin2001** [flowable/flowable-engine#3935]
When I got historicTasks by 【historyService.createHistoricTaskInstanceQuery().taskInProgressStartedBy("*****").list()】, 
the program throws an exception 【Unknown column 'RES.IN_PROGRESS_STARTED_BY' in 'where clause' (ACT_HI_TASKINST)】

**Code**
flowable7.0.1

**Comment by filiphr** [comment]
This was fixed with #3827
