### ISSUE TITLE
historicTaskService Command mode update "START_TIME_",can't update

### ISSUE THREAD

**Issue by keqingf** [flowable/flowable-engine#3938]
**Code**
@Override
    public Boolean execute(CommandContext commandContext) {
        HistoricTaskService historicTaskService = CommandContextUtil.getHistoricTaskService(commandContext);
        HistoricTaskInstanceEntity historicTask = historicTaskService.getHistoricTask(taskId);
        historicTask.setCreateTime(new Date());  // can't update
        historicTask.setAssignee("10086");  // can update
        historicTaskService.updateHistoricTask(historicTask, true);
        return true;
    }

**Comment by filiphr** [comment]
Hey @keqingf,

What's the purpose of doing that?

You are using internal APIs and we do not support updating the `createTime` of a historic task instance through those internal APIs.

Cheers,
Filip

**Comment by keqingf** [comment]
I want to transfer the review of a record. After the transfer, the task should recalculate the time.

> 嘿@keqingf，
> 
> 这么做的目的是什么？
> 
> 您正在使用内部 API，我们不支持`createTime`通过这些内部 API 更新历史任务实例。
> 
> 干杯， 菲利普

I want to transfer the review of a record. After the transfer, the task should recalculate the time.

**Comment by filiphr** [comment]
Ideally, you would create a new Task. Currently, we do not support updating the create time of a historic task.

**Comment by keqingf** [comment]
> Ideally, you would create a new Task. Currently, we do not support updating the create time of a historic task.

Okay, I'll give it a try.
