### ISSUE TITLE
Run Software from Source Code

### ISSUE THREAD

**Issue by mobin-alz** [flowable/flowable-engine#3941]
**Issue Description**
I am encountering difficulties with the most recent version (7.0.1) of the software. In contrast to the preview release, which included a JAR file facilitating execution from the source code, the current version lacks this component. Consequently, I am seeking guidance on how to proceed with running the application from its source code. Additionally, I aim to customize the application according to my requirements.

**Requested Assistance**
Could you kindly assist me in navigating through the process of executing the application from its source code? Furthermore, I would greatly appreciate any advice or resources on customizing the application to better suit my needs.

Thank you for your attention to this matter.

**Comment by tijsrademakers** [comment]
Sorry, it's not clear what kind of issue you are facing. Can you explain in more detail how you were running Flowable before and what is not working for you with version 7.0.1?

**Comment by mobin-alz** [comment]
I can't run it from source code 
1 - git clone (sh link)
2 - open it on intellij 
after that I don't know how to run it and where is main file to run ?

**Comment by mobin-alz** [comment]
> Sorry, it's not clear what kind of issue you are facing. Can you explain in more detail how you were running Flowable before and what is not working for you with version 7.0.1?

1- I used **mvn clean install -DskipTests**
2 - result of this command : 
[INFO] Reactor Summary for Flowable 7.0.1:
[INFO] 
[INFO] Flowable BOM ....................................... SUCCESS [  0.107 s]
[INFO] Flowable ........................................... SUCCESS [  0.026 s]
[INFO] Flowable - BPMN Model .............................. SUCCESS [  2.552 s]
[INFO] Flowable - Process Validation ...................... SUCCESS [  0.444 s]
[INFO] Flowable - BPMN Layout ............................. SUCCESS [  0.287 s]
[INFO] Flowable - Image Generator ......................... SUCCESS [  0.451 s]
[INFO] Flowable - Engine Common API ....................... SUCCESS [  0.287 s]
[INFO] Flowable - Variable Service API .................... SUCCESS [  0.179 s]
[INFO] Flowable - Event Registry Model .................... SUCCESS [  0.212 s]
[INFO] Flowable - Event Registry API ...................... SUCCESS [  0.249 s]
[INFO] Flowable - Content API ............................. SUCCESS [  0.150 s]
[INFO] Flowable - Mail .................................... SUCCESS [  0.285 s]
[INFO] Flowable - Engine Common ........................... SUCCESS [  4.254 s]
[INFO] Flowable - BPMN Converter .......................... SUCCESS [  5.276 s]
[INFO] Flowable - Entity Link Service API ................. SUCCESS [  0.109 s]
[INFO] Flowable - Entity Link Service ..................... SUCCESS [  0.409 s]
[INFO] Flowable - Variable Service ........................ SUCCESS [  0.687 s]
[INFO] Flowable - Identity Link Service API ............... SUCCESS [  0.089 s]
[INFO] Flowable - Identity Link Service ................... SUCCESS [  0.395 s]
[INFO] flowable-event-registry-json-converter ............. SUCCESS [  1.096 s]
[INFO] Flowable - Event Subscription Service API .......... SUCCESS [  0.120 s]
[INFO] Flowable - Event Registry .......................... SUCCESS [ 34.692 s]
[INFO] flowable-event-registry-configurator ............... SUCCESS [  0.135 s]
[INFO] Flowable - Event Subscription Service .............. SUCCESS [  0.389 s]
[INFO] Flowable - Task Service API ........................ SUCCESS [  0.119 s]
[INFO] Flowable - IDM API ................................. SUCCESS [  0.145 s]
[INFO] Flowable - Task Service ............................ SUCCESS [  0.571 s]
[INFO] Flowable - Job Service API ......................... SUCCESS [  0.109 s]
[INFO] Flowable - Job Service ............................. SUCCESS [  2.183 s]
[INFO] Flowable Job Spring Service ........................ SUCCESS [  0.101 s]
[INFO] Flowable - Batch Service API ....................... SUCCESS [  0.093 s]
[INFO] Flowable - Batch Service ........................... SUCCESS [  0.279 s]
[INFO] Flowable - IDM Engine .............................. SUCCESS [  4.790 s]
[INFO] flowable-idm-engine-configurator ................... SUCCESS [  0.112 s]
[INFO] Flowable - Form API ................................ SUCCESS [  0.124 s]
[INFO] Flowable - Form Model .............................. SUCCESS [  0.117 s]
[INFO] Flowable - DMN Model ............................... SUCCESS [  0.183 s]
[INFO] Flowable - DMN API ................................. SUCCESS [  0.196 s]
[INFO] Flowable - DMN XML Converter ....................... SUCCESS [  1.438 s]
[INFO] Flowable - DMN Image Generator ..................... SUCCESS [  0.146 s]
[INFO] Flowable - DMN Engine .............................. SUCCESS [ 37.633 s]
[INFO] Flowable - CMMN Model .............................. SUCCESS [  0.209 s]
[INFO] Flowable - CMMN API ................................ SUCCESS [  0.243 s]
[INFO] Flowable - HTTP Common ............................. SUCCESS [  1.189 s]
[INFO] Flowable - Engine .................................. SUCCESS [12:14 min]
[INFO] Flowable - CMMN Image Generator .................... SUCCESS [  0.966 s]
[INFO] Flowable - CMMN Converter .......................... SUCCESS [  4.570 s]
[INFO] Flowable - Case Validation ......................... SUCCESS [  0.765 s]
[INFO] Flowable - CMMN Engine ............................. SUCCESS [02:11 min]
[INFO] Flowable - CMMN Engine Configurator ................ SUCCESS [ 58.823 s]
[INFO] Flowable - Dmn Engine Configurator ................. SUCCESS [ 37.477 s]
[INFO] Flowable - App Engine API .......................... SUCCESS [  0.129 s]
[INFO] Flowable - App Engine .............................. SUCCESS [ 34.481 s]
[INFO] flowable-spring-security ........................... SUCCESS [  2.034 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18:29 min
[INFO] Finished at: 2024-08-05T00:51:20+03:30
[INFO] ------------------------------------------------------------------------


3 - **mvn spring-boot:run**
[mobin@mobin flowable-engine-flowable-7.0.1]$ mvn spring-boot:run
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Flowable BOM                                                       [pom]
[INFO] Flowable                                                           [pom]
[INFO] Flowable - BPMN Model                                              [jar]
[INFO] Flowable - Process Validation                                      [jar]
[INFO] Flowable - BPMN Layout                                             [jar]
[INFO] Flowable - Image Generator                                         [jar]
[INFO] Flowable - Engine Common API                                       [jar]
[INFO] Flowable - Variable Service API                                    [jar]
[INFO] Flowable - Event Registry Model                                    [jar]
[INFO] Flowable - Event Registry API                                      [jar]
[INFO] Flowable - Content API                                             [jar]
[INFO] Flowable - Mail                                                    [jar]
[INFO] Flowable - Engine Common                                           [jar]
[INFO] Flowable - BPMN Converter                                          [jar]
[INFO] Flowable - Entity Link Service API                                 [jar]
[INFO] Flowable - Entity Link Service                                     [jar]
[INFO] Flowable - Variable Service                                        [jar]
[INFO] Flowable - Identity Link Service API                               [jar]
[INFO] Flowable - Identity Link Service                                   [jar]
[INFO] flowable-event-registry-json-converter                             [jar]
[INFO] Flowable - Event Subscription Service API                          [jar]
[INFO] Flowable - Event Registry                                          [jar]
[INFO] flowable-event-registry-configurator                               [jar]
[INFO] Flowable - Event Subscription Service                              [jar]
[INFO] Flowable - Task Service API                                        [jar]
[INFO] Flowable - IDM API                                                 [jar]
[INFO] Flowable - Task Service                                            [jar]
[INFO] Flowable - Job Service API                                         [jar]
[INFO] Flowable - Job Service                                             [jar]
[INFO] Flowable Job Spring Service                                        [jar]
[INFO] Flowable - Batch Service API                                       [jar]
[INFO] Flowable - Batch Service                                           [jar]
[INFO] Flowable - IDM Engine                                              [jar]
[INFO] flowable-idm-engine-configurator                                   [jar]
[INFO] Flowable - Form API                                                [jar]
[INFO] Flowable - Form Model                                              [jar]
[INFO] Flowable - DMN Model                                               [jar]
[INFO] Flowable - DMN API                                                 [jar]
[INFO] Flowable - DMN XML Converter                                       [jar]
[INFO] Flowable - DMN Image Generator                                     [jar]
[INFO] Flowable - DMN Engine                                              [jar]
[INFO] Flowable - CMMN Model                                              [jar]
[INFO] Flowable - CMMN API                                                [jar]
[INFO] Flowable - HTTP Common                                             [jar]
[INFO] Flowable - Engine                                                  [jar]
[INFO] Flowable - CMMN Image Generator                                    [jar]
[INFO] Flowable - CMMN Converter                                          [jar]
[INFO] Flowable - Case Validation                                         [jar]
[INFO] Flowable - CMMN Engine                                             [jar]
[INFO] Flowable - CMMN Engine Configurator                                [jar]
[INFO] Flowable - Dmn Engine Configurator                                 [jar]
[INFO] Flowable - App Engine API                                          [jar]
[INFO] Flowable - App Engine                                              [jar]
[INFO] flowable-spring-security                                           [jar]
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 kB at 4.0 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (21 kB at 4.9 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Flowable 7.0.1:
[INFO] 
[INFO] Flowable BOM ....................................... SKIPPED
[INFO] Flowable ........................................... SKIPPED
[INFO] Flowable - BPMN Model .............................. SKIPPED
[INFO] Flowable - Process Validation ...................... SKIPPED
[INFO] Flowable - BPMN Layout ............................. SKIPPED
[INFO] Flowable - Image Generator ......................... SKIPPED
[INFO] Flowable - Engine Common API ....................... SKIPPED
[INFO] Flowable - Variable Service API .................... SKIPPED
[INFO] Flowable - Event Registry Model .................... SKIPPED
[INFO] Flowable - Event Registry API ...................... SKIPPED
[INFO] Flowable - Content API ............................. SKIPPED
[INFO] Flowable - Mail .................................... SKIPPED
[INFO] Flowable - Engine Common ........................... SKIPPED
[INFO] Flowable - BPMN Converter .......................... SKIPPED
[INFO] Flowable - Entity Link Service API ................. SKIPPED
[INFO] Flowable - Entity Link Service ..................... SKIPPED
[INFO] Flowable - Variable Service ........................ SKIPPED
[INFO] Flowable - Identity Link Service API ............... SKIPPED
[INFO] Flowable - Identity Link Service ................... SKIPPED
[INFO] flowable-event-registry-json-converter ............. SKIPPED
[INFO] Flowable - Event Subscription Service API .......... SKIPPED
[INFO] Flowable - Event Registry .......................... SKIPPED
[INFO] flowable-event-registry-configurator ............... SKIPPED
[INFO] Flowable - Event Subscription Service .............. SKIPPED
[INFO] Flowable - Task Service API ........................ SKIPPED
[INFO] Flowable - IDM API ................................. SKIPPED
[INFO] Flowable - Task Service ............................ SKIPPED
[INFO] Flowable - Job Service API ......................... SKIPPED
[INFO] Flowable - Job Service ............................. SKIPPED
[INFO] Flowable Job Spring Service ........................ SKIPPED
[INFO] Flowable - Batch Service API ....................... SKIPPED
[INFO] Flowable - Batch Service ........................... SKIPPED
[INFO] Flowable - IDM Engine .............................. SKIPPED
[INFO] flowable-idm-engine-configurator ................... SKIPPED
[INFO] Flowable - Form API ................................ SKIPPED
[INFO] Flowable - Form Model .............................. SKIPPED
[INFO] Flowable - DMN Model ............................... SKIPPED
[INFO] Flowable - DMN API ................................. SKIPPED
[INFO] Flowable - DMN XML Converter ....................... SKIPPED
[INFO] Flowable - DMN Image Generator ..................... SKIPPED
[INFO] Flowable - DMN Engine .............................. SKIPPED
[INFO] Flowable - CMMN Model .............................. SKIPPED
[INFO] Flowable - CMMN API ................................ SKIPPED
[INFO] Flowable - HTTP Common ............................. SKIPPED
[INFO] Flowable - Engine .................................. SKIPPED
[INFO] Flowable - CMMN Image Generator .................... SKIPPED
[INFO] Flowable - CMMN Converter .......................... SKIPPED
[INFO] Flowable - Case Validation ......................... SKIPPED
[INFO] Flowable - CMMN Engine ............................. SKIPPED
[INFO] Flowable - CMMN Engine Configurator ................ SKIPPED
[INFO] Flowable - Dmn Engine Configurator ................. SKIPPED
[INFO] Flowable - App Engine API .......................... SKIPPED
[INFO] Flowable - App Engine .............................. SKIPPED
[INFO] flowable-spring-security ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.420 s
[INFO] Finished at: 2024-08-05T00:51:58+03:30
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'spring-boot' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/mobin/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

**Comment by tijsrademakers** [comment]
You can run the  Flowable REST Spring Boot application with the spring-boot:run command from modules/flowable-app-rest.
