### ISSUE TITLE
Extension attribute delegateExpression defined for a ServiceTask is lost while using BpmnXMLConverter

### ISSUE THREAD

**Issue by janslee** [flowable/flowable-engine#3942]
**Describe the bug**
When using the BpmnXMLConverter to convert a BpmnModel to XML, I defined a delegateExpression for the servicetask element, but it is lost during the conversion process,

**Expected behavior**
conversion process can convert the delegateExpression attribute

**Code**
BpmnModel model = new BpmnModel();
Process process = new Process();
...
        flowElement = new ServiceTask();
        ...
        ExtensionAttribute extensionAttribute = new ExtensionAttribute();
        extensionAttribute.setNamespace(BpmnXMLConstants.FLOWABLE_EXTENSIONS_NAMESPACE);
        extensionAttribute.setNamespacePrefix(BpmnXMLConstants.FLOWABLE_EXTENSIONS_PREFIX);
        extensionAttribute.setName("delegateExpression");
        extensionAttribute.setValue("${" + delegateExpression + "}");
        flowElement.addAttribute(extensionAttribute);

          BpmnAutoLayout bpmnLayout = new BpmnAutoLayout(model); //debug can see the delegateExpression attribute
            bpmnLayout.execute();
            // convert to xml
            BpmnXMLConverter converter = new BpmnXMLConverter();
            xmlBytes = converter.convertToXML(model, "UTF-8");
            String xmlString = new String(xmlBytes, "UTF-8");  //missing the delegateExpression attribute in XML

**Additional context**
flowable version: 6.8.1, using mysql database, spring boot:2.7.18

**Comment by filiphr** [comment]
Hey @janslee,

Some attributes are treated specially by Flowable. In order to achieve what you are looking for you should not use an extension attribute. Rather use the setters on the `ServiceTask` itself.

e.g.

```java
ServiceTask serviceTask = new ServiceTask();
serviceTask.setImplementationType(ImplementationType.IMPLEMENTATION_TYPE_DELEGATEEXPRESSION);
serviceTask.setImplementation("${" + delegateExpression + "}");
```

Doing it this way should export the delegate expression attribute in the XML.

**Comment by janslee** [comment]
Thanks a lot!you da man, it works perfectly
