### ISSUE TITLE
Flowable UI and Whitelabel Error Page

### ISSUE THREAD

**Issue by mobin-alz** [flowable/flowable-engine#3947]
I want to use flowable-ui and I go to flowable website and logged in after that I download trail version I don't know how to connect engine to ui I want to customize ui myself .
I also go to http://localhost:8080/flowable-rest/ and see this error
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Aug 12 22:36:04 IRST 2024
There was an unexpected error (type=Not Found, status=404).
No message available
 I don't know how to fix it ?

**Comment by filiphr** [comment]
Hey @mobin-alz, as we announced with the Flowable 7.0 Release in the [forum](https://forum.flowable.org/t/flowable-7-0-0-release/10861), [our website](https://www.flowable.com/blog/releases/flowable-open-source-7-0-0-release) and the [Release Notes](https://github.com/flowable/flowable-engine/releases/tag/flowable-7.0.0) there are no longer UI Applications.

If you want to get the REST Application you can still get it from the flowable-7.0.0.zip from the release notes, but there is no UI there. The trial that you download when you login to Flowable is the enterprise UI (Flowable Work) that you can try for a limited period.

Hope this answers your question
