### ISSUE TITLE
Title: How to Ensure Non-Nullable Fields with Default Values in Flowable 6.6.0?

### ISSUE THREAD

**Issue by wyx-98** [flowable/flowable-engine#3966]
I'm currently using Flowable 6.6.0, and my company requires that all database fields must be defined as non-nullable and have default values. Is there a way to achieve this through configuration settings, or do I need to modify the database schema directly? Any guidance on best practices or examples would be greatly appreciated!

**Comment by filiphr** [comment]
You cannot achieve this since Flowable has nullable fields in the database and those fields cannot have a default value. It's first time hearing that some company requires all database fields to be non-nullable.
