### ISSUE TITLE
Why the FormEngineConfiguration disappear?

### ISSUE THREAD

**Issue by kelvin-cai** [flowable/flowable-engine#3986]
**Describe the bug**
when using 6.x ,  I can see FormEngineConfiguration  and table act_fo_*, but now use 7.1.0 , can not find "flowable-form-engine" this dependency.
Thus, when using  "runtimeService.getStartFormModel(procDefId, proInsId)" , the framework report error "Form engine not initialized error". Eventhough I can use method "submitFormData" , eventually I can not get the data from database.

**Expected behavior**
can use FormEngine, can use "runtimeService.getStartFormModel"

**Additional context**
springboot 3.1.4
flowable 7.1.0
mysql

**Comment by dbmalkovsky** [comment]
The Form engine is no longer part of Flowable 7.x; see https://www.flowable.com/blog/releases/flowable-open-source-7-0-0-release

**Comment by filiphr** [comment]
Thanks for the explanation @dbmalkovsky. Closing this now.
