### ISSUE TITLE
Bug in error propagation

### ISSUE THREAD

**Issue by explorer566** [flowable/flowable-engine#399]
Sorry to bother again, but I posted a comment to my closed issue #350 that might have gone unnoticed.
The fix to class _org.flowable.engine.impl.bpmn.helper.ErrorPropagation_ applied to version 601 isn't working correctly in some cases.
I attach a unit test case (_ErrorPropagation3Test_) to demonstrate this. The other included unit tests refer to my issues #350 and #364 that have been fixed in version 601.

[flowable-test.zip](https://github.com/flowable/flowable-engine/files/1033300/flowable-test.zip)

Thanx
Ralf

**Comment by tijsrademakers** [comment]
Hi Ralf,

Thanks for getting back to this, it got indeed lost in the closed issues ;-)
Will have a look at your test project and get back to you.

Regards,

Tijs

**Comment by tijsrademakers** [comment]
Hi Ralf,

I've added the ErrorPropagation3Test unit test class to the current master (6.1.0-SNAPSHOT), and it runs green there. Should the test be changed to demonstrate the error propagation doesn't work in some cases?

Regards,

Tijs

**Comment by explorer566** [comment]
Hi Tijs,

with version 6.0.1 I get a NullpointerException running this unit test. Have you changed something in class _org.flowable.engine.impl.bpmn.helper.ErrorPropagation_ since 6.0.1?

The two BPMNs involved in this workflow (_catchError3.bpmn_ and _catchError4.bpmn_) have both one sub process with the same id. _catchError4.bpmn_ calls _catchError3.bpmn_ as call activity.

The problem is in method _propagateError_ of class _org.flowable.engine.impl.bpmn.helper.ErrorPropagation_. In line 79 all the catching boundary events of the entire super execution hierarchy is stored in one event map (using the id of sub processes with catching boundary events as keys). So in my unit testcase only one of the boundary events attached to the sub processes with the same id "survives" in the map - in my case the one from the _catchError4.bpmn_ that shouldn't be used since the one from _catchError4.bpmn_ is the right one.

Regards, 

Ralf

**Comment by tijsrademakers** [comment]
Hi Ralf,

I'm not aware of a change, but I did do some changes now based on your info. Could you check if the changes work for the error event use cases you can think about?

Thanks,

Tijs

**Comment by explorer566** [comment]
Hi Tijs,

I can confirm that your fix works with my unit tests. It was a good idea to make the keys of the event map unique.

Thanks for your effort,

Ralf
