### ISSUE TITLE
Database migration 7.0.1 to 7.1.0 fails on postgres

### ISSUE THREAD

**Issue by thmarx** [flowable/flowable-engine#3990]
**Describe the bug**
We use flowable in an embedded scenario within a spring boot application. Postgres is used as the database. After updating from flowable 7.0.1 to 7.1.0, the application no longer starts. According to the log, the migration of the database does not work.

**Expected behavior**
Database is migrated without problems and the applications starts.

**Logs**
[INFO] Upgrade needed: 7011 -> 7100. Looking for schema update resource for component 'common'

[INFO] upgrading flowable common schema from 7.0.1.1 to 7.1.0.2

[INFO] performing upgrade on common with resource org/flowable/common/db/upgrade/flowable.postgres.upgradestep.7011.to.7100.common.sql

[ERROR] problem during schema upgrade, statement create index ACT_IDX_ACT_HI_TSK_LOG_TASK on ACT_HI_TSK_LOG(TASK_ID_)

Here's the stacktrace

`Caused by: org.postgresql.util.PSQLException: ERROR: relation "act_hi_tsk_log" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2733)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2420)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:372)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:517)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:434)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:356)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:341)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:317)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:312)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at org.flowable.common.engine.impl.db.AbstractSqlScriptBasedDbSchemaManager.executeSchemaResource(AbstractSqlScriptBasedDbSchemaManager.java:320)`

**Comment by tijsrademakers** [comment]
Hi, the ACT_HI_TSK_LOG table is already there since version 6.4.x of Flowable. Do you know if you changed the database schema manually? Maybe dropped this table manually?

**Comment by thmarx** [comment]
No, we didn't change the db schema by ourselves.

But I got some more information about our setup:
we run flowable in multi tenant mode, with a separate datasource for each tenant. This system doesn't have any tenant, so only the database create, by default, is available.

Our service was originally developed with flowable 7.0.1 and now after updating to 7.1.0 this error occurred.

These are the created tables in the "default" db.
![image](https://github.com/user-attachments/assets/3d600f3f-5011-4f2b-b41c-9d0a8805e671)

**Comment by thmarx** [comment]
no, our main usage is the process engine.
we use the spring-boot-starter for process.
```xml
<dependency>
    <groupId>org.flowable</groupId>
    <artifactId>flowable-spring-boot-starter-process</artifactId>
    <version>${flowable.version}</version>
</dependency>
```

the only reference to event registry is this one:

```java
//by having dependency only for processEngine at pom.xml, if you disable event registry at processdefinition
//it tries to find bean for event registry and the application doesn't start if you don't create one!
@Bean
public EngineConfigurationConfigurer
    <SpringEventRegistryEngineConfiguration> eventRegistryEngineConfigurationEngine() {
    return SpringEventRegistryEngineConfiguration::buildEventRegistryEngine;
}
```

**Comment by thmarx** [comment]
Thank you, we will try that. But would the database migration still not run and cause the error?

**Comment by filiphr** [comment]
I am assuming that the problem is happening due to the fact that the event registry DB migration is running, and this is causing the problem. If you disable the event registry then its DB migration should not run.

**Comment by thmarx** [comment]
@filiphr we just tested this in a test environment. It works as you wrote. Thank you very much for the quick help.
