### ISSUE TITLE
HistoricActivityInstanceQuery search unfinished activities - always zero results

### ISSUE THREAD

**Issue by motorina0** [flowable/flowable-engine#40]
Query for all unfinished Historyc Activity Instances using HistoricActivityInstanceQuery.

**Actual result:**

- always get zero result

**Expected result:**

- should return the entries that do NOT have an END_TIME (END_TIME is null)
```

    HistoryService historyService = activitiRule.getHistoryService();
    HistoricActivityInstanceQuery historicActivityInstanceQuery = historyService.createHistoricActivityInstanceQuery();

    long finishedActivityInstanceCount = historicActivityInstanceQuery.finished().count();
    assertEquals("The Start event is completed", 1, finishedActivityInstanceCount);
    
    //select count(RES.ID_) from ACT_HI_ACTINST RES WHERE RES.END_TIME_ is null and RES.END_TIME_ is not null 
    long unfinishedActivityInstanceCount = historicActivityInstanceQuery.unfinished().count();
    assertEquals("There is one active task", 1, unfinishedActivityInstanceCount);

```
The generated SQL query is:
`select count(RES.ID_) from ACT_HI_ACTINST RES WHERE RES.END_TIME_ is null and RES.END_TIME_ is not null `

**Comment by motorina0** [comment]
Problem present since the first version:
commit 31a518db8470747b946b92683b33c87e9835ddf9
ACT-327: added finished() to historicActivityInstanceQuery/HistoricProcessInstanceQuery

The query terms **finished()** and **unfinished()** are mutually exclusive. When one is **true**, the other should be **false**.

**Comment by tijsrademakers** [comment]
Merged the PR, thanks
