### ISSUE TITLE
Locale support for MomentJS (UI)

### ISSUE THREAD

**Issue by yvoswillens** [flowable/flowable-engine#409]
As described in forum post (https://forum.flowable.org/t/momentjs-does-not-work-in-modeler-and-task/614) current MomentJS is not taking the browser's locale into account.

MomentJS should be initialized with the locale determined by Angular translate.

**Comment by tijsrademakers** [comment]
Option datesLocalization is added to the app-cfg.js files in the UI apps to use the browser language for moment js. The default value is set to false, so it will use English by default. There's an issue currently to get the locale determined by Angular translate, so therefore this intermediate solution.
