### ISSUE TITLE
UI applications do not work on a port other then 8080

### ISSUE THREAD

**Issue by nick-pww** [flowable/flowable-engine#417]
Deploy UI applications to a container not running on 8080 and all the redirects to IDM still try to point to 8080. Even the IDM Login page incorrectly ports back to 8080 when trying to login.

Also, even after logging in and manually navigating back to the IDM application to very success and then going to the modeler application I still get redirected back to the IDM application as if I'm not logged in.

The flowable login cookie does appear to be set correctly.

**Comment by tijsrademakers** [comment]
In the flowable-ui-app.properties you can override the default redirect urls:

idm.app.url=http://localhost:8080/flowable-idm
app.redirect.url.on.authsuccess=http://localhost:8080/flowable-task
