### ISSUE TITLE
DefaultFlowable5CompatibilityHandler class not found

### ISSUE THREAD

**Issue by qiudaoke** [flowable/flowable-engine#418]
hi:
I use flowable-engine6.0.1, my flowable.cfg.xml

	<bean id="processEngineConfiguration"
		class="org.flowable.engine.impl.cfg.StandaloneProcessEngineConfiguration">
		<property name="dataSource" ref="dataSource" />
		<property name="databaseSchemaUpdate" value="true" />
		<property name="flowable5CompatibilityEnabled" value="true" />
	</bean>

public class DefaultFlowable5CompatibilityHandlerFactory implements Flowable5CompatibilityHandlerFactory {

    private static final Logger logger = LoggerFactory.getLogger(DefaultFlowable5CompatibilityHandlerFactory.class);

    protected String compatibilityHandlerClassName;

    @Override
    public Flowable5CompatibilityHandler createFlowable5CompatibilityHandler() {

        if (compatibilityHandlerClassName == null) {
            compatibilityHandlerClassName = "org.flowable.compatibility.DefaultFlowable5CompatibilityHandler";
        }

        try {
            Flowable5CompatibilityHandler handler = (Flowable5CompatibilityHandler) Class.forName(compatibilityHandlerClassName).newInstance();
            return handler;
        } catch (Exception e) {
            logger.info("Flowable 5 compatibility handler implementation not found or error during instantiation : {}. Flowable 5 backwards compatibility disabled.",
                    e.getMessage());
        }
        return null;
    }

it's error  not found class org.flowable.compatibility.DefaultFlowable5CompatibilityHandler 
in jar

Thank you

**Comment by tijsrademakers** [comment]
Hi,

Please use the forum for these kind of questions.
You can find that you need to add a flowable5-compatibility dependency to your project as well, in the migration guide -> http://www.flowable.org/docs/userguide/migration.html#_v5_compatibility
