### ISSUE TITLE
Completed process instances - diagram not available

### ISSUE THREAD

**Issue by motorina0** [flowable/flowable-engine#447]
Forum Topic:
https://forum.flowable.org/t/completed-process-instance-diagram/684

After a process instance is completed or canceled the diagram is no longer available.

IMHO it makes more sense to have the diagram for the completed process than for the active process (which could live for only a few seconds).

  For active instances there is this API:
   `GET runtime/process-instances/{processInstanceId}/diagram`

However for completed processes there is nothing of the form:
   `GET history/historic-process-instances/{processInstanceId}/diagram`

Also in the web-apps (admin and task) the diagram is only available for active process instances.

**Comment by motorina0** [comment]
**Completed Process Instance**

![image](https://user-images.githubusercontent.com/2951406/27724490-d3a089dc-5d7a-11e7-99bf-ee81cc49e8f0.png)

**Comment by motorina0** [comment]
**Active Process Instance**

![image](https://user-images.githubusercontent.com/2951406/27724509-ef02ee40-5d7a-11e7-939d-ab584d038f6e.png)

**Comment by tijsrademakers** [comment]
The process instance diagram is now also available for completed process instances. In the REST API there's no diagram image resource, because we want to focus development on the JS rendered process image.

**Comment by motorina0** [comment]
Great, thanks!

One more question :)

The JS renderer uses the normal `history/historic-process-instances`  API for "populating" the view, or is there a separate API?

**Comment by muhdkhokhar** [comment]
please someone look at my recent issue. I am having issue I am not seeing diagram button

**Comment by tijsrademakers** [comment]
@muhdkhokhar please don't comment on closed issues

**Comment by muhdkhokhar** [comment]
sorry about that
