### ISSUE TITLE
Recording of task events for user identity links is inconsistent

### ISSUE THREAD

**Issue by reva** [flowable/flowable-engine#448]
Given a user task and calling `taskService.claim('1', 'flowable')`, flowable will add a comment with action `AddUserLink`. Calling `taskService.unclaim('1')` should create a `DeleteUserlink`comment, but doesn't.

This leads to the recording of an incorrect task history.

I would suggest maybe removing the add*IdentityLinkComment() methods from the HistoryManager interface and moving all of that logic into the AbstractHistoryManager.

**Comment by reva** [comment]
Actually, `claim`doesn't event add a `AddUserLink`, only `setAssignee` does, so even more inconsistency there.

**Comment by tijsrademakers** [comment]
Fixed inconsistency
