### ISSUE TITLE
"Couldn't get data from the server" error in flowable-admin app

### ISSUE THREAD

**Issue by Neurf** [flowable/flowable-engine#449]
In the flowable-admin app, in the "form engine" tab when i click on the "definitions" sub-tab i get an error message "we couldn't get the data from the server" and i get this trace in my Eclipse (STS) console : GRAVE: Servlet.service() for servlet [dispatcher] in context with path [/flowable-admin] threw exception [Request processing failed; nested exception is org.flowable.admin.service.engine.exception.FlowableServiceException: An error occurred while calling Flowable: HTTP/1.1 404 Introuvable] with root cause. But the admin-app is up and running, i can access it without problems

Forum's question reference :
https://forum.flowable.org/t/missing-dependencies-in-admin-app/678/4

Flowable version 6.1.0

**Comment by simadrig75** [comment]
i am also facing the same issue.
