### ISSUE TITLE
Non-stop refresh of tasks page with programmatically created tasks

### ISSUE THREAD

**Issue by Neurf** [flowable/flowable-engine#450]
In the flowable-task app, in the "tasks" tab, tasks from programmatically started processes make the page refresh continuously (as if i was spamming F5) but whenever the task is created through the "create task" button or is created by a process started from the "processes" page, the  "tasks" page works perfectly.

I also noticed the following things : 

- There is no process corresponding to the task in the "processes" tab
- When the page appears between each refresh the task is visible in the left column and its description appears briefly in the right column then disappears and the central panel's text change to "the task you are looking for cannot be found"

There's no error in my server's log and the only error in the javascript console was due to a missing i18n json file corresponding to my native language (fr-FR.json) which i fixed by copying, pasting and renaming the en.json file in the appropriate folder.

I tested this behaviour on Chrome ( Version 58.0.3029.110 (64-bit) ) and Internet Explorer 11.

Here is my java code to deploy the process and start it programmatically and the process definition (had to rename them in txt to attach them in github) :

[SimpleProcessTest.txt](https://github.com/flowable/flowable-engine/files/1115238/SimpleProcessTest.txt)
[myProcess.bpmn20.txt](https://github.com/flowable/flowable-engine/files/1115241/myProcess.bpmn20.txt)

**Comment by tijsrademakers** [comment]
I'm sorry but I can't reproduce this behaviour in any way. The task is showing correctly in the Flowable Task app and no refresh is happening. Could you do some debugging to see where this refresh action is triggered by?

**Comment by Neurf** [comment]
Unfortunately javascript and web aren't my speciality at all so i'm not able to use anything other than the  "Inspect" menu in chrome :( 

But i did notice another error in the javascript console that i did not see before (don't know why) : i'm getting a "403 forbidden" with the message "User is not allowed to work with task <id_of_task>" while being connected with the user to which the user task was assigned (i'm using the admin user created by default).

It happens with the url "http://localhost:8080/flowable-task/app/rest/tasks/<id_of_task>" (that javascript is trying to use) which gives me this json {"message":"User is not allowed to work with task <id_of_task>","messageKey":"GENERAL.ERROR.FORBIDDEN"}.

I tested the rest api directly with http://localhost:8080/flowable-rest/service/runtime/tasks/<id_of_task> and it works correctly.

**Comment by tijsrademakers** [comment]
This issue should not occur anymore on the current master.
