### ISSUE TITLE
Eclipse Designer: Not possible to set inheritBusinessKey property for callActivity task

### ISSUE THREAD

**Issue by mdulisch72** [flowable/flowable-engine#452]
It is not possible to set the inheritBusinessKey property in Eclipse Designer.
When adding this attribute via XML editor it is deleted again when opening in Flowable Diagram Editor.

**Comment by koke24** [comment]
The change is complex but not difficult. I have created a branch called designer-changes based on flowable-engine 5.22.0 in my fork https://github.com/koke24/flowable-engine.git. You'll have to rebuild the jars flowable-bpmn-converter-5.22.0.jar and flowable-bpmn-model-5.22.0.jar with these changes. Then repack them into org.flowable.designer.libs_5.22.0.jar and put it into the zip you download from http://www.flowable.org/designer/archived/flowable-designer-5.22.0.zip. Install the plugin in Eclipse as explained and inheritBusinessKey won't vanish anymore when saving with the designer.

Best regards

**Comment by filiphr** [comment]
Because of the focus on the engine development + the web modeler, closing this issue
