### ISSUE TITLE
Question regarding HTTP Task request and response handler

### ISSUE THREAD

**Issue by h7kanna** [flowable/flowable-engine#454]
Hi @tijsrademakers ,

Any reason why the CloseableHttpClient is used here instead of just HttpClient interface?

https://github.com/flowable/flowable-engine/blob/master/modules/flowable-http/src/main/java/org/flowable/http/delegate/HttpRequestHandler.java#L18

Also is anyone working on documenting the usage of request/response handlers?

Thanks,
Harsha

**Comment by tijsrademakers** [comment]
Hi @h7kanna,

Good point about the CloseableHttpClient usage, I think this can be changed to HttpClient.
I don't think anyone is working on documenting the usage of request/response handlers yet.

Best regards,

Tijs

**Comment by tijsrademakers** [comment]
Changed CloseableHttpClient usage to HttpClient
