### ISSUE TITLE
Migration: 'trigger-timer' timer jobs not migrated, get executed immediately

### ISSUE THREAD

**Issue by reva** [flowable/flowable-engine#455]
In the flowable.oracle.upgradestep.6001.to.6002.engine.sql migration script, timer jobs are moved to the new ACT_RU_TIMER_JOB table. However, timers with 'HANDLER_TYPE_ = 'trigger-timer'' (`TriggerTimerEventJobHandler`) are not moved. Unless I'm missing something, this is a pretty critical bug, resulting in all affected timers beeing executed immediatley, and effectively lost!

**Comment by tijsrademakers** [comment]
Hi,

trigger-timer is a new job type we introduced with Flowable 6, so are you upgrading from an alpha / beta release? Because the 'trigger-timer' job type should not have been there with Flowable 5.

Best regards,

Tijs

**Comment by reva** [comment]
You are right, I am migrating from an (Activiti) 6 beta version. Anything else one should be aware of when doing that?

**Comment by tijsrademakers** [comment]
Ok that explains the issue. From a early beta release right?
The only additional thing I can think of is that we changed the creation of executions a bit since the early releases, but that shouldn't cause issues.
