### ISSUE TITLE
Problem when reusing the group of people

### ISSUE THREAD

**Issue by robsoncardosoti** [flowable/flowable-engine#456]
If there is more than 1 component of the Group of People type, only the second is returned with the reuse of the variable.
Example: if to create a current field group (group of people) and another group intended and the Task to fill the 2 fields. When opening the filled form or already reutizar 2 variables from resort in another form, the second field just makes the value of the variables.

**Comment by tijsrademakers** [comment]
Fixed the issue, thanks for reporting
