### ISSUE TITLE
Option to Fire create task listener when released(unclaim)

### ISSUE THREAD

**Issue by kdevineni** [flowable/flowable-engine#457]
I have a task create listener which auto assigns the tasks to available candidate group users is being fired during task creating time.... 

But when the user releases(unclaim) the task, I want to have to fire the same listener to auto assign the tasks to other available users ..

Would be nice to provide an option to fire the create task listener, OR any other way to fire the event...

**Comment by tijsrademakers** [comment]
See the referenced commit where I've added a test for unclaiming a task. You can use an "assignment" event on a task listener and this listener will get invoked when unclaiming a task.
