### ISSUE TITLE
Refresh flowable-task gui

### ISSUE THREAD

**Issue by eportico** [flowable/flowable-engine#463]
Hi,
when I create a new process instance from REST API  then the flowable-task web gui don't refresh for the asigned user. This is a inconvenient. I think that Angular could make this.

**Comment by paulhh** [comment]
Hi,
Yes, that would be nice, but it's working as designed, so this would be more an enhancement request.  I suggest you raise this on the [forums](https://forum.flowable.org/) to see what people think.

Cheers
Paul.
