### ISSUE TITLE
Some messages not translated into Portuguese in task application

### ISSUE THREAD

**Issue by douglascrp** [flowable/flowable-engine#464]
I have noticed that some of the calculated dates messages are not completely translated into Portuguese.
Please, check the images below, from the task details form, to understand what I am talking about.

![imagem](https://user-images.githubusercontent.com/5930258/27977321-818ed60a-6340-11e7-87a4-229796c020a8.png)

![imagem](https://user-images.githubusercontent.com/5930258/27977329-91d6c090-6340-11e7-8cc8-f851d2452e22.png)

It seems those messages are being rendered by Angular using the function **dateformat:'fromNow'**

**Comment by yvoswillens** [comment]
Hi Douglas,

This has been addressed in PR #410.

Translation of 'MomentJS dates' is disabled by default but can be enabled in 

https://github.com/flowable/flowable-engine/blob/master/modules/flowable-ui-task/flowable-ui-task-app/src/main/webapp/scripts/app-cfg.js#L24

Regards,

Yvo

**Comment by douglascrp** [comment]
@yvoswillens Thank you.

Is it possible to edit that option without having to touch the war file to edit it?
Maybe something in the classpath?

If not possible, may you share the recommended way.

Thank you again.

**Comment by yvoswillens** [comment]
Hi.

This is a client side Javascript property setting. Currently there is no server side settings resource. But we are open for suggestions.

There are several ways to edit to the config file. The recommended way depends on your deployment scenario. If you deploy for example on a Tomcat that explodes the wars then it perhaps the easiest way to change it in the expanded folder.

Regards, 
Yvo

**Comment by douglascrp** [comment]
I see.
Currently I am deploying everything manually, but I really do not like the idea of having to change the war file.

And about the suggestion, I believe that having that option enabled by default would be enough.
For me, it doesn't make sense to have all the interface "translated", but not the dates.

**Comment by douglascrp** [comment]
@yvoswillens It seems there is a problem with that.
https://github.com/flowable/flowable-engine/issues/409#issuecomment-307037077

**Comment by yvoswillens** [comment]
There is a reason it's disabled by default.
This is because of the fallback mechanisme of our translations.
If there is no translation present it will fallback to English. But with the option enable (by default) the dates would be translated.

**Comment by douglascrp** [comment]
Web development is not my area, but isn't possible to make that page call a server side API to retrieve the value from the server? 
Something execute before the page is rendered?
By doing so, it would be possible to set that property somewhere in the classpath.

I am just wondering how it could be done, but I do not know the best way to implement such mechanism.

**Comment by yvoswillens** [comment]
Of course that's possible. But it's just currently not in there.
Perhaps you could start a conversation on the forum to see if people would like to see this feature.
That could help prioritizing this feature.

**Comment by douglascrp** [comment]
Good idea.
Thank you for your time.
