### ISSUE TITLE
Error in flowable-admin

### ISSUE THREAD

**Issue by eportico** [flowable/flowable-engine#465]
I installled 6.1.1-SNAPSHOT and I find a error in flowable admin in all options menu. For example when ui call to /flowable-admin/app/rest/admin/decision-table-deployments?order=asc&size=25&sort=id

return {"message":"com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')\n at [Source: <!DOCTYPE html>\n<html>\n  <head>\n    <meta charset=\"utf-8\">\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n    <meta id=\"viewport\" name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n    <link rel=\"icon\" href=\"/assets/images/logos/favicon.ico\">\n    <title>Loading&hellip;</title>\n    \n    <meta name=\"description\" content=\"\">\n    <base href=\"/\" />\n    <link id = \"vendor\" rel=\"stylesheet\" href=\"/assets/vendor.css\">\n    <link id=\"theme\" rel=\"stylesheet\">\n    \n  </head>\n  <body>\n    \n    <script src=\"/assets/vendor-67bbfad62aeceea28fc65fb877a62f60.js\"></script>\n    <script src=\"/assets/ui-9ff4e0f7149d48d6bb46c780a83cf75d.js\"></script>\n    <div id=\"ember-basic-dropdown-wormhole\"></div>\n  </body>\n</html>\n; line: 1, column: 2]","messageKey":"GENERAL.ERROR.BAD-REQUEST"}

Any idea ?

**Comment by yvoswillens** [comment]
Hi

Did you configure the engines endpoints correctly? And that they're accessible?

(with the 'check endpoint' button on the Configuration page)

Regards,

Yvo

**Comment by eportico** [comment]
Hi Yvo,
yes, the other components run well. I review config from admin component.

**Comment by eportico** [comment]
Sorry Yvo,
fixed in my config

**Comment by eportico** [comment]
close
