### ISSUE TITLE
Question about generate project

### ISSUE THREAD

**Issue by eportico** [flowable/flowable-engine#468]
Hi,
I'm adding new function in API Rest to return internal variables with JSON format.

@RestController
@Api(tags = { "Process Instances" }, description = "Manage Process Instances", authorizations = { @Authorization(value = "basicAuth") })
public class ProcessInstanceVariableDataResource extends BaseExecutionVariableResource {

@RequestMapping(value = "/runtime/process-instances/{processInstanceId}/variables/{variableName}/json", method = RequestMethod.GET)
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Indicates the process instance was found and the requested variables are returned."),
            @ApiResponse(code = 404, message = "Indicates the requested task was not found or the task doesn’t have a variable with the given name (in the given scope). Status message provides additional information.")
    })
    @ApiOperation(value = "Get the JSON data for a variable", tags = { "Process Instances" }, nickname = "getProcessInstanceVariableJson")
    @ResponseBody
    public String getVariableJson(@ApiParam(name = "processInstanceId") @PathVariable("processInstanceId") String processInstanceId, @ApiParam(name = "variableName") @PathVariable("variableName") String variableName,
            @RequestParam(value = "scope", required = false) String scope,
            HttpServletRequest request, HttpServletResponse response) {
        Execution execution = getProcessInstanceFromRequest(processInstanceId);
        LOGGER.info("Get the JSON data for a variable");
        return getVariableDataJson(execution, variableName, scope, response);
    }

When generate project it return me that the new entry point  /runtime/process-instances/{processInstanceId}/variables/{variableName}/json don't exist. 
I don't know that could occur. Do I have to change anything in project settings?  Thanks any help

**Comment by eportico** [comment]
`` sfddfdf 
dasda
``

**Comment by tijsrademakers** [comment]
Hi,

Best ask questions on the forum ->https://forum.flowable.org
In which package did you add this REST controller? Are you sure the package is scanned by Spring?

**Comment by eportico** [comment]
V:\SANTI\flowable-engine\modules\flowable-rest\src\main\java\org\flowable\rest\service\api\runtime\process\ProcessInstanceVariableDataResource.java

**Comment by tijsrademakers** [comment]
Ok that should be fine. Which URL are you calling exactly? I also assume that markup got lost while copying the code to the Github issue? Because requestmapping is written lowercase instead of RequestMapping.
