### ISSUE TITLE
Inconsistencies with ACTIVITY_CANCELLED events for multi-instance user task

### ISSUE THREAD

**Issue by stephraleigh** [flowable/flowable-engine#471]
I created pull request that includes tests to recreate the inconsistencies, https://github.com/flowable/flowable-engine/pull/470

When the multi-instance user task is cancelled by terminate end, an ACTIVITY_CANCELLED event is received for both instances as well as the root of the multi-instance user task.  When the multi-instance user task is cancelled by a boundary message event, an ACTIVITY_CANCELLED event is received for the root of the multi-instance user task only. We do not see events for each instance of the user task.  I would expect the events to consistent no matter how the task is cancelled.

**Comment by tijsrademakers** [comment]
Thanks, merged the PR
