### ISSUE TITLE
Multi-instance collection syntax proposal

### ISSUE THREAD

**Issue by lsmall** [flowable/flowable-engine#474]
We are using the flowable extensions for multi-instance user assignment, but we would like to be able to support either a data object which contains a set of users or a string.

Refer to discussion thread [here](https://forum.flowable.org/t/multi-instance-collection-syntax-proposal/615)

**Comment by lsmall** [comment]
We would like to propose the addition of a collection element in addition to the existing attribute to support CDATA values:

`<userTask`` id="usertask1" name="Task A-${loopCounter}">
  <extensionElements>
    <flowable:taskListener event="create" flowable:delegateExpression="${jsonParticipantListener}">
      <flowable:field name="participants">
        <flowable:expression>${participant}</flowable:expression>
      </flowable:field>
    </flowable:taskListener>
  </extensionElements>
  <multiInstanceLoopCharacteristics isSequential="true" flowable:elementVariable="participant">
   <extensionElements>
    **<flowable:collection>**
     <![CDATA[
            [
              {
                "principalType" : "User",
                "role" : "PotentialOwner",
                "principal" : "wfuser1",
                "version" : 1
              },
              {
                "principalType" : "User",
                "role" : "PotentialOwner",
                "principal" : "wfuser2",
                "version" : 1
              }
            ]
            ]]>
    </flowable:collection>
   </extensionElements>`

**Comment by lsmall** [comment]
created pull request #475

**Comment by tijsrademakers** [comment]
Merged PR
