### ISSUE TITLE
UseTLS / UseSSL

### ISSUE THREAD

**Issue by YouMadeMeEnthusiast** [flowable/flowable-engine#476]
Just followed the discussion on https://forum.flowable.org/t/configure-email-notifications-in-flowable/520

I would like to see the following properties in flowable-ui-app.properties: 
email.UseTLS and email.UseSSL, so that it is possible to enable STARTTLS from the Flowable UI apps without implementing a task listener.

Regards, RP.

**Comment by tijsrademakers** [comment]
email.useTLS and email.useSSL options are added.
