### ISSUE TITLE
Questionable code; easy fix for those that know what is going on

### ISSUE THREAD

**Issue by dbmalkovsky** [flowable/flowable-engine#478]
@yvoswillens I think this is in your area of expertise.  

In `org.flowable.editor.dmn.converter.DmnJsonConverter.DmnJsonConverter` lines 337 through 340 are:
<pre>
                        if (stringBuilder.length() > 0) {
                            stringBuilder.append("\"");
                        } else {
                            stringBuilder.append("\"");
                        }
</pre>

Note that no matter what the length of the string is the same character is appended.  Looks like this is a case of cut-n-paste error.

**Comment by tijsrademakers** [comment]
Did a cleanup and removed the unnecessary if check.
