### ISSUE TITLE
Javascript error when selecting enum type for a form property

### ISSUE THREAD

**Issue by paulhh** [flowable/flowable-engine#480]
No apparent functional impact, just a JS error.

Steps to reproduce:
- Create a process
- Select the Start event
- Click the Form properties field in the properties panel
- Click the + to add a property
[Turn on JS inspector before next action]
- Select enum from the Type dropdown

![screen shot 2017-07-17 at 17 55 57](https://user-images.githubusercontent.com/1086885/28279915-eab7ef46-6b19-11e7-9a12-d63148d9d98c.png)

**Comment by tijsrademakers** [comment]
Fixed
