### ISSUE TITLE
eclipse plugin "Generate unit test" have a questions

### ISSUE THREAD

**Issue by ksoem04612299** [flowable/flowable-engine#485]
Dear develop groups:
  Just like the pictures below：
![image](https://user-images.githubusercontent.com/16598454/28360370-ce6dbbec-6ca7-11e7-8a4a-298b580677d1.png)
![image](https://user-images.githubusercontent.com/16598454/28360382-d6a79a62-6ca7-11e7-9d85-bed38b9d904c.png)
I hope you can do better and better, come on.

- from china java programer . zohar liu

**Comment by tijsrademakers** [comment]
We released this Eclipse version to work with Flowable 5.22.0 (in November 2016). Since we changed package names starting from Flowable 6 you are running into this issue.
