### ISSUE TITLE
In Path :"flowable/modules/" ,"flowable-ui-idm-logic" project have a bug

### ISSUE THREAD

**Issue by ksoem04612299** [flowable/flowable-engine#491]
Dear develop groups:
This piece of code have bug , throw NullpointException, the part that is circled with a red frame.
![image](https://user-images.githubusercontent.com/16598454/28518278-ec230412-7099-11e7-99b4-59397a8485ea.png)

I tried. It should be written this way.
![image](https://user-images.githubusercontent.com/16598454/28518401-4f9bb9bc-709a-11e7-9052-e2d3c10ab3e6.png)
An error parameter was passed by the updateUserPassword method。

Hope for an early repair

**Comment by tijsrademakers** [comment]
Thanks, issue fixed
