### ISSUE TITLE
Can you add to REST API get return var data in JSON format ?

### ISSUE THREAD

**Issue by eportico** [flowable/flowable-engine#499]
Can you add to REST API get return var data in JSON format ? I implemented this function in flowable-engine\modules\flowable-rest\src\main\java\org\flowable\rest\service\api\runtime\process\ProcessInstanceVariableDataResource.java

  @RequestMapping(value = "/runtime/process-instances/{processInstanceId}/variables/{variableName}/json", method = RequestMethod.GET, produces = "application/json")
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Indicates the process instance was found and the requested variables are returned."),
            @ApiResponse(code = 404, message = "Indicates the requested task was not found or the task doesn’t have a variable with the given name (in the given scope). Status message provides additional information.")
    })
    @ApiOperation(value = "Get the JSON data for a variable", tags = { "Process Instances" }, nickname = "getProcessInstanceVariableJson")
    @ResponseBody
    public Object getVariableJson(@ApiParam(name = "processInstanceId") @PathVariable("processInstanceId") String processInstanceId, @ApiParam(name = "variableName") @PathVariable("variableName") String variableName,
            @RequestParam(value = "scope", required = false) String scope,
            HttpServletRequest request, HttpServletResponse response) {

        Execution execution = getProcessInstanceFromRequest(processInstanceId);
        response.setContentType("application/json;charset=utf-8");
        return getVariable(execution, variableName, scope, false);
    }

**Comment by jbarrez** [comment]
You mean returning one variable value for a process instance? 

That's what https://github.com/flowable/flowable-engine/blob/master/modules/flowable-rest/src/main/java/org/flowable/rest/service/api/runtime/process/ProcessInstanceVariableResource.java#L60 already does (and it returns json). Or am I misunderstanding something?

**Comment by tijsrademakers** [comment]
Closing issue
