### ISSUE TITLE
Multi-instance collection syntax proposal - revised

### ISSUE THREAD

**Issue by lsmall** [flowable/flowable-engine#512]
We have been trying to use the new syntax and would eventually like to include a pluggable function (similar to the expression functions) that would parse the string and return a collection. For now, we would like to update the BPMN syntax and include it in the validation so that it can be deployed. As discussed on the forum [here](https://forum.flowable.org/t/multi-instance-collection-syntax-proposal/615), using a collection element might have been more efficient since you could specify whether the value is a string or expression using a child element. The attributes were less verbose and will need to stay to maintain backwards-compatibility, but we would like to update the collection element syntax to support both types. We will submit a separate proposal for behavior to support pluggable passing functionality based on the child element type. Meanwhile, we will continue to use our taskListener to set the relevant task participants.

**Comment by lsmall** [comment]
Revised syntax is as follows:

        <extensionElements>
          <flowable:collection>
             <flowable:string>
               <![CDATA[
                 [
                   {
                     "principalType" : "User",
                     "role" : "PotentialOwner",
                     "principal" : "wfuser1",
                     "version" : 1
                   },
                   {
                     "principalType" : "User",
                     "role" : "PotentialOwner",
                     "principal" : "wfuser2",
                     "version" : 1
                   }
                 ]
                ]]>
             </flowable:string>
          </flowable:collection>
        </extensionElements>

where the flowable:string child element can be replaced by a flowable:expression element if an expression is used.

**Comment by jbarrez** [comment]
@lsmall : thanks for the PR. It's merged. 

You referenced this issue here: https://github.com/flowable/flowable-engine/blob/e44e182932a350cbb78f42cbae5cb7c1c6dbc3ee/modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/MultiInstanceActivityBehavior.java#L317. Do you want to keep this issue open for resolving the static string value?

**Comment by lsmall** [comment]
I will open a new one for the function support - thanks!

**Comment by lsmall** [comment]
Opened issue [520](https://github.com/flowable/flowable-engine/issues/520) for adding function support

**Comment by lsmall** [comment]
Noting revised PR [518](https://github.com/flowable/flowable-engine/pull/518) for this issue that has been merged and closed.
