### ISSUE TITLE
Add support for revised syntax collectionString parsing function

### ISSUE THREAD

**Issue by lsmall** [flowable/flowable-engine#520]
Related to issue[512](https://github.com/flowable/flowable-engine/issues/512)

**Comment by lsmall** [comment]
Generated PR [523](https://github.com/flowable/flowable-engine/pull/523) for review.

**Comment by lsmall** [comment]
Generated revised implementation PR [527](https://github.com/flowable/flowable-engine/pull/527) for review.

**Comment by lsmall** [comment]
Created new PR 533 for review

**Comment by tijsrademakers** [comment]
Done
