### ISSUE TITLE
Provide a separate deployable for only the task-ui

### ISSUE THREAD

**Issue by klu2** [flowable/flowable-engine#526]
The current flowable-ui-task-app.war contains all task-list, but also the whole flowable engine in the web-inf/lib folder. If I want to customize the engine or add custom code while reusing the task-webapp, I need to unpack the WAR, extract the UI code, and package it with my own engine.

It would be smarter to have one deployable which only contains the UI and that I can configure such to point to the rest endpoint of another engine (i.e. in another WAR)

**Comment by tijsrademakers** [comment]
This has no priority in the project, therefore closing the issue.
