### ISSUE TITLE
Removing admin user in flowable-idm leads to invalid state

### ISSUE THREAD

**Issue by aaronkavlie-wf** [flowable/flowable-engine#530]
I removed the admin user in flowable-idm, so the admin user would be recreated with a new password I set in the `.properties` file.

This created a new admin user in `ACT_ID_USER`, but I'm unable to login with that username/password.

There are no entries in `ACT_ID_PRIV_MAPPING`; missing data in that table (or another) may be the cause.

**Comment by aaronkavlie-wf** [comment]
@tijsrademakers thanks for the fix!
Will that make its way into a 6.1.3 release?

**Comment by tijsrademakers** [comment]
@aaronkavlie-wf thanks for reporting the issue. We are currently working on a 6.2.0 release and this fix will be part of that release. If we have blocker issues on 6.1.2 we might want to do a 6.1.3 release and then this fix can be part of that as well. Is that ok?

**Comment by aaronkavlie-wf** [comment]
@tijsrademakers sure, either way is fine.
