### ISSUE TITLE
 flowable:assignee="$INITIATOR" doesn't work

### ISSUE THREAD

**Issue by simon998yang** [flowable/flowable-engine#534]
Dears,

Can any one shed some light? I managed to make flowable:assignee="${INITIATOR}" works but flowable:assignee="$INITIATOR" doesn't work, and this is generated automatically in explorer application if I select process initiator as task assignee. 

I see in act_ru_task table the assignee is "$INITIATOR"  

Best Regards,
Simon

**Comment by tijsrademakers** [comment]
Hi Simon,

Best to ask these questions on the forum.
What you want to do is use an expression (referencing a variable) to assign a user task. The expression format is ${INITIATOR} or #{INITIATOR}, so $INITIATOR doesn't work. When using $INITIATOR the engine will just see this as a piece of text and use that as the assignee value.

**Comment by simon998yang** [comment]
I understood ${INITIATOR} works. But i saw $INITIATOR in some test process. and it's the format generated automatically by explorer application if select process initiator as task assignee. 

Just cannot figure out what's the trick to make it work. fine, I will ask same question in forum.

Thanks.

**Comment by tijsrademakers** [comment]
Can you point me to that test process?

**Comment by simon998yang** [comment]
modules\flowable-engine\src\test\resources\org\flowable\engine\test\bpmn\event\message\MessageEventSubprocessTest.testStartingAdditionalTasks.bpmn20.xml
modules\flowable-engine\src\test\resources\org\flowable\engine\test\bpmn\event\message\MessageEventSubprocessTest.testStartingAdditionalTasksInterrupting.bpmn20.xml
modules\flowable-spring-boot\flowable-spring-boot-samples\flowable-spring-boot-sample-rest-api\src\main\resources\processes\doge.bpmn20.xml

There are many, just search for  flowable:assignee="$INITIATOR"  or activiti:assignee="$INITIATOR"

**Comment by tijsrademakers** [comment]
Ok thanks, in these examples the assignee expression isn't used in the unit tests. But I can see why you were confused. It only works with ${INITIATOR} and #{INITIATOR}. Otherwise it's just a piece of text.

**Comment by simon998yang** [comment]
then in flowable ui modeler app, in the task assignment dialog, if select "assigned to process initiator", then export the process to xml, then you can see flowable:assignee="$INITIATOR" . I guess this is a bug?

**Comment by tijsrademakers** [comment]
Thanks for pointing at that, if you look at the BPMN XML that is deployed on Flowable you will see the flowable:assignee="${initiator}" value. The $INITIATOR value is replaced at runtime with either the default ${initiator} expression or with a specific initiator variable name that is defined on the start event. The IDM user task configuration is to be used together with the Flowable Task application. If you are using the BPMN XML to deploy it on a standalone Flowable Engine it might be better to use an assignee expression directly in the Flowable Modeler.

**Comment by simon998yang** [comment]
I see, thanks for the explanation
