### ISSUE TITLE
Add support for CamelBehavior in CDI environment

### ISSUE THREAD

**Issue by ruzkant** [flowable/flowable-engine#538]
Currently the CamelBehavior class only works with a SpringProcessEngineConfiguration. In order to make it work in a CDI environment a new Behavior implementation is needed. This has a knock on effect on the DefaultActivityBehaviorFactory which then needs to construct this class for a CDI processEngine.

I have created an implementation in a branch on my flowable fork:
https://github.com/flowable/flowable-engine/compare/master...ruzkant:camel-cdi

I wasn't sure about whether this should be in the flowable-camel module or in a module of its own, dependency wise. For now I have it in the flowable-camel module and introduced a dependency on flowable-cdi, but this forced me to put a version in as well, not sure if this has something to do with the maven profiles as I am not a maven expert (more used to gradle). Not sure if it should be marked with scope optional.

I am willing to make whatever updates the flowable team envisions necessary to be incorporated.

**Comment by tijsrademakers** [comment]
Thanks for looking into this. I think it's fine to have it as part of the flowable-camel module but the dependency should be set to optional indeed. The main thing that's missing right now are unit tests to show it's working in a CDI environment. Would it be possible for you to add this?

**Comment by ruzkant** [comment]
Yeah, I'll add some unit tests, it was quick for me to test manually with an existing setup, so wanted to first make sure I am barking up the right tree...

**Comment by ruzkant** [comment]
@tijsrademakers It took a while but I finally had time to do some tests and added a pull request for this issue (https://github.com/flowable/flowable-engine/pull/728)

**Comment by tijsrademakers** [comment]
Thanks for the PR @ruzkant !

**Comment by ruzkant** [comment]
@tijsrademakers cool no prob... no PR without your hard work, thx for all you guys :)
