### ISSUE TITLE
Flowable Admin can not show Chinese character

### ISSUE THREAD

**Issue by WillWei1983** [flowable/flowable-engine#539]
The flowable-ui-idm,task,modeler can show the Chinese character correctly, but the flowable-ui-admin can't.
Please check the attach

![chinesecharacter](https://user-images.githubusercontent.com/13535017/29505926-a38f88a4-867b-11e7-9788-4ef06638524b.png)

**Comment by tijsrademakers** [comment]
Hi,

Can you paste the full chinese process definition name here, so we can test it?

Thanks

**Comment by WillWei1983** [comment]
Hi,
Below is the process definition

`<?xml version="1.0" encoding="UTF-8"?>
<definitions
  xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:flowable="http://flowable.org/bpmn"
  xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
  xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC"
  xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  targetNamespace="Demo">

  <process id="newProdctRequest" name="新商品采购申请">
    <startEvent id="request" name="开始申请" flowable:initiator="applyUserId">
      <extensionElements>
        <flowable:formProperty id="productId" name="产品ID"  readable="true" writable="true"></flowable:formProperty>
        <flowable:formProperty id="productName" name="产品名称" required="true" readable="true" writable="true"></flowable:formProperty>
        <flowable:formProperty id="supplier" name="供应商" required="true" readable="true" writable="true"></flowable:formProperty>
      </extensionElements>
    </startEvent>
    <sequenceFlow id="flow1" sourceRef="request" targetRef="handleRequest" />
    <userTask id="handleRequest" name="采购员审核" flowable:candidateUsers="lily">
      <extensionElements>
        <flowable:formProperty id="productId" name="产品ID"  readable="true"></flowable:formProperty>
        <flowable:formProperty id="productName" name="产品名称" required="true" readable="true"></flowable:formProperty>
        <flowable:formProperty id="supplier" name="供应商" required="true" readable="true"></flowable:formProperty>
        <flowable:formProperty id="remarks" name="备注" required="true" readable="true" writable="true"></flowable:formProperty>
        <flowable:formProperty id="purchaserApproved" name="审批操作" type="enum" required="true" writable="true">
          <flowable:value id="true" name="同意"></flowable:value>
          <flowable:value id="false" name="拒绝"></flowable:value>
        </flowable:formProperty>
      </extensionElements>
    </userTask>
    <sequenceFlow id="flow2" sourceRef="handleRequest" targetRef="purchaserDecision" />
    <exclusiveGateway id="purchaserDecision"/>
    <sequenceFlow id="flow3" name="采购员同意" sourceRef="purchaserDecision" targetRef="handleRequest2">
      <conditionExpression xsi:type="tFormalExpression">
        <![CDATA[ ${purchaserApproved=='true'} ]]>
      </conditionExpression>
    </sequenceFlow>
    <sequenceFlow id="flow4" name="采购员不同意" sourceRef="purchaserDecision" targetRef="adjustSupplier">
      <conditionExpression xsi:type="tFormalExpression">
        <![CDATA[ ${purchaserApproved=='false'} ]]>
      </conditionExpression>
    </sequenceFlow>
    <userTask id="adjustSupplier" name="调整供应商信息" flowable:assignee="${applyUserId}">
      <extensionElements>
        <flowable:formProperty id="productId" name="产品ID"  readable="true" writable="true"></flowable:formProperty>
        <flowable:formProperty id="productName" name="产品名称" required="true" readable="true" writable="true"></flowable:formProperty>
        <flowable:formProperty id="supplier" name="供应商" required="true" readable="true" writable="true"></flowable:formProperty>
        <flowable:formProperty id="reApply" name="重新申请" type="enum" required="true" writable="true">
          <flowable:value id="true" name="重新申请"></flowable:value>
          <flowable:value id="false" name="取消申请"></flowable:value>
        </flowable:formProperty>
      </extensionElements>
    </userTask>
    <sequenceFlow id="flow5" sourceRef="adjustSupplier" targetRef="applyerDecision" />
    <exclusiveGateway id="applyerDecision"/>
    <sequenceFlow id="flow5_1" name="重新申请" sourceRef="applyerDecision" targetRef="handleRequest">
      <conditionExpression xsi:type="tFormalExpression">
        <![CDATA[ ${reApply=='true'} ]]>
      </conditionExpression>
    </sequenceFlow>
    <sequenceFlow id="flow5_2" name="取消申请" sourceRef="applyerDecision" targetRef="theEnd">
      <conditionExpression xsi:type="tFormalExpression">
        <![CDATA[ ${reApply=='false'} ]]>
      </conditionExpression>
    </sequenceFlow>
    <userTask id="handleRequest2" name="采购经理审核" flowable:candidateGroups="purchaseManager">
      <extensionElements>
        <flowable:formProperty id="productId" name="产品ID"  readable="true"></flowable:formProperty>
        <flowable:formProperty id="productName" name="产品名称" required="true" readable="true"></flowable:formProperty>
        <flowable:formProperty id="supplier" name="供应商" required="true" readable="true"></flowable:formProperty>
        <flowable:formProperty id="remarks" name="备注" required="true" readable="true" writable="true"></flowable:formProperty>
        <flowable:formProperty id="purchaseManagerApproved" name="审批操作" type="enum" required="true" writable="true">
          <flowable:value id="true" name="同意"></flowable:value>
          <flowable:value id="false" name="拒绝"></flowable:value>
        </flowable:formProperty>
      </extensionElements>
    </userTask>
    <sequenceFlow id="flow6" sourceRef="handleRequest2" targetRef="purchaseManagerdecision" />
    <exclusiveGateway id="purchaseManagerdecision"/>
    <sequenceFlow id="flow7" name="采购经理同意" sourceRef="purchaseManagerdecision" targetRef="externalSystemCall">
      <conditionExpression xsi:type="tFormalExpression">
        <![CDATA[ ${purchaseManagerApproved=='true'} ]]>
      </conditionExpression>
    </sequenceFlow>
    <sequenceFlow id="flow8" name="采购经理不同意" sourceRef="purchaseManagerdecision" targetRef="sendRejectionMessage">
      <conditionExpression xsi:type="tFormalExpression">
        <![CDATA[ ${purchaseManagerApproved=='false'} ]]>
      </conditionExpression>
    </sequenceFlow>
    <serviceTask id="externalSystemCall" name="生成ERP采购计划" flowable:class="com.yysoft.oa.demo.CreatePurchasePlan"/>

    <serviceTask id="sendRejectionMessage" name="发送拒绝消息" flowable:class="com.yysoft.oa.demo.SendRejectionMessage"/>

    <sequenceFlow id="flow9" sourceRef="externalSystemCall" targetRef="theEnd" />
    <sequenceFlow id="flow10" sourceRef="sendRejectionMessage" targetRef="theEnd" />
    <endEvent id="theEnd" />
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_newProdctRequest">
    <bpmndi:BPMNPlane bpmnElement="newProdctRequest" id="BPMNPlane_newProdctRequest">
      <bpmndi:BPMNShape bpmnElement="request" id="BPMNShape_request">
        <omgdc:Bounds height="30.0" width="30.0" x="0.0" y="178.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="handleRequest" id="BPMNShape_handleRequest">
        <omgdc:Bounds height="60.0" width="100.0" x="80.0" y="163.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="purchaserDecision" id="BPMNShape_purchaserDecision">
        <omgdc:Bounds height="40.0" width="40.0" x="230.0" y="173.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="adjustSupplier" id="BPMNShape_adjustSupplier">
        <omgdc:Bounds height="60.0" width="100.0" x="320.0" y="163.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="applyerDecision" id="BPMNShape_applyerDecision">
        <omgdc:Bounds height="40.0" width="40.0" x="350.0" y="330.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="handleRequest2" id="BPMNShape_handleRequest2">
        <omgdc:Bounds height="60.0" width="100.0" x="320.0" y="53.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="purchaseManagerdecision" id="BPMNShape_purchaseManagerdecision">
        <omgdc:Bounds height="40.0" width="40.0" x="470.0" y="63.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="externalSystemCall" id="BPMNShape_externalSystemCall">
        <omgdc:Bounds height="60.0" width="100.0" x="560.0" y="0.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="sendRejectionMessage" id="BPMNShape_sendRejectionMessage">
        <omgdc:Bounds height="60.0" width="100.0" x="560.0" y="160.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="theEnd" id="BPMNShape_theEnd">
        <omgdc:Bounds height="28.0" width="28.0" x="840.0" y="105.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="flow5_2" id="BPMNEdge_flow5_2">
        <omgdi:waypoint x="390.0" y="350.0"></omgdi:waypoint>
        <omgdi:waypoint x="854.0" y="350.0"></omgdi:waypoint>
        <omgdi:waypoint x="854.0" y="133.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow1" id="BPMNEdge_flow1">
        <omgdi:waypoint x="30.0" y="193.0"></omgdi:waypoint>
        <omgdi:waypoint x="80.0" y="193.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow5_1" id="BPMNEdge_flow5_1">
        <omgdi:waypoint x="350.0" y="350.0"></omgdi:waypoint>
        <omgdi:waypoint x="130.0" y="350.0"></omgdi:waypoint>
        <omgdi:waypoint x="130.0" y="223.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow2" id="BPMNEdge_flow2">
        <omgdi:waypoint x="180.0" y="193.0"></omgdi:waypoint>
        <omgdi:waypoint x="230.0" y="193.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow3" id="BPMNEdge_flow3">
        <omgdi:waypoint x="250.0" y="173.0"></omgdi:waypoint>
        <omgdi:waypoint x="250.0" y="83.0"></omgdi:waypoint>
        <omgdi:waypoint x="320.0" y="83.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow4" id="BPMNEdge_flow4">
        <omgdi:waypoint x="270.0" y="193.0"></omgdi:waypoint>
        <omgdi:waypoint x="320.0" y="193.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow5" id="BPMNEdge_flow5">
        <omgdi:waypoint x="370.0" y="223.0"></omgdi:waypoint>
        <omgdi:waypoint x="370.0" y="330.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow6" id="BPMNEdge_flow6">
        <omgdi:waypoint x="420.0" y="83.0"></omgdi:waypoint>
        <omgdi:waypoint x="470.0" y="83.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow7" id="BPMNEdge_flow7">
        <omgdi:waypoint x="490.0" y="63.0"></omgdi:waypoint>
        <omgdi:waypoint x="490.0" y="30.000000000000007"></omgdi:waypoint>
        <omgdi:waypoint x="560.0" y="30.000000000000004"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow10" id="BPMNEdge_flow10">
        <omgdi:waypoint x="660.0" y="190.0"></omgdi:waypoint>
        <omgdi:waypoint x="750.0" y="190.0"></omgdi:waypoint>
        <omgdi:waypoint x="750.0" y="119.0"></omgdi:waypoint>
        <omgdi:waypoint x="840.0" y="119.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow8" id="BPMNEdge_flow8">
        <omgdi:waypoint x="490.0" y="103.0"></omgdi:waypoint>
        <omgdi:waypoint x="490.0" y="190.0"></omgdi:waypoint>
        <omgdi:waypoint x="560.0" y="190.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow9" id="BPMNEdge_flow9">
        <omgdi:waypoint x="660.0" y="30.0"></omgdi:waypoint>
        <omgdi:waypoint x="854.0" y="30.0"></omgdi:waypoint>
        <omgdi:waypoint x="854.0" y="105.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>`

**Comment by WillWei1983** [comment]
Hi,
As I can't upload the xml file.
Please check the process definition with .txt attach
[pd.txt](https://github.com/flowable/flowable-engine/files/1238019/pd.txt)
