### ISSUE TITLE
JobQuery no longer has method noRetriesLeft

### ISSUE THREAD

**Issue by filiphr** [flowable/flowable-engine#546]
For some reason the `JobQuery` is missing the `noRetriesLeft` method. However it's implementation `JobQueryImpl` has it see [JobQueryImpl#L176](https://github.com/flowable/flowable-engine/blob/master/modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/JobQueryImpl.java#L176).

A Bonus suggestion from me, all methods that implement a method from an interface should have the `@Override` annotation, which will lead to compile problems and things like this would be avoided

**Comment by jbarrez** [comment]
Correct: jobs with no retries are moved to the deadletterjob table. This method can be removed (and the same applies to TimerJobQueryImpl and HistoryJobQueryImpl from a first glance).

**Comment by filiphr** [comment]
Btw @jbarrez while working on this I noticed some other discrepancies:

* `JobQueryImpl` has the method `executable`, but that method is missing in the `JobQuery`. The executable is also used in the `Job.xml`
* `TimerJobQueryImpl` has the method `handlerType(String)`, but that method is missing in the `TimerJobQuery`. The `handlerType` is also used in the `TimerJob.xml`
* The `TimerJobQuery` has the methods `timers` and `messages`, but from what I can see they are not used in the `TimerJob.xml`. Also can a `TimerJob` be a message?

**Comment by jbarrez** [comment]
* _executable_ : can be removed from both the JobQuery and Job.xml
* _handlerType_ : same, can be removed.
* both can be removed, only timers can be returned from that query

**Comment by filiphr** [comment]
Great, thanks for the info. I'll push those changes to the PR as well.

>both can be removed, only timers can be returned from that query

Shouldn't we deprecate this first, or I should directly remove it from the API?

Btw. There are `7085` methods that have `@Override` missing (maybe even more, I have only the `distro` profile activated). Do you want a PR for that as well?

**Comment by tijsrademakers** [comment]
I think we should keep the handlerType and expose it also in the TimerJobQuery. It can always be handy to query on a specific job handler type value.

**Comment by jbarrez** [comment]
You're right about the messages() / timers() method. Looking at the code, it looks like these have to be added to the mybatis query xml, as a 'message' (an async job) can become a timer when it is retried, but the original type is kept (see https://github.com/flowable/flowable-engine/blob/6bfadc02465f0b5e95aa61390b10f6fbe4759e7c/modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/asyncexecutor/DefaultJobManager.java#L494). 

@tijsrademakers :  do you agree?

On the @Override: ok (distro profile should have all modules).

**Comment by tijsrademakers** [comment]
@jbarrez yes would be good to add that to the timer mybatis query xml. In the job.xml it is implemented.

**Comment by filiphr** [comment]
All the suggestions are in one commit in the PR. 

I'll make a new one for the `@Override`
