### ISSUE TITLE
where is the flowable-root?

### ISSUE THREAD

**Issue by didoguan** [flowable/flowable-engine#549]
![image](https://user-images.githubusercontent.com/10651134/29913481-ea4c5544-8e67-11e7-81cd-340f6b3ca367.png)

**Comment by yvoswillens** [comment]
Did you take a look in the root of the flowable project folder?

**Comment by didoguan** [comment]
thank's for your answer! I really did. But I really don't know where it is. Can you tell me the path? thank you very much!

**Comment by yvoswillens** [comment]
https://github.com/flowable/flowable-engine/blob/master/pom.xml
