### ISSUE TITLE
Allow query tasks in which a variable is not equal to a value OR the variable doesn't exist

### ISSUE THREAD

**Issue by leandrocosta** [flowable/flowable-engine#577]
T TaskInfoQuery#taskVariableValueNotEquals(String variableName, Object variableValue) only selects tasks which have a local task variable with the given name, but with a different value than the passed value.
In this case I'd like to select tasks which don't have a local task variable with the given name too.

**Comment by tijsrademakers** [comment]
Added support for variable exists and variable not exists in process instance, task and execution queries
