### ISSUE TITLE
Multi-instance export not working properly for all collection syntax combinations

### ISSUE THREAD

**Issue by lsmall** [flowable/flowable-engine#578]
The flowable prefix is missing from the collection element and the collection expression is always set as the collection attribute. Unfortunately, this causes any custom collection handler to get lost upon export.

I have added a new unit test for these conditions and refactored the handler export.

**Comment by lsmall** [comment]
Created [PR](https://github.com/flowable/flowable-engine/pull/579)

**Comment by tijsrademakers** [comment]
thanks, fixed

**Comment by lsmall** [comment]
My apologies for not testing the export more thoroughly. Thanks as usual for your prompt response!
