### ISSUE TITLE
Docs contains information about old job executor

### ISSUE THREAD

**Issue by hipnoizz** [flowable/flowable-engine#597]
Docs at http://www.flowable.org/docs/userguide/index.html contain at lot of references to old job executor, which I think is removed in 6.x.

E.g. search for 'jobExecutorActivate' - you will find many places that mention both old and new (async) job executor, many example Spring XML configurations etc. etc.

**Comment by tijsrademakers** [comment]
Removed several references. If there are more references let us know.
