### ISSUE TITLE
Docs reference an Eclipse update site that does not exist

### ISSUE THREAD

**Issue by jpotts** [flowable/flowable-engine#6]
Under the [Eclipse Designer section](http://www.flowable.org/docs/userguide/index.html#flowableDesigner), the docs reference http://flowable.org/designer/update/ as the Eclipse update site, but that does not yet exist.

The screenshot still has the old Activiti Designer update site, however.

**Comment by tijsrademakers** [comment]
Hi Jeff, thanks for pointing at this. We will create a Flowable Designer and add the artefacts to the url as pointed out in the docs. It just needs a bit of time to get it ready for a first release.

**Comment by tijsrademakers** [comment]
The Flowable Designer is released now

**Comment by dbmalkovsky** [comment]
I just submitted a [pull request](https://github.com/flowable/flowable-engine/pull/33l) with some updates to the user guide documentation.

**Comment by dbmalkovsky** [comment]
FWIW, more changes to the images, etc. are needed in this section.   I only a few because I wasn't sure whether my Windows based images were acceptable. :)
