### ISSUE TITLE
Add some codestyle and import order checks

### ISSUE THREAD

**Issue by filiphr** [flowable/flowable-engine#626]
I think it would be nice if there are at least some minor Eclipse / IntelliJ code style / import order checks and rules. Also reformatting the code and reording the imports once can lead to better / easier code reviews

**Comment by dbmalkovsky** [comment]
See this [thread](https://forum.flowable.org/t/coding-style-and-standards/154l) for a related discussion.

**Comment by filiphr** [comment]
Thanks a lot for the link. I've missed the post. I'll post something more in there tomorrow.

I actually did a PR which was merged for the `@Override`(s), which by the way showed some other bugs / missing methods in the interfaces.

**Comment by filiphr** [comment]
One more thing. The link has an extra charge at the end. You can edit it pero

**Comment by dbmalkovsky** [comment]
Updated the link; sorry about that.
