### ISSUE TITLE
Incomplete support for variable based user task assignments

### ISSUE THREAD

**Issue by glennmorell** [flowable/flowable-engine#629]
Dynamically assigning a user task via a variable (ex: activiti:assignee="${assignmentId}") works well but in my scenario I'm using a decision table to determine either an individual to assign a task to **or** a list of candidate users **or** groups:

<userTask id="review" name="Task Review" activiti:assignee="${assignmentId}" activiti:candidateUsers="${candidateUserIds}" activiti:candidateGroups="${candidateGroupIds}">

The code in UserTaskActivityBehavior.handleAssignments is testing the assignee, candidateUsers and candidateGroups attributes to see if they are blank before evaluating any expression that is set for those attributes.  It should first evaluate the expression if set and then test to see if the result is blank before processing each type of assignment:

    protected void handleAssignments(TaskEntityManager taskEntityManager, String assignee, String owner, List<String> candidateUsers,
            List<String> candidateGroups, TaskEntity task, ExpressionManager expressionManager, DelegateExecution execution) {

        //
        // NOTE: Should also test for isNotEmpty after evaluating the expression to allow for dynamic assignments of an individual member or candidateUsers or candidateGroups
        //
        if (StringUtils.isNotEmpty(assignee)) {
            Object assigneeExpressionValue = expressionManager.createExpression(assignee).getValue(execution);
            String assigneeValue = null;
            if (assigneeExpressionValue != null) {
                assigneeValue = assigneeExpressionValue.toString();
            }

            taskEntityManager.changeTaskAssignee(task, assigneeValue);
        }

        //
        // NOTE: Should also test for isNotEmpty after evaluating the expression to allow for dynamic assignments of an individual member or candidateUsers or candidateGroups
        //
        if (StringUtils.isNotEmpty(owner)) {
            Object ownerExpressionValue = expressionManager.createExpression(owner).getValue(execution);
            String ownerValue = null;
            if (ownerExpressionValue != null) {
                ownerValue = ownerExpressionValue.toString();
            }

            taskEntityManager.changeTaskOwner(task, ownerValue);
        }

        //
        // NOTE: Should also test for isNotEmpty after evaluating the expression to allow for dynamic assignments of an individual member or candidateUsers or candidateGroups
        //
        if (candidateGroups != null && !candidateGroups.isEmpty()) {
            for (String candidateGroup : candidateGroups) {
                Expression groupIdExpr = expressionManager.createExpression(candidateGroup);
                Object value = groupIdExpr.getValue(execution);
                if (value instanceof String) {
                    List<String> candidates = extractCandidates((String) value);
                    task.addCandidateGroups(candidates);
                } else if (value instanceof Collection) {
                    task.addCandidateGroups((Collection) value);
                } else {
                    throw new FlowableIllegalArgumentException("Expression did not resolve to a string or collection of strings");
                }
            }
        }

        //
        // NOTE: Should also test for isNotEmpty after evaluating the expression to allow for dynamic assignments of an individual member or candidateUsers or candidateGroups
        //
        if (candidateUsers != null && !candidateUsers.isEmpty()) {
            for (String candidateUser : candidateUsers) {
                Expression userIdExpr = expressionManager.createExpression(candidateUser);
                Object value = userIdExpr.getValue(execution);
                if (value instanceof String) {
                    List<String> candidates = extractCandidates((String) value);
                    task.addCandidateUsers(candidates);
                } else if (value instanceof Collection) {
                    task.addCandidateUsers((Collection) value);
                } else {
                    throw new FlowableException("Expression did not resolve to a string or collection of strings");
                }
            }
        }

**Comment by tijsrademakers** [comment]
Hi,

Can you share your BPMN XML for a user task where you use the decision table output for candidate users and groups? Because I would expect an expression in the flowable:candidateUsers or Groups attribute in your use case. And then candidateGroups and candidateUsers would not be empty and contain the expression value.

**Comment by glennmorell** [comment]
Good day and thanks for the quick response.

The decision table (which is actually implemented as a Service task) sets those 3 variables ($assignmentId, $candidateUserIds, $candidateGroupIds).  It's an implementation of a multi-level assignment matrix which determines whether a user task gets assigned to a individual user or to a set of users (candidate users) or to a set of groups (candidate groups).  So one of those variables will be set with an identifier while the others will be blank.  They're not really expressions but rather are just variables set on the userTask attributes that will either be blank or will contain an identifier (comma separated for multiple candidates).

    <userTask id="usertask2" name="External Communication Review" activiti:assignee="${assignmentId}" activiti:candidateUsers="${candidateUserIds}" activiti:candidateGroups="${candidateGroupIds}"/>

**Comment by tijsrademakers** [comment]
Ok, so do I understand it correctly that for example $assignmentId resolves to an empty string and for example $candidateUserIds resolves to a set of users? And with the current logic an empty assignee will be set in that case. Or am I misunderstanding the issue?

**Comment by glennmorell** [comment]
Yeah, it will be assigned to an empty assignee (which it seems to handles well or at least doesn't throw an exception) but the blocker for me is that if the other 2 variables aren't set then it throws the below exception.  I've just tried setting those variables to empty strings (instead of null) and while it avoids the exception the assignment code proceeds to add an empty candidate user and group assignments  If that has no impact on the assignments then I'm good with setting the variables as empty string instead.

Apologies, I should have included this exception in my original submission.

    org.flowable.engine.common.api.FlowableIllegalArgumentException: Expression did not resolve to a string or collection of strings
	at org.flowable.engine.impl.bpmn.behavior.UserTaskActivityBehavior.handleAssignments(UserTaskActivityBehavior.java:273)
	at org.flowable.engine.impl.bpmn.behavior.UserTaskActivityBehavior.execute(UserTaskActivityBehavior.java:209)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeActivityBehavior(ContinueProcessOperation.java:233)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeSynchronous(ContinueProcessOperation.java:153)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.continueThroughFlowNode(ContinueProcessOperation.java:110)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.continueThroughSequenceFlow(ContinueProcessOperation.java:280)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:76)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:86)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:70)
	at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:54)
	at org.flowable.engine.impl.interceptor.BpmnOverrideContextInterceptor.execute(BpmnOverrideContextInterceptor.java:25)
	at org.flowable.engine.common.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:50)
	at org.flowable.engine.common.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:68)
	at org.flowable.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.flowable.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
	at org.flowable.engine.common.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)
	at org.flowable.engine.common.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at org.flowable.engine.common.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
	at org.flowable.engine.impl.RuntimeServiceImpl.startProcessInstanceByKeyAndTenantId(RuntimeServiceImpl.java:114)

**Comment by tijsrademakers** [comment]
Ok fully clear, will make sure this gets fixed.

**Comment by glennmorell** [comment]
Thanks, and kudos to Flowable, I've just started working with it but am impressed so far.

**Comment by tijsrademakers** [comment]
Fixed, thanks for reporting the issue
