### ISSUE TITLE
REST deployed apps do not show up in Modeler

### ISSUE THREAD

**Issue by zwets** [flowable/flowable-engine#635]
Zip-files deployed using the REST interface don't show up in the Modeler App. The models are deployed successfully, but neither the app itself, nor its contained BPMN and Form models show up in the Modeler App.

**Comment by tijsrademakers** [comment]
Hi,

How did you deploy the apps exactly? On the Flowable Engine REST API or the Flowable Modeler REST API?

**Comment by zwets** [comment]
Hi Tijs, I deployed them to `flowable-task/process-api/repository/deployment` in the pretty much out-of-the-box setup with the IDM, Admin, Modeler and Task Apps, where the Task App has the engines.

**Comment by tijsrademakers** [comment]
Ok, right. Then it's by design. The Modeler is fully separated from the Flowable runtime Engines. So if you want to import an app / process model to the Modeler, that's a separate step.

**Comment by prem911** [comment]
@tijsrademakers What is the separate step? Is the REST API only for runtime engine?

**Comment by verheyenkoen** [comment]
@tijsrademakers Also interested in the modeler API so I can automate exporting models. Where can I find it and is it documented somewhere?
