### ISSUE TITLE
Running Crystallball tests

### ISSUE THREAD

**Issue by dbmalkovsky** [flowable/flowable-engine#64]
I believe that the class `org.flowable.engine.impl.interceptor.CommandConfig` has been renamed to `org.flowable.engine.common.impl.interceptor.CommandConfig`.

In the Crystallball test suites there are two config files with the old names.

See `\flowable-crystalball\src\test\resources\org\flowable\crystalball\examples\tutorial\step01\FirstSimulationRunTest.cfg.xml` around line 74:

``` xml
<property name="defaultCommandConfig">
          <bean class="org.flowable.engine.impl.interceptor.CommandConfig">
            <constructor-arg name="contextReusePossible" value="false"/>
          </bean>
 </property>
```
And `\flowable-crystalball\src\test\resources\org\flowable\crystalball\simulator\impl\ScriptEventHandlerTest.cfg.xml` around line 77 that has a similar construct.

FWIW, there are references to a databases that include activiti in the name.  For xample in flowable.cfg.xml file in the same module.

**Comment by tijsrademakers** [comment]
Thanks, tests run ok now
