### ISSUE TITLE
Entry criterion export/import does not support all attributes

### ISSUE THREAD

**Issue by martin-grofcik** [flowable/flowable-engine#649]
![original entry criterion](https://user-images.githubusercontent.com/5585296/32648457-094f035e-c5f6-11e7-883e-496ec81db49e.PNG)
![imported entry criterion](https://user-images.githubusercontent.com/5585296/32648460-0bd1b9e6-c5f6-11e7-9125-796229651a43.PNG)

exported xml:
```
      <sentry id="sentry1">
        <ifPart>
          <condition><![CDATA[${true}]]></condition>
        </ifPart>
      </sentry>
```

the problem is that entry and exit criterion are loosing their reference to parent after import/export

**Comment by martin-grofcik** [comment]
https://github.com/flowable/flowable-engine/pull/645

**Comment by tijsrademakers** [comment]
Merged
