### ISSUE TITLE
about the 'explorer',such as activiti-explorer

### ISSUE THREAD

**Issue by Paleozoic** [flowable/flowable-engine#665]
there is a project named activiti-explorer in the activiti 5.x , what about the flowable 6.x?
Or how can we show  the hightlight process instance with html and js?

**Comment by tijsrademakers** [comment]
This is more a question for the Flowable forum (forum.flowable.org).
In Flowable 6 the UI apps have been rewritten in AngularJS, the Explorer was using Vaadin.
The Flowable Task app can be used to start process instances and complete tasks etc. It also contains the overview diagram of a running process instance. There's also the Flowable Admin app for more administrative purpose that also contains the same diagram logic.
