### ISSUE TITLE
flowable-modeler :There's something wrong with BpmnJsonConverter.convertToBpmnModel‘s return

### ISSUE THREAD

**Issue by huangxun131** [flowable/flowable-engine#667]
I tried to change acitiviti to flowable,but can't solve the following line of code when i changed the dependency from activiti-modeler to flowable-modeler:
`BpmnModel model = new BpmnJsonConverter().convertToBpmnModel(modelNode);`
It required org.flowable.bpmn.model.BpmnModel but found org.activiti.bpmn.model.BpmnModel.

**Comment by tijsrademakers** [comment]
Make sure you include the flowable-bpmn-model module as well.
