### ISSUE TITLE
Variable scope inconsistency with parallel executions

### ISSUE THREAD

**Issue by marcus-nl** [flowable/flowable-engine#694]
I've added a test "testVariableScopes" to ParallelGatewayTest, which you can see here:
[ParallelGatewayTest.java](https://github.com/marcus-nl/flowable-engine/blob/2fe0cb6236718dc1ea1bb7cccc996441dc168774/modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/gateway/ParallelGatewayTest.java#L114)
[ParallelGatewayTest.testVariableScopes.bpmn20.xml](https://github.com/marcus-nl/flowable-engine/blob/2fe0cb6236718dc1ea1bb7cccc996441dc168774/modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/gateway/ParallelGatewayTest.testVariableScopes.bpmn20.xml)

I may be misunderstanding something, but the behaviour I'm observing seems incorrect to me.

The manual states:
> Note that variables can be set local for a given execution (remember, a process instance consists of a tree of executions). The variable will only be visible on that execution and not higher in the tree of executions. This can be useful if data shouldn’t be propagated to the process instance level, or the variable has a new value for a certain path in the process instance (for example, when using parallel paths).

I would expect each parallel path to have their own (new) scope, with the scope at the fork (let's call it the "outer" scope) as their parent, and:
(a) In the parallel paths all variables (including locals) that were visible before the fork should be visible. 
(b) Variables local to the parallel paths should no longer be visible after the join.
(c) All variables that were visible before the fork should be visible after the fork.

The failing assertions on line 146 and 147 show that (a) is not always the case. Local variables in the "outer" scope are only visible to the execution that was reused (because it's the outer execution itself that is reused). The non-reused executions have the outer-execution's parent (which is the process instance in this case) as their parent, so won't see those local variables.

The failing assertion on line 169 shows that the local variable of one of the parallel executions is still visible. That's because it's the reused execution.

In addition, the failing assertion on line 168 indicates another problem: the variable that was set on the outer execution is no longer visible (I'm not entirely sure why). This indicates that (c) does not hold.

I think this can be solved by always creating a new execution for the parallel paths (instead of trying to reuse them) that have the "outer" execution as their parent. Those executions should be destroyed at the fork, and flow should then continue using the original outer execution. What do you think?

**Comment by tijsrademakers** [comment]
Hi Marcus,

Thanks for including the unit test, that makes it a lot easier to comprehend the issue.
The way it works is that each parallel path has its own execution, and each execution will have the scope as the parent execution, which can be the process instance execution or a sub process scope execution for example. For this first parallel path we reuse the fork parallel gateway execution, for the other parallel paths a new execution is created.

So, the fork parallel gateway is not a parent execution for all the outgoing parallel paths. Parent executions can only be a scope (either process instance or sub process or a multi instance). So each path will need to have its own local variables. You could also use an embedded sub process and put the parallel gateway construct inside that, then you can use the embedded sub process scope to set local variables that will be available for every parallel path.

Best regards,

Tijs

**Comment by marcus-nl** [comment]
Hi Tijs,

As I understand it right now, executions can be scoped or not (indicated by the boolean isScope). A scoped execution has their own local variables. Local variables that are set on a non-scoped execution should end up in the first scoped execution in its parent hierarchy.

In my test case I use the execution from the first task in the process to set the initial variables. Since that execution is unscoped I would expect the local variables to end up in the root execution (the process instance), since that's the first parent in the hierarchy to be scoped.

If that's right then I still think there may be an issue. You say that each [parallel, I assume] path will need to have its own local variables, and this is consistent with the quoted part of the manual and with what I would expect. Do I correctly interpret that to mean that the executions for those paths should be scoped (so isScope is true)? That does not seem to be the case right now.

Vriendelijke groeten, 

Marcus

**Comment by tijsrademakers** [comment]
Hi Marcus,

Each execution can have local variables, scoped or not. 
The main difference is that for a logical scope (process instance, embedded sub process, multi instance), we create an additional parent execution which you can nicely use to set variables on. So if you use the parallel gateway inside an embedded sub process, you know there's a parent sub process execution on which you can set local variables and that are accessible for every child execution inside the embedded sub process.

Best regards,

Tijs

**Comment by marcus-nl** [comment]
Ah, I see: my misunderstanding is what it means for an execution to be scoped (or "to be a scope"? what is the correct term you use?). I assumed it would be a scope in the sense of a variable scope as well, but I see now that's not the case. Could you clear up for me what it means exactly? Once I understand I can help clarify the JavaDoc if you want. While we're at it I'm not entirely clear about the concurrent and multiinstanceroot attributes either.

Regards, Marcus
