### ISSUE TITLE
How does "PersistentTokenServiceImpl" behave on multi-instance environment.

### ISSUE THREAD

**Issue by CanerPatir** [flowable/flowable-engine#695]
Hello, 
Is there any way to keep active sessions in a common cache context (redis etc.) which is shared by idm-app instances in order to leverage multi-instance idm-app in a cluster environment. Otherwise, login system does not supply persistency with multi-instance idm-app.

**Comment by tijsrademakers** [comment]
Hi,

The Flowable UI apps use cookies to determine if a user is logged in. The cookies are based on the persistent tokens stored in the ACT_ID_TOKEN table. So if you would have multiple IDM apps pointing to the same database this should already work.
