### ISSUE TITLE
Different sub-domain name usage per ui-app

### ISSUE THREAD

**Issue by CanerPatir** [flowable/flowable-engine#696]
Hello, 

I am redirected to idm app continuously when I tried to deploy flowable UI applications by using different sub-domains instead of different ports. Is there any workaround to solve this issue?  How can I share cookie between sub-domains?

**Comment by tijsrademakers** [comment]
Hi,

Best to ask these kind of questions on the Flowable forum.
You can use the following properties to define different sub domains:

idm.app.url=http://idm.test.com
idm.admin.user=admin
idm.admin.password=test

app.redirect.url.on.authsuccess=http://task.test.com
