### ISSUE TITLE
Cannot add assignments in the modeler on a migrated model

### ISSUE THREAD

**Issue by mlippens** [flowable/flowable-engine#697]
All models we have migrated (models that existed pre flowable 6) have the problem that assignments cannot be added any more.

This is how we reproduced this:
- Edit a userTask of a model and add a candidateGroup
- Close the assignments popup by saving
Now when reopening the assignment is not present.

The cause is that now we have two 'types' of assignments, being `idm` and `static`. The existing properties can then no longer be changed since it relies on this type property to be present in `properties-assignment-controller.js`.

An extra check to make sure this property is set to `static` if it does not exist fixes this issue. 

I will submit a pull request soon.

**Comment by tijsrademakers** [comment]
Thanks for the PR, merged it
