### ISSUE TITLE
[Flowable5] Async executor not behaving properly

### ISSUE THREAD

**Issue by StefanHenke** [flowable/flowable-engine#700]
Hi,
I´m experiencing a weird behavior with flowable 5.21. The scenario is, we are having a process definition with a number of script tasks in a sequence (no parallel branches). Every activity has the “async=true” flag. What I can see is that every script task is only executed after the asyncJobAcquireTime is over. My assumption so far was that after executing an activity the async executor directly submits the next job into the async executor. From what I can see in the debugger, this seems to happen. However, this new thread tries to lock the process instance before the first (original) thread is able to unlock the process instance. In the logs, I see that the second thread throws an ActivitiOptimisticLockingException in ExecutionEntityManager#updateProcessInstanceLockTime.

My observation is also that the first thread uses two different transactions for executing the job and unlocking it. As the submission to the async executor happens in a commit transaction listener, it is at least executed in parallel to the actual unlocking.

I´m attaching a simple JUnit test which reproduces the issue. It seems to be applicable only if you use the SpringProcessEngineConfiguration. In order to "provoke" the situation, I artificially increased the wait time for the async job to an abnormal high value. My expectation would be that the process runs to the end even without the async executor polling the database. If you change the wait time to e.g. 100ms, the test succeeds.
Originally, I was detecting this issue with activiti 5.21.0 But it seems to be present as well in flowable 5.

Best regards,
Stefan

[resources.zip](https://github.com/flowable/flowable-engine/files/1538675/resources.zip)

**Comment by tijsrademakers** [comment]
Thanks for raising the issue, it's fixed with the linked commit.
