### ISSUE TITLE
JSON converter is AL 2.0 licensed but has LGPL 2.0 dependency

### ISSUE THREAD

**Issue by ilgrosso** [flowable/flowable-engine#701]
JSON converter is released under AL 2.0 (as the whole Activiti platform) but depends on javaGeom, which is released under LGPL 2.0, according to https://sourceforge.net/projects/geom-java/.

I also reported this issue as Activiti/Activiti#842

**Comment by tijsrademakers** [comment]
JavaGeom dependency has been removed

**Comment by ilgrosso** [comment]
Great work guys, thanks!
