### ISSUE TITLE
Add taskAssigneeIn method for searching/filtering tasks

### ISSUE THREAD

**Issue by ktschmidt** [flowable/flowable-engine#71]
The TaskQuery interface provides for retrieving/filtering tasks that are assigned to a specific user, but if one wants to search for tasks assigned to several users, individual queries must be done and the results merged together.  It would be much more convenient if there was a taskAssigneeIn method that took a list of users.

**Comment by tijsrademakers** [comment]
Added assigneeIds option to the task and historic task query interface.
