### ISSUE TITLE
flowable-modeler: changing business process model name and key does not change process name and identifier

### ISSUE THREAD

**Issue by PascalSchumacher** [flowable/flowable-engine#719]
When you create a business process model the name and the key are used as the process name and identifier.

If you later change the business procees model name and key this is not protagated to the process name and identifier.

This behavior is confusing our users, because they do not see their new models as deployed processes.

**Comment by tijsrademakers** [comment]
Merged the PR and this should fix the issue. Thanks for the PR @seifeldeen92 !

**Comment by PascalSchumacher** [comment]
@tijsrademakers I guess you did not push yet (I do not see the PR merged yet.)?

**Comment by PascalSchumacher** [comment]
@tijsrademakers Sorry I missed https://github.com/flowable/flowable-engine/commit/2fa4b45440f8e1c0c6fa5c0012879686288a7520 somehow.
