### ISSUE TITLE
ClassCastException with JUEL expression

### ISSUE THREAD

**Issue by suttermichael** [flowable/flowable-engine#733]
Hi,

I experienced an issue with an user task and a Juel expression as name. In case the Juel expression evaluates to a number I get a ClassCastException "Cannot cast class java.lang.Integer to class java.lang.String".

I first experienced this issue in activiti 5, but also evaluated it with flowable 6.2.1.
Attached is a simple test to reproduce the issue.

Can you please have a look into it?

Kind regards,
Michael

[test.zip](https://github.com/flowable/flowable-engine/files/1597650/test.zip)

**Comment by tijsrademakers** [comment]
Hi Michael,

A task name needs to be a String. We could add an instanceof check and do a toString() for non String values. Is it important for your use case to use number values for user task names?

Best regards,

Tijs

**Comment by suttermichael** [comment]
Hi Tijs,

it is understandable that it must be string. Nevertheless for us it is a generic engine for which users also can use non string values. Therefore a ClassCastException is looks really weird. 

An instanceof check with a corresponding toString sounds perfect.

Kind regards,
Michael
