### ISSUE TITLE
request app/rest/models?filter=processes&modelType=0&sort=modifiedDesc 404

### ISSUE THREAD

**Issue by mineycz** [flowable/flowable-engine#737]
i want use flowable by spring-boot, but, request app/rest/models?filter=processes&modelType=0&sort=modifiedDesc and app/rest/account couldn't found,
myconfig : 
'contextRoot' : '/activiti',
'webContextRoot' : '/activiti/plugins/flowable/modeler',

spring-boot dependency:
flowable-spring-boot-starter-basic
flowable-spring-boot-starter-rest-api
version :6.2.1

web:
all page from modeler.war(6.2.1)

**Comment by tijsrademakers** [comment]
Best to first ask on the forum before creating an issue.
Are you running both the Spring Boot REST backend as well as the frontend on the same context root?

**Comment by tijsrademakers** [comment]
Closing the issue, due to no response. Please reopen the issue when needed.
