### ISSUE TITLE
flowable-ui-admin module Chinese characters

### ISSUE THREAD

**Issue by MichaelDiane** [flowable/flowable-engine#739]
flowable-ui-idm / task / modeler three modules can display Chinese, but flowable-ui-admin Chinese can not be displayed correctly, this problem has been fixed in # 541, but the actual situation in version v6.2.1 flowable-ui -admin still exists. The steps to reproduce the problem are as follows:
The first step: create a Chinese APP and deploy
Part II: login flowable-ui-admin view garbled
Please check, is not merged into the master branch?
[<img src=http://chuantu.biz/t6/201/1515488660x1703164337.jpg />](url)

**Comment by PascalSchumacher** [comment]
https://github.com/flowable/flowable-engine/pull/541 seems to be in master (and 6.2.1) see https://github.com/flowable/flowable-engine/commit/31afa5353b27bb2c86448cda4b7289813072f12d and 59ad7a865d8ac7536cda72c21884e03d275a9ff6

I lack knowledge of Angular, but https://github.com/flowable/flowable-engine/pull/541 seemed to address parameters only (not sure if the name and description on the screenshot are parameters) so maybe it did not really fix this issue?

Could also be an issue of encoding of the servlet container you use (I think e.g. tomcat does not use UFT-8 by default).

**Comment by tijsrademakers** [comment]
Closing issue, due to no response
