### ISSUE TITLE
Invoking methods in decision table fails to select correct method if methods are overloaded

### ISSUE THREAD

**Issue by AminaZoheir** [flowable/flowable-engine#742]
In a process with variable date_in is a DateTime the following decision table is used:

<img width="1383" alt="screen shot 2018-01-09 at 8 43 12 pm" src="https://user-images.githubusercontent.com/3508748/34737117-ddd61386-f57d-11e7-98ab-9ffbfb9d7db2.png">

The method minus in DateTime is overloaded. One accepts a long, another accepts a ReadablePeriod and the last accepts a ReadableDuration.
In the above decision table the minus method is used with a parameter of type Long. This error is thrown in the console.
Cannot coerce '56,780,984' of class java.lang.Long to interface org.joda.time.ReadablePeriod (incompatible type)

It mapped to the method accepting the ReadablePeriod.

**Comment by PascalSchumacher** [comment]
I believe DMN uses the Java Unified Expression Language (JUEL) and JUEL does not support method overloading (see, e.g. https://stackoverflow.com/questions/9763619/does-el-support-overloaded-methods). Therefore I would not expect this issue to be solved quickly (if at all) :(.

**Comment by tijsrademakers** [comment]
No indeed, the DMN engine uses JUEL for the expression evaluation and this is not supported by JUEL. It's easy however to plugin a custom static bean method so you can add logic into an expression.
