### ISSUE TITLE
Flowable 6.2.1 OSGI dependency on junit.framework.

### ISSUE THREAD

**Issue by mperestrelo** [flowable/flowable-engine#744]
The org.flowable.idm.engine in 6.2.1 contains a dependency on junit.framework.

IN the manifest for org.flowable.idm.engine we find

Import-Package: junit.framework

This should not be necessary.

**Comment by tijsrademakers** [comment]
Thanks for reporting the issue, changed the junit OSGi dependency to optional, like it was done for the BPMN and CMMN engine already
