### ISSUE TITLE
OSGI Exports Flowable - REST - Common

### ISSUE THREAD

**Issue by mperestrelo** [flowable/flowable-engine#754]
Right now I am trying to setup the rest api on OSI/KARAF.

Shouldn't "Flowable - REST - Common" export the package: org.flowable.rest.application, otherwise how would flowable-rest import it as an OSGI package? 

I added this line to the POM for version 6.3.0-SNAPSHOT

 <flowable.osgi.export.additional>
            org.flowable.rest.application,
 </flowable.osgi.export.additional>

This allowed the package import.

**Comment by tijsrademakers** [comment]
Fixed by changing the package names of the REST modules. Could you validate that it's working for you with the current master?
