### ISSUE TITLE
Cannot run callActivity with Process Definition ID

### ISSUE THREAD

**Issue by shyamraghavan** [flowable/flowable-engine#756]
It's not possible to start a Call Activity with a particular process definition ID. The engine only supports call activities by process definition key.

**Comment by tijsrademakers** [comment]
Hi, correct. In addition, you can also use a boolean attribute flowable:sameDeployment="true" on a callActivity element, so the process definition will be first searched as part of the same deployment as the parent process definition. What would be the use case of using a specific process definition id? It's really difficult to know this upfront when designing a process model. This value will be different in your testing environment compared to your production environment for example. Do you have a use case where you would need this?

**Comment by shyamraghavan** [comment]
Hi, thanks for getting back. I use Flowable with an external service for _versioning_ the various process definitions. For example, I want to be able to roll back a particular process definition (for a call activity) without changing the calling process definition.

**Comment by tijsrademakers** [comment]
A property flowable:calledElementType has been added. Now you can also reference a process definition id directly.
