### ISSUE TITLE
initiator variable not visible

### ISSUE THREAD

**Issue by taniyer** [flowable/flowable-engine#757]
I have a form where I added a expression to display the process initiator username( logged in user name).

I tried 2 ways.

1)  I used the form in the start event as a form reference. Also set the Initiator:initiator.
Result: When I start the process in the Flowable Task application it shows the form. However it displays  ${initiator} as a plain text rather than resolving the expression with the value of variable.
Seem to be a problem.

2) I used the same form in a subsequent user form.
Result: When I see the task the form resolved the ${initiator} expression. Works perfectly.
  
Why the 2nd approach working and 1st one not working. Am I doing anything wrong? Your response is highly appreciated

Thanks

**Comment by martin-grofcik** [comment]
I would say that ${initiator} process variable is not initialized yet, because process instance still does not exist in the case 1. From my point of view the behavior is correct.

**Comment by tijsrademakers** [comment]
Hi,

Like Martin was already saying, when showing a start form, the process instance hasn't started yet, so the initiator of the process instance is also not known yet. If you would like to have an initator value shown in the form then the second approach of having a user task as first step in the process instance would work. So closing the issue.

Best regards,

Tijs

**Comment by taniyer** [comment]
Thank you very much Martin & Tijs. The explanation makes perfect sense.

Thanks & Regards

taniyer
