### ISSUE TITLE
Flowable IDM Privilege issue with LDAP

### ISSUE THREAD

**Issue by taniyer** [flowable/flowable-engine#763]
Hi,
I have configured Flowable IDM to use Apache DS 2.0.0 as LDAP Server. 
I have 2 groups 
1) Administrators ( default)
2) staff ( I created that one)
and I have 1 user. 
See the screen shot attached.
I could login with admin and with the custom user.
I could assign privileges via Flowable IDM f-> Access ID Management Application - > User add User with out any issues.
However when
I tried to add the privileges to a group (staff). I am getting the following error. Is this a defect or Am I doing anything wrong on LDAP configuration

Thanks & Regards

taniyer

**org.flowable.engine.common.api.FlowableException: Query return 2 results instead of max 1
	at org.flowable.engine.common.impl.AbstractQuery.executeSingleResult(AbstractQuery.java:165)
	at org.flowable.engine.common.impl.AbstractQuery.singleResult(AbstractQuery.java:106)
	at org.flowable.app.idm.service.PrivilegeServiceImpl.isGroupPrivilege(PrivilegeServiceImpl.java:90)**

flowable-ui-app.properties

#
#LDAP
#
ldap.enabled=true
ldap.server=ldap://localhost
ldap.port=10389
ldap.user=uid=admin,ou=system
ldap.password=secret
#ldap.basedn=o=flowable
ldap.basedn=ou=system
ldap.query.userbyid=(&(objectClass=inetOrgPerson)(uid={0}))
ldap.query.userbyname=(&(objectClass=inetOrgPerson)(|({0}=*{1}*)({2}=*{3}*)))
ldap.query.userall=(objectClass=inetOrgPerson)
ldap.query.groupsforuser=(&(objectClass=groupOfUniqueNames)(uniqueMember={0}))
ldap.query.groupall=(objectClass=groupOfUniqueNames)
ldap.attribute.userid=uid
ldap.attribute.firstname=cn
ldap.attribute.lastname=sn
ldap.attribute.email=mail
ldap.attribute.groupid=cn
ldap.attribute.groupname=cn
ldap.attribute.grouptype=cn
ldap.cache.groupsize=10000
ldap.cache.groupexpiration=180000
#

**Comment by taniyer** [comment]
![flowable-idm](https://user-images.githubusercontent.com/10656521/35153201-1ad74ea2-fceb-11e7-94de-b5a4c42b18d4.jpg)

**Comment by lucjross** [comment]
I'm seeing this as well. A possible fix is adding a check for `getId() != null` to this method: https://github.com/flowable/flowable-engine/blob/master/modules/flowable-ldap/src/main/java/org/flowable/ldap/impl/LDAPGroupQueryImpl.java#L57

If someone could confirm this is a good fix, I will open a PR.

**Comment by frod0** [comment]
> I'm seeing this as well. A possible fix is adding a check for `getId() != null` to this method: https://github.com/flowable/flowable-engine/blob/master/modules/flowable-ldap/src/main/java/org/flowable/ldap/impl/LDAPGroupQueryImpl.java#L57
> 
> If someone could confirm this is a good fix, I will open a PR.

How do you suggest the function be?
