### ISSUE TITLE
execute HistoricTaskService.findHistoricTaskInstancesByQueryCriteria method error with taskVariable

### ISSUE THREAD

**Issue by jmm1207** [flowable/flowable-engine#768]
test code:
HistoricTaskInstanceQueryImpl query = new HistoricTaskInstanceQueryImpl();
query.processInstanceId(task.getProcessInstanceId()).finished().taskVariableValueEquals("empId","1");
historicTaskService.findHistoricTaskInstancesByQueryCriteria(query);

error message:
Error querying database.  Cause: java.lang.NullPointerException: target is null for method equals;

source code :
HistoricTaskInstance.xml file 864 row

**Comment by tijsrademakers** [comment]
Did you also try to use historyService.createHistoricTaskInstanceQuery() instead of instantiating the query class yourself? Because that's the supported way. If so then please reopen the issue.
