### ISSUE TITLE
flowable-modeler: duplicating a business process with deferent name and key does not change the duplicated process name and identifier

### ISSUE THREAD

**Issue by seifeldeen92** [flowable/flowable-engine#771]
When you duplicate a business process model the name and the key are not used as the process name and identifier. instead, it uses the original process name and identifier

This behavior is confusing because users do not see their new model as deployed processes.

**Comment by PascalSchumacher** [comment]
I guess this can be closed (as the pull request has been merged)?

**Comment by tijsrademakers** [comment]
Merged the PR, thanks!
