### ISSUE TITLE
A strange question in Countersign 

### ISSUE THREAD

**Issue by jianlinz** [flowable/flowable-engine#772]
a Countersign have  ten numberOfInstances
I use a executionListener event="end"  to see nrOfCompletedInstances 
when countersign end in activiti6.* the nrOfCompletedInstances is 10
but flowable 6.2.1 the nrOfCompletedInstances  is null

**Comment by tijsrademakers** [comment]
Hi, in Flowable there's a parent execution for a multi instance child execution that has the nrOfCompletedInstances variable with the value.
