### ISSUE TITLE
Same db package names in 2 different modules

### ISSUE THREAD

**Issue by andreessen** [flowable/flowable-engine#777]
Hello. We have just completed beta version for Flowable 6.2.1 and Liferay 7 integration module. During migration we found out one issue that prevented us from deployment into Liferay OSGi(Equinox) - db package names in 2 different modules are the same: https://github.com/flowable/flowable-engine/tree/flowable-6.2.1/modules/flowable-engine/src/main/resources/org/flowable/db1 and https://github.com/flowable/flowable-engine/tree/flowable-6.2.1/modules/flowable-engine-common/src/main/resources/org/flowable/db3 though we have to rename package name for flowable-engine-common in our fork. So I wonder - are you planing to change package name in some of this 2 modules or it will remain the same? Thanks.

See https://forum.flowable.org/t/migration-from-6-1-2-to-6-2-1/1542

**Comment by tijsrademakers** [comment]
Moved the common engine folder to org/flowable/common/db. Thanks for pointing this out!
