### ISSUE TITLE
Script task without scriptFormat attribute is silently skipped

### ISSUE THREAD

**Issue by zwets** [flowable/flowable-engine#782]
I had forgotten to set the `scriptFormat` attribute on a task to `JavaScript`. This resulted in the script being silently not executed. There is no exception or error entry in the log to indicate that the task was not executed.

**Comment by tijsrademakers** [comment]
When the scriptFormat is not set to JavaScript the default script format will be used, JUEL. So the script should have been executed with the JUEL scripting engine. Could you validate this?

**Comment by zwets** [comment]
I'm not conversant in JUEL, so it's hard to tell. Below is the code. It looks quite generic to me. (Note `stringHelper` and `config` are names of objects in the application context.)

```
if (stringHelper.isBlank("vcbPostpone")) {
    execution.setVariable("vcbPostpone", 7);
}

execution.setVariable("vcbInterval", "P" + (config.testMode ? "T" : "") + vcbPostpone + (config.testMode ? "0S" : "D"));
```

It works when I set `scriptFormat` to `JavaScript`, but not without.

**Comment by tijsrademakers** [comment]
We changed the logic and now throw an error if the scriptFormat is not set and the script evaluation fails.
