### ISSUE TITLE
Multi instance, add more elements at runtime

### ISSUE THREAD

**Issue by edgarjoao** [flowable/flowable-engine#787]
Hi,
I have a muti instance "Call Activity", I was wondering if its possible to add more instances to the current activity at runtime? 

Regards

**Comment by dzj2046** [comment]
+1

**Comment by PascalSchumacher** [comment]
Hi edgarjoao,

questions should be asked at https://forum.flowable.org/

Regards,
Pascal

**Comment by tijsrademakers** [comment]
Hi,

In RuntimeService you can find the addMultiInstanceExecution method, that does exactly what you are looking for.

Best regards,

**Comment by edgarjoao** [comment]
Thank you very much @tijsrademakers, next time I will use flowable forum.
