### ISSUE TITLE
Feature Request: Add a "Password" field in Forms

### ISSUE THREAD

**Issue by seifeldeen92** [flowable/flowable-engine#797]
I think it would be a good addition to have a "password" field as an option while building a From in the flowable modeler

A simple usage for it would be:
if a user wants to create a form that authenticates using a username and password. in the current state, the user will create a form with two normal input fields so that password will be visible which is not the best practice when dealing with password as an input. it would be better to have a password field

**Comment by tijsrademakers** [comment]
Thanks for the PR!
