### ISSUE TITLE
Test queries that depend on the order of date/times

### ISSUE THREAD

**Issue by dbmalkovsky** [flowable/flowable-engine#8]
Depending how, where, and when I run the suite of unit tests I often get some set of the same errors.  When examining the errors they all have the same common trait:  there is an SQL query that is sorting on some date/time field. Because of the speed of the machine and the lack of resolution in Java date/time values some operations appear as the executed exactly at the same time even though executed sequentially. The unit tests depend on explicit ordering as the ```assert``` statements are fetching and comparing to specific values in the returned result sets.  The SQL query when seeing exactly the same ``ordering`` is free to return the values in any order thus the errors.

There are 4 main tests that exhibit this behavior and they are:

- AdhocSubProcessTest - see (1) below
- HistoricProcessInstanceTest - see (2) below 
- HistoricTaskQueryEscapeClauseTest - see (3) -> (12) below; only annotated a few as the pattern became clear
- FullHistoryTest - see (13) below

I see 3 possible _solutions_:

- always run on a slow machine :)
- add sleep statements to force different dates/time values so the ordering is correct
- use ```contains``` type test logic instead of comparing to specific values in the returned result set list

I lean towards the last option as we really aren't testing the ability of SQL engines to sort the data but rather the presence or absence of specific records.

Comments?  

I'll provide a pull request when a decision is made.

Thanks

## Details
1. 
```java
testSimpleCompletionCondition(org.activiti.engine.test.bpmn.subprocess.adhoc.AdhocSubProcessTest)
```
```java
junit.framework.ComparisonFailure: expected:<subProcessTask[]> but was:<subProcessTask[2]>
at org.activiti.engine.test.bpmn.subprocess.adhoc.AdhocSubProcessTest.testSimpleCompletionCondition(AdhocSubProcessTest.java:112)
```
The query includes: ```.orderByHistoricTaskInstanceEndTime()```

The returned data values are:

2016-10-18 06:19:28.716
2016-10-18 06:19:28.716
2016-10-18 06:19:28.732

(2) 
```java
testHistoricProcessInstanceSorting(org.activiti.engine.test.history.HistoricProcessInstanceTest)
```
```java
junit.framework.ComparisonFailure: expected:<15[898]> but was:<15[903]>
at org.activiti.engine.test.history.HistoricProcessInstanceTest.testHistoricProcessInstanceSorting(HistoricProcessInstanceTest.java:353)
```
The query includes: ```.orderByProcessInstanceEndTime()```

(3) 
```java
testQueryByTaskNameLikeIgnoreCase(org.activiti.standalone.escapeclause.HistoricTaskQueryEscapeClauseTest)
```
```java
junit.framework.ComparisonFailure: expected:<1[1]> but was:<1[6]>
at org.activiti.standalone.escapeclause.HistoricTaskQueryEscapeClauseTest.testQueryByTaskNameLikeIgnoreCase(HistoricTaskQueryEscapeClauseTest.java:269)
```
The query includes: ```.orderByHistoricTaskInstanceStartTime()```

The returned date values are:

2016-10-18 06:21:19.996
2016-10-18 06:21:19.996

(4) 
```java
testQueryByProcessDefinitionNameLike(org.activiti.standalone.escapeclause.HistoricTaskQueryEscapeClauseTest)
```
```java
junit.framework.ComparisonFailure: expected:<1[1]> but was:<1[6]>
at org.activiti.standalone.escapeclause.HistoricTaskQueryEscapeClauseTest.testQueryByProcessDefinitionNameLike(HistoricTaskQueryEscapeClauseTest.java:148)
```
which has: ```.orderByHistoricTaskInstanceStartTime()```

(5) 
```java
testQueryByTaskDescriptionLike(org.activiti.standalone.escapeclause.HistoricTaskQueryEscapeClauseTest)
```
```java
junit.framework.ComparisonFailure: expected:<1[1]> but was:<1[6]>
at org.activiti.standalone.escapeclause.HistoricTaskQueryEscapeClauseTest.testQueryByTaskDescriptionLike(HistoricTaskQueryEscapeClauseTest.java:296)
```
which has: ```.orderByHistoricTaskInstanceStartTime()```

(6) 
```java
testQueryByTaskNameLike(org.activiti.standalone.escapeclause.HistoricTaskQueryEscapeClauseTest)
```

(7) 
```java
testQueryByTaskAssigneeLike(org.activiti.standalone.escapeclause.HistoricTaskQueryEscapeClauseTest)
```

(8) 
```java
testQueryLikeByQueryVariableValue(org.activiti.standalone.escapeclause.HistoricTaskQueryEscapeClauseTest)
```

(9) 
```java
testQueryLikeIgnoreCaseByQueryVariableValue(org.activiti.standalone.escapeclause.HistoricTaskQueryEscapeClauseTest)
```

(10) 
```java
testQueryByProcessInstanceBusinessKeyLikeIgnoreCase(org.activiti.standalone.escapeclause.HistoricTaskQueryEscapeClauseTest)
```

(11) 
```java
testQueryByTenantIdLike(org.activiti.standalone.escapeclause.HistoricTaskQueryEscapeClauseTest)
```

(12) 
```java
testQueryByProcessDefinitionNameLike(org.activiti.standalone.escapeclause.TaskQueryEscapeClauseTest)
```
(13) 
```java
testHistoricVariableRemovedWhenRuntimeVariableIsRemoved(org.activiti.standalone.history.FullHistoryTest)
```
```java
junit.framework.AssertionFailedError
at org.activiti.standalone.history.FullHistoryTest.testHistoricVariableRemovedWhenRuntimeVariableIsRemoved(FullHistoryTest.java:1392)
```
which has: ```.orderByTime()```

**Comment by tijsrademakers** [comment]
Interesting, didn't experience this myself. Is this happening on H2?
I think your 3rd solution, with contains checks makes a lot of sense to solve this.

**Comment by dbmalkovsky** [comment]
Yes I find running this with H2 on the full suite.  When I run individual classes in my IDE they pass without problem.  

I will work on a patch.  Are you OK with adding hamcrest matchers?

**Comment by tijsrademakers** [comment]
Ok cool. Yes hamcrest matchers are fine.

**Comment by dbmalkovsky** [comment]
More information:  At home today I cloned the project on my Linux box; at work I am using Windows.  Running "mvn clean test" inside of my IDE and from the command line on Linux results in no errors (that is my changes for using "contains" are not included).  

This leads me to assume that there might be a difference with the JDK or H2 implementations between the two operating systems.

I will continue to dig into this before submitting the patch.
