### ISSUE TITLE
Flowable-Modeler: Add Web Service Task

### ISSUE THREAD

**Issue by PascalSchumacher** [flowable/flowable-engine#814]
As reported in https://forum.flowable.org/t/soap-in-flowable-modeler-app/1478/3 the Web Service Task is missing from the modeler.

It would be nice if support for this would be added. 

Thanks!

**Comment by bvedam** [comment]
Same requirement here. Integration thru SOAP/REST service is a common use-case, and this appears to be missing in the modeler while the documentation says "web service" task is something that is supported.

**Comment by paulhh** [comment]
Always happy for a contribution :)

**Comment by alexander-perucci** [comment]
Hi, what is the status of this issue? Have you plan to introduce the `Web Service Task` as described in the documentation?

**Comment by tijsrademakers** [comment]
Hi,

Adding basic support for the web service task is not too difficult to add, but to make it user friendly it would be nice to support reading a WSDL document and selecting the operation and input and output parameters from there. This work is still to be done, and there is no planning yet. A community contribution to work on this together would be the best way forward.

**Comment by alexander-perucci** [comment]
Thanks a lot for your prompt reply. I understand the point.

Is it possible to manually add a `Web Service Task` in the bpmn file and programmatically map operation and I/O parameters, without using the flowable-modeler? If yes, there is a step-by-step tutorial that can help users to do it?

**Comment by zhenchuan9r** [comment]
Any further progress on this issue?

**Comment by tijsrademakers** [comment]
The last feedback from 2019 still stands, but since there was no progress since then, I'm closing the issue.
