### ISSUE TITLE
flowable.org -> www.flowable.org

### ISSUE THREAD

**Issue by n0mer** [flowable/flowable-engine#815]
hello, 
wikipedia article https://en.wikipedia.org/wiki/Flowable contains link to http://flowable.org (which is not working).

So, either update wikipedia article, or make redirect flowable.org -> www.flowable.org (although "www" is so 1990 :) )

**Comment by tijsrademakers** [comment]
Thanks, changed it to www.flowable.org for now to make it work. You can make changes to wikipedia as well of course :-)

**Comment by n0mer** [comment]
same problem: http://www.flowable.org/docs/userguide/index.html#flowableDesigner - it mentions http://flowable.org/designer/update/ as update site, but (as you can guess) it does not work either.

Have to provide http://www.flowable.org/designer/update/

**Comment by n0mer** [comment]
https://github.com/flowable/flowable-engine - same here, "Homepage" link is broken.

Really, i advice to setup HTTP/301 redirect from www.flowable.org to flowable.org, otherwise this problem will persist

**Comment by tijsrademakers** [comment]
The Eclipse Designer update site is not an url accessible by a web browser. It's only accessible with Eclipse.

**Comment by tijsrademakers** [comment]
We need to configure the redirect indeed. For now the links are changed.
