### ISSUE TITLE
spring-boot-admin 2.x support

### ISSUE THREAD

**Issue by n0mer** [flowable/flowable-engine#816]
Hello,

author of spring-boot-admin is not going to rewrite activiti integration for 2.x (https://github.com/codecentric/spring-boot-admin/issues/465#issuecomment-364837831) : 

> Currently only 5% of the core-ui downloads uses the uiactivitu as well - so I'm not planning on reimplementing this for 2.0

So, are there any plans to support Flowable in spring-boot-admin?

**Comment by tijsrademakers** [comment]
Hi,

Like already mentioned, please use the forum to ask questions (https://forum.flowable.org).
We are not aware of the functionality provided by the Spring boot admin project. Let's discuss this further on the forum, would be good if you show what the provided functionality is exactly.

**Comment by n0mer** [comment]
@tijsrademakers done: https://forum.flowable.org/t/spring-boot-admin-2-x-support/1664

**Comment by n0mer** [comment]
cross-reference: https://github.com/codecentric/spring-boot-admin/issues/683
