### ISSUE TITLE
why SecurityUtils is final

### ISSUE THREAD

**Issue by jianlinz** [flowable/flowable-engine#825]
Hi!
I have a question. why SecurityUtils is final? How can I cover getCurrentFlowableAppUser method.

i hope i can inject my impl. if is ok,i will submit a PR

**Comment by tijsrademakers** [comment]
Hi,

There's no good reason, I think it should not be final.

Best regards,

Tijs

**Comment by jianlinz** [comment]
Hi!
I submit a PR https://github.com/flowable/flowable-engine/pull/827
add a SecurityService  have a default impl SecurityServiceImpl 
when I want cover getCurrentFlowableAppUser method,i will inject  a impl implements SecurityService.
like this
@Service
@Primary
public class PEPSecurityServiceImpl implements SecurityService
