### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by jianlinz** [flowable/flowable-engine#862]
Hi！
 please help me，When to insert ACT_RE_MODEL，I only See when i create or import a model  ACT_DE_MODEL update but ACT_RE_MODEL is null。

thanks！

**Comment by tijsrademakers** [comment]
Hi,

Please use the Flowable forum for these kind of questions. When using the Modeler, the models will be inserted in the ACT_DE_MODEL table. The ACT_RE_MODEL table is there for legacy reasons and is not used by the Flowable Modeler application.
