### ISSUE TITLE
[Task UI] Assignee isn't displayed in subtask list

### ISSUE THREAD

**Issue by paulhh** [flowable/flowable-engine#868]
Not obvious from a quick look at the source, but is a subtask has an assignee, the subtask list shows it as "nobody"...
<img width="629" alt="screen shot 2018-03-07 at 15 05 07" src="https://user-images.githubusercontent.com/1086885/37099927-8520e9aa-2219-11e8-90ac-11f3bb2959c1.png">

**Comment by tijsrademakers** [comment]
Fixed
