### ISSUE TITLE
Call Activity Does not start referenced process

### ISSUE THREAD

**Issue by michaelplavnik** [flowable/flowable-engine#88]
I have created application with two processes, one calling into another. When token of the parent process passes into the call activity, no tasks of the called process appear in the task application. Below is BPMN files:

`<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:activiti="http://activiti.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath" targetNamespace="http://www.activiti.org/processdef">
  <process id="learning_Subprocess" name="Learning Subprocess" isExecutable="true">
    <startEvent id="startEvent1"></startEvent>
    <userTask id="subprocessTask" name="Subprocess Task"></userTask>
    <sequenceFlow id="sid-2A367ED3-5718-4C47-8EF5-C1E811E7F8ED" sourceRef="startEvent1" targetRef="subprocessTask"></sequenceFlow>
    <endEvent id="sid-BF7D8ACD-837F-4F3F-9370-15510C8EE5B3"></endEvent>
    <sequenceFlow id="sid-4A22B10B-F5FC-4C78-AC95-9B3F7B27EF80" sourceRef="subprocessTask" targetRef="sid-BF7D8ACD-837F-4F3F-9370-15510C8EE5B3"></sequenceFlow>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_learning_Subprocess">
    <bpmndi:BPMNPlane bpmnElement="learning_Subprocess" id="BPMNPlane_learning_Subprocess">
      <bpmndi:BPMNShape bpmnElement="startEvent1" id="BPMNShape_startEvent1">
        <omgdc:Bounds height="30.0" width="30.0" x="100.0" y="163.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="subprocessTask" id="BPMNShape_subprocessTask">
        <omgdc:Bounds height="80.0" width="100.0" x="175.0" y="138.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="sid-BF7D8ACD-837F-4F3F-9370-15510C8EE5B3" id="BPMNShape_sid-BF7D8ACD-837F-4F3F-9370-15510C8EE5B3">
        <omgdc:Bounds height="28.0" width="28.0" x="320.0" y="164.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sid-2A367ED3-5718-4C47-8EF5-C1E811E7F8ED" id="BPMNEdge_sid-2A367ED3-5718-4C47-8EF5-C1E811E7F8ED">
        <omgdi:waypoint x="130.0" y="178.0"></omgdi:waypoint>
        <omgdi:waypoint x="175.0" y="178.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-4A22B10B-F5FC-4C78-AC95-9B3F7B27EF80" id="BPMNEdge_sid-4A22B10B-F5FC-4C78-AC95-9B3F7B27EF80">
        <omgdi:waypoint x="275.0" y="178.0"></omgdi:waypoint>
        <omgdi:waypoint x="320.0" y="178.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>`

`<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:activiti="http://activiti.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath" targetNamespace="http://www.activiti.org/processdef">
  <process id="learning_ContainerProcess" name="Learning Container Process" isExecutable="true">
    <startEvent id="startEvent1"></startEvent>
    <userTask id="containerUserTask" name="User Task"></userTask>
    <sequenceFlow id="sid-F76B057D-2A41-45D6-B449-711BBC4AFBB8" sourceRef="startEvent1" targetRef="containerUserTask"></sequenceFlow>
    <callActivity id="callSubprocess" name="Call Subprocess" calledElement="learning_Subprocess" activiti:inheritVariables="false"></callActivity>
    <sequenceFlow id="sid-3DB8F357-0A51-44B7-ACFA-3E9A41B5E9E3" sourceRef="containerUserTask" targetRef="callSubprocess"></sequenceFlow>
    <endEvent id="sid-679B0ACA-2BE6-4DF4-B264-6952E3349EFD"></endEvent>
    <sequenceFlow id="sid-9E287818-BCD7-474A-9B1B-F5BAD5DF42D8" sourceRef="callSubprocess" targetRef="sid-679B0ACA-2BE6-4DF4-B264-6952E3349EFD"></sequenceFlow>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_learning_ContainerProcess">
    <bpmndi:BPMNPlane bpmnElement="learning_ContainerProcess" id="BPMNPlane_learning_ContainerProcess">
      <bpmndi:BPMNShape bpmnElement="startEvent1" id="BPMNShape_startEvent1">
        <omgdc:Bounds height="30.0" width="30.0" x="100.0" y="163.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="containerUserTask" id="BPMNShape_containerUserTask">
        <omgdc:Bounds height="80.0" width="100.0" x="175.0" y="138.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="callSubprocess" id="BPMNShape_callSubprocess">
        <omgdc:Bounds height="80.0" width="100.0" x="360.0" y="138.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="sid-679B0ACA-2BE6-4DF4-B264-6952E3349EFD" id="BPMNShape_sid-679B0ACA-2BE6-4DF4-B264-6952E3349EFD">
        <omgdc:Bounds height="28.0" width="28.0" x="505.0" y="164.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sid-3DB8F357-0A51-44B7-ACFA-3E9A41B5E9E3" id="BPMNEdge_sid-3DB8F357-0A51-44B7-ACFA-3E9A41B5E9E3">
        <omgdi:waypoint x="275.0" y="178.0"></omgdi:waypoint>
        <omgdi:waypoint x="360.0" y="178.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-9E287818-BCD7-474A-9B1B-F5BAD5DF42D8" id="BPMNEdge_sid-9E287818-BCD7-474A-9B1B-F5BAD5DF42D8">
        <omgdi:waypoint x="460.0" y="178.0"></omgdi:waypoint>
        <omgdi:waypoint x="505.0" y="178.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-F76B057D-2A41-45D6-B449-711BBC4AFBB8" id="BPMNEdge_sid-F76B057D-2A41-45D6-B449-711BBC4AFBB8">
        <omgdi:waypoint x="130.0" y="178.0"></omgdi:waypoint>
        <omgdi:waypoint x="175.0" y="178.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>`

**Comment by tijsrademakers** [comment]
Hi Michael, we have quite a number of tests with a call activity and don't run into this issue. Could you provide a unit test showing the problem?

**Comment by tijsrademakers** [comment]
Closing it due to no response.
