### ISSUE TITLE
in mysql liqiubase init act_de error

### ISSUE THREAD

**Issue by jianlinz** [flowable/flowable-engine#899]
HI！
Specified key was too long; max key length is 767 bytes error  when i run with mysql.
I think the primaryKey 64 length is good.
because is primaryKey too long ,create Index  error

**Comment by tijsrademakers** [comment]
Hi, can you please provide more details about the error and which table and primary key you are referring to?

**Comment by jianlinz** [comment]
Hi!
 in flowable-modeler-app-db-changelog.xml the primaryKey all 255 length 
when i run with h2 is ok ,but when i run with mysql  i find a error is “Specified key was too long; max key length is 767 bytes”. 255*3<767 but the error  does exist.

**Comment by tijsrademakers** [comment]
which primary key exactly? which table? Which version of MySQL are you using? It's working fine on the MySQL database we tested with

**Comment by jianlinz** [comment]
my mysql varsion is 5.7.18 
the sql is 
Query is : CREATE TABLE zjl.ACT_DE_MODEL (id VARCHAR(255) NOT NULL, name VARCHAR(400) NOT NULL, model_key VARCHAR(400) NOT NULL, description VARCHAR(400) NULL, model_comment VARCHAR(400) NULL, created datetime(6) NULL, created_by VARCHAR(255) NULL, last_updated datetime(6) NULL, last_updated_by VARCHAR(255) NULL, version INT NULL, model_editor_json LONGTEXT NULL, thumbnail LONGBLOB NULL, model_type INT NULL, CONSTRAINT PK_ACT_DE_MODEL PRIMARY KEY (id))

**Comment by jianlinz** [comment]
when i execute it 
[SQL]CREATE TABLE zjl.ACT_DE_MODEL (
	id VARCHAR (255) NOT NULL,
	NAME VARCHAR (400) NOT NULL,
	model_key VARCHAR (400) NOT NULL,
	description VARCHAR (400) NULL,
	model_comment VARCHAR (400) NULL,
	created datetime (6) NULL,
	created_by VARCHAR (255) NULL,
	last_updated datetime (6) NULL,
	last_updated_by VARCHAR (255) NULL,
	version INT NULL,
	model_editor_json LONGTEXT NULL,
	thumbnail LONGBLOB NULL,
	model_type INT NULL,
	CONSTRAINT PK_ACT_DE_MODEL PRIMARY KEY (id)
)

[Err] 1071 - Specified key was too long; max key length is 767 bytes

**Comment by jianlinz** [comment]
Hi！in mysql param innodb_large_prefix default is ON with greater than mysql 5.7.7.
but my param innodb_large_prefix default is OFF.
I think it's helpful.
thanks

**Comment by jianlinz** [comment]
@tijsrademakers 
Hi！in mysql param innodb_large_prefix default is ON with greater than mysql 5.7.7.
but my param innodb_large_prefix default is OFF.
I think it's helpful.
thanks , i am so sorry
