### ISSUE TITLE
Allow task owner to manually select the assignee of next task from candidate list

### ISSUE THREAD

**Issue by Tarekajaj** [flowable/flowable-engine#948]
Hello,
I'm just curious to see if this behavior is even possible using flowable, since I wasn't able to find any hint about it anywhere.

We want the user assigned to a task to fill in a form and manually select the next user from a list of possible options, so when he complete the task the selected user get automatically assigned the next task.
 We are facing two problems to achieve this goal:

- How to create a form field with users options to select one from, the list should not have all users in the system but only the possible candidate for the next task
-  how to automatically assign the task to the selected users.

We need to be able to achieve this behavior from the visual editor would be great.

Any help would be appreciated.

**Comment by paulhh** [comment]
Hi,

This is really a question that should be asked in the forums, not created as an issue.

Setting the assignee to a following task is straight-forward: whatever form field you use for selecting the next assignee is used as the value for the assignee.  If your form field is 'nextAssignee' then using the web process editor, select the assignments property, choose Fixed values and enter ${nextAssignee} as the assignee.

To populate a list of users based on some query will be easier with the upcoming 6.3.0 release (may be tomorrow) where dropdown and radio button fields can use an expression to populate the selection.  There's probably some extra work needed to tie everything together with a bit of script work.  Alternatively, you could extend the person-picker form control to restrict it's user list to a more specific list.

The challenge to make a solution generalized is that you cannot guarantee there's always just one user task coming next in a process that you can grab the candidate users from.  You may be better off modeling the candidate users more explicitly, e.g. using groups, which makes working with things a bit easier.

Cheers
Paul.

**Comment by Tarekajaj** [comment]
Thank you for your quick reply and sorry for posting my question here.
will post on forum next time.

**Comment by Tarekajaj** [comment]
We decided to extend person-picker because it seemed simpler, but we are stuck again,
Just created a [forum question](https://forum.flowable.org/t/extending-person-picker-to-show-only-user-in-selected-groups/1824), any help would be appreciated.
