### ISSUE TITLE
Connection to reveal

### ISSUE THREAD

**Issue by jianlinz** [flowable/flowable-engine#950]
Hi!
  org.flowable.app.conf.DatabaseConfiguration   liquibase  get a jdbcConnection  but not close, i think we should close it in finally. Thanks.

**Comment by PascalSchumacher** [comment]
Hi!

Thanks for reporting this. I haven't debugged the problem, but I believe you are right.

My understanding is that the `liquibase` bean is used by spring boot during start-up and needs the database connection, therefore it can not be closed inside the methods (e.g. https://github.com/flowable/flowable-engine/blob/master/modules/flowable-ui-modeler/flowable-ui-modeler-conf/src/main/java/org/flowable/app/conf/DatabaseConfiguration.java#L132).

Sadly the `Liquibase` class does not offer any method to close the underlying database connection.

The default `liquibase` bean of spring boot (https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration.java#L121) uses a special class to ensure that the underlying database connection is closed (https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration.java#L195).

Maybe flowable needs something similar?

@filiphr Am I missing something?

**Comment by jianlinz** [comment]
i think you are right!Thank you for your reply.

**Comment by filiphr** [comment]
@PascalSchumacher you are correct. I noticed that too during the migration to Spring Boot 2.0 in our apps. We need something similar. Or we could directly use the Spring Liquibase support for the apps.
