### ISSUE TITLE
cmmn engine

### ISSUE THREAD

**Issue by qiudaoke** [flowable/flowable-engine#976]
hello,I import casemodel from /flowable-engine/modules/flowable-cmmn-engine/src/test/resources/org/flowable/cmmn/test/one-human-task-model.cmmn

like  this:
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/CMMN/20151109/MODEL" 
    xmlns:dc="http://www.omg.org/spec/CMMN/20151109/DC" 
    xmlns:di="http://www.omg.org/spec/CMMN/20151109/DI"
    xmlns:cmmndi="http://www.omg.org/spec/CMMN/20151109/CMMNDI" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    targetNamespace="http://flowable.org/cmmn">

    <case id="myCase">
        <casePlanModel id="myPlanModel" name="My CasePlanModel">

            <planItem id="planItem1" name="Task One" definitionRef="rootTask" />
            <planItem id="planItem2" name="Stage One" definitionRef="stage1" />

            <task id="rootTask" name="The Task" isBlocking="true" />

            <stage id="stage1" name="Nested Stage">

                <planItem id="planItem3" name="Task Two" definitionRef="rootTask" />
                <planItem id="planItem4" name="Task Three" definitionRef="nestedTask" />

                <task id="nestedTask" name="Nested Task" isBlocking="true" />

            </stage>

        </casePlanModel>
    </case>

</definitions>

==============

but  it is error ,can you help me 。

**Comment by tijsrademakers** [comment]
Can you provide more details about the exact error? Do you see a stacktrace?

**Comment by qiudaoke** [comment]
Many CMMN files for testing are not available. 
like 
<cmmndi:CMMNDI>
    <cmmndi:CMMNDiagram id="CMMNDiagram_humanTaskCompletionExits">
      <cmmndi:CMMNShape id="CMMNShape_casePlanModel" cmmnElementRef="casePlanModel">
        <dc:Bounds height="717.0" width="893.0" x="40.0" y="40.0"></dc:Bounds>
        <cmmndi:CMMNLabel></cmmndi:CMMNLabel>
      </cmmndi:CMMNShape>

**Comment by qiudaoke** [comment]
So the import is wrong.

**Comment by tijsrademakers** [comment]
Ok let's continue the discussion on the Flowable forum. Please create a post there describing step by step what the issue is you are running into.
