### ISSUE TITLE
remember-me service fails with spring-boot 2

### ISSUE THREAD

**Issue by lucjross** [flowable/flowable-engine#979]
Trying to access the IDM UI, an NPE occurs on [this line](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/authentication/rememberme/AbstractRememberMeServices.java#L124). The cause is CGLIB having proxied [flowable's subclass](https://github.com/flowable/flowable-engine/blob/master/modules/flowable-ui-idm/flowable-ui-idm-conf/src/main/java/org/flowable/app/security/CustomPersistentRememberMeServices.java), leaving most fields null on the proxy instance. This happens since spring-boot 2.0.1.RELEASE, in which [the default of `spring.aop.proxy-target-class` changed to `true`.](https://github.com/spring-projects/spring-boot/commit/78845fe63a75b01f1e4a7166a356834c0884f8d5)

A workaround is to set the property to `false` or empty, but it might be preferable to avoid the `@Transactional` annotation (which requires CGLIB proxy) on this particular service, and instead enforce transactionality programmatically, which should prevent AOP from trying to proxy the class.

**Comment by filiphr** [comment]
@lucjross the default in our application properties is set to `false`.

Have a look at the idm default [`application.properties`](https://github.com/flowable/flowable-engine/blob/master/modules/flowable-ui-idm/flowable-ui-idm-app/src/main/resources/application.properties#L5-L6).

Are you overriding the defaults?

**Comment by lucjross** [comment]
Yes, my mistake. Thanks :-)
