### ISSUE TITLE
Wrong OSGi export for some Flowable bundles in 6.3.0

### ISSUE THREAD

**Issue by andreessen** [flowable/flowable-engine#986]
Hi,
We've just run into an issue when some bundles do the wrong osgi export.  E.g. 

- https://github.com/flowable/flowable-engine/blob/flowable-6.3.0/modules/flowable-spring/pom.xml
`<flowable.artifact>
            org.flowable.spring
        </flowable.artifact>`
exports all packages also from flowable-spring-common bundle

- https://github.com/flowable/flowable-engine/blob/flowable-6.3.0/modules/flowable-engine/pom.xml
`<flowable.artifact>
            org.flowable.engine
        </flowable.artifact>`
exports all packages also from flowable-engine-common bundle.
It results in errors when other bundles try to import these packages.
To fix it for our needs we have done the following: https://github.com/emdev-limited/flowable-engine/commit/a8269e894194b6aeb68dc8c8d24379989e927894 but I believe it should be fixed here.

**Comment by tijsrademakers** [comment]
thanks for raising the issue, I think we should modify the common module packages to have org.flowable.common.engine and org.flowable.common.spring
