### ISSUE TITLE
Flowable-Rest/ Forms API (POST form/form-instances) gives JSON parse error.

### ISSUE THREAD

**Issue by bhaskarmelkani** [flowable/flowable-engine#999]
**Flowable-rest/Forms API**

**Context**: The `flowable-rest.war` is deployed to `Tomcat` and is used via REST APIs.

**API:**  [`POST form/form-instances`](https://www.flowable.org/docs/userguide-form/index.html#_store_a_form_instance).
While POSTing on this API, it gives an  JSON parse error.

**POST Body:**
```json
{
   "formDefinitionKey":"simpleForm",
   "taskId":"<taskId>",
   "processInstanceId":"<processInstanceId>",
   "processDefinitionId":"<processDefinitionId>",
   "variables": [
      {
        "name":"input1",
        "value":"test",
      }
   ]
}
```
**Error:**
```json
{
    "message": "Bad request",
    "exception": "JSON parse error: Cannot deserialize instance of `java.util.LinkedHashMap` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.LinkedHashMap` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 6, column: 17] (through reference chain: org.flowable.form.rest.service.api.form.FormRequest[\"variables\"])"
}
```

**Questions:**
1. Is the documentation updated, looks like the API doesn't expect `Array` as a value of variables.
2. Is this API stable and can be used in production ?

**Comment by tijsrademakers** [comment]
Yes this API is stable. You need to pass a map with "key": "value" with the variables property. So something like:

"variables": {
    "input1": "test"
}
